### ISSUE TITLE
How to map capslock to work as meta key?

### ISSUE THREAD

**Issue by mnn** [rvaiya/keyd#10]
What I want:
```
ckb1: Corsair Gaming K95 RGB PLATINUM Keyboard vKB: leftmeta down
ckb1: Corsair Gaming K95 RGB PLATINUM Keyboard vKB: left down
ckb1: Corsair Gaming K95 RGB PLATINUM Keyboard vKB: left up
ckb1: Corsair Gaming K95 RGB PLATINUM Keyboard vKB: leftmeta up
```
My attempt:
```
capslock = mods_on_hold(M, leftmeta)
```
results in
```
keyd virtual keyboard: leftmeta down
keyd virtual keyboard: leftmeta up
keyd virtual keyboard: leftmeta down
keyd virtual keyboard: leftmeta up
```
I held capslock, pressed once left arrow and released capslock. But arrow is missing and (slow) hold&release of capslock lead to `leftmeta down` (hold started), nothing (here should be left arrow down and up) and `leftmeta up, leftmeta down, leftmeta up` (all tree events fired when key was released).

Some keys (mostly letters on first and second row) are not dropped, but meta goes "up and down" around them which isn't good (also there are excessive meta presses). This is from capslock down, `a` key down and up, capslock up (both keys pressed only once):
```
keyd virtual keyboard: leftmeta down
keyd virtual keyboard: leftmeta up
keyd virtual keyboard: leftmeta down
keyd virtual keyboard: leftmeta up
keyd virtual keyboard: a down
akeyd virtual keyboard: a up
keyd virtual keyboard: leftmeta down
keyd virtual keyboard: leftmeta up
keyd virtual keyboard: leftmeta down
keyd virtual keyboard: leftmeta up
```

I also tried simpler `capslock = leftmeta`, but that didn't work too (one less down+up of meta, but still meta key was mapped as held, was released when other key was pressed and then pressed down again on its own).

It this a bug, or do I have something wrong in the configuration?

**Comment by rvaiya** [comment]
It looks like you are using a keyboard that comes with some remapping software. It is possible that it interferes with keyd. Can you try disabling it and see if that makes a difference? I believe the relevant service would be `ckb-next-daemon` but it may vary by distro.

> capslock = mods_on_hold(M, leftmeta)

This should still work, but you probably just want `capslock = leftmeta`. `mods_on_hold` is intended to be used when you want the tap key to differ from the modifier. E.G `mods_on_hold(M, esc)`.

**Comment by mnn** [comment]
I disabled ckb-next (at least I think, my main keyboard no longer has the `ckb1` prefix in `keyd -m`).

With `capslock = leftmeta` I am getting now:
```
keyd virtual keyboard: leftmeta down
keyd virtual keyboard: leftmeta up
```
so left arrow is still not showing up. It seems to behave same as previously.

Forgot to post version (installed today from aur):
```
$ keyd -v
keyd version: 0.0.2 (b61ff92d7c165f1496a33a9ab0163eea067d2773)
```

**Comment by rvaiya** [comment]
Thanks, this should work. I am not familiar with the ckb driver, but just to be sure can you try plugging in another keyboard?

Additionally, can you post the output of `keyd -m` after performing
the following key sequences both while keyd is running and not running?

```
<capslock down><left arrow down><left arrow up><capslock up>
<capslock down><a down><a up><capslock up>
```

**Comment by mnn** [comment]
I tried it without running keyd and it seems like the keyboard doesn't support capslock combinations with some keys (not just in `keyd -m`, in any other application too).

This is me pressing down capslock, left down and up, capslock up:
```
RMC RMC 16k Keyboard: capslock down
RMC RMC 16k Keyboard: capslock up
```

Sorry, I had no idea it's the fault of the keyboard. For others having similar issue, the keyboard is reported in `lsusb` as
`ID 25a7:0026 Areson Technology Corp RMC 16k` and the name on the eshop I bought it from was "Air Mouse".

**Comment by rvaiya** [comment]
No worries. Thanks for the confirmation.
