### ISSUE TITLE
keyd-application-mapper: "could not connect to keyd instance"

### ISSUE THREAD

**Issue by canadaduane** [rvaiya/keyd#101]
I'm trying to troubleshoot the new `keyd-application-mapper` script's connection to `keyd`. The error message I'm getting is:

> ERROR: could not connect to keyd instance, make sure it is running and you are a member of `keyd`

Well, as far as I can tell, `keyd` _is_ running:

```
$ ls -al /var/run/keyd.socket 
0660 srw-rw---- 0 root 15 Jan 21:18 /var/run/keyd.socket
```

and I'm a member of `keyd`:

```
$ groups duane
duane : duane adm sudo kvm lpadmin libvirt docker keyd
```

What am I missing?

**Comment by rvaiya** [comment]
What does `groups` as `duane` yield? You may need to log out for the changes to take effect in the current session.

**Comment by canadaduane** [comment]
```$ groups
duane adm sudo kvm lpadmin libvirt docker
```

No keyd. Hmm. Why is it different?

**Comment by rvaiya** [comment]
You may have to restart your login manager (e.g `systemctl restart gdm`) or reboot the machine. The current process is a descendant of the login process which establishes group membership when you login.

**Comment by canadaduane** [comment]
You're right, that did the trick (I restarted my system completely).

**Comment by rvaiya** [comment]
This should no longer be necessary under gnome. The extension now manages the script lifecycle so you can remove it from ~/.xsession and just rerun the latest version.
