### ISSUE TITLE
Macro delay in expression not respected

### ISSUE THREAD

**Issue by canadaduane** [rvaiya/keyd#107]
I've written an expression that uses delay of between 100ms and 1000ms and it seems there is no delay happening:

```
meta_mac., = macro(a 1000ms b 1000ms c)
```

Should slowly write "abc" but writes it instantaneously.

Using latest master.

**Comment by rvaiya** [comment]
This should be fixed.

**Comment by canadaduane** [comment]
I think the fix may have caused another issue:

Now, when I use a macro in an expression such as `meta_mac.k = macro(C-a C-S-k)` I get the following key sequence from keyd monitor:

```
$ sudo keyd -m
[sudo] password for duane: 
keyd virtual keyboard	0fac:0ade	enter up
keyd virtual keyboard	0fac:0ade	leftcontrol down
keyd virtual keyboard	0fac:0ade	a down
keyd virtual keyboard	0fac:0ade	a up
keyd virtual keyboard	0fac:0ade	leftshift down
keyd virtual keyboard	0fac:0ade	k down
keyd virtual keyboard	0fac:0ade	k up
keyd virtual keyboard	0fac:0ade	leftshift up
keyd virtual keyboard	0fac:0ade	leftcontrol up
```

I'm expecting it to look like this (my manual re-arrangement):
```
keyd virtual keyboard	0fac:0ade	leftcontrol down
keyd virtual keyboard	0fac:0ade	a down
keyd virtual keyboard	0fac:0ade	a up
keyd virtual keyboard	0fac:0ade	leftcontrol up
keyd virtual keyboard	0fac:0ade	leftcontrol down
keyd virtual keyboard	0fac:0ade	leftshift down
keyd virtual keyboard	0fac:0ade	k down
keyd virtual keyboard	0fac:0ade	k up
keyd virtual keyboard	0fac:0ade	leftshift up
keyd virtual keyboard	0fac:0ade	leftcontrol up
```

It seems to be squishing the two macro-sequences together and skipping the C-up, C-down

**Comment by rvaiya** [comment]
This is expected behaviour. keyd tried to reduce noise by only sending the necessary sequences. 

This generally shouldn't cause a problem since sane applications don't care care about intervening modifier key up events, but if it is causing you grief for some reason then you can avoid it by using `+` in conjunction with explicit keycodes. E.G `macro(leftcontrol+a leftcontrol+leftshift+k)`, etc. 

Is this causing a specific problem?

**Comment by canadaduane** [comment]
> This is expected behaviour. keyd tries to reduce noise by only sending the necessary events.

Oh strange! Even in a macro like that?

> Is this causing a specific problem?

Yes, it isn't sending the key sequences ha. The actual key sequence I'm trying to send is "C-c" (SIGINT) followed by "C-S-k" (clear and reset terminal). I lied a bit by sending you "C-a" in the example earlier (I couldn't test "C-c" because it would quit `keyd -m`).

I'll try the `+` version you sent along.

**Comment by canadaduane** [comment]
Wait, it might be my OS grabbing Ctrl+Shift+K.

**Comment by canadaduane** [comment]
My bad. I changed two things at once and blamed `keyd`. It's all better! Macro delays are working now.
