### ISSUE TITLE
f keys

### ISSUE THREAD

**Issue by jedugsem** [rvaiya/keyd#11]
i want to remap F1 to esc because my escape key is broken but F1 = esc doesnt work

**Comment by rvaiya** [comment]
You probably want 'f1 = esc'. You can find a list of valid key names by
using -m and then pressing the key of interest or using '-l'. E.G 'keyd
-l|grep -i f1'.

**Comment by jedugsem** [comment]
thanks a lot espesily for the fsat awnser, everything working now

**Comment by rvaiya** [comment]
Glad to hear it :). I also recommend giving `capslock = mods_on_hold(C, esc)` a shot. It makes capslock behave as control when held and escape when tapped. After getting used to it, I've come to find it indispensable on my machines.
