### ISSUE TITLE
Swap modifier key not working as expected

### ISSUE THREAD

**Issue by canadaduane** [rvaiya/keyd#110]
I think this worked in `keyd` 1.x, but I'm having difficulty replicating the behavior. I'd like leftmeta to behave exactly as leftalt:

```
[ids]
*

[main]
leftalt = layer(meta_mac)
leftmeta = leftalt

[meta_mac:C]
space = M-/
```

However, when I press something like "M-S-f", I get an unexpected `leftalt up` before the `f` key:

```
keyd virtual keyboard	0fac:0ade	enter up
keyd virtual keyboard	0fac:0ade	leftshift down
keyd virtual keyboard	0fac:0ade	leftalt down
keyd virtual keyboard	0fac:0ade	leftalt up   <-- NOT expected here
keyd virtual keyboard	0fac:0ade	f down
keyd virtual keyboard	0fac:0ade	f up
keyd virtual keyboard	0fac:0ade	leftshift up
```

Is this correct behavior for `keyd`? If so, how do I get the desired "leftmeta acts as leftalt" behavior?

**Comment by rvaiya** [comment]
This should now be `meta = layer(alt)` (for both right and left) or `leftmeta = layer(alt)`. Modifiers should be treated as layers, and mapping directly to modifier keycodes produces undefined results. I've made this illegal in the latest commit.
