### ISSUE TITLE
WM_NAME is sometimes None, sometimes a binary that is neither utf-8 nor ascii

### ISSUE THREAD

**Issue by canadaduane** [rvaiya/keyd#112]
The `XMonitor` code in `keyd-application-mapper` is failing to recognize app switching, especially when I switch to Firefox. It turns out there are multiple "failure modes" here that cause the try/except to simply "pass", ignoring app-specific key bindings for firefox (in some websites--due to the nature of the WM_NAME).

**Failure 1**
It's possible for `win.get_full_property(WM_NAME, 0)` to return `None`. In this failure case, a modified `keyd-application-mapper` tells me why it skips calling `on_window_change`: `'NoneType' object has no attribute 'value'`. An example where `get_full_property(WM_NAME, 0)` returns `None` is when the wm_class is `root`. (This is not the only case, however).

**Failure 2**
When I modify `keyd-application-mapper` to guard against Failure 1, I still get another failure: `'utf-8' codec can't decode byte 0xb7 in position 10: invalid start byte`. For example, here is what `get_full_property(WM_NAME, 0).value` returns for the github page I'm currently typing this into:

```
b'New Issue \xb7 rvaiya/keyd \x1b%G\xe2\x80\x94\x1b%@ Mozilla Firefox'
```

The encoding seems to be neither `ascii` nor `utf-8`. When I switch to `ascii`: `'ascii' codec can't decode byte 0xb7 in position 10: ordinal not in range(128)`.

Edit:
**Failure 3**
Sometimes when processing events in the event loop, the "root" window says that it is active and therefore overrides all previous events from the actually focused window.

**Comment by canadaduane** [comment]
Apparently WM_NAME is legacy, and is a "compound text" encoding:

https://stackoverflow.com/questions/7706589/is-there-any-difference-with-the-x11-atoms-xa-wm-name-and-net-wm-name

**Comment by rvaiya** [comment]
I believe this should be fixed

**Comment by canadaduane** [comment]
It's a lot of fun working with you--you work so quickly & you have such deep experience in so many aspects of this work. So cool!

Will test momentarily.

**Comment by canadaduane** [comment]
Looks good! Thanks.

**Comment by rvaiya** [comment]
> It's a lot of fun working with you--you work so quickly & you have such deep experience in so many aspects of this work. So cool!
> 
> Will test momentarily.

That is very kind of you to say, but it is worth noting that I have had the misfortune of writing a window manager (many moons ago) so it is actually quite embarrassing that I made this mistake in the first place :P.
