### ISSUE TITLE
A few typos in the manual

### ISSUE THREAD

**Issue by alefbragin** [rvaiya/keyd#116]
1. https://github.com/rvaiya/keyd/blob/d475661f9361fa24f166c9b5ed0b660b96a055b3/man.md?plain=1#L399
   Tab in the begging of the line renders as a quote in markdown that is not intended behavior.

2. https://github.com/rvaiya/keyd/blob/d475661f9361fa24f166c9b5ed0b660b96a055b3/man.md?plain=1#L452
   It seems mention of `e` key in `esc+q/w/e` in the example is a typo.

**Comment by rvaiya** [comment]
> Tab in the begging of the line renders as a quote in markdown that is not intended behavior.

Pandoc does weird things when you convert to roff. The additional tab is needed to indent the definition paragraph. There are probably a few other idiosyncracies which make the markdown output look uglier, but the target output is the system man page so I am less concerned if the github version looks a bit ugly :P.

> It seems mention of e key in esc+q/w/e in the example is a typo.

Thanks for catching this. I have fixed it in the latest commit. If you find any other discrepancies feel free to submit a PR :).
