### ISSUE TITLE
Is there any way to switch modifiers?

### ISSUE THREAD

**Issue by LilithhhBlackkk** [rvaiya/keyd#118]
With the V1, I could just, for instance
capslock = leftmeta
leftmeta = capslock
However, with the V2, I need a separate layer and I would have to define every possible keybind, and that seems exhausting, is there anything I'm missing?
Thank you

**Comment by rvaiya** [comment]
You want

```
capslock = layer(meta)
leftmeta = capslock
```

The syntax has changed since v1 but most things should be just as easy. I encourage you to reread the man page and changelog.
