### ISSUE TITLE
Debug mode?

### ISSUE THREAD

**Issue by canadaduane** [rvaiya/keyd#120]
Is there a way to see the internal state of keyd at any given moment?

I have a config with several named layers and I'd like to know which layer I'm in. Like `-m` but after having loaded a conf file.

**Comment by rvaiya** [comment]
Not at the moment. Is there a specific bug you are trying to track down? It might help to define a unique macro to help identify the current layer:

E.G

```
[mylayer]
1 = macro(Inside space mylayer)
```

**Comment by canadaduane** [comment]
Here's the short version of the config I'm trying to build:

```
[ids]
*

[main]
leftalt = layer(meta_mac)
leftmeta = layer(alt)

[meta_mac:C]
left = swap(no_ctrl, home)

[no_ctrl]
leftshift = swap(ctrl_shift)
left = home

[ctrl_shift]
left = S-home
```

There are lots of other things happening in "meta_mac" layer, but I think they can be safely ignored here.

The goal is to get `leftalt+left` to emit "home", but if `leftalt+leftshift+left` is pressed, it emits "S-home". I'm not sure if I'm ever reaching the `ctrl_shift` state though.

**Comment by rvaiya** [comment]
> The goal is to get leftalt+left to emit "home", but if leftalt+leftshift+left is pressed, it emits "S-home". I'm not sure if I'm ever reaching the ctrl_shift state though.

You probably want something like
	
	[main]

	alt = layer(myalt)

	[shift]
	alt = layer(alt_shift)

	# Corresponds to your 'meta_mac' layer.
	[myalt:C]
	shift = layer(alt_shift)
	left = home

	[alt_shift]
	left = S-home

Unless you are doing something more complicated, the swap is unncessary. You just want `alt+shift` to put you in the layer of interest.

**Comment by canadaduane** [comment]
That did the trick, thank you.

Maybe a debug mode would just be a good educational tool for experimenters :)

**Comment by canadaduane** [comment]
Follow-up question for the solution you provided: Is there a way to tell keyd that all of the other key combinations should remain the same? For example, now when I press alt+shift+t it no longer emits ctrl+shift+t.

**Comment by rvaiya** [comment]
This is the purpose of modifier layers. You can just do `[meta_mac_shift:C-S]` which will also cause the layer to stack properly and emit `C-S` as soon as the layer is activated.

**Comment by rvaiya** [comment]
If you set KEYD_DEBUG=1 keyd will log the active layer (e.g `sudo KEYD_DEBUG=1 keyd`)

**Comment by canadaduane** [comment]
Thanks!
