### ISSUE TITLE
`Ctrl+Shift+Alt+Super` to `Super` remap

### ISSUE THREAD

**Issue by andrey-shigantsov** [rvaiya/keyd#124]
Hi, thanks for this cool project!

> ArchLinux
> kernel version: 5.15.13-arch1-1
> keyd version: 2.2.4-beta (cc84f3db9d77c724a7b2e56d04696927f5c71dfd)

On my keyboard, the `super_rigt` key gives `control+shift+alt+super_left`. I want it to work like a regular super.

I have tried the following.
```
# Microsoft Ergonomic Keyboard (LXM-00001)
[ids]
045e:082c

[control]
shift = layer(control_shift)

[control_shift]
alt = layer(control_shift_alt)

[control_shift_alt]
#meta = macro(h e l l o , space K E Y D) # works
#meta = swap(meta) # not works
#meta = macro(M) # break my keyboard
```

How can I properly configure this?

**Comment by andrey-shigantsov** [comment]
Stumbled upon https://github.com/rvaiya/keyd/issues/111#issuecomment-1019363519

```
# Microsoft Ergonomic Keyboard (LXM-00001)
[ids]
045e:082c

[control]  
shift = swap(control_shift)  

[control_shift:C-S]
alt = swap(control_shift_alt)  

[control_shift_alt:C-S-A]
meta = swap(meta)
```

It works! I will test...

**Comment by andrey-shigantsov** [comment]
I tested my cases ... Not perfect, but good. The problem remains that combinations with left modifiers do not work (nothing can be done about it). However, it works with the right (fakemeta + rightshift / rightalt / rightcontrol).

**Comment by rvaiya** [comment]
Thanks for closing the loop :). The additional data points are useful.
