### ISSUE TITLE
overload(capslock, esc) : it's not a valid layer

### ISSUE THREAD

**Issue by explosion-mental** [rvaiya/keyd#125]
Hello. I've been tweking my config and after two days of some reading (very nice docs btw) I have finally move my xmodmap keys config to keyd.
Now that I have more liberty in this program I'm experimenting with `esc`ing in other key rather than the actual esc key, my config:

```
[ids]

*

[main]

# Don't hold that shift
shift = oneshot(shift)

# meta as esc?
meta = overload(esc, meta)

# remap the escape key to capslock if held
esc = overload(capslock, esc)

# CapsLock to delete (very fast)
capslock = backspace

# Left alt to altgr
leftalt = layer(altgr)

# Right alt (altgr) to control for pinky safety
rightalt = layer(control)

[altgr]

# vim keys in altgr (deadkeys) mode
h = left
j = down
k = up
l = right

```

which gives me:

```
ERROR /etc/keyd/default.conf:11: "esc" is not a valid layer
ERROR /etc/keyd/default.conf:14: "capslock" is not a valid layer
```

I've tried with:
```
[capslock]

capslock = capslock

[esc]

esc = esc
```
at the end (making a layer?) but when I hold esc does not enables capslock. I'm sure I missed something but I don't seem to find it.

**Comment by rvaiya** [comment]
The first argument of overload must be a layer. So instead of 

	meta = overload(esc, meta)

You want

	meta = overload(meta, esc)

since `meta` is a layer.

However 

	overload(capslock, esc)


Is not valid since neither capslock nor esc are valid layers. Overload is intended to be used in the case where a given key acts as both some kind of modifier (i.e layer toggle) and a normal key. If the above was valid, then the only way to access capslock would be to hold capslock and press another key, which makes little sense.

You might want to try something like this instead:

	capslock = overload(capslock, esc)

	[capslock:C]

	1 = capslock

Which will allow you to access capslock with `C-1` and otherwise treat capslock as a control key when held.

**Comment by explosion-mental** [comment]
> `meta = overload(meta, esc)`
Oh I thought overload args was (tap, hold), thanks.


> Overload is intended to be used in the case where a given key acts as both some kind of modifier (i.e layer toggle) and a normal key. If the above was valid, then the only way to access capslock would be to hold capslock and press another key, which makes little sense.

I C. excuse the little experience I have about this, I'm still getting my head around this..
My intended use case is to have the esc key act as `esc`, but when held act as capslock. would that be possible?

**Comment by rvaiya** [comment]
> My intended use case is to have the esc key act as esc, but when held act as capslock. would that be possible?

It depends on what you mean by 'held'. In this context 'held' means 'depressed while another key is struck'.

E.G

	capslock down
	a down
	a up
	capslock down

as opposed to

	capslock down
	capslock down
	a down
	a up

In this context it makes little sense to have the first case generate capslock and the second case generate escape.

If by held you simply mean 'depressed for a certain period of time' then this is unsupported.  I would submit that this is probably a bad idea anyway since you don't want time to be the only thing which distinguishes `escape` from `capslock` in the course of normal typing (see also #81 and #34).

**Comment by explosion-mental** [comment]
> you don't want time to be the only thing which distinguishes `escape` from `capslock` in the course of normal typing

Well, some keys are **not useful when typying** or might be used much less. I think this is a very large topic, but in general you could name the function keys, volume up/down and the like (play/next song/airplane mode/etc. Not sure how to name those).

Anyway, in that context i'm sure it will be useful to have an X _not that useful_ key to act as an Y  _useful key_.

> If by held you simply mean 'depressed for a certain period of time' then this is unsupported.

May I ask why? is it that complicated?
I think `overload()` is: `waiting for X ms` + `another key stroke`. So another func like `overheld()` could only look at time. Just a suggestion, I haven't touch `keyd` source (yet..).

**Comment by rvaiya** [comment]
> Well, some keys are not useful when typying or might be used much less. 

Agreed. This is the purpose of layers.

> Anyway, in that context i'm sure it will be useful to have an X not that useful key to act as an Y useful key.

This is the purpose of overload (which avoids the time based ambiguity, is faster and gives you more flexibility).

> May I ask why? is it that complicated?

The complexity lies in the problem domain, not in the implementation. To summarize:

`<x down> <x up>` = `a`

`<x down> <300 ms> <x up>` = `b`

Has several problems which make it undesirable in practice

1. It introduces visual latency.

2. It impedes normal typing flow unless the timeout is sufficiently high.

3. If the timeout is sufficiently high it is less efficient than just using a normal layer (which allows you to define multiple keys).

The pitafalls of using time to distinguish between keys has already been discussed at length in the referenced threads (and elsewhere). I would advise you to read through them.

> I think overload() is: waiting for X ms + another key stroke. 

Overload is purely sequence based unless you add a timeout, in which case it will exclusively use time. This behaviour makes sense in the case of layers, it doesn't make sense in the case of individual keys. That is, having a key's entire up/down lifecycle purely depend on time is an inherently bad idea with little benefit. Having said that, you are welcome to make a case for it in one of the aforementioned threads.

**Comment by explosion-mental** [comment]
Okay I think to summarize, the problems are basically **too slow** or _inefficient_. Which I think really doesn't matter since the usecase I said it's on a 'non-typing' (or atleast not _that_ constant) state.

> you are welcome to make a case for it in one of the aforementioned threads.

I don't see other usecase rather than the one I mention.

If several other users encounter this, then maybe this topic does deserves a separate issue?

**Comment by explosion-mental** [comment]
Anyway thank you very much for your feedback and, again, excuse my confusion on this _key mapping_ journey.

One more suggestion, maybe add this example? `meta = overload(meta, esc)`

**Comment by rvaiya** [comment]
Thanks for the feedback.

> Which I think really doesn't matter since the usecase I said it's on a 'non-typing' (or atleast not that constant) state.

This assumes that both keys are used infrequently. If at least one of them is then it still presents a problem as outlined in the referenced post. 

Even if neither key is used very frequently, I would argue:

`<key1 down> <key2 down> <key2 up> <key1>` is superior to `<key1 down> <300 ms> <key1 up>` in almost every real world use case. 


> If several other users encounter this, then maybe this topic does deserves a separate issue?

Agreed. I am open to reconsidering the feature if there is real world demand (i.e If a non trivial number of people use the set up and don't eventually grow to despise it). I have learned from personal experience that many things which seem appealing in theory don't work in practice.

> One more suggestion, maybe add this example? meta = overload(meta, esc)

Done.
