### ISSUE TITLE
How to install it on NixOS?

### ISSUE THREAD

**Issue by fedoranvar** [rvaiya/keyd#126]
Good day to you all!

Does anyone succeed in installing keyd in NixOS?

Can you please share steps to it

Thanks!

**Comment by fedoranvar** [comment]
resolved it.

Ended with flake and `nix develop`

**Comment by jbrechtel** [comment]
@fedoranvar Would you mind sharing more details?

**Comment by hyx0329** [comment]
I'm new to NixOS, and I managed to create my solution [here](https://github.com/hyx0329/nix-keyd). Hope this will help someone.
