### ISSUE TITLE
bug: complete freeze while starting X (keyd as a runit service)

### ISSUE THREAD

**Issue by explosion-mental** [rvaiya/keyd#130]
I have set up  a runit script `exec /usr/local/bin/keyd`, so keyd bindings are avaliable not only on _X_ but on a tty as well (even on the login prompt). For some reason I cannot `startx` before doing `sv stop keyd` to disable the service.
I power up/off my laptop like 5 times just in case, the freeze is constant.

First of all, how will I go on about debuging? was this behaviour reported before?
The last thing I did was `git pull` the repo and change prefix to `/usr/local`.

**Comment by rvaiya** [comment]
By default keyd will run in the foreground, if you are putting it in a startup script you will probably want to daemonize it. Are you using `-d`? This is documented in the man page. The output is stored in `/var/log/keyd.log` if you run it as a daemon.

**Comment by explosion-mental** [comment]
Hmmm I C. The problem here is the program going into the background, since (I think) all `runsv` (runit service manager) does is to run the _run_ script and make sure it doesn't die (and more options). `keyd -d` goes into the background and the service manager tries to respawn it 'forever'.

Would help if **log** had it's own flag (say `-l`).

**Comment by explosion-mental** [comment]
After some tweaking I've come up with this
```sh
#!/bin/sh
sleep 0.5
exec /usr/local/bin/keyd 2>> /tmp/keyd.log
```
I'm guessing runit starts keyd service 'too fast' and for some reason X doesn't recognize the keys? I'm not sure.
Anyway the hack was to sleep 0.5 secs and also I've made it to '_log_' into a file.
