### ISSUE TITLE
Makefile: make better for distro packaging

### ISSUE THREAD

**Issue by eNV25** [rvaiya/keyd#135]
The current Makefile is not very good for building into a package.

The environment the package is installed does need to be the same as the environment the package is built.

- using pgrep to check for systemd: package may be built in environment without systemd running
- checking for directory in host system (libinput quirks): libinput may not be installed in build environment
- adding keyd group in install: does not affect the package

For systemd and libinput support: I think checking for folder in DESTDIR (not host) is fine. Packagers can add directory before make install.

```
if [ -d $(DESTDIR)$(PREFIX)/dir ]
```

For adding groups you can use systemd-sysusers in systemd systems

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=keyd-git

I think instead of using if statements in Makefile. It should let packagers or users delete unneeded files.

Or maybe packages shouldn't be using Makefile at all?

**Comment by rvaiya** [comment]
> The environment the package is installed does need to be the same as the environment the package is built.
> using pgrep to check for systemd: package may be built in environment without systemd running
> checking for directory in host system (libinput quirks): libinput may not be installed in build environment

Good point.

> adding keyd group in install: does not affect the package

Nevertheless, I would prefer to have `make install` do the sane thing in the event that it is run directly on the system of interest.

> Packagers can add directory before make install.

Sounds reasonable.

> For adding groups you can use systemd-sysusers in systemd systems

I would prefer to leave this up to the packagers.

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=keyd-git

> I think instead of using if statements in Makefile. It should let packagers or users delete unneeded files.

I would prefer to avoid polluting the user's disk unnecessarily. Most people who compile from source will probably just run `make install` directly on the target system.

Does be154a7a address these adequately?

**Comment by eNV25** [comment]
Yea, this is fine.
