### ISSUE TITLE
With "[ids] *" Logitech Ergo -trackball stops working correctly

### ISSUE THREAD

**Issue by nkahe** [rvaiya/keyd#139]
If in /etc/keyd/default.conf I put:
```
[ids]
*
```
Logitech Ergo -trackball's scroll wheel stops working and shortcuts that have modifier + mouse key. I have to exclude Ergo with:
-046d:406f

**Comment by rvaiya** [comment]
Can you post the output of `journalctl -fu keyd`?

**Comment by nkahe** [comment]
Sure. Without the "-046d:406f" line in /etc/keyd/default.conf:
```
❯ journalctl -fu keyd
helmi 15 13:01:54 ryzen keyd[243647]: Starting keyd v2.2.0-beta ().
helmi 15 13:01:54 ryzen keyd[243647]: Parsing /etc/keyd/default.conf:
helmi 15 13:01:54 ryzen systemd[1]: Stopped key remapping daemon.
helmi 15 13:01:54 ryzen systemd[1]: Started key remapping daemon.
helmi 15 13:01:55 ryzen keyd[243647]: Managing USB-HID Keyboard (04d9:0295) (/etc/keyd/default.conf)
helmi 15 13:01:55 ryzen keyd[243647]: Managing USB-HID Keyboard (04d9:0295) (/etc/keyd/default.conf)
helmi 15 13:01:55 ryzen keyd[243647]: Managing Logitech MX Ergo (046d:406f) (/etc/keyd/default.conf)
helmi 15 13:01:55 ryzen keyd[243647]: Managing Logitech USB Receiver (046d:c529) (/etc/keyd/default.conf)
helmi 15 13:01:55 ryzen keyd[243647]: Managing Wings Tech Xtrfy M4 Keyboard (2ea8:2203) (/etc/keyd/default.conf)
helmi 15 13:01:55 ryzen keyd[243647]: Managing Logitech K580 (046d:4089) (/etc/keyd/default.conf)
❯
```
there was also this line if makes any difference:
`helmi 14 20:21:21 ryzen keyd[197615]: WARNING: failed to set effective group to "keyd" (make sure the group exists)`

**Comment by rvaiya** [comment]
Thanks. It looks like you are running an older version. The commit hash is conspicuously missing, how did you install it? I suspect this should no longer be an issue in the latest commit.

**Comment by nkahe** [comment]
Ok. I installed it using an [Copr user repository](https://copr.fedorainfracloud.org/coprs/dspom/keyd/) (for Fedora 35). Maybe should build it myself then.

**Comment by rvaiya** [comment]
Thanks for making me aware of this. `v2` is currently in beta and changing quite regularly, so I would advise you to check often for bugs and changes. I am trying to keep it reasonably stable, but there is no guarantee of backwards compatibility until it leaves beta, so I encourage you to read the changelog of each release.

**Comment by rvaiya** [comment]
Did upgrading resolve your problem?

**Comment by rvaiya** [comment]
Ah, it seems certain mice (mostly logitech) also behave as keyboards (i.e they have the ability to emit normal keypresses). Unfortunately there doesn't seem to be a way to automatically distinguish between them and keyboards with trackpads. The  recommended workaround is to explicitly blacklist them as you have done.
