### ISSUE TITLE
Key repeat for tap key in overload action

### ISSUE THREAD

**Issue by funcrab** [rvaiya/keyd#140]
Thanks for the cool tool.

Is it possible to make the key repeat if hold down the tapping key (in this case space) with the following settings?

```
[main]
space = overload(M, space)
```

If there is no way to do that, how about making the key repeat when you double-tap within the set time?

The following tool seems to have achieved the tap key repeat function in that way.
https://gitlab.com/interception/linux/plugins/dual-function-keys/

**Comment by rvaiya** [comment]
Thanks, at the moment this is not possible. I am not convinced this is useful enough to warrant a dedicated feature, however I am in the process of considering a generic timeout mechanism which might make this indirectly possible. I would keep an eye on #138.

**Comment by rvaiya** [comment]
It should be possible to achieve this using the new timeout feature. 

E.G 

`timeout(overload(meta, space), 1000, space)`. 

modify to taste.

**Comment by funcrab** [comment]
The following was continuously entered 1 second after `space` was pressed.
```
$ keyd --version
keyd v2.3.0-rc (6581f36)
$
```
```
space = timeout(overload(meta, space), 1000, space)
```
Other existing settings also work by replacing them with the following form.
```
# For vim
:%s@C@control@g
:%s@A@alt@g
:%s@S@shift@g
:%s@M@meta@g
```
#157 problem also solved.
Thank you, Excellent.

**Comment by acro5piano** [comment]
Now `overload_tap_timeout` option is avalable:

```conf
[global]
overload_tap_timeout = 200

[main]
rightshift = overload(shift, esc)
```
