### ISSUE TITLE
Layout doesn't use default bindings

### ISSUE THREAD

**Issue by Jacksaur** [rvaiya/keyd#141]
I could be entirely misunderstanding something here, but Layouts don't seem to work as I expect.
I'm trying to set up a Layout to act as a toggle version of my main layer. According to the manpage, "By default all keys are mapped to themselves within a layout." Which I assumed to mean that any key I do not define in a layout will just act as normal.
But this doesn't seem to be the case. When I switch to my Layout, the keys I've deliberately bound work as such, but any undefined key will not send any output at all. Am I doing something wrong with my config?
I tried adding [main] to the top like in the Manpage sections, but my all bindings would stop working entirely after that.

capslock = overload(layer1, capslock)
rightshift = layout(toggle)

[layer1]
h = left
j = down
k = up
l = right
control = control
shift = shift

[toggle:layout]
rightshift = layout(main)
h = left
j = up
k = down
l = right

**Comment by rvaiya** [comment]
I just tried your config and it seems to work as expected (adding `[main]` to the top, since it is mandatory). What version are you using? The behaviour has changed substantially since v1.

**Comment by Jacksaur** [comment]
Ayup, that should have been my first thing to check. Works under the latest beta, cheers.
Though it does seem to break the method I had to preserve Shift and Control's function whilst keeping my layer enabled. Now both keys just do nothing while the layer is activated. Is there a way to fix that?

**Comment by rvaiya** [comment]
The solution to this is to define a nested layer. See #103 and #137 for details.

**Comment by Jacksaur** [comment]
Adding "left" to each modifier key like in #103 solved my issue. Cheers.
