### ISSUE TITLE
Pressing `Right Shift` + the overloaded `Enter` + `C` key does not produce `c down` event

### ISSUE THREAD

**Issue by alefbragin** [rvaiya/keyd#142]
I have overloaded the `Enter` key in the config:

```ini
[ids]
*

[main]
enter = overload(control, enter)
```

Pressing `Right Shift` + `Enter` + `C` keys emits:

```
keyd virtual keyboard	0fac:0ade	leftshift down
keyd virtual keyboard	0fac:0ade	leftcontrol down
keyd virtual keyboard	0fac:0ade	leftshift up
```

, while pressing these keys with other letters (e.g. the `V` key) emits expected events:

```
keyd virtual keyboard	0fac:0ade	leftshift down
keyd virtual keyboard	0fac:0ade	leftcontrol down
keyd virtual keyboard	0fac:0ade	v down
```

My system:

```
> inxi -Sz
System:
  Kernel: 5.15.21-1-MANJARO x86_64 bits: 64 Desktop: i3 4.20.1
    Distro: Manjaro Linux
> keyd --version
keyd version: 2.2.6-beta (fe49c5cd785ab1c4ccd9aaf4e7a85c30b20a3182)
```

**Comment by rvaiya** [comment]
It would also help if you post the output of `keyd -m` when pressing the same sequence while keyd is *not* running to rule out any issues with your keyboard.

**Comment by alefbragin** [comment]
> I can't seem to reproduce this. Can you post your full config?

This is the full config. I reduce it to minimal state that reproduced this behavior.

> It would also help if you post the output of keyd -m when pressing the same sequence while keyd is not running to rule out any issues with your keyboard.

Pressing and releasing `Right Shift` + `Enter` + `C`:

```
Microsoft Microsoft Ergonomic Keyboard	045e:082c	rightshift down
Microsoft Microsoft Ergonomic Keyboard	045e:082c	enter down
Microsoft Microsoft Ergonomic Keyboard	045e:082c	rightshift up
```

Pressing and releasing `Right Shift` + `Enter` + `V` (other letter works too):

```
Microsoft Microsoft Ergonomic Keyboard	045e:082c	rightshift down
Microsoft Microsoft Ergonomic Keyboard	045e:082c	enter down
Microsoft Microsoft Ergonomic Keyboard	045e:082c	v down
```

It is worth noting that `Left Shift` + `Enter` + `C` works as expected:

```
Microsoft Microsoft Ergonomic Keyboard	045e:082c	leftshift down
Microsoft Microsoft Ergonomic Keyboard	045e:082c	enter down
Microsoft Microsoft Ergonomic Keyboard	045e:082c	c down
```

I connect other keyboard and it works correctly:

```
Logitech K400	046d:4024	rightshift down
Logitech K400	046d:4024	enter down
Logitech K400	046d:4024	c down
```

It seems this is an issue with my keyboard :sweat_smile:

It is not a X11 bug, because it is reproduced in virtual console as well.

I don't know what wrong with Microsoft Microsoft Ergonomic Keyboard.

**Comment by slakkenhuis** [comment]
> I don't know what wrong with Microsoft Ergonomic Keyboard.

Its designers probably just didn't foresee that their artifact would be subjected to the kind of black magic we study here. See https://en.wikipedia.org/wiki/Rollover_(keyboard)

**Comment by rvaiya** [comment]
Thanks for the confirmation.

> Its designers probably just didn't foresee that their artifact would be subjected to the kind of black magic we study here. 

Which is just a fancy way of saying 'blame microsoft' ;).

I'm going to close this for now.
