### ISSUE TITLE
Parse error in application support

### ISSUE THREAD

**Issue by shungo27** [rvaiya/keyd#143]
Doesn't support more than one modifier key?

~/.config/keyd/app.conf
```
[chromium-browser]
control.shift.[ = C-pageup
```

Error message:
`ERROR parsing control.shift.[ = C-pageup: shift.[ is not a valid key.`

keyd 2.2.6-beta

**Comment by rvaiya** [comment]
Each entry in `app.conf` must be a valid keyd expression. `control.shift.[ = C-pageup` doesn't work since `control.shift` is not a valid layer. See the man page for details.

**Comment by shungo27** [comment]
thank you. I understand how it works.

**Comment by Acumane** [comment]
For posterity, since I too had this question,
The statement on `bind` from man page: 
```
The bind command accepts one or more bindings, each of which must have the following form:

           [<layer>.]<key> = <key>|<macro>|<action>

       Where <layer> is the name of an (existing) layer in which the key is to be bound.
```
Emphasis on *existing*. Composite layer `[control+shift]` exists, so `control+shift.[ = C-pageup` works
