### ISSUE TITLE
Can not start keyd-application-mapper with GNOME 3.38 wayland

### ISSUE THREAD

**Issue by shungo27** [rvaiya/keyd#146]
It worked in X11, but Wayland could not start keyd-application-mapper. The extension was not installed too.

```
pi@rpi:~ $ keyd-application-mapper
Gnome detected
Extension ?keyd? doesn't exist
Traceback (most recent call last):
  File "/usr/bin/keyd-application-mapper", line 379, in <module>
    mon.init()
  File "/usr/bin/keyd-application-mapper", line 274, in init
    if 'DISABLED' in run('gnome-extensions show keyd'):
  File "/usr/bin/keyd-application-mapper", line 36, in run
    return subprocess.check_output(['/bin/sh', '-c', cmd]).decode('utf8')
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/bin/sh', '-c', 'gnome-extensions show keyd']' returned non-zero exit status 2.
```

gnome 3.38
keyd 2.2.6-beta

**Comment by rvaiya** [comment]
Gnome's extension system is notoriously erratic and breaks compatibility across versions. Currently I don't plan to support anything older than 41, but patches are welcome :). If upgrading doesn't solve the problem feel free to open another issue.

**Comment by shungo27** [comment]
The cause and timing are unknown, but keyd was added to gnome extensions. It also worked with gnome 3.38 wayland.

**Comment by shungo27** [comment]
I have found that keyd-application-mapper may not work properly if autokey-gtk or its dependent packages are installed. I also found that the keyd extension wouldn't install unless I logged in to Gnome in Wayland.

Uninstall autokey-gtk
`$ sudo apt remove autokey-gtk && sudo apt autoremove`

Install keyd
`$ sudo apt install python3-xlib && git clone https://github.com/rvaiya/keyd && cd keyd && make && sudo make install && cd && sudo rm -r ~/keyd && sudo adduser <USERNAME> keyd && touch ~/.config/keyd/app.conf`

Reboot
`$ sudo reboot`

If you're using Xorg, switch to Wayland and login

Install keyd-application-mapper
`$ keyd-application-mapper`

Logout and Login with Xorg or Wayland

Open the Extensions app and enable keyd

gnome3.38
keyd 2.2.6-beta

**Comment by rvaiya** [comment]
>  I have found that keyd-application-mapper may not work properly if autokey-gtk or its dependent packages are installed.

I believe autokey is an evdev based remapper. In general it is ill advised to use multiple pieces of remapping software since they can interfere with each other. If possible, you should try and do everything in keyd.

> I also found that the keyd extension wouldn't install unless I logged in to Gnome in Wayland.

Yes, this is by design. The user is expected to run `keyd-application-mapped` in the target environment. If you run it under the X version of gnome it will favour X based application tracking.

> Open the Extensions app and enable keyd

It should enable itself using the `gnome-extensions` command, but it is possible this is broken on earlier versions. As I mentioned, anything older than 41 is unsupported.
