### ISSUE TITLE
[Question] Layout indicator

### ISSUE THREAD

**Issue by FoundOne** [rvaiya/keyd#147]
Is there a way to get the current layout/layer and what is the proper way to do it?

**Comment by rvaiya** [comment]
You can set KEYD_DEBUG=1 and inspect the logs. Alternatively you can create a special binding inside the layer like`1 = macro(inside my layer)` to help you debug.

**Comment by FoundOne** [comment]
I was looking for more straight forward feedback, because having the wrong layout when you are typing a password for an example can be frustrating.

**Comment by rvaiya** [comment]
Can you elaborate? I don't know what you mean by 'more straightforward'.

**Comment by FoundOne** [comment]
I mean like a way to say "I'm switching to <this> layout" when the layout hotkey combination is pressed, so it could be captured and used in an app or a toolbar in order to say the current layout. Another option would be just to ask the server from the said app "what's the current layout". In xkb there is an option to make one of the LEDs to be kind of layout indicator, but that imo is sub optimal, because some keyboards don't have them.

**Comment by FoundOne** [comment]
Thanks for the answer.

> It would certainly be possible to add something like this if there is interest, however it would have to be opt-in.
Of course. I agree it should be opt-in.

P.S. I really like this project for its simplicity and zero dependencies. Also I'm pretty tired of the need to deal once for the terminal and once for the gui to have the layouts I need and to have different settings for each of them. I'm bilingual, one of which does not use the Latin alphabet. Also a big fan of colemak, so having an easy way to reconfigure and to have a way to make my own layout is a necessity.

**Comment by rvaiya** [comment]
I finally got around to implementing this. You can opt in by setting `layer_indicator` in the global section.
See the man page for more information.

>  I really like this project for its simplicity and zero dependencies.

I am glad to hear it, those were both design goals :).

> I'm bilingual, and my native language does not use the Latin alphabet.

You may also be interested in the new unicode feature (see the man page). Feedback is welcome.

**Comment by rvaiya** [comment]
I'm closing this for now.
