### ISSUE TITLE
Config is not loaded when file is a symbolik link

### ISSUE THREAD

**Issue by Compile-Time** [rvaiya/keyd#148]
My config is symlinked to the `etc/keyd` directory. Today I upgraded to the 2.2.6-beta and noticed 
that my config would not be loaded.

After a short debugging session I noticed that my config file was not found. I then removed the 
symlink and copied the config file into the `etc/keyd` directory. With a copy of the file keyd finds my config.

I checked if this behavior occurred in the 2.2.5-beta and there symlinks still work without issue. 
Then I checked each commit after the 2.2.5-beta and found out that `23d16a8` is the cause.

More specifically, It is this code:
```c
// src/config.c
const char *config_find_path(const char *dir, uint16_t vendor, uint16_t product)
{
	// ...

	while ((ent = readdir(dh))) {
		char path[1024];
		int len;

		// This if checks for regular files. Symlinks are not regular files.
		if (ent->d_type != DT_REG)
			continue;

		len = snprintf(path, sizeof path, "%s/%s", dir, ent->d_name);
		if (len >= 5 && !strcmp(path+len-5, ".conf")) {
			int ret = config_check_match(path, vendor, product);
			if (ret && ret > priority) {
				priority = ret;
				strcpy(result, path);
			}
		}
	}
	// ...
}
```

Simply changing the if to include symlinks fixes the problem.
```c
if (ent->d_type != DT_REG && != ent->d_type != DT_LNK)
	continue;
```

Is this an intentional change or an oversight?

**Comment by rvaiya** [comment]
Thanks, this was indeed a regression. It should be fixed in the latest commit. I will probably do a version bump layer today.
