### ISSUE TITLE
Doesn't work with Steam

### ISSUE THREAD

**Issue by raffaem** [rvaiya/keyd#151]
I set up keyd using the Quickstart config file to swap Esc with CapsLock.

It works except for Steam games.

When I am on a Steam game, pressing CapsLock does nothing at all, while pressing Esc shows the popup that informs me that CapsLock is on/off.

I have tried doing it at the display server level with:
```
gsettings set org.gnome.desktop.input-sources xkb-options "['caps:swapescape']"
```
but I obtained the exact same result.

Do you know why?

**Comment by rvaiya** [comment]
My guess would be the game is accessing the input devices directly. This is unusual behaviour for most programs, but in the case of steam games all bets are off. The output of `journalctl -fu keyd` after reproducing the problem (running a game) might yield some clues to help confirm this.

**Comment by raffaem** [comment]
So the response is that the "Esc" key works (it means, it acts as CapsLock), but CapsLock does not work (it does nothing).

There is nothing in that log, except that the daemon started and the devices is managing (I don't understand why it's managing also my mouse and my Yubikey)

**Comment by rvaiya** [comment]
Sorry, I misread your original post. If escape is functioning as capslock then keyd still has control the keyboard. What is your full config? Bear in mind that if you are using overload then an extraneous `<control down> <control up>` event will be emitted, which some games may not like.

> I don't understand why it's managing also my mouse and my Yubikey

Presumably because those things can emit key events (so keyd treats them like keyboards). You will probably want to explicitly blacklist the corresponding ids. If you still have problems please open a dedicated issue.

**Comment by raffaem** [comment]
My `/etc/keyd/default.conf` is:

```
[ids]

*

[main]

# Maps capslock to escape when pressed and control when held.
capslock = overload(control, esc)

# Remaps the escape key to capslock
esc = capslock
```

> Bear in mind that if you are using overload then an extraneous <control down> <control up> event will be emitted, which some games may not like.

I don't know what overload is

**Comment by rvaiya** [comment]
In this case it allows capslock to behave as control when held and escape when tapped. In order to achieve this it emits control as soon as capslock is held and releases it when capslock is released, if no other keys have been struck in the interval it will emit `escape`. In most cases this isn't an issue, but most games will probably map control to something important. Try using just `capslock = esc` instead.

**Comment by raffaem** [comment]
Yes! It works with `capslock = esc`! Thank you very much!

Do you by any chance know why it doesn't work at the display server level with:
```
gsettings set org.gnome.desktop.input-sources xkb-options "['caps:swapescape']"
```
?

**Comment by rvaiya** [comment]
The game is likely using evdev directly, which bypasses the display server's input mechanism. The advantage of keyd is that it operates at a lower level and avoids this problem. In general I would avoid mixing keyd and display server input logic.

**Comment by umi2002** [comment]
I've been running into this problem as well. Removing the overload does indeed work, but I would like to keep the tap/hold functionality because I use both often. Is there a better workaround for this?

**Comment by ohmree** [comment]
I ran into this in Hades (the Windows version running through Proton), can confirm changing the `capslock` binding from `overload(control, esc)` to `esc` works as expected.


I tried using the included application mapper script to set `capslock = esc` for the window class `steam_app_<appid>` (as reported by `xprop`) but it doesn't seem to do or log anything (I'm running plasma on x11 and it seems to have a few implementations of its functionality for different desktops though so YMMV).

[`interception-tools`](https://gitlab.com/interception/linux/tools) with its [`caps2esc`](https://gitlab.com/interception/linux/plugins/caps2esc) plugin doesn't have this issue but requires more configuration than I'm comfortable with to get escape to act as control when used in combination with a mouse input so I'll be sticking with keyd for now.

**Comment by nsbgn** [comment]
Might this not be related to https://github.com/rvaiya/keyd/issues/732? Ie the game doesn't register keyup-keydown events that happen instantaneously? To confirm, I would expect `capslock = macro(esc)` to also not work.

If so, the solution would be the same as there: allow configurable time between keyup and keydown.
