### ISSUE TITLE
commit fe49c5cd785ab1c4ccd9aaf4e7a85c30b20a3182 removes mouse support

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/keyd#155]
Hello,

I just noticed that since commit fe49c5cd785ab1c4ccd9aaf4e7a85c30b20a3182 (reducing the memory footprint) mouse key presses (btn left/middle/right) are no longer supported. At least for me this is a huge issue, since I click using capslock and homerow keys. In general, I think that mouse control is quite an important feature, is there a way to get it back? Thanks in advance!

**Comment by rvaiya** [comment]
This is indeed a regression. I have a fairly major patch in the pipeline that should fix this (among other things) which I expect to be released in the next day or two.

**Comment by herrsimon** [comment]
perfect, I'm looking forward to it!

**Comment by rvaiya** [comment]
This should be fixed, though the mouse keys are now called 'leftmouse' 'rightmouse' and 'middlemouse'.

**Comment by rvaiya** [comment]
I'm closing this for now. Feel free to reopen it if you encounter any issues.

**Comment by herrsimon** [comment]
Works like a charm!
