### ISSUE TITLE
With CapsLock as control, Ctrl+space doesn't work with some additional modifiers

### ISSUE THREAD

**Issue by mamg22** [rvaiya/keyd#156]
CapsLock as control and pressing Ctrl+space in combination with some modifiers causes missed keyboad events, Initialy noticed this after `ctrl+super+space` stopped working on my herbstluftwm setup (which uses that for a default keybind).

Steps to reproduce:

1. Use this configuration

```
[ids]

*

[main]

capslock = overload(control, esc)
# Also happens with `layer(control)`
```

2. Open `xev`, combine space with modifiers and check the output.

This is what I get:

1. Pressing `ctrl+space` and `ctrl+alt+space` show up in `xev` as usual
2. Pressing `ctrl+shift+space`, `ctrl+super+space` and `ctrl+AltGr+space` don't produce any events.

Using any other key as control works correctly. Also space seems to be the only one with issues, other keys show up in `xev` no matter how I combine them.

**Comment by slakkenhuis** [comment]
This sounds like a [rollover](https://en.wikipedia.org/wiki/Rollover_(keyboard)) issue; have you checked if the problem persists with another keyboard? Cf. #142

**Comment by mamg22** [comment]
I don't have another keyboard that I can plug into my laptop to test this, but it does seem to be a rollover issue with my keyboard. Tested without `keyd` running and got the same behavior, so doesn't seem and issue on `keyd`'s side.

Thanks for the help :-)
