### ISSUE TITLE
Apple keyboard 'fn' key not being handled correctly

### ISSUE THREAD

**Issue by tjisse** [rvaiya/keyd#159]
The keyboard on my macbook contains a 'fn' key that emits a separate keycode (0x1d0/464) when pressed. I would like to use this key as a modifier, but it doesn't seem to be handled correctly at the moment. In fact, in v2.3.0-rc it seems to trigger the wrong key name.

Output of `keyd -m` when I press the key:

v2.2.7-beta
`Out of bounds evdev keycode: 464`

v2.3.0-rc
`Apple Inc. Apple Internal Keyboard / Trackpad	05ac:025a	fastforward down`
`Apple Inc. Apple Internal Keyboard / Trackpad	05ac:025a	fastforward up`

**Comment by rvaiya** [comment]
I believe this should be fixed in the latest commit.

**Comment by tjisse** [comment]
Yes it works, thanks!
