### ISSUE TITLE
[Usage Question] Possibility to use this to simulate mac-like keyboard function?

### ISSUE THREAD

**Issue by AndrewVanAllen** [rvaiya/keyd#16]
I know this would be possible to use to swap the modifier keys, but in terms of the way those keys change when interacting with certain applications (i.e, terminals), is that something that's within the scope of this project? Or is that something that's going to be limited to display servers? Basically can this project do something similar to [Kinto](https://github.com/rbreaves/kinto/)?

**Comment by rvaiya** [comment]
keyd operates at the level of the keystroke, application specific logic has
to be done at the level of the application or (potentially) display server.
If you provide a better idea of what you are trying to achieve I can point
you in the direction of the appropriate tools.

**Comment by AndrewVanAllen** [comment]
So basically in macos the way the keyboard works (in the ways I wish Linux were to), you have control, option, and command. And they're in the place of Ctrl, Super/Win, and Alt on the keyboard respectively. Command (Alt on normal layout) is used for copy/paste and similar stuff, ctrl is basically the place of super, and option is alt (basically). I can see this by itself being doable with keyd, however macos handles terminal windows as normal (basically treating it as a ctrl/win/alt layout instead of ctrl/option/cmd) and I'm basically asking if that's something that's within the scope of this project. 

I'm currently using [Kinto](https://github.com/rbreaves/kinto/) to achieve it but I'd like something that might be a bit faster and be usable on wayland as well (as kinto relies on X).

**Comment by rvaiya** [comment]
Application specific remapping requires knowledge of the display server as you correctly surmised, however you could do something like the following in keyd.

    alt = layer(M)
    meta = layer(myalt)
    
    [myalt:A]
    
    c = C-c
    v = S-insert

Note that this will cause the command key to behave as a normal alt key in all instances except when c or v is pressed. This is not easily achievable in most other remappings tools. I'm not sure how kinto handles this but I suspect it would break certain modifier combinations.

**Comment by AndrewVanAllen** [comment]
Understandable, that answers my question pretty much. thanx

**Comment by rvaiya** [comment]
If you are still interested in this, keep an eye on #51 and #59.

**Comment by rvaiya** [comment]
Experimental support for this has been added to the latest commit. Your feedback would be appreciated in #91 :).
