### ISSUE TITLE
sending keypresses to upper layer

### ISSUE THREAD

**Issue by aletus** [rvaiya/keyd#163]
Hi, this is most likely not a keyd issue but looking for help troubleshooting its interaction with upper layers.

I compiled and installed keyd on a SBC (running an older kernel 3.10 which may or maynot be related, this system does have X11 and xmodmap works fine).  Compiled fine, make install mentioned something about not installing quirks since libinput is not available or something to that effect.

Created a default config (copied it from the README) that remaps capslock to escape etc. When I start the service, all key presses just stop working, mouse still work.

Luckily the panic buttons combination to stop keyd works and I was able to get keyboard control back.

The monitoring -m switch works well at detecting keypresses so that is working.

I digged into the code and started putting printf to trace the flows and from a cursory understanding everything works internally at detecting and mapping keypresses.   

I ended the tracing at vkbd_send_key function as I understand that would pass it to upper layers.  I think it writes to /dev/uinput.  Apparently it never connected because no keypresses came out. 

Excuse my ignorance but I don't know the layers and flows enough to proceed.    Any suggestion of where to look, and what command to run? 

Thanks

**Comment by rvaiya** [comment]
An you post a copy of your config(s) and the log output (e.g `journalctl -fu keyd`)? Make sure you are running
the latest version as 2.3.1-rc was involved some major changes.

**Comment by rvaiya** [comment]
P.S

I assume you are not using the SBC as an intermediary (usb gadget) and have build without modifying VKBD. That is, you are running it on the SBC itself like you would on any other machine.

**Comment by aletus** [comment]
Hi, thanks for getting back.

No usb gadget, just desktop usage. I compiled from master, just make and make install following instruction on REDAME.  I did not set any special environmental variable as part of the compilation process.

default.conf
```
[ids]

04f2:0402

[main]
```

I just copied the default config from README file.  I added the actual keyboard device vendor ID just in case the other devices  (which came with the kernel, not actual keyboard plugged in) was causing issues.

Currently, I removed the capslock mapping from the default config in README file so the main section is empty which I believe should be pass through everything.

journalctl -fu keyd
```
Mar 24 21:25:14 x keyd[17618]: socket: /var/run/keyd.socket
Mar 24 21:25:14 x keyd[17618]: device added: 0000:0000 MCE IR Keyboard/Mouse (sunxi-rc-recv) (/dev/input/event8)
Mar 24 21:25:14 x keyd[17618]:         ignored (no matching config)
Mar 24 21:25:14 x keyd[17618]: device added: 0001:0001 sunxi_ir_recv (/dev/input/event7)
Mar 24 21:25:14 x keyd[17618]:         ignored (no matching config)
Mar 24 21:25:14 x keyd[17618]: device added: 04f2:0402 Chicony USB Keyboard (/dev/input/event4)
Mar 24 21:25:14 x keyd[17618]:         matched /etc/keyd/default.conf
Mar 24 21:25:18 x systemd[1]: keyd.service: Main process exited, code=exited, status=255/n/a
```

This show process exited when I press the panic combo

**Comment by rvaiya** [comment]
What does `keyd -m` produce while keyd is running? You can test it by doing something like this

`sudo systemctl restart keyd & sudo keyd -m`

and then pressing some keys

What DE/OS are you using? Do you get any output in a virtual console?

**Comment by aletus** [comment]
As mentioned `keyd -m`  detected and shows keypressed and released.  

I have also added  printf in the keyd code to follow the path all the way to vkbd_send_key and it does show keyd detected key pressed and send it on.  

For this SBC I'm using DietPI which is base of Debian 9.13 and XFCE4.

However I have tried keyd in a VT console and it still has the same issues. Once keyd started I can press keys on the keyboard and no output on the console.  I can only get keyboard back by the panic combo.

**Comment by rvaiya** [comment]
> sudo systemctl restart keyd & sudo keyd -m actually only shows a single enter up and then blocked.

Can you post the full output (including all detected devices)?

To clarify, you build with:

`make && sudo make install`

correct?

**Comment by aletus** [comment]
yes, `make && sudo make install`

```
device added: 0000:0000 (MCE IR Keyboard/Mouse (sunxi-rc-recv))
device added: 0001:0001 (sunxi_ir_recv)
device added: 04f2:0402 (Chicony USB Keyboard)
Chicony USB Keyboard    04f2:0402       enter up
```
and then blocked.

That only enter up is the enter key press for starting the command.  It does not occurs every time, probably a timing thing.

Thanks

**Comment by rvaiya** [comment]
Thanks for the additional details. As I suspected, it appears the virtual
device is not getting created. I have added some more failure checks to the
latest commit, can you try running that and posting the log output?

> It does not occurs every time, probably a timing thing before keyd block the rest of the key presses.

Do you mean that keyd works as expected sometimes, or simply that the key up
event is not always emitted? The latter is expected since it depends on how
fast you release enter.

**Comment by aletus** [comment]
> Do you mean that keyd works as expected sometimes, or simply that the key up
> event is not always emitted? The latter is expected since it depends on how
> fast you release enter.

The latter

```
# make
mkdir bin
mkdir: cannot create directory ‘bin’: File exists
Makefile:23: recipe for target 'all' failed
make: [all] Error 1 (ignored)
cp scripts/keyd-application-mapper bin/
cc -DVERSION=\"v2.3.1-rc\ \(417cc5c\)\" -I/usr/local/include -L/usr/local/lib -O3  src/*.c src/vkbd/uinput.c -o bin/keyd -lpthread
```


```
# make install
WARNING: libinput not found, not installing keyd.quirks.
mkdir -p /usr/bin/
mkdir -p /usr/share/man/man1/
mkdir -p /usr/share/doc/keyd/
mkdir -p /usr/share/doc/keyd/examples/
groupadd keyd
groupadd: group 'keyd' already exists
Makefile:34: recipe for target 'install' failed
make: [install] Error 9 (ignored)
install -m755 bin/* /usr/bin/
install -m644 docs/*.1.gz /usr/share/man/man1/
install -m644 docs/*.md /usr/share/doc/keyd/
install -m644 examples/* /usr/share/doc/keyd/examples/
```

When I did `sudo systemctl restart keyd & sudo keyd -m`  it started working, registering keypresses and I thought it was fixed.  

But it's just keyd exiting on its own now due to the code change.  Here is the journal:

```
Mar 25 17:49:38 x systemd[1]: Started key remapping daemon.
Mar 25 17:49:38 x keyd[23723]: ioctl dev_setup: Invalid argument
Mar 25 17:49:38 x systemd[1]: keyd.service: Main process exited, code=exited, status=255/n/a
Mar 25 17:49:38 x systemd[1]: keyd.service: Unit entered failed state.
Mar 25 17:49:38 x systemd[1]: keyd.service: Failed with result 'exit-code'.
```

So it's failing the `ioctl(fd, UI_DEV_SETUP, &usetup) `call but this is too low level for me to understand why.

Although good call on exiting on error otherwise it would blocked all keypresses.

**Comment by rvaiya** [comment]
It looks like your kernel uses an older uinput API. I have made some adjustments to try and accommodate this, can you try the latest version?

**Comment by aletus** [comment]
Awesome, works great now. Typed this using keyd remapping. Thanks!

**Comment by rvaiya** [comment]
Great :). Thanks for reporting this. I'm closing this for now, but feel free to open another issue if you encounter any bugs.
