### ISSUE TITLE
[Question] Some special character mappings are not working

### ISSUE THREAD

**Issue by momu** [rvaiya/keyd#165]
I'm trying to convert my `Xmodmap` settings to `keyd`. It works basically, but some characters don't.

```
[ids]

*

[main]

rightalt = layer(dia)

[dia]

# Map o to ö
o = ω
; = macro(compose o ")
' = macro(compose a ")
[ = macro(compose u ")
s = ß
- = –
\ = °
m = μ
, = «
. = »
r = ™
  

# Map e to €
e = macro(compose c =)

[dia+shift]

o = Ω
; = macro(compose O ")
' = macro(compose A ")
[ = macro(compose U ")
s = ẞ
\ = … 
, = „
. = “
- = —

```
`ä`, `ö`, `ß`, `°` is working, but `μ`, `ω`,`«` not. How can I make them working?

**Comment by rvaiya** [comment]
Can you try the latest patch? I've improved unicode support, though you will need to explicitly link your `~/.XCompose` file (see the man page).

**Comment by momu** [comment]
Thanks for the fast response. I updated to `keyd-git-2.3.1.rc.r18.b04ce33-1`, linked my `.XCompose` (`ln -s /etc/keyd/keyd.compose ~/.XCompose`), restarted `keyd` (`sudo systemctl restart keyd`). But it is not properly working.

When I press `rightalt+s` I expect `ß` but I get `00095`. That was working before, so something definitely changed ;)

Any hints how to investigate?

**Comment by rvaiya** [comment]
Did you restart your applications after linking the XCompose file? Each application reads the file on initialization.

**Comment by momu** [comment]
That was it. Thanks a lot \o/

**Comment by rvaiya** [comment]
Thanks for closing the loop. I've added a note about this in the man page.
