### ISSUE TITLE
Compile errors on musl based Alpine Linux 

### ISSUE THREAD

**Issue by moiselazarus** [rvaiya/keyd#169]
Since a few days, I can't compile keyd on Alpine LInux. Before, it compiled and worked perfect. Here are my errors:

cc -DVERSION=\"v2.3.1-rc\ \(\)\" -I/usr/local/include -L/usr/local/lib -O3  src/*.c src/vkbd/uinput.c -o bin/keyd -lpthread 
src/descriptor.c:15:10: fatal error: error.h: No such file or directory
   15 | #include "error.h"
      |          ^~~~~~~~~
compilation terminated.
src/device.c:21:10: fatal error: linux/input.h: No such file or directory
   21 | #include <linux/input.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
src/vkbd/uinput.c:11:10: fatal error: linux/uinput.h: No such file or directory
   11 | #include <linux/uinput.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:25: all] Error 1

**Comment by rvaiya** [comment]
> 15 | #include "error.h"

Oops. I believe this should be fixed.

> #include <linux/input.h>

This error would suggest you don't have the linux headers installed. If you are using alpine you can install them with `apk install linux-headers`.

**Comment by moiselazarus** [comment]
It is working now! Thank you! I have a APKBUILD and install the alpine-sdk, so the headers should be there.
I use warpd and keyd, and I am very happy with both. Thank you, vielen Dank!
