### ISSUE TITLE
Inconsistency in manpage documentation

### ISSUE THREAD

**Issue by Compile-Time** [rvaiya/keyd#17]
In the manpage an example is given to overload the escape key by using the overload action like this: `overload(C, esc)`. However, under the "Actions" section the manpage states that the `overload` action takes the `keyseq` as the first argument and a `layer` as the second argument: `overload(<keyseq>,<layer>)`

I noticed this inconsistency while migrating my config where the overload action works in the format `overload(<layer>, <keyseq>)`.
I don't know if there are other inconsistencies in the manpage, since I only noticed this issue explicitly. It probably is a good idea to have a look over it to see if everything is correct.

**Comment by rvaiya** [comment]
Thanks for catching this, it has been fixed in the latest commit. I have
reviewed the man page and believe everything else should be correct. Let me
know if you find any other discrepancies.

**Comment by Compile-Time** [comment]
There is one more thing I noticed. In the section "The Modifier Layout" it is mentioned that the `layout` action can take an optional second layer argument and an example like this is given: `layout(dvorak, main)`.

However, this is not reflected in the "Action" section. There it simply states that the `layout` action only takes one argument: `layout(<layer>)`. I think it would be a good idea to represent the optional argument and provide a reference to the "The Modifier Layout" section for more information.

Something like this, perhaps:
**layout(\<layer\>, [\<layer\>]):** Sets the current layout to the given layer. You will likely want to ensure you have a way to switch layouts within the new one. The second layer argument is optional. For more information about the second argument see "The Modifier Layout".

**Comment by rvaiya** [comment]
Fixed in the latest commit.
