### ISSUE TITLE
man.md missing

### ISSUE THREAD

**Issue by mechkit** [rvaiya/keyd#170]
man.md is linked from readme.md, and existed available in [Update docs · rvaiya/keyd@0a5a80e](https://github.com/rvaiya/keyd/commit/0a5a80e6dc5e62663999c51fced8c661799ebad4), but I do not see where it was moved/deleted. (It is not in the file history. I have been on Gitlab for awhile, so don't know where else to look on github.). It is in V1, but not master.

**Comment by rvaiya** [comment]
It was moved to docs/keyd.scdoc. I've amended the readme to remove the link entirely. You are encouraged to access it the old fashioned way :P, but you can browse the scdoc file on github if you really want.
