### ISSUE TITLE
Overload doesn't work with multi-modifier layer?

### ISSUE THREAD

**Issue by DevinTDHa** [rvaiya/keyd#172]
Hello,

First of all thank you for the project, I really appreciate the effort that went into this.

I am having some issues since the latest update though. I want to configure a capslock key that will be escape when tapped and Control+Meta when held. This used to work before.

My Config:

```
[ids]

*

[main]

# capslock = overload(layer(caps), esc)
capslock = layer(caps)

[caps:C-M]


[shift]

leftshift = capslock
rightshift = capslock
```

This config works, but if I try to overload it, it will complain:

```
Apr 01 14:16:54 keyd[23917]: device added: 0c45:9510 S U Keyboard (/dev/input/event23)
Apr 01 14:16:54 keyd[23917]: ERROR /etc/keyd/default.conf:7: layer(caps) is not a valid layer.
Apr 01 14:16:54 keyd[23917]:         matched /etc/keyd/default.conf

```
Although the layer by itself doesn't cause any problems.

**Comment by rvaiya** [comment]
> # capslock = overload(layer(caps), esc)

should be

> # capslock = overload(caps, esc)

I believe this has always been true, but it's possible the syntax changed at some point. `2.3.0-rc` was a major release. so I would recommend reading the [changelog[(https://github.com/rvaiya/keyd/blob/master/docs/CHANGELOG.md#v230-rc). Though your config looks sufficiently spartan to be unaffected by most of the changes.

**Comment by rvaiya** [comment]
Did this solve your problem?

**Comment by DevinTDHa** [comment]
Sorry for the delay, I did not have access to my computer the last couple of days.

Thanks it did indeed solve the issue! Was it because caps defined like `[caps:C-M]` is already a layer?

**Comment by rvaiya** [comment]
Thanks for closing the loop. 

> Was it because caps defined like [caps:C-M] is already a layer?

No, it was just that `overload` takes a layer name directly. `overload(layer(name), key)` is invalid syntax.
