### ISSUE TITLE
keyd-application-mapper fails when system startup

### ISSUE THREAD

**Issue by shungo27** [rvaiya/keyd#173]
Sometimes the keyd-application-mapper fails when system startup.

log message
`keyd-application-mapper fails when system startup`

Mostly started successfully, but if it fails, I must turn on Keyd Extention on GNOME Extentions to start KAM.

**Comment by rvaiya** [comment]
What is the output of ~/.config/keyd/app.conf? Where are you seeing the log
message you posted? It doesn't look like anything produced by the script.

**Comment by shungo27** [comment]
I'm sorry. I copied a completely different text 😰

Correct error message
```
Apr  2 18:19:29 raspberrypi gnome-shell[13252]: ERROR: could not connect to keyd instance, make sure it is running and you are a member of `keyd`
```

**Comment by diegodario88** [comment]
For me it was the following

`Traceback (most recent call last):
  File "/usr/bin/keyd-application-mapper", line 336, in <module>
    lock()
  File "/usr/bin/keyd-application-mapper", line 303, in lock
    lockfh = open(LOCKFILE, 'w')
PermissionError: [Errno 13] Permission denied: '/home/$USER/.config/keyd/app.lock'
`

When running as sudo 
`ERROR: could not find app.conf, make sure it is in ~/.config/keyd/app.conf`

**Comment by rvaiya** [comment]
I'm assuming this is happening because keyd-application-mapper is somehow getting started before keyd. I've allowed the initialization order to be reversed in the latest commit. Can you see if this solves your problem?

**Comment by shungo27** [comment]
I tested the reboot 5 times with keyd 2.3.1-rc (ed7991d). There seems to be no problem so far👍

**Comment by rvaiya** [comment]
Thanks for the confirmation. Feel free to reopen if the issue resurfaces.
