### ISSUE TITLE
Mouse not working as soon as keyd is running

### ISSUE THREAD

**Issue by JanJamaszyk-FlyNow** [rvaiya/keyd#175]
First of all: Super cool project, I love it!
Unfortunately as soon I start keyd my Logitech Mouse using the Unifing Wireless Receiver does not work anymore until I stop it again.

**Comment by rvaiya** [comment]
You will probably need to blacklist your mouse, since it has the ability to send keys. I'm assuming one of your config files looks like this

```
[ids]
*
```

You will need to change it to

```
[ids]
*
-<mouse id>
```
You can discover <mouse id> by running `sudo keyd -m` or inspecting your logs with `sudo journalctl -u keyd -n 100`.

**Comment by JanJamaszyk-FlyNow** [comment]
Thanks @rvaiya !
Maybe the documentation should tell you not use use * or only if you know what you are doing and instead add only the keyboards you want to control?

**Comment by rvaiya** [comment]
Yes, I should probably add a note about it to the documentation. I've been meaning to create a FAQ anyway. For most users this won't be necessary unless they have a mouse which emit keys.

**Comment by fxyu** [comment]
I reinstall my Kernel because of keyd disable the mouse movement. This should be mention on the frontpage.

**Comment by rvaiya** [comment]
@fxyu I've added a note to the readme.

**Comment by JanJamaszyk-FlyNow** [comment]
Hello again,
I still have an issue: I have a Logitech K400 and want to use keyd to remap some keys (https://www.logitech.com/de-de/products/keyboards/k400-plus-touchpad-keyboard.html) as soon as I add the Logitech ID to the keyd config file the logitech touchpad stops working.
Best,
Jan

**Comment by rvaiya** [comment]
Devices like the K400 behave as a single device, which means all mouse events get routed through keyd, which presently doesn't handle them. Fixing this will entail adding proper mouse support, which is on my todo list.

**Comment by rvaiya** [comment]
This should be fixed in the latest commit.

**Comment by JanJamaszyk-FlyNow** [comment]
Cool!! Thanks a lot :)
For some reason it is now always "eating" the mouse wheel of a mouse I have not in my config:
```
[ids]
#046d:4024
1532:0253

[main]
# Remaps the capslock key to backspace
capslock = backspace
```
The ID of the mousewheel that is not working is:
device added: 046d:407b (Logitech MX Vertical)

**Comment by rvaiya** [comment]
Can you post the full log output?

**Comment by JanJamaszyk-FlyNow** [comment]
Interesting, while playing some more with it I found out it is only broken in some applications.
The mousewheel does work under:
- gnome terminal emulator
- gnome pdf viewer
- gedit
The mousewheel is broken under:
- google chrome
- ms teams
- signal messenger
- vs code
- spotify

As soon as I stop keyd the mousewheel starts to work normally again.
To me the logs look all good, keyd seems to spam events for each scroll event:
```
keyd virtual pointer: scroll 0 -1
keyd virtual pointer: scroll 0 -1
Logitech MX Vertical: move 1 0
Logitech MX Vertical: move 0 -1
keyd virtual pointer: move 1 0
keyd virtual pointer: move 0 -1
Logitech MX Vertical: move 0 -1
keyd virtual pointer: move 0 -1
keyd virtual pointer: scroll 0 -1
Logitech MX Vertical: scroll 0 -1
Logitech MX Vertical: scroll 0 -1
keyd virtual pointer: scroll 0 -1
keyd virtual pointer: scroll 0 -1
Logitech MX Vertical: scroll 0 -1
Logitech MX Vertical: scroll 0 -1
keyd virtual pointer: scroll 0 -1
keyd virtual pointer: move -1 0
Logitech MX Vertical: move -1 0
Logitech MX Vertical: move 0 2
keyd virtual pointer: move 0 2
Logitech MX Vertical: scroll 0 -2
Logitech MX Vertical: scroll 0 -2
keyd virtual pointer: scroll 0 -2
keyd virtual pointer: scroll 0 -2
```

**Comment by rvaiya** [comment]
> To me the logs look all good

Nonetheless, I would appreciate if you could post it (the output of `keyd -m` doesn't help).

It would also help to know what DE you are using.

**Comment by JanJamaszyk-FlyNow** [comment]
> Nonetheless, I would appreciate if you could post it (the output of `keyd -m` doesn't help).

Okay, I thought `keyd -m` was what you where looking for. Which logs are you interested in?
> It would also help to know what DE you are using.

I am on Ubuntu 20.04 with standard config so it should be gnome shell I believe?

**Comment by rvaiya** [comment]
> Okay, I thought keyd -m was what you where looking for. Which logs are you interested in?

The output of the daemon. If you are using systemd to manage the process it can be obtained using something like `journalctl -fu keyd`.

I suspect the latest patch should fix this anyway. Can you give it a go?

**Comment by JanJamaszyk-FlyNow** [comment]
Yes, it is fixed, thanks a lot :-)

**Comment by svonjoi** [comment]
Mx Ergo via unifing-wireless-receiver working with * but the configurations applied by xinput also doesnt work. Excluding the mouse id solved the issue
