### ISSUE TITLE
[feature request] key repeat control

### ISSUE THREAD

**Issue by shungo27** [rvaiya/keyd#176]
I made the following key assignment to prevent malfunction of ctrl + q.

```
[control]
q = timeout(noop, 1000, C-q)
```

The purpose is to execute "ctrl + q" and exit only one app if press ctrl + q for more than 1 second. But, if do not release the key immediately after 1 second, ctrl + q will be repeated and the application will be closed one after another. It would be useful to be able to control key repeat.

example 1
```
[control]
# no repeat
q = timeout(noop, 1000, C-q:norp)
```
This allows add a "long press function" to keyboard.

**Comment by shungo27** [comment]
I tried `timeout(noop, 1000, macro(C-q 700ms))`, but I couldn't use it because the keyboard freeze too long when I set a practical value(over 5000ms) to prevent malfunctions.

I found a bug that ctrl is not released when set to 2899ms or longer while testing keyd.

I also tried macro_timeout, but it wasn't practical either because all macros wouldn't repeat.
```
[global]
macro_timeout = 99999

[control]
q = timeout(noop, 1000, C-q)
```

After all, I want the option of "do not repeat" individually.

just idea:
```
timeout(noop, 1000, norepeat(C-q))
```

**Comment by rvaiya** [comment]
> when I set a practical value(over 5000ms) to prevent malfunctions.

5 seconds seems far too long. What is your use case? Most keypresses are on the order of 50ms, so something on the order of 500ms should do the trick without freezing the keyboard for a noticeable amount of time.

I'm not necessarily opposed to making timeouts configurable on a per-macro basis, but I am not yet persuaded that this generically useful, and I'm still not sure why anyone would want a timeout longer than 1s after pressing a key.

**Comment by shungo27** [comment]
I don't want the repeat to be 5 seconds. I want to disable repeat. 5 seconds is an example.

I like the "Warn Before Quitting" feature of Google Chrome for macOS.

How to Bring Back the "Hold ⌘Q to Quit" Prompt in Google Chrome:
https://lifehacker.com/how-to-bring-back-the-hold-q-to-quit-prompt-in-googl-5784153

I'm using macbook as a main PC. I've customized this feature for use in all other apps. Can prevent the app from quitting if accidentally press command + q. If press and hold command + q for 1 second to the app will be closed, but if keep pressing it, other apps will not be closed. Because command + q is not repeating. Also, even if you intentionally press command + q, 1 second is enough time to cancel the end.

I'm using linux as a sub PC. I'd like to achieve the same function with keyd, but if I keep pressing the key for more than 1 second because command + q repeats, all apps will be closed. I can prevent it by releasing the key after a second, but I don't want to be nervous about typing.

**Comment by rvaiya** [comment]
> If press and hold command + q for 1 second to the app will be closed, but
> if keep pressing it, other apps will not be closed. Because command + q is not
> repeating. Also, even if you intentionally press command + q, 1 second is
> enough time to cancel the end.


I understand this part, but I don't understand why you need a large (or infinite) timeout on the other side.

E.G

```
timeout(noop, 1000, macro(C-q 500ms))
```

Or are you suggesting 500ms isn't enough time to recognize that the window has been closed and release the key?

**Comment by shungo27** [comment]
First, you can understand the need to disable repeat by holding down ctrl + q without keyd. Only one app will exit if you hold ctrl + q. Anyway, try holding ctrl + q 10 seconds. However, if you assign [control] q = timeout (noop, 1000, macro (C-q 500ms)), the apps will exit one after another.

Second, it takes a few milliseconds to close the app. Especially for big apps like chromium, it can take even longer. Therefore, in the case of timeout 500ms, there may be almost no time left from the end of the application to the next repeat. I think this also depends on the cpu load and memory usage.

Third, You have to keep looking at the screen to exit the app. Then, it is required to release the finger at the severe timing of 0.x seconds like a video game 😯

**Comment by rvaiya** [comment]
Ok, you've convinced me to make macro timeouts configurable on a per key basis. I will address this when I get some time.

**Comment by rvaiya** [comment]
This should be implemented int he latest commit.

**Comment by shungo27** [comment]
It works perfect!
