### ISSUE TITLE
how to use xf86 keys

### ISSUE THREAD

**Issue by CRAG666** [rvaiya/keyd#177]
@rvaiya Currently I need to add the following keys to a layer
XF86LaunchA
XF86Display
XF86Explorer
etc.

**Comment by rvaiya** [comment]
keyd operates at the level of the keycode. Those are X keysyms, you will to figure out which key codes correspond to the desired keysyms in your X keymap. I believe `XF86Display = switchvideomode`, `XF86Explorer = file`, and `XF86BrightnessDown = brightnessdown`. You can find a list of supported keycodes with `sudo keyd -l`.

**Comment by CRAG666** [comment]
I already found most of them, the most complicated are the XF86LaunchA

**Comment by rvaiya** [comment]
For posterity, here is a complete list:

https://gist.githubusercontent.com/rvaiya/be31f42049a4b5ad46666a8e120d9843/raw/a441bc104f2eba0fb8bf53053d82f06c3a19da64/keysym_to_keyd.txt

**Comment by CRAG666** [comment]
thanks
