### ISSUE TITLE
Meta+Tab+Tab not working as before

### ISSUE THREAD

**Issue by canadaduane** [rvaiya/keyd#178]
Hello!

I'm using config at https://github.com/canadaduane/meta-mac/blob/main/keyd/default.conf

As of https://github.com/rvaiya/keyd/commit/39696b946484e70530e9a42b5c03e0e2a6d157bc, hitting tab more than once while `meta` is held no longer works as expected (this remains true for me if I check out master head as well). With two `tab` presses, I'm expecting the Gnome app switcher to let me switch "two apps" from most recent. It may also be because of https://github.com/rvaiya/keyd/commit/f87d356ff414947e9dd3b75add5ba93459d3d733 but for some reason I was unable to run `make` on that version.

Lastly, I recently re-installed my operating system, so it's also possible I did something dumb when re-installing meta-mac/keyd.

Here is the sequence of events recorded when I hit "meta+(tab tab)". ~~It seems the "not working" version sends an additional tab~~ or maybe it's the opposite?:

```
Working at bce93d5:
keyd virtual keyboard	0fac:0ade	enter up
keyd virtual keyboard	0fac:0ade	leftcontrol down
keyd virtual keyboard	0fac:0ade	leftcontrol up
keyd virtual keyboard	0fac:0ade	leftmeta down
keyd virtual keyboard	0fac:0ade	tab down
keyd virtual keyboard	0fac:0ade	tab up
keyd virtual keyboard	0fac:0ade	leftmeta up
keyd virtual keyboard	0fac:0ade	leftcontrol down
keyd virtual keyboard	0fac:0ade	leftcontrol up
keyd virtual keyboard	0fac:0ade	leftmeta down
keyd virtual keyboard	0fac:0ade	leftcontrol down
keyd virtual keyboard	0fac:0ade	leftmeta up
keyd virtual keyboard	0fac:0ade	leftcontrol up
keyd virtual keyboard	0fac:0ade	leftmeta down
keyd virtual keyboard	0fac:0ade	tab down
keyd virtual keyboard	0fac:0ade	tab up
keyd virtual keyboard	0fac:0ade	leftmeta up
keyd virtual keyboard	0fac:0ade	leftmeta down
keyd virtual keyboard	0fac:0ade	leftcontrol down
keyd virtual keyboard	0fac:0ade	leftmeta up
keyd virtual keyboard	0fac:0ade	leftcontrol up
keyd virtual keyboard	0fac:0ade	leftcontrol down
keyd virtual keyboard	0fac:0ade	leftcontrol up
keyd virtual keyboard	0fac:0ade	leftmeta down
keyd virtual keyboard	0fac:0ade	tab down
keyd virtual keyboard	0fac:0ade	tab up
keyd virtual keyboard	0fac:0ade	leftmeta up
keyd virtual keyboard	0fac:0ade	leftcontrol down
keyd virtual keyboard	0fac:0ade	leftcontrol up
keyd virtual keyboard	0fac:0ade	leftmeta down
keyd virtual keyboard	0fac:0ade	leftcontrol down
keyd virtual keyboard	0fac:0ade	leftmeta up
keyd virtual keyboard	0fac:0ade	leftcontrol up
keyd virtual keyboard	0fac:0ade	leftcontrol down
keyd virtual keyboard	0fac:0ade	c down


Not working at 39696b:
duane@pop-os:~/tmp/keyd$ sudo keyd -m
device added: 0fac:0ade (keyd virtual device)
device added: 0001:0001 (AT Translated Set 2 keyboard)
keyd virtual device	0fac:0ade	enter up
keyd virtual device	0fac:0ade	leftcontrol down
keyd virtual device	0fac:0ade	leftcontrol up
keyd virtual device	0fac:0ade	leftmeta down
keyd virtual device	0fac:0ade	tab down
keyd virtual device	0fac:0ade	tab up
keyd virtual device	0fac:0ade	leftmeta up
keyd virtual device	0fac:0ade	leftcontrol down
keyd virtual device	0fac:0ade	leftmeta down
keyd virtual device	0fac:0ade	leftcontrol up
keyd virtual device	0fac:0ade	leftcontrol down
keyd virtual device	0fac:0ade	leftmeta up
keyd virtual device	0fac:0ade	leftcontrol up
keyd virtual device	0fac:0ade	leftmeta down
keyd virtual device	0fac:0ade	tab down
keyd virtual device	0fac:0ade	tab up
keyd virtual device	0fac:0ade	leftmeta up
keyd virtual device	0fac:0ade	leftmeta down
keyd virtual device	0fac:0ade	leftcontrol down
keyd virtual device	0fac:0ade	leftmeta up
keyd virtual device	0fac:0ade	leftcontrol up
keyd virtual device	0fac:0ade	leftcontrol down
keyd virtual device	0fac:0ade	c down
```

**Comment by rvaiya** [comment]
This is probably a byproduct of changes to the sequence handling logic. swap now accepts a full macro which keyd treats as an independent unit. It seems your config was relying on undefined behaviour, namely that `swap(layer, M-tab)` would not release `meta` after executing `M-tab` as long as `layer` had `M` in its modifier set. Fixing this might be a bit involved. Fixing this might be a bit tricky. I will have to give it some thought.

**Comment by canadaduane** [comment]
There is one other subtle bug that seems to have been introduced--and it may be related (unsure as yet):

When I swap between apps using Cmd+Tab, occasionally the focus does not follow. It's strange, because even clicking on the window with the mouse does not give the window focus. (To get focus back, I have to switch back to original app, then switch again--usually I get focus the 2nd time).

I suspect some kind of complex interaction between the application switcher, keyd, and maybe even gdm, but I haven't been able to pin it down yet.

**Comment by rvaiya** [comment]
I suspect it is a symptom of the same problem. I've modified what I believe to be the the offending behaviour in the latest commit. Can you see if it fixes the problem?

**Comment by canadaduane** [comment]
Success! With regard to `Meta+(Tab Tab)`, this restores the original working behavior, thank you!

WRT the second issue (focus lost on occasion), it seems I still have a problem, but I can't say whether it's keyd or not.

Is there a way to disable the additional 'ctrl' down/up presses, perhaps just to eliminate that as a possible cause of the issue?

**Comment by rvaiya** [comment]
Doing that might have a few other implications (which don't immediately come to mind). I doubt the additional control is causing the problem. You could always disable keyd and see if you can reproduce it. My gnome install is borked (it has randomly decided to segfault) so I can't reproduce this at the moment. My suspicion is that it may have something to do with the application specific remapping logic. If you can't reproduce it while keyd isn't running, the next thing to try is to reproduce it while keyd-application-mapper isn't running.

**Comment by antontkv** [comment]
Also was having this issue in gnome when using alt+tab. I'm not using swap, but this config:
```
[alt]
# Direction keys with alt pressed.
w = A-up
s = A-down
d = A-right
a = A-left
```

Latest commit fixed alt+tab for me also. Thank you.

**Comment by canadaduane** [comment]
I will open a separate ticket for the mysterious focus problem. Thanks again for tab switching joy!
