### ISSUE TITLE
Right Shift and Ctrl keys produce left keys

### ISSUE THREAD

**Issue by antontkv** [rvaiya/keyd#180]
When keyd enable pressing right Shift or Ctrl produces left Shift or Ctrl. I certain that the problem in my environment, because on the other PC it's working fine. I don't know how to diagnose this issue, can you advise?

**Comment by antontkv** [comment]
Sorry didn't found at first issue #114. I'm using Wayland and workaround `rightshift = rightshift` works.

**Comment by rvaiya** [comment]
In general, I would recommend against this. It would be useful to know why you want do this. What is your usecase?

**Comment by antontkv** [comment]
I'm using leftshift and rightshift together as a toggle for capslock. 

```
[main]

capslock = overload(control, esc)

leftshift = layer(shift)
rightshift = rightshift

[shift]
rightshift = capslock
```

**Comment by rvaiya** [comment]
I'm not sure why you need to rebind rightshift. In fact, both rightshift and leftshift are already bound to `layer(shift)`, so you should just be able to do
```
[main]
capslock = overload(control, esc)

[shift]
shift = capslock
```
Which will cause rightshift and leftshift pressed in any order to toggle capslock. Note that `shift` as a key is an alias for `leftshift` and `rightshift` so the above is equivalent to

```
[main]
capslock = overload(control, esc)

[shift]
leftshift = capslock
rightshift = capslock
```

**Comment by antontkv** [comment]
Thank you for the advice. I tried this and it works even better, because now I can press two shifts in any order.

**Comment by rvaiya** [comment]
As a general note, keyd's design encourages you to think about modifiers as just another kind of layer. So the above can be conceptualized as 'make the `shift` key activate `capslock` inside the default `shift` layer'.
