### ISSUE TITLE
[Feature Request] Smoothly transition application bindings for different titles of same app

### ISSUE THREAD

**Issue by i-c-u-p** [rvaiya/keyd#182]
In my app.conf for keyd I'm trying to add mappings for alacritty specifically when htop is opened. After opening htop in alacritty, the binds specific to it under `[alacritty|htop]` in app.conf only work after the window's focus is lost and regained (either by alt-tabbing to another window and back to htop, or dragging alacritty's window). Once the htop specific bindings are active, after exiting htop I have to toggle the window's focus again to go back to the regular `[alacritty]` bindings.

The feature requested is to have the bindings transition seamlessly between `[alacritty]` and `[alacritty|htop]` whenever htop is opened/closed in alacritty without having to toggle the window's focus.

Here's my configs:

~/.config/keyd/app.conf:

```
[alacritty]
extend.i = S-pagedown
extend.o = S-pageup

[alacritty|htop]
extend.i = pagedown
extend.o = pageup

[lorien]
extend+shift.b = C-y
```

<details>
<summary>
/etc/keyd/default.conf:
</summary>

```
[ids]
*

# Colemak-DH (Curl+Angle mods)
[main]
esc = overload(switch, capslock)
capslock = overload(extend, esc)
rightmeta = compose
rightcontrol = rightcontrol
rightshift = rightshift
e = f
r = p
t = b
y = j
u = l
i = u
o = y
p = ;
s = r
d = s
f = t
h = m
j = n
k = e
l = i
; = o
z = x
x = c
c = d
b = z
n = k
m = h

[qwerty]
esc = overload(switch, capslock)
capslock = overload(extend, esc)
rightmeta = compose
rightcontrol = rightcontrol
rightshift = rightshift
e = e
r = r
t = t
y = y
u = u
i = i
o = o
p = p
s = s
d = d
f = f
h = h
j = j
k = k
l = l
; = ;
z = z
x = x
c = c
b = b
n = n
m = m

[noCapsLayer]
capslock = esc

[extend:C]
j = left
k = down
l = up
; = right
1 = f1
2 = f2
3 = f3
4 = f4
5 = f5
6 = f6
7 = f7
8 = f8
9 = f9
0 = f10
- = f11
= = f12
m = home
/ = end
i = pagedown
o = pageup
f = backspace
r = delete
s = layer(alt)
d = layer(shift)
space = layer(control)
g = enter

[extend+control]
s = layer(alt)
d = layer(shift)

[extend+shift]
space = layer(control)
s = layer(alt)

[extend+alt]
d = layer(shift)
space = layer(control)

[extend+control+shift]
s = layer(alt)

[extend+control+alt]
d = layer(shift)

[extend+shift+alt]
space = layer(control)

[extend+control+shift+alt]

[switch]
q = toggle(qwerty)
w = toggle(noCapsLayer)
```

</details>

**Comment by rvaiya** [comment]
Achieving this would require monitoring for title changes that occur while a window is active. The detection code is currently based on focus changes, I believe this is true on all implemented platforms, but I can't remember the specific event hooks used for Gnome/Sway off the top of my head. Implementing this in a cross platform way might be a bit cumbersome. What are you running under?

**Comment by i-c-u-p** [comment]
> Achieving this would require monitoring for title changes that occur while a window is active. The detection logic is currently based on focus changes. I believe this is true on all implemented platforms, but I can't remember the specific event hooks used for Gnome/Sway off the top of my head. Implementing this in a cross DE way might be a bit cumbersome. What are you running under?

My DE is Xfce 4.16

**Comment by rvaiya** [comment]
I've added X support for this in the latest commit. Let me know if it solves your problem.

**Comment by i-c-u-p** [comment]
> I've added X support for this in the latest commit. Let me know if it solves your problem.

Updated and it seems to be working. Thank you!
