### ISSUE TITLE
App focus lost while tab switching

### ISSUE THREAD

**Issue by canadaduane** [rvaiya/keyd#184]
This is a continuation of an issue first reported at https://github.com/rvaiya/keyd/issues/178

> When I swap between apps using Cmd+Tab, occasionally the focus does not follow. It's strange, because even clicking on the window with the mouse does not give the window focus. (To get focus back, I have to switch back to original app, then switch again--usually I get focus the 2nd time).

> I suspect some kind of complex interaction between the application switcher, keyd, and maybe even gdm, but I haven't been able to pin it down yet.

> Is there a way to disable the additional 'ctrl' down/up presses, perhaps just to eliminate that as a possible cause of the issue?

rvaiya wrote:

> Doing that might have a few other implications (which don't immediately come to mind). I doubt the additional control is causing the problem. You could always disable keyd and see if you can reproduce it. My gnome install is borked (it has randomly decided to segfault) so I can't reproduce this at the moment.
> 
> My suspicion is that it may have something to do with the application specific remapping logic. If you can't reproduce it while keyd isn't running, the next thing to try is to reproduce it while keyd-application-mapper isn't running.

**Comment by canadaduane** [comment]
So I disabled `keyd-application-mapper` and the issue is still present.

When I disable `keyd` entirely, there is no issue--tab switching with both "Alt+Tab" and "Meta+Tab" are able to switch apps as designed.

So I'm left with the suspicion that it is keyd, but unsure what to check next. Perhaps I will trim down my keyd configuration and see if I can get a simplest-possible replication.

**Comment by canadaduane** [comment]
Anecdotally, the lost focus issue seems to be happening LESS after your patch that removed extraneous modifier events. However, it has not been entirely eliminated. It feels like a timeout-like issue--something, somewhere, is waiting for N ms after a key press, but not getting the signal it expected (for example).

Thanks for the above patch, I will try it next.

**Comment by canadaduane** [comment]
Disabling additional CTRL sequences via above patch did not improve the situation.

What's strange is that when I use (remapped) Alt-Tab instead of (remapped) Meta-Tab, I never see the "focus lost" issue.

**Comment by rvaiya** [comment]
Can you try the latest commit? I made several changes to the key handling logic which should produce a lot less noise (comparable to v1). I suspect your issue may be related to a race condition in Gnome's input handling which was previously avoided by not immediately sending key down/up pairs in succession.

**Comment by canadaduane** [comment]
I applied the latest, but I'm still seeing the issue on occasion.

**Comment by rvaiya** [comment]
Can you try the tip of test?

**Comment by canadaduane** [comment]
> Can you try the tip of [test](https://github.com/rvaiya/keyd/tree/test)?

2 days of app switching and it has not once failed me since this test branch. How does that extra timeout help??

**Comment by rvaiya** [comment]
I believe it is related to a race condition in mutter (which seems to have originated in clutter). I was able to track it down here:

https://gitlab.gnome.org/GNOME/mutter/-/blob/main/src/core/keybindings.c#L2316

but was too lazy to try and make sense of the ensuing input processing mess. I've encountered a similar issue before, which causes certain clutter based programs to ignore key down/up pairs in quick succession. 

The reason this used to work is because swap would take a key sequence which was held for the duration of the keystroke. Since it now accepts a macro, the initial `<tab down> <tab up>` is sent immediately, causing gnome to choke. I will have to think about how to best address this.

**Comment by rvaiya** [comment]
Apologies for letting this languish. I believe this should be fixed in the latest commit.

**Comment by canadaduane** [comment]
Thanks! I will test and report back in a day or so.

**Comment by canadaduane** [comment]
I think this can be closed--works flawlessly!
