### ISSUE TITLE
Oneshot latch acts over more than one keypress

### ISSUE THREAD

**Issue by ricardo-ayres** [rvaiya/keyd#187]
Okay, I'm not sure if this is a bug or intended behavior:
When a oneshot modifier is tapped and the following keypress is not released before a second key is pressed the oneshot actually works over both keys. Like this:
~Press~ **Tap** oneshot shift; press a, press b, release a, relese b
produces: AB.
I believe this behavior is helpful for pressing combos on a oneshot layer without holding the layer activation button, but it does disrupt typing when using oneshot shift or control: If I hit shift for a oneshot capital letter I expect to get only a single capital letter, not two of them. In my experience this does disrupt typing, especially for passwords as we have no feedback of what was actually typed.
I have 'fixed' this for myself by clearing the oneshot at every keydown event that emits a keycode:
```
@@ -424,8 +424,9 @@ static long process_descriptor(struct keyboard *kbd, uint8_t code, struct descri
                } else {
                        kbd_send_key(kbd, d->args[0].code, 0);
                        send_mods(kbd, descriptor_layer_mods, 1);
-                       clear_oneshot = 1;
+                       //clear_oneshot = 1;
                }
+               clear_oneshot = 1;

                oneshot_latch = 0;
                break;
```
Again, I'm not sure if this is intended or if it is there for any other specific reason, I'm just sharing my rationale based on my own experience. I can surely provide a pull request if that is desirable.

**Comment by slakkenhuis** [comment]
The current behaviour is exactly the reason for me to love oneshot keys, so I'm pretty sure it's intended behaviour. However, I suppose that I could get it back with `overload(shift, oneshot(shift))`? It would evidently cover both our use cases then... but it doesn't look as nice :P

**Comment by ricardo-ayres** [comment]
I'm sorry, I don't think I was very clear on my wording. The behavior you describe is desirable and it is also maintained with the change I proposed. I have edited my text to be more clear.

**Comment by rvaiya** [comment]
I believe the original reason for this was to produce sequences like:

```
shift down
j down
j up
shift up
```

as opposed to

```
shift down
j down
shift up
j up
```

Aside from offending my aesthetic sensibilities, the former intuitively seemed less likely to produce conflicts, though I suspect in practice most software will probably just inspect the modifier mask on key down.

I am not opposed to changing the default behaviour to counteract the problem you describe, but I will have to think about potential side effects. 

I am currently in the process of performing some major surgery on the input logic to address a few other problems, and will probably integrate this into those changes if no objections are raised.

**Comment by rvaiya** [comment]
I suppose once instance in which the current behaviour might be desirable is if the user does something like `<control down> <control up> <c down>` with a oneshot control. The present behaviour will cause holding `c` to produce successive `C-c` events, while the proposed change would subsequently produce an unmodified `c`.

**Comment by ricardo-ayres** [comment]
> I believe the original reason for this was to produce sequences like:
> 
> ```
> shift down
> j down
> j up
> shift up
> ```
> 
> as opposed to
> 
> ```
> shift down
> j down
> shift up
> j up
> ```
> 
> Aside from offending my aesthetic sensibilities, the former intuitively seemed less likely to produce conflicts, though I suspect in practice most software will probably just inspect the modifier mask on key down.

Well, that does make sense, but I also think most software will just use the keydown immediately and just ignore the order in which the keyups happen. I think the reasoning lemnos provided at #34 relates to this: when typing naturally key releases are not really accounted by our brains, so we might really do:
shift down, a down, shift up, a up
when we mean A instead of the intuitive way of thinking of the keypresses:
shift down, a down, a up, shift up
so any software relying on shift being still down on keyup would probably show itself quite weird to

About this:

>The present behaviour will cause holding c to produce successive C-c events, while the proposed change would subsequently produce an unmodified c.

**Comment by rvaiya** [comment]
> Well, that does make sense, but I also think most software will just use the keydown immediately and just ignore the order in which the keyups happen. I think the reasoning lemnos provided at #34 relates to this: when typing naturally key releases are not really accounted by our brains, so we might really do:

I should probably note that I am lemnos :P.

> so any software relying on shift being still down on keyup would probably show itself quite weird to use even without keyd.

This is likely true, though as noted it breaks down in the case in the case of repetitions since the display server generates additional key down events after the modifier is released.

> From what I read of the source code it seems that 'pressed' almost always takes the value from evdev event value, which makes me believe it would have value 2 if an auto-repeat is being triggered and the described behavior could be maintained by not setting clear_oneshot if pressed == 2.

Your patch clears the oneshot modifier immediately on key down, so changing behaviour on repeat wouldn't make a difference. If you clear on key up, then the intervening key down inevitably becomes collateral, but if you clear on key down you lose the ability to repeat the modified key. Having said that, I think the first option is probably more desirable than the first. One could also generate a synthetic key up event after an intervening key down, but that potentially has other implications.

**Comment by rvaiya** [comment]
I believe this should be fixed in the latest commit, which facilitates both behaviours by updating mod state on either the next key up or key down.

**Comment by ricardo-ayres** [comment]
a1edfab5d124aa70493dd988973f17bf4a9a4c30 definetely solves the issue for me. It also preserves the behavior of repeating modifiers. Thank you very much!
