### ISSUE TITLE
Cannot map some keys

### ISSUE THREAD

**Issue by jean-tissot** [rvaiya/keyd#193]
It seems impossible to map some keys if the physical keyboard layout doesn't match the keys defined in the [keys.c](https://github.com/rvaiya/keyd/blob/v2.3.1-rc/src/keys.c) file.  
For example if the _dollar_ ($) key is defined in its own key (and not in the 4 key) it seems impossible to map it  
![image](https://user-images.githubusercontent.com/77532671/164092885-ee1e5ddb-5b1e-4857-baf9-0c86a23cb9fb.png)

**Comment by jean-tissot** [comment]
Is there a solution for (french) azerty keyboards (which doesn't have the _dollar_ key on 4) without using a standard US layout (it would force me to remap many keys) ? 
My problem is that I can't reference the _dollar_ key (S-4 is '4' and 4 is '-' in azerty keyboards) so I can't map it (I want to map A-$ to end to have a vim-like mode)

**Comment by rvaiya** [comment]
How do you access this key normally on an AZERTY layout? keyd operates at the level of the key code, so you need to figure out what keycodes your display server key map uses to produce `$` and map them in keyd. You can discover this using `keyd -m` and pressing the combination that normally produces `$`.

**Comment by rvaiya** [comment]
To elaborate, keyd uses key code names based on a standard US qwerty keyboard (originally the same named used in the kernel). The names themselves correspond to positions (i.e they represent same key codes) which may have different markings on them for non-english boards. The display server then translates these into key syms based on the current layout. In other words `s` in keyd corresponds to the key co

**Comment by jean-tissot** [comment]
> How do you access this key normally on an AZERTY layout? keyd operates at the level of the key code, so you need to figure out what keycodes your display server key map uses to produce `$` and map them in keyd. You can discover this using `keyd -m` and pressing the combination that normally produces `$`.
> 
> Eyeballing some images I've found online, I believe it should be `S-]`, since `]` seems to correspond to the `£` position on french keyboards.

Thanks, I successfully mapped the _dollar_ key, referencing it with ']'
![image](https://user-images.githubusercontent.com/77532671/164105997-fe8c8824-7c26-4f12-85ee-67bfe0992ceb.png)

So, for others like me which don't use a standard US keyboard, the `keyd -m` command is very usefull to get the name of the key

**Comment by rvaiya** [comment]
Yes, I should probably better document this :P. keyd was originally intended for the QMK crowd, who probably have a better understanding of the pitfalls.

**Comment by jean-tissot** [comment]
Thanks a lot !
