### ISSUE TITLE
two-times pressing for changing layer

### ISSUE THREAD

**Issue by fedoranvar** [rvaiya/keyd#194]
Good day to  you!

i have mapped  russian layout to  a layer and switching to it and from it by `rightcontrol`

i've noticed that i need to press 2 times `rightcontrol` to switch layout (it happens in `main` layout and in `russian` layout)

what can cause this behaviour?

thank you!

**Comment by rvaiya** [comment]
Can you post your config?

**Comment by fedoranvar** [comment]
sure.

<details>
<summary> config </summary>
[ids]
*

#-------------------------------------------------------#
#                      main layout
#-------------------------------------------------------#

[main]
rightcontrol=toggle(russian)
leftalt = layer(meta)
capslock = overload(control, esc)
space = overload(space_fn, space)
rightalt = enter
tab = overload(alt,tab)
esc = home
leftcontrol = delete
leftmeta = insert
enter=sysrq
backspace = end

#-------------------------------------------------------#
#                      space_fn
#-------------------------------------------------------#
[space_fn]
# -----------------------------
# ---       functions       ---
# -----------------------------
backspace=capslock

# ------------------------------
# ---       navpad       ---
# ------------------------------
#

y = C-u
u = C-w
i = backspace
o = delete
h = left
j = down
k = up
l = right
# scrolling
m = pageup
, = pagedown

# --------------------------
# ---       numpad       ---
# --------------------------

r=`
q=1
w=2
e=3
a=4
s=5
d=6
z=7
x=8
c=9
v=0

1=f1
2=f2
3=f3
4=f4
5=f5
6=f6
7=f7
8=f8
9=f9
0=f10
-=f11
==f12


# #-------------------------------------------------------#
# #                      russian layout
# #-------------------------------------------------------#
#
[russian]
shift=layer(russian_shift)
space = overload(space_fn, space)
rightcontrol=toggle(main)

q=й
w=ц
e=у
r=к
t=е
y=н
u=г
i=ш
o=щ
p=з
[=х
]=ъ

a=ф
s=ы
d=в
f=а
g=п
h=р
j=о
k=л
l=д
;=ж
'=э

z=я
x=ч
c=с
v=м
b=и
n=т
m=ь
,=б
.=ю
/=.

[russian_shift]
q=Й
W=Ц
e=У
r=К
t=Е
y=Н
u=Г
i=Ш
o=Щ
p=З
[=Х
]=Ъ

a=Ф
s=Ы
d=В
f=А
g=П
h=Р
j=О
k=Л
l=Д
;=Ж
'=Э

z=Я
x=Ч
c=С
v=М
b=И
n=Т
m=Ь
,=Б
.=Ю
/=.

</details>

**Comment by rvaiya** [comment]
You need to eliminate `rightcontrol=toggle(main)` in `[russian]`. This will deactivate the main layer, which is not what you want. 

Simply putting `rightcontrol=toggle(russian)`  in main is sufficient since it will toggle the state of the russian layer. The layer model has changed in `v2.3.0-rc`  (they are now transparent and stacking), so you may want to reread the man page.

**Comment by fedoranvar** [comment]
removing `rightcontrol` resolved the issue
 
 thank you!
