### ISSUE TITLE
How to bind numpad keys?

### ISSUE THREAD

**Issue by ableunable** [rvaiya/keyd#195]
Sorry if issue is not the proper way to ask this - I am fairly new to github. I cannot find anywhere how to signify that the key I want to bind is a numpad key.

For example, I can bind 1 to be Esc, and it works on the alphanumerical 1, but not on the numpad 1. What I would want is that the numpad 1 works as bound, and the alphanumerical 1 works as normal.

How do I denote a numpad key in the conf file? I have tried numpad1, n1, and num1. None of those worked. Please assist me with this issue as I was not able to find any information on how to denote a numpad key.

**Comment by ableunable** [comment]
I have dug through the source code, and in the keys.c file there are all the keys. Numpad keys are kp (numpad 1 is kp1, etc).

**Comment by rvaiya** [comment]
You can also use `keyd -m` to discover keys. Please see the man page.
