### ISSUE TITLE
Alt layouts

### ISSUE THREAD

**Issue by iandoug** [rvaiya/keyd#197]
Hi 

Can this be used to specify alt layouts instead of xkb?

Thanks, Ian

**Comment by rvaiya** [comment]
Indeed. It looks something like this:

```
[ids]
*
[main]
a = a
s = o
....
```

Though if you don't intend to use any of the other features, you may as well just stick to xkb.

**Comment by iandoug** [comment]
Last time I checked QMK, it was not so happy dealing with re-arranged shifts (vs QWERTY), eg having a key that does , and ; instead of , and < 

So exploring alternatives. I think I saw that they have improved that handling.

Does your config above handle 
< = ; 
?

Thanks, Ian

**Comment by rvaiya** [comment]
You can't do `< = ;` directly since `<` doesn't correspond to a key code, but you can treat all modifiers (including shift) as layers. 

E.G

```
[shift]

, = ;
```

**Comment by iandoug** [comment]
So noted, thanks :-)
