### ISSUE TITLE
Enter keeps pressing and then doesn't work

### ISSUE THREAD

**Issue by raffaem** [rvaiya/keyd#198]
Whenever I start the service from the terminal, the enter key is likes is constantly pressed and released.

If I close the terminal with alt+f4 and restart it, the enter key does not work anymore.

I have to use the enter from my numpad, like i'm doing right now

**Comment by rvaiya** [comment]
I believe this should be fixed in the latest commit. Confirmation would be appreciated.

**Comment by rvaiya** [comment]
I'm closing this for now. Feel free to reopen it if the issue is unresolved.
