### ISSUE TITLE
Sharing layer state across multiple keyboards

### ISSUE THREAD

**Issue by slakkenhuis** [rvaiya/keyd#202]
When I press `oneshot(shift)` on one keyboard, keys pressed on another keyboard will be shifted until I press a subsequent key on the first one (or until I confuse `keyd` by also pressing shift on the second keyboard). Switching to a non-modifier layer on one keyboard, of course, has no effect on the other at all.

Contrived as this may sound, there's a use case for changing this behaviour: I have a foot switch that I'd like to use for switching layers, but it's necessarily a separate device and so it can't communicate with what happens on my main keyboard. And, if I remember correctly, the two halves of the R-Go Split keyboard are also registered as two separate keyboards, meaning that it would also be affected by this issue (though I can't confirm that now, as mine is at a friend's).

I can't think of a (non-technical) reason why it would be undesirable to share layer state across multiple keyboards, particularly for those that share the same configuration file. What are your thoughts on this?

Thanks, as always!

**Comment by slakkenhuis** [comment]
> This is a feature not a bug

I figured. :P

> I would be surprised if this was true. 

It's surprising, I know. I'm fairly confident, though: back when I used `setxkbmap`, I actually used this property to assign different keys for each spacebar half, even though the buttons send the same code and there was no custom firmware. My other split keyboards are more sane.

> having state at the level of the keyboard seems like the right thing to do

From a purely technical-aesthetic perspective, I tend to agree. Pragmatically, though, I see little benefit --- whereas I'm probably not going to be the only one with a foot switch or a pathological keyboard. Plus: modifier-layers *aren't* restricted to the keyboard they originate on, so there's an asymmetry there. Even though I admit it's an asymmetry that makes sense, it does reduce the aesthetic value of maintaining the separation.

> One thing it facilitates is making per-keyboard configuration changes with `keyd -e`.

Ah, yeah, I didn't think of that. But `-e` can only operate on existing layers, right? So it would still be possible to have layers activate globally, even if those layers might correspond to different keys for different keyboards. This makes some sense, given that the aforementioned modifier-layers also cross over. It would make custom layers feel more like "real" ones (as long as both devices are managed by `keyd`). But it might upset your stomach for design/implementation reasons, which is a fair cause for closing this issue :)

> This is a reasonable use case, but I would be inclined to fuse the devices using a third party tool. Perhaps interception-tools might be up to the task?

Oooh, good idea, thanks! I was already preparing to write a Python script in case there's a reason for not including it in keyd, but didn't think of interception-tools. Whatever I end up doing, I'll update this issue for posterity.

**Comment by rvaiya** [comment]
> Pragmatically,
though, I see little benefit --- whereas I'm probably not going to be the only
one with a foot switch or a pathological keyboard.

There are some potential practical implications. At the moment a single virtual
keyboard is used for output, but having one per keyboard has previously been contemplated
and may still be implemented at some point in the future (e.g to support multi-seat
setups).

It also isn't clear how keys from one board will apply to the state of the other.
What should a layer key on one board do on another? I suppose one could limit
this to keyboard which share the same config, but that would force the
use of a shared output device (which might not be a big deal).

> Plus: modifier-layers aren't restricted to the keyboard they originate on, so there's an asymmetry there.

This is a function of the fact that all devices share a single output device. Internally, keyd still treats these as distinct events. Though it is worth noting that even if each keyboard had its own output device, modifier state would probably still be shared by the display server in the case of single seat setups.

> Ah, yeah, I didn't think of that. But -e can only operate on existing layers, right? So it would still be possible to have layers activate globally, even if those layers might correspond to different keys for different keyboards. This makes some sense, given that the aforementioned modifier-layers also cross over. It would make custom layers feel more like "real" ones (as long as both devices are managed by keyd). But it might upset your stomach for design/implementation reasons, which is a fair cause for closing this issue :)

Yes, it would be possible to do this (indeed it would be a byproduct of your proposed change) but it would make experimenting with per-keyboard changes more difficult. Most sane people (I'm mad as a hatter) probably don't have multiple keyboards on their desk anyway, so this shouldn't be a major issue.

> I was already preparing to write a Python script in case there's a reason for not including it in keyd, but didn't think of interception-tools. Whatever I end up doing, I'll update this issue for posterity.

👍

**Comment by slakkenhuis** [comment]
> At the moment a single virtual keyboard is used for output, but having one per keyboard has previously been contemplated and may still be implemented at some point in the future (e.g to support multi-seat setups).

Ah, that would make this all more difficult. I suppose you could have one virtual keyboard per config, and that would solve it if every user can have their own config? Pairing virtual keyboards (and therefore layer activations) to configs does sound like a sensible thing to do.

> It also isn't clear how keys from one board will apply to the state of the other. What should a layer key on one board do on another?

I was imagining treating two keyboards as, basically, one big one. A layer would be treated as a global identifier, and toggling/switching/oneshotting to it would apply to all boards. In case the boards don't share the same config, and the layer does not exist for the second one, it would just fall through to the main layer (which is not much different from the current behaviour!).

It's not a bad idea imo, but I confess that assessment is biased by the eccentricities of my own setup. The reasons for not doing this also make sense, so unless the above changed your mind, let's close this issue. Thanks for thinking along!

On the topic of alternative solutions: I roamed the webs and found that I'm [not the only one](https://unix.stackexchange.com/questions/527724/merge-two-usb-ports-two-keyboards-into-one). There even exists a [mergeinputs](https://github.com/Ckath/mergeinputs) program ready-made. I'll try that out when I'm back.

**Comment by rvaiya** [comment]
> Ah, that would make this more difficult, yes. I suppose you could have one
> virtual keyboard per config, and that would solve it if every user can have
> their own config? Pairing virtual keyboards (and therefore layer activations)
> to configs does sound like a sensible thing to do.

This would render wildcard configs useless for multi-seat setups, though they are presently unsupported anyway, and the more I think about it the less inclined I am to add explicit support given that they are probably almost non-existent in the wild.

> I was imagining treating two keyboards as, basically, one big one. A layer
> would be treated as a global identifier, and toggling/switching/oneshotting to
> it would apply to all boards. 
> In case the boards don't share the same config,
> and the layer does not exist for the second one, it would just fall through
> ...
> but limiting to shared config files is probably better).

+1

> The reasons for not doing this make sense, so unless the above has changed your mind, let's close this issue.

The more I think about it, the more it makes sense. You've convinced me to make state per-config. If/when the multi-seat question arises it can be re-examined in isolation.

> There even exists a mergeinputs program ready-made.

This is precisely the sort of thing I had in mind, though I believe that particular implementation has a race condition since it doesn't wrap the output device in a mutex.

**Comment by slakkenhuis** [comment]
>The more I think about it, the more it makes sense. 

That's really great to hear! I can relate, in the past few days it's sounded more and more natural (... the initial suggestion of just sharing layers everywhere, less so.) I also suspect that needing to share layers is more common than I first assumed, since I ran into a Reddit post of someone using two macropads as a split keyboard with separate layers as an explicit drawback.

> that particular implementation technically has a race condition since it doesn't wrap the output device in a mutex.

I was wondering about that but hadn't looked into it. Thanks, now I don't have to ;P

**Comment by rvaiya** [comment]
This should be implemented in the latest commit.

**Comment by slakkenhuis** [comment]
It works really well. Also, your speed continues to impress me. Thanks so much!
