### ISSUE TITLE
`keyd -m` incorrectly displays mouse inputs

### ISSUE THREAD

**Issue by i-c-u-p** [rvaiya/keyd#203]
In `keyd -m` some mouse inputs show up wrong. It displays right clicks as "middlemouse" and middle clicks as "rightmouse". I also have 2 side buttons for navigation but I don't know if their `keyd -m` output is correct or not. The one that goes forward (e.g. in history, for browsers and gui file managers) shows up as "mouse2" and the backward one as "mouse1".

**Comment by rvaiya** [comment]
Oops. Classic transposition error :P. Thanks for catching this.

**Comment by i-c-u-p** [comment]
fixed in 9e49371
