### ISSUE TITLE
Oneshot + toggle does not work as docs describe

### ISSUE THREAD

**Issue by canadaduane** [rvaiya/keyd#204]
I may be misreading, but this "example 3" from the docs does not seem to work as described:

```
	[main]

	control = oneshot(control)

	[control]

	toggle(control)
```

The oneshot aspect seems to work fine, but pressing `ctrl` twice does not seem to enter a state where `ctrl` is always pressed (what should happen, according to doc: "tapping it twice activates it until it is pressed again").

**Comment by rvaiya** [comment]
Oops. That should read `control = toggle(control)`. Thanks for reporting this. 

P.S

The version of swap you were using has been renamed to `swap2`. See the man page for details.
