### ISSUE TITLE
regression: 083b124 breaks certain overload behaviour

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/keyd#205]
Hello,

since commit 083b124bb9858d11c3af3ddcb8699d8b9aa90163, my beloved space-cadet shift like bindings with timeout, such as `leftcontrol = timeout(overload(control,[), 300, overload(control,noop))` have stopped working (neither is the control layer activated, nor a bracket typed upon tapping within the threshold). Did the syntax change?

**Comment by rvaiya** [comment]
Thanks. I believe this should be fixed in the latest commit.
