### ISSUE TITLE
"No defaults" mode

### ISSUE THREAD

**Issue by NekoiNemo** [rvaiya/keyd#209]
Would it be possible to add some sort of flag to have keyd not add default bindings, like mapping rightcontrol to leftcontrol?
I just had a very unpleasant surprise being completely locked inside a VirtualBox's VM since it uses specifically rightcontrol to release inputs back to the host machine (left is used for combinations inside the VM).
I would very much prefer to just set one flag globally rather than having to add "rightcontrol = rightcontrol" across all of the configs on all my machines.

**Comment by slakkenhuis** [comment]
To safeguard against this specific situation, would it be a good idea to have default bindings like this

```
rightcontrol = overload(control, rightcontrol)
rightshift = overload(shift, rightshift)
```

? 

I realize it's very particular, but it would prevent VM confusion like this and it I don't see an obvious downside (you can override it anyway).

**Comment by rvaiya** [comment]
@slakkenhuis The problem with that solution is that it produces an extraneous leftshift keystroke.

E.G

```
leftshift down
leftshift up
rightshift down
rightshift up
```

which potentially has other side effects (and will probably cause even more confusion).  If this is a common enough problem I would be more inclined to fix this from the config side (e.g make `[shift]` a special kind of layer), though that would also involve some ugly tradeoffs.

**Comment by slakkenhuis** [comment]
Ah, good point. Yeah, I agree, then. Was just wondering as I was also setting up a VM
