### ISSUE TITLE
Trying to execute commands as a different user with `su <user> -c <code>` doesn't always work

### ISSUE THREAD

**Issue by TadejDragojlovic** [rvaiya/keyd#211]
I've been trying to get this to work but with no particular success:
```
capslock = layer(l1)

[capslock]
x = command(su <user> -c spotify)
```
After updating the default.conf and restarting the service, utilizing this action doesn't result in anything. I've tried making it work without switching users but some applications couldn't be simply ran as root.

However, I tried stopping the service and manually starting the keyd to see what would happen. 
`sudo keyd`
Utilizing the 'command()' action  now works without a problem and command `spotify` executes without the problem when pressing assigned keys. 
Is there any way I can achieve the successful execution of this command when the keyd.service is ran?

Thank you!

**Comment by rvaiya** [comment]
```
capslock = layer(l1)
```

should be

```
capslock = layer(capslock)
```

unless you have defined `l1` somewhere else.

```
x = command(su <user> -c spotify)
```

I would strongly recommend against doing this. You should map programs like this inside of your window manager or desktop environment. If you are on a single user machine and know what you are doing (e.g have set `DISPLAY` appropriately, etc) then inspecting the log output should yield some clues.

**Comment by TadejDragojlovic** [comment]
Setting the `DISPLAY` variable does the trick. Appreciate it, thank you so much!
