### ISSUE TITLE
"oneshot" link in README is broken

### ISSUE THREAD

**Issue by racalav** [rvaiya/keyd#213]
In the FAQS section of the README, the "oneshot" link is broken. It looks like the updated link should be https://docs.qmk.fm/#/one_shot_keys which matches what I found [on archive.org](https://web.archive.org/web/20211121101129/https://beta.docs.qmk.fm/using-qmk/software-features/one_shot_keys)

**Comment by rvaiya** [comment]
Thanks. I've updated the readme accordingly.
