### ISSUE TITLE
feature request: dynamic macros

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/keyd#215]
As keyd already supports macros, it would be nice if those could be created and played dynamically during runtime. This could for example be implemented by creating `play_macro(register)`, `record_macro(register)`, `record_macro2(register)` actions, where `register` is a single letter (so that 26 macros can be stored on the fly, which should be more than enough) and the three actions record or play a macro inside a given register, with the difference between `record_macro` and `record_macro2` being that `record_macro` plays the macro while it is being recorded (i.e. the application sees the keys while they are being recorded) whereas `record_macro2` doesn't.

Of course, there should be some `max_macro_length` variable so that keyd can't be abused as a clipboard manager and a configurable `end_macro_recording_keyseq` with a sane default. 

Storing into or playing from a specific register could be configured by the user by creating `record_macro`, `record_macro2` and `play_macro` layers, where each letter key is mapped to the corresponding action. For example,

```
[control]
r = record_macro(a)
p = play_macro(a)

[alt+control]
r = oneshot(record_macro)
p = oneshot(play_macro)

[record_macro]
a = record_macro(a)
b = record_macro(b)
...

[play_macro]
a = play_macro(a)
b = play_macro(b)
...
```

Would have `C-r` and `C-p` record and play into/from register `a`, respectively, whereas `C-A-r` would wait for a register to record into as a next keypress and then start recording (analogously for `C-A-p`). 

Maybe it would be a good idea to directly create these special layers inside keyd (similar to the modifier layers), so that switching to such a layer automatically maps the letter keys to the corresponding actions. The above config snippet could then be shortened to

```
[control]
r = swap_layer2(record_macro,a)
p = swap_layer2(play_macro,a)

[alt+control]
r = oneshot(record_macro)
p = oneshot(play_macro)
```

Implementing `record_macro()` could be a bit tricky, as it should completely ignore any of keyd's configuration and only react to `end_macro_recording_keyseq` as well as the usual backspace+escape+enter emergency exit sequence while recording, properly restoring layer and key state in the first case so that `oneshot()`, `layer()`, `toggle()`, `swap()` and `swap2()` all work as expected.

Finally, let me mention that I already wondered whether this functionality should be part of keyd or not, as one could of course easily implement it in a separate tool. However, such a tool would then again be bound to a specific environment (X11, wayland, tmux when inside a terminal etc.) whereas keyd could provide this functionality system wide.

**Comment by rvaiya** [comment]
I am generally opposed to introducing vim-style macros. I'm not convinced they are useful enough to warrant the additional complexity. 

When editing text, such macros are useful because they provide a mechanism by which one off batch operations can be saved and applied within some local context but these opportunities rarely (in my experience) arise when interacting with GUI applications. Occasionally a complex macro can be useful within a particular workflow, but at that point it is worth explicitly writing it out rather than trying to define it on the fly.

**Comment by lucasmr** [comment]
I have another use-case for user-made dynamic macros: games. I would love to record a set of commands on a game and just playing the macro again if needed. Should I make a new feature request or reopen this one?
