### ISSUE TITLE
feature request: enable monitoring of keyd state

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/keyd#217]
It would be useful if one could read the currently active keyd layer and optionally the full layer stack from keyd. The name of the active layer could then be included as a widget in the status bar, optionally printed as a system notification etc. The lack of this functionality currently prevents me from moving rather involved nested layer mappings from my editor to keyd, which would make those mappings available system wide (in particular inside a browser). While this is not critical for my personal use case, it would still be very convenient.

If the debug option (#216) gets implemented, one could possibly solve this by introducing a debug level, so that on the lowest level only layer changes (with the full stack on each layer change) are written to STDOUT in a nicely parseable way. Then the required information could be read in real time by a simple script, filtering and pretty printing the output.
A cleaner option (also applying to the debug option) could be to write this information to some socket, which could then be monitored by external scripts. Active macro recording (#215) could be included in this information as well.

**Comment by rvaiya** [comment]
I've been considering adding something like this, though I'm not sure whether I want it to have first party support (accessible via the IPC interface) as that would encourage polling (without introducing long lived connections) and slow down the main event loop, albeit to an insignificant degree.

At the very least adding some additional debug statements is in order (layer state was in fact logged at one point), though parsing these should be considered fragile as I am liable to occasionally change the wording :P.

**Comment by rvaiya** [comment]
Update: The latest commit logs active layers if `$KEYD_DEBUG` is `>=1`, but I would recommend against relying on the output.
