### ISSUE TITLE
Loading external configuration files

### ISSUE THREAD

**Issue by tkna91** [rvaiya/keyd#218]
Thanks for the cool tool.

I am thinking that if we are using common settings on different keyboards, we need to update each settings file in the same way. (sorry if this isn't the case)

How do you feel it would be useful to be able to load an external settings file with the following image?

Example 1
```
[ids]
0001:0001
source(/etc/keyd/common.conf)
```

Example 2
```
[ids]
0001:0001

[main]
source(common.conf)
```

Example 3
```
[ids]
0001:0001

[source:common.conf]

[main]
```

**Comment by rvaiya** [comment]
I intend to add a simple include mechanism to the config file when I have some time which should address exactly this use case.

**Comment by rvaiya** [comment]
This should be implemented in the latest commit.
