### ISSUE TITLE
`Hyper` key?

### ISSUE THREAD

**Issue by augustebaum** [rvaiya/keyd#220]
Is there a way to remap, say, the spacebar to `space` when pressed and `Hyper` when held?
Asking for a friend wanting to get into i3wm.

**Comment by rvaiya** [comment]
It depends on what you mean by the 'Hyper' key. If you mean 'C-S-M-A' then you can do something like this

```
[main]
space = overload(hyper, space)

[hyper:C-M-S-A]
```

If you just mean the meta key then you can just do

```
[main]
space = overload(meta, space)
```

Please see the man page for more details.

**Comment by augustebaum** [comment]
Thanks so much for the quick reply; I meant the true `Hyper_L` key, the one I see linked to `mod4` when I run `xmodmap`:
```
shift       Shift_L (0x32),  Shift_R (0x3e)
lock        Caps_Lock (0x42)
control     Control_L (0x25),  Control_R (0x69)
mod1        Alt_L (0x40),  Meta_L (0xcd)
mod2        Num_Lock (0x4d)
mod3
mod4        Super_L (0x85),  Super_R (0x86),  Super_L (0xce),  Hyper_L (0xcf)
mod5        ISO_Level3_Shift (0x5c),  Mode_switch (0xcb)
```

The first solution would not work for me because I need to then have `Hyper_L` map to `mod3` for i3 to work -- it can't be a combination of keys AFAIK.

I tried the second solution, but in most situations applications don't recognize that it's a `Meta_L`; `xev` says that I'm holding `Control_L`, `keyd -m` says I'm doing
```
keyd virtual keyboard	0fac:0ade	leftmeta down
keyd virtual keyboard	0fac:0ade	leftcontrol down
keyd virtual keyboard	0fac:0ade	leftmeta up
keyd virtual keyboard	0fac:0ade	leftcontrol up
keyd virtual keyboard	0fac:0ade	space down
keyd virtual keyboard	0fac:0ade	space up
```
and Gnome says I'm holding `Super`.

I know it's not super clear -- I don't understand much about all this and would appreciate any resources or help of any kind. Please tell me if there is anything I should clarify.

**Comment by rvaiya** [comment]
> keyd -m says I'm doing
> [...]

This is the correct *tap* sequence.

If you *hold* space and press another key you should see something like:

```
leftmeta down
a down
a up
leftmeta up
```

where `leftmeta` is what Gnome refers to as the `super` key. Most window managers (including i3) uses `meta` (`super`) by default, so you shouldn't have to mess with your X modifier map.

The `Hyper_L` you are referring to is an X *keysym* that is a relic of another era and is not mapped to any keycode by default. It is best to ignore it unless you are sure you need it.

It is possible that you are releasing space before pressing the next key in your tests. `overload` is sequence based by default, so you may want to use a timeout based solution like `space = timeout(space, 120, layer(meta))`, modifying `120` to taste. 

See also #34 for a discussion about space overloading, though be aware that some of the information is no longer applicable.

**Comment by augustebaum** [comment]
Got it, thanks for the context.

I wanted to avoid using `super` as my window manager mod because I was guessing other applications would be using it and that would generate conflicts -- it doesn't seem to be the case so far. I'll be back if anything comes up.

Thanks again for the quick responses and for the work on `keyd`.

**Comment by svonjoi** [comment]
> The `Hyper_L` you are referring to is an X _keysym_ that is a relic of another era and is not mapped to any keycode by default. It is best to ignore it unless you are sure you need it.

any possibility to add additional full-functional modifier like Mod3 via xmodmap in order to use it in i3? or can it be a possible feature request?

```
clear Lock
keycode 66 = Hyper_L
remove mod4 = Hyper_L
add mod3 = Hyper_L
```

> It depends on what you mean by the `Hyper` key. If you mean `control+shift+meta+alt` then you can do something like this:
> 
> ```
> [main]
> space = overload(hyper, space)
> 
> [hyper:C-M-S-A]
> ```
> 

the problem with creating fake modifier from a combination of other modifiers (C-S-A-M) is that it cannot be used in conjunction with the modifiers that compose it
