### ISSUE TITLE
Modifier keys breaking Unicode characters.

### ISSUE THREAD

**Issue by loops** [rvaiya/keyd#222]
On my Wayland based Linux system here, using Wezterm,  Unicode support works pretty well after linking keyd.compose to ~/.XCompose.  However, having a config like this:

[shift]
102nd = 😹

Doesn't work.  And instead generates  "@#*&"  when the key is pressed.  This happens since the shift key is not released prior to sending the Unicode data.  Something similar happens for an entry in the [main] section, which breaks when you try to shift that key.

The following patch, allows things to work here, but I have no idea if this breaks anything else, or what the ramifications may be for other setups.

```
diff --git a/src/keyboard.c b/src/keyboard.c
index fad8cd7..1db1818 100644
--- a/src/keyboard.c
+++ b/src/keyboard.c
@@ -208,6 +208,7 @@ static void execute_macro(struct keyboard *kbd, int dl, const struct macro *macr
                case MACRO_UNICODE:
                        n = ent->data;

+                       set_mods(kbd, 0);
                        send_key(kbd, KEYD_LINEFEED, 1);
                        send_key(kbd, KEYD_LINEFEED, 0);
```

**Comment by rvaiya** [comment]
Thanks for reporting this. This looks like the right fix. I have applied it to tip of master.
