### ISSUE TITLE
How to put accents on different characters

### ISSUE THREAD

**Issue by momu** [rvaiya/keyd#226]
With xmodmap I was used to have something like this `<compose key>+'+e` which resulted in `é`. How can I do it with `keyd` to put the accent on different characters?

**Comment by slakkenhuis** [comment]
That behaviour should still work. The caveat is that you should run `setxkbmap -option compose:menu` after `keyd` has started. If it doesn't work: what is your compose key set to? What DE are you running?

**Comment by momu** [comment]
> That behaviour should still work.

It does indeed. Thanks
