### ISSUE TITLE
Hold repeat doesn't work in tty

### ISSUE THREAD

**Issue by timsofteng** [rvaiya/keyd#227]
Hello. When i hold h key in my vim or file manager I expect scrolling to bottom.
With enabled keyd it works as expected in sway wm but it doesnt in tty. It does only one jump and stop.

How to fix it?

**Comment by rvaiya** [comment]
This was a bug (actually a regression). It should be fixed in the latest commit.

**Comment by timsofteng** [comment]
Cool!
Could you please prepare minor release with this bugfix? I guess it's important thing.

**Comment by rvaiya** [comment]
I would prefer to let some of the latest changes gestate for a bit longer.
I will probably create another point release in a week or two.
