### ISSUE TITLE
enter key spam after launching keyd

### ISSUE THREAD

**Issue by i-c-u-p** [rvaiya/keyd#230]
Similar to #198

Sometimes when keyd is ran from the terminal using `sudo systemctl start keyd`, the enter key is sent rapidly until a key is pressed. After this happens, the first time enter is pressed nothing happens (it works normally afterwards. This doesn't include pressing numpad's enter since doesn't have this issue).

Steps to reproduce:
1. if keyd is running, stop it with `sudo systemctl stop keyd`
2. launch keyd with `sudo systemctl start keyd`

**Comment by rvaiya** [comment]
I can't seem to reproduce this. What keyboard are you using?

**Comment by slakkenhuis** [comment]
I sometimes have the same issue with my standard laptop keyboard (0001:0001). I'll update too when I find out how to reliably reproduce it.

**Comment by i-c-u-p** [comment]
> I can't seem to reproduce this. What keyboard are you using?

Corsair K70 LUX

Without keyd running this is the output of `keyd -m`:

- Pressing enter
```
Corsair Corsair Gaming K70 LUX RGB Keyboard  Keyboard	1b1c:1b33	enter down
Corsair Corsair Gaming K70 LUX RGB Keyboard  Keyboard	1b1c:1b33	enter up
```
- Pressing numpad enter
```
Corsair Corsair Gaming K70 LUX RGB Keyboard  Keyboard	1b1c:1b33	kpenter up
Corsair Corsair Gaming K70 LUX RGB Keyboard  Keyboard	1b1c:1b33	kpenter down
```

**Comment by bogdbo** [comment]
same thing is happening to me, my entire config is:

```
[ids]

0f39:1083
0001:0001
248a:8367

[main]
capslock = esc
esc = capslock

[control]
n = down
p = up
```

**Comment by jtroo** [comment]
I've found this is pretty easily replicable in my similar project when starting the program via CLI as opposed to running it as a daemon. Seems like it's triggered by having `Enter` held when the `/dev/input` device gets opened.

Two mitigations I've added:
https://github.com/jtroo/kanata/blob/044cf59ede49046921a42f0c1ed358a644051594/src/kanata/mod.rs#L375 (not consistent)
https://github.com/jtroo/kanata/blob/044cf59ede49046921a42f0c1ed358a644051594/src/main.rs#L96 (more effective)

**Comment by rvaiya** [comment]
Thanks for sharing. A timeout is a suboptimal solution, keyd already accounts for this by reading key state directly from the kernel and waiting for any currently pressed keys to be released before grabbing the device. This seems to work on all of my systems, but evidently there is a bug which affects some users.

**Comment by rvaiya** [comment]
I took another look at this. I believe the root problem was a race condition between libinput and the evdev grab. I believe the latest commit should fix it. Would appreciate confirmation from everyone who commented on this thread.

**Comment by i-c-u-p** [comment]
Fixed for me

**Comment by slakkenhuis** [comment]
I suspect it is fixed for me, too. In the previous version, when I held the enter key for a second after pressing it for `sudo keyd`, the enter spam would occur; it no longer does in the new version.

**Comment by rvaiya** [comment]
I'm closing this for now.
