### ISSUE TITLE
map `ctrl+n` to `down`

### ISSUE THREAD

**Issue by bogdbo** [rvaiya/keyd#233]
Hey 👋 first of all thank you for making this tool, this has been the only tool that managed to remap keys correctly in every app I use so far! 

I have been using an old version for a while, `2.1.x` or maybe `2.2.x` it's my bad for not noting it down and now I've upgraded to latest `2.4.0` and a `ctrl+n` still works fine but now if I press `ctrl+shift+n` the end result seems to be `shift+down` which breaks apps that expect `ctrl+shift+n`. I've tried various ways of re-writing this binding but I was unsuccessful so any help/suggestion about how I could obtain the old behaviour would be much appreciated. 

My config is:
```
[ids]
0f39:1083
0001:0001
248a:8367

[main]
capslock = esc
esc = capslock

[control]
n = down
p = up
```

**Comment by rvaiya** [comment]
For consistency, modifiers now apply to layer bindings. If you really want `control+n` to produce `down` and `control+shift+n` to produce `C-S-n` you will have to create an explicit mapping for the latter. You can achieve this using composite layers like so:

 
```
[control]

n = down

[control+shift]

n = C-S-n
```

Note that you will have to do this for each desired modifier combination (e.g `meta+shift+control`).

**Comment by bogdbo** [comment]
Thank you for the help, works wonderful 👍️
