### ISSUE TITLE
please don't put layouts in /etc/keyd

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/keyd#237]
Sorry for being pedantic, but could the new layout files please not be put into `/etc/keyd` but instead into `/usr/share/keyd`? In my opinion they clearly belong there, in good company with X11 xkb layouts, zoneinfo data for setting the timezone etc.

I know that this is a slight inconvenience for the user, who would have to symlink or copy the layout into `/etc/keyd` first (unless the include statement is modified to also accept absolute paths), but given that this is typically done just once it should be bearable.

Another point to make my case: The `/etc/keyd/layouts` subdirectory is a rather canonical name to store custom layouts shared between config files in. It does not feel right that keyd puts some default files there, possibly clashing with preexisting files in case more standard layouts will be added in the future. Even worse, a careless user could modify one such layout file and will then be caught by surprise when the changes are overwritten on the next keyd update.

**Comment by rvaiya** [comment]
I would prefer to keep config paths simple. All paths are relative to the configuration directory and configuration directory is `/etc/keyd/`. 

`/etc/keyd/layouts` just includes some fragments which can optionally be included from within config files. Distros will often prepopulate `/etc/` with things like ssl certs, so there is some precedent.

> Another point to make my case: The /etc/keyd/layouts subdirectory is a rather canonical name to store custom layouts shared between config files in. It does not feel right that keyd puts some default files there, possibly clashing with preexisting files in case more standard layouts will be added in the future. 

I would advise putting custom layers either in the root of `/etc/keyd` or a custom subdirectory to avoid this. 

>  Even worse, a careless user could modify one such layout file and will then be caught by surprise when the changes are overwritten on the next keyd update.

If you need to edit `/etc/keyd/layouts` for legitimate reasons you should probably submit a PR.

**Comment by rvaiya** [comment]
@jbeich @jirutka What do you think?

**Comment by jirutka** [comment]
I completely agree with @herrsimon, these files should be installed into `/usr/share/keyd`.

**Comment by rvaiya** [comment]
Fair enough. I've made `/usr/share/keyd/` a valid search path and modified the Makefile to install the layouts there by default.

> How about a preference based approach (which also lots of applications take)

Yes, that was my intention. I didn't plan on making `/usr/share/keyd` exclusive, I just wanted to minimize surprises by avoiding it altogether. In practice this probably isn't an issue.

> . Another possible advantage of this approach would be that one could move sufficiently generic standard configurations (some already exist in the examples directory) there as well.

`/usr/share/keyd/` seems a bit cleaner. Sub directories can still be used and included for organization.

> This would cater to users who don't want to spend time learning the full configuration syntax (though I suspect that among all keyd users, this is a tiny minority).

+1.
