### ISSUE TITLE
Use plaintext uncompressed man pages (`.1` not `.1.gz`)

### ISSUE THREAD

**Issue by eNV25** [rvaiya/keyd#24]
Man pages don't need to be compressed the work the same as long as they are installed to somewhere in `$MANPATH`.

Most software in my experience always deal with plaintext uncompressed man pages. The man page compression is always done by distro packagers.

It will also be better because git won't need to deal with binary files.

This should be simple to fix by amending the Makefile. I can make a PR if you agree.

**Comment by rvaiya** [comment]
The diff of the troff output isn't useful since it is a generated asset. Man pages are gziped by default on almost all major distros anyway. Unless you are aware of some specific requirement or some package maintainer takes issue with it, I would prefer to leave it as is.
