### ISSUE TITLE
documentation of parsing logic

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/keyd#241]
With the introduction of the new inclusion mechanism, it would be useful to add some more documentation about the parsing logic when the same layer is declared in multiple blocks. Is it true that all but the first modifier declarations are ignored and keybindings from all blocks are taken into account, with later bindings taking precedence over earlier ones ("earlier" and "later" here of course means appearing earlier or later in the file)?

If so, the snippet

```
[test:S]
a = b

[test:C]
a = c
b = c

[test]
b = d
d = e
```

would result in

```
[test:S]
a = c
b = d
d = e
```

If my understanding is correct, I could add a polished version of the above to the documentation and send a pull request.

**Comment by rvaiya** [comment]
This is indeed the current behaviour. I've been reluctant to document it because I haven't decided whether or not declaration behaviour is a feature or a bug. Redundant blocks + precedence based on order are definitely features that are intended to be leveraged by the include mechanism.
