### ISSUE TITLE
[Help] how to use CAPSLOCK as both ESC and CONTROL and ESC as CAPSLOCK

### ISSUE THREAD

**Issue by shaeinst** [rvaiya/keyd#244]
i want my CAPSLOCK as both ESC and CONTROL(held) and SEC as CAPSLOCK.
for example:

```
CAPSLOCK(held) + h/j/k/l should work as left/down/up/right
CAPSLOCK(held) + keys (other than h/j/k/l) should work as CONTROL + keys

ESC(not held) = CAPSLOCK     -> ESC should work as CAPSLOCK
CAPSLOCK(not held) = ESC     -> CAPSLOCK should work as ESC
```

**Comment by rvaiya** [comment]
You want:

```
[main]
capslock = overload(capslock, esc)
esc = capslock

[capslock:C]
h = left
k = up
j = down
l = right
```

Please see the man page for more details.

**Comment by shaeinst** [comment]
@rvaiya works as expected. actually i read the man page but it was little confusion for me. it would be great if you add above example in man page too.
thanks for such great tool

**Comment by shaeinst** [comment]
i made a PR [246](https://github.com/rvaiya/keyd/pull/246) to add that example
