### ISSUE TITLE
cannot write left square bracket inside comment in config file

### ISSUE THREAD

**Issue by lacygoill** [rvaiya/keyd#245]
**Steps to reproduce**

Write this in `/etc/keyd/default.conf`:

    [ids]
    # some [ comment
    *

    [main]
    capslock = overload(control, esc)

(Re)start the keyd service:

    $ sudo systemctl restart keyd

Run `cat(1)`:

    $ cat

Press the capslock key: nothing is inserted.

**Expected behavior**

A literal escape character (caret notation `^[`) is inserted.

**Version of keyd**

`$ keyd --version`: keyd v2.4.1 (bb49007)

**Environment**

Operating system: Ubuntu 20.04.4 LTS

**Additional context**

Relevant entries from the systemd journal:

    $ journalctl --pager-end --no-hostname --unit=keyd.service
    ... systemd[1]: Started key remapping daemon.
    ... keyd[122243]: Starting keyd v2.4.1 (bb49007)
    ... keyd[122243]: socket: /var/run/keyd.socket
    ... keyd[122243]: device added: 046d:c318 Logitech Logitech Illuminated Keyboard (/dev/input/event2)
    ... keyd[122243]:         ignored (no matching config)

The last line suggests that the config file has been ignored, possibly because it was considered as invalid.

---

Not sure, but maybe there is an issue in the parser which should ignore commented lines, including brackets, to prevent a layer heading from being found in the middle of a comment.

---

This is an issue for me, because I would like to write comments such as this one:

    # You can use a whitelist:{{{
    #
    #     [ids]
    #
    #     <vendor id 1>:<product id 1>
    #     <vendor id 2>:<product id 2>
    #     ...
    #}}}
    #   Or a blacklist:{{{
    #
    #     [ids]
    #
    #     *
    #     -<vendor id 1>:<product id 1>
    #     -<vendor id 2>:<product id 2>
    #     ...
    #
    # See: `man keyd /CONFIGURATION/;/exclude`
    #}}}

Or this one:

    # TODO: In the future, replace all occurrences of "{left|right}_square_bracket".{{{
    #
    # We can't do that right now, because of a bug in the `keyd(1)`'s parser.
    # It would make the config invalid:
    #
    #     $ journalctl --pager-end --no-hostname --unit=keyd.service
    #     systemd[1]: Started key remapping daemon.
    #     keyd[116012]: Starting keyd v2.4.1 (bb49007)
    #     keyd[116012]: socket: /var/run/keyd.socket
    #     keyd[116012]: device added: 046d:c318 Logitech Logitech Illuminated Keyboard (/dev/input/event2)
    #     keyd[116012]:         ignored (no matching config)
    #}}}

Both of them contain square brackets.

**Comment by rvaiya** [comment]
Thanks for reporting this. It should be fixed in the latest commit.

**Comment by lacygoill** [comment]
> It should be fixed in the latest commit.

Indeed, it is.  Thank you very much for the quick fix.
