### ISSUE TITLE
[Feature request] create virtual pointer when keyd starts

### ISSUE THREAD

**Issue by i-c-u-p** [rvaiya/keyd#249]
After starting keyd (with `sudo systemctl start keyd`), "keyd virtual pointer" doesn't show up in xinput. For it to be created and show up, the mouse has to be interacted with in some way (Moving the cursor, left/right/middle click, scrolling the mousewheel up/down, or, if present, clicking 1 of the 2 navigation side buttons ("mouse1/2" in `keyd -m`)).

It would be nice if the device was created as soon as keyd started, as my aliases/scripts that change the virtual pointer's sensitivity using xinput on login or after restarting keyd need a sleep period beforehand so I can create the device by moving the mouse.

**Comment by rvaiya** [comment]
This was originally done to prevent libinput from (#66, #42) identifying an external mouse and changing trackpad behaviour. I believe 4426cbc1e obviated the need for this. so I have reverted the change on master. 

I would appreciate confirmation from @canadaduane  and @suderman that this doesn't break anything.

**Comment by i-c-u-p** [comment]
The latest commit fulfills the feature request, though my bash alias for restarting keyd still needs ~0.02s of sleep before the virtual pointer shows up in xinput.

```
rkeyd() {
	sudo systemctl restart keyd
	sleep 0.02
	xinput set-prop 'keyd virtual pointer' 'Coordinate Transformation Matrix' .1, 0, 0, 0, .1, 0, 0, 0, 1
}
```

**Comment by rvaiya** [comment]
>  though my bash alias for restarting keyd still needs ~0.02s of sleep before the virtual pointer shows up in xinput.

This is par for the course. systemd will asynchronously start the daemon. I intend to add sensitivity options shortly, which should obviate the need for the second command altogether.

**Comment by rvaiya** [comment]
@canadaduane 

Yes, that is expected behaviour. I was interested in whether or not the mere existence of the virtual pointer causes any issues on your end (as in #66). 

Your mouse won't actually be subsumed by keyd unless you explicitly add the id to your config file.

E.G

```
[ids]
*
093a:0274
```

At which point you should see movement events with `KEYD_DEBUG=1 sudo keyd -m`.

**Comment by canadaduane** [comment]
I tested with my mouse ID (`093a:0274`) listed under the `[ids]` section, but did not see any mouse events with `sudo KEYD_DEBUG=1 keyd -m`.
