### ISSUE TITLE
Is it possible to use Layers in Application Specific Mappings?

### ISSUE THREAD

**Issue by ziontee113** [rvaiya/keyd#252]
Thank you for the amazing program. My question is Is it possible to use Layers in Application Specific Mappings? I tried writing the same overload layer syntax in my `app.conf` as my `default.conf` and I couldn't make layers work in Application Specific Mappings.

The reason I use this is that I want to map my `space` key to trigger layers. But I only want to do that in Neovim only. Is having layers for `app.conf` possible at all? Thank you very much!

**Comment by rvaiya** [comment]
As outlined in the man page, the syntax of app.conf is `<layer>.<key> = <binding>`. This works as long as `<layer>` is defined in your keyd config (e.g `default.conf`). 

So you can do:

```
[neovim]

space = layer(<layer>)
```

as long as `<layer>` is an existing layer.
