### ISSUE TITLE
Extra `ctrl` for remap from `alt+altgr` layer

### ISSUE THREAD

**Issue by andrey-shigantsov** [rvaiya/keyd#257]
Hi)

>Operating System: Arch Linux                      
>Kernel: Linux 5.18.5-arch1-1
>Architecture: x86-64
>keyd: v2.4.1 (bb49007)

`altgr + alt + h` maps to `left`. When I press `alt` then `altgr` then `h` it works as expected. However, if I first press `altgr` then `alt` then `h`, extra `ctrl` presses and releases are generated.

```
rasaro ~ $ sudo keyd -m
device added: 0fac:0ade (keyd virtual device)
device added: 1532:022b (Razer Razer Tartarus V2)
device added: 1532:022b (Razer Razer Tartarus V2 Keyboard)
device added: 1532:022b (Razer Razer Tartarus V2)
device added: 045e:082c (Microsoft Microsoft Ergonomic Keyboard Mouse)
device added: 045e:082c (Microsoft Microsoft Ergonomic Keyboard)
device added: 1b1c:1b70 (Corsair CORSAIR M55 RGB PRO Gaming Mouse)
device added: 1b1c:1b70 (Corsair CORSAIR M55 RGB PRO Gaming Mouse)
keyd virtual device	0fac:0ade	enter up

# when pres `alt+altgr+h` all ok

# press `alt+altgr`
keyd virtual device	0fac:0ade	leftalt down
keyd virtual device	0fac:0ade	rightalt down
# press `h`
keyd virtual device	0fac:0ade	leftalt up
keyd virtual device	0fac:0ade	rightalt up
keyd virtual device	0fac:0ade	left down
# release `h`
keyd virtual device	0fac:0ade	left up
keyd virtual device	0fac:0ade	leftalt down
keyd virtual device	0fac:0ade	rightalt down
# release `alt+altgr`
keyd virtual device	0fac:0ade	leftalt up
keyd virtual device	0fac:0ade	rightalt up

# when pres `altgr+alt+h` got `ctrl` press and release

# press `altgr+alt`
keyd virtual device	0fac:0ade	rightalt down
keyd virtual device	0fac:0ade	leftalt down
# press `h`
keyd virtual device	0fac:0ade	leftcontrol down  # ???
keyd virtual device	0fac:0ade	leftalt up
keyd virtual device	0fac:0ade	leftcontrol up  # ???
keyd virtual device	0fac:0ade	rightalt up
keyd virtual device	0fac:0ade	left down
# release `h`
keyd virtual device	0fac:0ade	left up
keyd virtual device	0fac:0ade	leftalt down
keyd virtual device	0fac:0ade	rightalt down
# release `altgr+alt`
keyd virtual device	0fac:0ade	rightalt up
keyd virtual device	0fac:0ade	leftalt up
```

**Config:**
```
# Microsoft Ergonomic Keyboard (LXM-00001)
[ids]
045e:082c

[main]

[control]

leftshift = timeout(swap(for_fakemeta_C_S), 1, layer(shift))

[shiftr:S]

#### FAKE META ################################################################

[for_fakemeta_C_S:C-S]
leftalt = timeout(swap(for_fakemeta_C_S_A), 1, layer(alt))

[for_fakemeta_C_S_A:C-S-A]
leftmeta = swap(fakemeta)

[fakemeta:M]

#### ALT VIM ##################################################################

[altgr+alt]

h = left
j = down
k = up
l = right
w = C-right
b = C-left

d = delete
a = home
; = end

/ = C-f

[altgr+alt+meta]
h = A-left
j = A-down
k = A-up
l = A-right

[altgr+alt+control]

f = pagedown
b = pageup
```

The same happens for `j`, `k`, `l`. Didn't check the rest.

Help me please.

**Comment by andrey-shigantsov** [comment]
Yes it does imact functionality in my case.

This is usually not noticeable, but in the application for training hotkeys, I prescribe a sequence of keystrokes and ambiguity is critical here.

**Comment by rvaiya** [comment]
@andrey-shigantsov 

Can you elaborate on your use case? The obvious solution is to temporarily disable keyd while you are running such a program (e.g `alias train="sudo systemctl stop keyd; <program>; sudo systemctl start keyd"`), but I'm curious to know why you find keyd macros insufficient.

> @rvaiya would it make sense to add a deactivation flag in [global]?

I might consider adding a config option to disable the default behaviour, but I will have to think about the potential implications.

**Comment by andrey-shigantsov** [comment]
>disable keyd
It would be possible to go for it, but this is an unnecessary inconvenience.

>but I'm curious to know why you find keyd macros insufficient
I don't understand how macros can help me with this.

>@rvaiya would it make sense to add a deactivation flag in [global]?
It would be nice if you add the ability to disable the default behavior.

Also, a normal solution would be to unify the behavior for both orders of pressing: `alt` then `altgr` and `altgr` then `alt` ... Although I still think the solution to generate control is a crutch.

I also have problems with some programs when using remapping. For example, the slack captures the first `alt` press and shifts the focus to the menu... So a crutch with controls is not a panacea.

**Comment by andrey-shigantsov** [comment]
>My understanding is that you are using another remapping tool to achieve some kind of macro behaviour.

No) I use keyd only)

**Comment by rvaiya** [comment]
> No) I use keyd only)

Can you elaborate? What are you using the 'hotkey training' program for?

> However, as these changes not only require quite some work, but also increase complexity, I think that a rather strong use case is needed. In my opinion, the case of the hotkey training application is not strong enough, as such applications are typically run in isolation (without any multitasking) and thus keyd can simply be disabled during use.

+1

> : If a mouse button is mapped to an overloaded key, then some programs expecting mouse clicks get confused. For example, scrot exits prematurely when called with the -s flag (which expects two successive mouse clicks to determine the rectangle it then takes a screenshot of).

Can you provide an example of this? Overloading necessarily sends the associated modifiers immediately on key (or button) down, this is by design and is distinct from the additional modifiers being discussed (if I've understood you correctly).

**Comment by rvaiya** [comment]
Genesis of the current behaviour: #128

**Comment by rvaiya** [comment]
I am contemplating adding an option to disable the default behaviour, but I am still having trouble convincing myself that this isn't an implementation detail that probably shouldn't be toggleable. 

@andrey-shigantsov Can you elaborate on what you are trying to achieve?  Can't you just train your program on `left`? If you really care about event order, can't you just train on both output sequences independently?

The current behaviour is designed to prevent issues in programs which care about alt keypresses (e.g firefox). Without the modifier guard in place `altgr+alt+h` will produce `<rightalt down> <leftalt down> <leftalt up> <rightalt up> <left>` which the likes of firefox will interpret as `<alt> <left>`, opening the menu and causing you to shake your fist at the heavens.

**Comment by rvaiya** [comment]
> I don't know any other mainstream program showing this behavior.

I believe some UI toolkits (GTK?) do this by default. There is also the matter of Gnome, which binds the meta key to the launcher. I agree that this is bad form, but it is a reality that must be accounted for.

> However, even though the number of users using firefox should by far outweigh
> those experiencing problems, there is still no reason to exclusively cater to
> the former.

I remain unconvinced that disabling the guard is good idea in any instance, though I am open to persuasion on the point if a use case can be presented. 

If another remapping tool (the use of which which is generally advised against) relies on sequence order, then it will still need to account for the difference between `<alt> <altgr> <left>` and <altgr> <alt> <left>`, even with the guard disabled.  This is a fundamental part of the problem of modifier remapping. keyd tries to make as painless as possible, but it is impossible to eliminate all extraneous events.

**Comment by andrey-shigantsov** [comment]
@rvaiya @herrsimon 
Sorry for not replying for a long time. A lot has been going on lately...

> Can you elaborate on what you are trying to achieve? Can't you just train your program on left? If you really care about event order, can't you just train on both output sequences independently?

Of course I can and it's not an important problem for me. However, I want maximum convenience without having to disable the service in particular cases. Therefore, I think it would be useful to disable the default behavior, which solves the problem for firefox and some other applications that I do not use, but does not solve my problem when using slack.

**About problems with [the Slack](https://slack.com/intl/en-gb/).**

> >I also have problems with some programs when using remapping. For example, the slack captures the first alt press and shifts the focus to the menu...
>
>Can you elaborate on this? What is the problematic key sequence in this case?

>I would be very interested in the concrete usability problems you're having with slack as well, i.e. details on

When I press alt (or altgr) inside the slack, the focus shifts from the input field to the menu bar and to return to the input field I need to release and press alt (or altgr) again. See https://user-images.githubusercontent.com/18098085/192240785-72baf38f-ce7e-491a-bd61-e28a1869a23d.mp4.

At the same time, when I hold down two altos, the alt-vim mode is activated (and I have long been accustomed to this) and the focus shift is terribly annoying!

**Comment by rvaiya** [comment]
I've added a flag which allows the user to disable this behaviour to the latest commit. @andrey-shigantsov Let me know if this solves your problem.

> Including the modifier to insert (unless there are good reasons why control is superior to, say, shift). 

This seems like an implementation detail. I am inclined to leave a hard coded control until it can be demonstrated that alternative modifiers are useful in the real world.
