### ISSUE TITLE
keyd and russian layout

### ISSUE THREAD

**Issue by n1rdeks** [rvaiya/keyd#26]
Hello, I use dvp and russian layout.

keyd didn't work with setxkbmap -option ctrl:nocaps -option grp:win_space_toggle us,ru -variant dvp,typewriter

I disable dvp and create dvp in default.cfg:
```
layout(dvorak)

[mylayer]
; = $
a = 0
s = 1
d = 2
f = 3
q = $
z = grave
w = 7
e = 8
r = 9
x = 4
c = 5
v = 6

[dvorak]
meta = meta
space = space
rightalt = layer(mylayer)
leftalt = leftcontrol
compose = compose
esc = esc
capslock = leftalt
leftcontrol = leftalt
rightcontrol = rightcontrol
leftshift = leftshift
rightshift = rightshift
enter = enter
tab = tab
backspace = backspace
up = up
down = down
left = left
right = right
mode = mode
q = semicolon
w = comma
e = dot
r = p
t = y
y = f
u = g
i = c
#....etc
```
after I chose Russian setxkbmap -option grp:win_space_toggle us,ru -variant ,typewriterwith , keymap use old (US). How implement Russian in cfg and change layout without setxkbmap?  Only keyd?

**Comment by n1rdeks** [comment]
i just hacking  holy XKB and add layout to RALT in /usr/share/xkb/symbols/en,ru and change LALT LCTRL in /usr/share/xkb/keycodes/evdev

**Comment by n1rdeks** [comment]
thanks

**Comment by rvaiya** [comment]
See also [#33](https://github.com/rvaiya/keyd/issues/33#issuecomment-916504078)

**Comment by rvaiya** [comment]
There is now first class support for this, so you can do `o = ö` directly in the config file (provided the xkb option `compose:menu` is set. See the man page for details.

**Comment by n1rdeks** [comment]
Thanks for answer, but I create my layout for XKB (X/Wayland), Windows.  
So, I didn't use any programs today.

**Comment by fedoranvar** [comment]
@rvaiya 

so we'll be able to map language layout in keyd itself?

[russian:layout]
q=й
w=ц
e=у
...

?

**Comment by rvaiya** [comment]
@fedoranvar Indeed. It uses X macros, so I'm not sure how well it would work for a full layout but it seems to work reasonably well for the odd international character. I would appreciate it if you could give it a try and let me know how it goes.

**Comment by rvaiya** [comment]
P.S

`:layout` is no longer valid syntax. You may want to reread the man page.

**Comment by fedoranvar** [comment]
there is no way for wayland yet?

**Comment by rvaiya** [comment]
It should work on both, though you may need to explicitly enable XIM if you
use gnome. If you encounter any issues, feel free to open a dedicated issue.

**Comment by fedoranvar** [comment]
tested full language remapping - it works on wayland

**Comment by n1rdeks** [comment]
Cool...

**Comment by fedoranvar** [comment]
@rvaiya there is some constaint.

If i remap all characters + digits and modifiers, it throws something liike: 

```you've exceeded max count of macros > 60```

**Comment by rvaiya** [comment]
> you've exceeded max count of macros > 60

This should be fixed in the latest commit.

> when i'm trying to type uppercase letter it prints this....

The reason this happens is because keyd doesn't know how to produce uppercase letters on its own. It just produces the unicode character you mapped to the key. So when you do `shift+<key>` it will do `<shift>+<xcompose macro>` which will result in the garbled output you are seeing. To solve this problem you need to manually override the shifted keys like so:

```
[russian]
q = д
[shift+russian]
q = Д
# etc..
```
