### ISSUE TITLE
Discussion place

### ISSUE THREAD

**Issue by timsofteng** [rvaiya/keyd#269]
Hello. May you open the discussion on GitHub or create irc channel to ask the questions which are not the tickets? Or it's ok for you to publish everything in the issues?

**Comment by rvaiya** [comment]
I've been meaning to create a FAQ file for commonly asked questions. Beyond that, I'm not convinced of the utility of a discussions page. 

Feature requests/ideas should be filed as issues, and I don't want to encourage the project page to become a place for non-development related questions. I am rvaiya on oftc and just created #keyd. Feel free to ping me there.

**Comment by timsofteng** [comment]
Cool! If that channels already work in irc then this issue is closed.
P.s please consider adding both irc to readme.
