### ISSUE TITLE
Bind macro and action to a single key

### ISSUE THREAD

**Issue by Nimmidev** [rvaiya/keyd#270]
Hey, thanks for this awesome tool.
Been using it for a week now and I just encountered a problem trying to switch the layer and executing a macro at the same time.
```ini
[ids]
*

[main]
a = toggle(some_layer)

[some_layer]
b = oneshot(other_layer)

[other_layer]
c = macro(C-l something enter) #, toggle(main)
```
I have roughly something like this.
I want to be able to toggle the main layer after using `c` in `other_layer`.
But it shouldn't just toggle the layer, it should also run the macro before.

Is this somehow possible at the moment?

**Edit:**
I also have a use case where a macro and running a command would be useful (for one key press). So i think the option to chain multiple actions/macros/etc together would be awesome.

**Comment by rvaiya** [comment]
Given your config snippet, I think you may have some misconceptions about how the layer model works. Layers are *occluding* which means that when you do `toggle(some_layer)` both `some_layer` and `main` are active, with any bindings in the former taking precedence over the latter. Thus you probably don't really want to toggle `main` inside `other_layer` *which will deactivate the already active main layer*, instead you simply want to disable all of the occluding layers.

If your goal is to have `<a><b><c>` produce `<C-l> "something" <enter>`, then you probably want something like this:

```
[ids]
*

[main]
a = oneshot(a)
[a]
b = oneshot(b)
[b]
c = macro(C-l something enter)
```

The first oneshot action will activate `a`, and then clear it after the first key stroke, so you don't have to worry about explicitly toggling it. Having said that, there is currently no way to both execute a macro and toggle a layer. I take a conservative approach to new actions, but if you feel there is a good use case for a variant of toggle feel free to make a case for it.

**Comment by rvaiya** [comment]
I've added a new action called `toggle2` which executes a macro before toggling the target layer. It should allow you to achieve your objective using something like this:

```
[vim_mode]
c = oneshot(vim_mode_change)

[vim_mode_change]
w = toggle2(vim_mode, macro(C-S-right delete))
c = toggle2(vim_mode, macro(home S-end delete))
```

**Comment by Nimmidev** [comment]
Oh man. You are the best. Works like a charm. Thank you very much.
