### ISSUE TITLE
Alias for # (number sign)

### ISSUE THREAD

**Issue by colinramsay** [rvaiya/keyd#271]
I feel like this might be my misunderstanding how keyd works, but it would be good to get some clarity. Here's my example config:

```
[ids]

*

[main]
3 = #
```

Now when I press 3, I get a pound sign: £. I'm guessing this is something to do with my underlying keyboard setup (UK) but nonetheless I kind of expected that whatever literal I put in an alias would be the thing I end up seeing. Any help understanding this would be much appreciated!

**Comment by rvaiya** [comment]
keyd operates at the level of the key code. It has no knowledge of your X layout, which converts key codes into key syms. On an ANSI US keyboard with a corresponding qwerty layout on X the two are the same, but they will differ in all other instances.

The keys on your keyboard may not actually correspond to keyd's internal names, which are based on a standard US ANSI board (and are the same names used in the kernel). You can discover the internal names of the codes the keys on your board produce by using `keyd -m`.

Broadly it looks something like this:

```
keyboard --------> kernel -------> keyd -------> Display Server (X/wayland)  -------> application
         scancode         keycode       keycode  (code->sym based on layout)  keysym
```

**Comment by colinramsay** [comment]
Thanks!

> You can discover the internal names of the codes the keys on your board produce by using keyd -m.

I don't think this helps me here as, in the example of my config, it just shows the letter 3 as that's (correctly) the physical key that's being pressed. 

Through `xmodmap -pke` I found out that AltGr + 3 should give me a # sign. Turns out my keyboard doesn't have AltGr so I've set capslock to do that:

```
[ids]

*

[main]
capslock = layer(capslock)

[capslock:G]
```

Hopefully that helps someone else, and I appreciate your quick response to point me in the right direction.

**Comment by rvaiya** [comment]
> I don't think this helps me here as, in the example of my config, it just shows the letter 3 as that's (correctly) the physical key that's being pressed.

The best way to solve this problem is to use a qwerty layout and link the Xcompose file listed in the unicode section of the man page. This should make all generated key syms (including arbitrary unicode character) match their text representations in the config file.

> Through xmodmap -pke I found out that AltGr + 3 should give me a # sign. Turns out my keyboard doesn't have AltGr so I've set capslock to do that:

AltGr is actually just the 'rightalt' keycode interpreted by your display server. If your keyboard really doesn't have one you can do '<key> = rightalt', but it would only be useful in conjunction with a non-us layout in your display server. 

Instead I would favour something like this:


```
# Replace rightcontrol with your desired altgr surrogate
rightcontrol = layer(myAltGrLayer)

[myAltGrLayer]

# Requires symlinked xcompose file to work
3 = £
4 = *
5 = 😊
# etc..

```

which offets more flexibility.
