### ISSUE TITLE
Can I map the left mouse button?

### ISSUE THREAD

**Issue by Leiyi548** [rvaiya/keyd#272]
This is my keyd config:
[ids]

*

[main]

capslock = overload(capslock_layer,esc)

[capslock_layer]

enter = left mouse down

I want map capslock+enter = left mouse click. but not working.

**Comment by rvaiya** [comment]
You want `leftmouse`. You can list all valid keys with `keyd -l`. See the man page for more details.

**Comment by Leiyi548** [comment]
> You want `leftmouse`. You can list all valid keys with `keyd -l`. See the man page for more details.

Thank you
