### ISSUE TITLE
Mouse control

### ISSUE THREAD

**Issue by fedoranvar** [rvaiya/keyd#275]
Good day to you!

Got a little bit confused, is `keyd` capable of controlling mouse?

I can see messages in commits and in issues, but still can't find a way to keybind mouse movement

Thank you!

**Comment by rvaiya** [comment]
At the moment keyd does not allow you to control your mouse from your keyboard. It should be fairly trivial to add this, and it is on the roadmap. You may want to check out https://github.com/rvaiya/warpd in the meantime. 

The mouse functionality you are seeing concerns coordinating mouse button presses with key presses (e.g clearing oneshot modifiers on button presses).

**Comment by fedoranvar** [comment]
got it. 

Thank you!

**Comment by voronind-com** [comment]
@rvaiya Is controlling mouse movement from key presses still planned? warpd is broken for me on Sway, sadly.
