### ISSUE TITLE
How to use keyd action in a shell script

### ISSUE THREAD

**Issue by yyy33** [rvaiya/keyd#276]
I want to bind a key to execute a shell script, and then make some logical judgments in the script. For example, depending on the current focus application, I know that rvaiya has written a python script to realize this function. However, I want to realize this function in the shell through the IPC of awesomewm, because the startup time of the shell should be a little faster than that of Python. Is there any way to achieve this

**Comment by yyy33** [comment]
> I don't know much about awesome but it is probably a better idea to bind your script to a key using awesome's keybinding mechanism, which can probably pass details of the currently focused window. Keyd is display server agnostic and hence scripts which rely on some display server are not a good fit for its `command()` action. Also, the startup time difference between python and a shell should be of no concern for interactively called scripts (or do you notice a couple of milliseconds difference)?
> 
> Apart from this, your question how to obtain the focused window from within a shell script is strictly speaking not related to keyd.

I am not asking how to get the focus of the window from the shell, I mean if it is possible to use keyd's action in the shell via ipc, it is possible to enhance the flexibility of keyd's profile so that keyd's action can be used dynamically in the shell according to some logical conditions
通过DeepL翻译 https://www.deepl.com/app/?utm_medium=android-share

**Comment by yyy33** [comment]
> I don't know much about awesome but it is probably a better idea to bind your script to a key using awesome's keybinding mechanism, which can probably pass details of the currently focused window. Keyd is display server agnostic and hence scripts which rely on some display server are not a good fit for its `command()` action. Also, the startup time difference between python and a shell should be of no concern for interactively called scripts (or do you notice a couple of milliseconds difference)?
> 
> Apart from this, your question how to obtain the focused window from within a shell script is strictly speaking not related to keyd.

I could do this via the bindings in awesome, but I think this should be done by keyd

**Comment by yyy33** [comment]
> I don't understand what you actually want to achieve. Can you please provide some details?`

For example, I bind action command(a.sh) to key a, when I press a script a.sh will be executed, at this time I want to execute some keyd action in a.sh by ipc, such as oneshot, toggle, etc.

**Comment by yyy33** [comment]
> I see. Extending the IPC mechanism is on @rvaiya's todo list, currently it is not possible to trigger actions from outside of keyd.
> 
> However, it is very likely that most of what you want to achieve can be done with the existing feature set. If you want some comments, please provide yet more details.

Yes, as the keyd documentation says, multiple tools are needed to implement

**Comment by rvaiya** [comment]
>I mean if it is possible to use keyd's action in the shell via ipc, it is possible to enhance the flexibility of keyd's profile so that keyd's action can be used dynamically in the shell according to some logical conditions.

Can you elaborate on your intended use case?

**Comment by yyy33** [comment]
> > I mean if it is possible to use keyd's action in the shell via ipc, it is possible to enhance the flexibility of keyd's profile so that keyd's action can be used dynamically in the shell according to some logical conditions.
> 
> Can you elaborate on your intended use case?

I'm using a browser plugin called `surfingkeys`, which allows me to use the keyboard to control my `chromium`, such as type `d` to `page down`, `u` to `page up`, `e` to jump to the `previous tab`, `r` to jump to the `next tab`

But due to some limitations of chromium, the plugin can not be used in the browser's built-in tabs, so I want to use `keyd` to bind some keys to solve this problem

For example, I want to bind `d` in keyd to execute a script, the flow of the script is like this:
1. determine whether the current focus of the application is chromium, if not, send the keycode `d`
2. determine if the current chromium is typing text, if it is, send the keycode `d`, if it is not, send the keycode `pagedown`

The first point I can achieve in the script through the ipc provided by `awsome wm`, however, the second point I have checked for a long time, there is no way to get whether chromium is typing text or not. So I think my idea is still not possible, even if the keyd can send action in the script

Translated with www.DeepL.com/Translator (free version)

**Comment by rvaiya** [comment]
> The first point I can achieve in the script through the ipc provided by awsome wm

You can just use `keyd-application-mapper(1)` which is intended for precisely that purpose (and works across multiple window managers). It has minimal dependencies, so unless you don't have python on your machine there is really no reason not to use it.

> determine if the current chromium is typing text, if it is, send the keycode d, if it is not, send the keycode pagedown

You can already achieve this using the existing IPC functionality by just changing the binding on focus (i.e `keyd -e 'd = pagedown'`). This is arguably more elegant than binding the key to an external command and trying to manage key state in-script.

> there is no way to get whether chromium is typing text or not.

A browser extension is probably the correct place for this since you are trying to interrogate and respond to local browser state, sadly chrome extension APIs are fairly restrictive. If you are desperate enough, you could probably write an extension which communicates with a local process on your machine that makes the necessary keyd invocations.

**Comment by yyy33** [comment]
> > The first point I can achieve in the script through the ipc provided by awsome wm
> 
> You can just use `keyd-application-mapper(1)` which is intended for precisely that purpose (and works across multiple window managers). It has minimal dependencies, so unless you don't have python on your machine there is really no reason not to use it.
> 
> > determine if the current chromium is typing text, if it is, send the keycode d, if it is not, send the keycode pagedown
> 
> You can already achieve this using the existing IPC functionality by just changing the binding on text-input (un)focus (i.e `keyd -e 'd = pagedown'`). This is arguably more elegant than binding the key to an external command and trying to manage key state in-script.
> 
> > there is no way to get whether chromium is typing text or not.
> 
> A browser extension is probably the correct place for this since you are trying to interrogate and respond to local browser state, sadly chrome extension APIs are fairly restrictive. If you are desperate enough, you could probably write an extension which communicates with a local process on your machine that makes the necessary keyd invocations.

You are right, using keyd -e is indeed more elegant, and I also took into account that if the keys are bound to the script, each input needs to start the shell, which may cause some delay, and if you use keyd, I think his start speed should be faster by the shell, right?
The suggestion of writing crhomium plugin I may try in the future, because I am not familiar with javascript and chromium api, if it works I will share it here

Thanks for the patient reply @herrsimon @rvaiya 

Translated with www.DeepL.com/Translator (free version)
