### ISSUE TITLE
dvorak layout is missing two remaps

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/keyd#281]
I just tried using the new layout mechanism (which is great by the way!) and noticed that the shipped dvorak layout is missing the two remaps on the number row (`-` and `=` are mapped to `[` and `]`, respectively). As you probably generate the layout files automatically, I didn't send a pull request.

**Comment by rvaiya** [comment]
Thanks. They are indeed generated (by `scripts/dump-xkb-config`). This should be fixed in the latest commit.
