### ISSUE TITLE
bug? Rebindings on main layer ignored with active layout

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/keyd#282]
I just noticed that any bindings in the main layer which are already bound by the layout (so alphanumerics and shift) seem to be ignored by keyd when that layout is active. As bindings of other keys (for example modifiers) are applied, I guess that that's a bug.

**Comment by rvaiya** [comment]
> I just noticed that any bindings in the main layer which are already bound by the layout (so alphanumerics and shift) seem to be ignored by keyd when that layout is active. As bindings of other keys (for example modifiers) are applied, I guess that that's a bug.

This is a feature, not a bug. The main layer always takes precedence, so it can apply to all layouts.
