### ISSUE TITLE
bug: keyd hogs cpu and becomes unresponsive

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/keyd#283]
I've been using the latest commit (was on fd6840ddf4fe6f1e4bc27fba268ded475d975a68 from August 7 before) since this morning and just experienced the following behaviour:

At some point, keyd started writing lots (several per seconds) of error messages 'accept: Too many open files' to the log, used all CPU time it could get and all managed keyboards became completely unresponsive. The virtual mouse still continued to work.

The only change I did after this occured was completely removing all layout-related configuration (removed the include and `default_layout` directive and reverted back to layout bindings in the main layer, because of the other issue I reported).

The exact configuration file used has been working flawlessly for weeks before.

Also, when restarting the systemd service (on arch), there is often a lingering `keyd -e reset` present (also eating up CPU) and keyd doesn't start again properly, but this probably has to do with the service unit. I will investigate it later.

**Comment by rvaiya** [comment]
Thanks. This should be fixed in the latest commit.
