### ISSUE TITLE
macro(compose a ") and qt qcompleter

### ISSUE THREAD

**Issue by ville-h** [rvaiya/keyd#288]
I've setup `a = macro(compose a ")` in `/etc/keyd/default.conf` and it mostly works as expected. However when used with a qt application which has a qcompleter active, that is it's showing a popup below a text input for example, the macro no longer works. Instead of inserting `ä` the individual characters `a`, `"` are inserted. I am guessing qt captures the keyboard when it shows the popup or some such.

**Comment by ville-h** [comment]
I tried with `macro(compose " a)` and the results are similar: `"`, `a` rather than `a`, `"`. The particular application is not publicly available, but I suppose I could whip up a dummy qt application that has just a text input with a completer.

**Comment by ville-h** [comment]
with `a = ä` input now fails in all applications and results in the string: `00100`

**Comment by rvaiya** [comment]
> with a = ä input now fails in all applications and results in the string: 00100

For this to work you will need to symlink the keyd XCompose file. See the section on
unicode support in the man page.

> e setup a = macro(compose a ") in /etc/keyd/default.conf and it mostly works as expected. However when used with a qt application which has a qcompleter active,

This is likely a buffering issue in qt's input logic. You can try setting `macro_sequence_timeout` in `[global]` to remedy this.

E.G

```
[global]
macro_sequence_timeout = 1
```

The value is in microseconds and should probably be between `1` and `400`. If this works, I would appreciate if you could report the lowest value you used.

**Comment by ville-h** [comment]
> The value is in microseconds and should probably be between 1 and 4000. If this works, I would appreciate if you could report the lowest value you used.

I tried this with values up to `macro_sequence_timeout = 256000`, but couldn't observe a difference in behaviour.

**Comment by ville-h** [comment]
> For this to work you will need to symlink the keyd XCompose file. See the section on unicode support in the man page.

I tried this with `/home/ville/.XCompose -> /usr/share/keyd/keyd.compose` and `ä` now works in other programs, but the qt application still shows the string `00100`.

**Comment by ville-h** [comment]
A publicly available qt application demonstrating the issue would be kdevelop in its `Project > Open / Import project...` dialog for example. However qtcreator works correctly in its `File > Open File or Project...` dialog.

It's possible the difference could be that kdevelop uses qt5 and qtcreator uses qt6. The original application is a qt5 application as well.

**Comment by rvaiya** [comment]
> I tried this with values up to macro_sequence_timeout = 256000, but couldn't observe a difference in behaviour.

Does this work when you manually enter the sequence `compose a "`? If so, please post the output of `sudo keyd -m` while executing the compose sequence manually as well as the output using the bound macro sequence. 
> but the qt application still shows the string 00100.

Did you restart he application?

**Comment by ville-h** [comment]
What does it mean to "manually enter the sequence `compose a "`"? Yes I did restart the application. I reboot the machine on every change. If I just `sudo systemctl restart keyd` I seem to have some issues with the macro-compose keys in general.

**Comment by rvaiya** [comment]
> What does it mean to "manually enter the sequence compose a ""?

It just means to enter the sequence you are trying to assign to a macro. Does the sequence `<compose> <a> <">` actually produce `ä` on your system? If not, then it is not a keyd issue.

**Comment by ville-h** [comment]
what is `<compose>`?

**Comment by rvaiya** [comment]
> what is <compose>?

The compose key (the thing you are trying to bind with `a = macro(compose a ")`. Most keyboards don't actually have a compose key.

**Comment by ville-h** [comment]
ok by `<compose>` you presumably mean whatever was used in `setxkbmap -option compose:menu`, so in this example the `menu` key? I don't think I've a menu key on this thinkpad keyboard so I can't press it physically.

**Comment by rvaiya** [comment]
Yes. You can temporarily assign one using keyd (e.g `capslock = compose`). At which point pressing `<capslock> <a> <">` should produce `ä`. If pressing that sequence manually still doesn't work, it is likely a bug in your application.

**Comment by ville-h** [comment]
Still fails the same way when using `capslock = compose` and entering the `compose a "` sequence individually with the keyboard.

The `sudo keyd -m` output for triggering macro-compose:
```
keyd virtual device	0fac:0ade	compose down
keyd virtual device	0fac:0ade	compose up
keyd virtual device	0fac:0ade	a down
keyd virtual device	0fac:0ade	a up
keyd virtual device	0fac:0ade	leftshift down
keyd virtual device	0fac:0ade	' down
keyd virtual device	0fac:0ade	' up
keyd virtual device	0fac:0ade	leftshift up
```

The `sudo keyd -m` output for triggering `compose a "`:
```
keyd virtual device	0fac:0ade	compose down
keyd virtual device	0fac:0ade	compose up
keyd virtual device	0fac:0ade	a down
keyd virtual device	0fac:0ade	a up
keyd virtual device	0fac:0ade	leftshift down
keyd virtual device	0fac:0ade	' down
keyd virtual device	0fac:0ade	' up
keyd virtual device	0fac:0ade	leftshift up
```

Did you try to replicate with kdevelop if you're able to see the behaviour?

**Comment by ville-h** [comment]
> You didn't answer whether you get ä when typing in a non-qt application

Thought I did in the very first post by specifically saying problem happens in qt application with completer popup active. So yes it works in non-qt programs and even in qt programs. The failure happens in qt programs with completer popup active. And seemingly limited to qt5 programs, but I've only tested 2 of them. Works in 1 qt6 program I tested.

**Comment by rvaiya** [comment]
It doesn't look like anything can be done from keyd's side. Googling around suggests QT compose handling is at least partially broken. You might want to try experimenting with a different compose key (e.g `setxkbmap -option compose:ralt`) given that it seems to be menu related. 

I'm closing this for now.
