### ISSUE TITLE
Differentiate between left and right modifiers in layer heading

### ISSUE THREAD

**Issue by georgetian3** [rvaiya/keyd#290]
I am trying to remap RShift + W/A/S/D to up/left/down/right arrows with the following config:
```
[ids]

*

[main]

rightshift = layer(rshift)

[rshift:S]

w = up
a = left
s = down
d = right
```

However, if I press the RShift by itself, only LShift is fired.

The documentation:
```
Formally, each layer heading has the following form:

                "[" <layer name>[:<modifier set>] "]"

       Where <modifier_set> has the form:

           <modifier1>[-<modifier2>]...

       and each modifier is one of:

           C - Control
           M - Meta/Super
           A - Alt
           S - Shift
           G - AltGr
```
Does not specify that the modifiers can be left-right differentiated.

Is there any way I could fire RShift instead?

**Comment by georgetian3** [comment]
Thank you for the workaround!

As for why I would want to differentiate between left and right, there are games which use specific keys for different actions, and the game differentiates between left and right (although admittedly this has not been an issue for me so far).

As for your example configuration, I would intuitively think that the actions would be:

| Combo | Action after holding 1st key | Action after pressing both keys |
| ------------- | ------------- | ------------- |
| `leftshift+a` | `leftshift`  | `leftshift+a`
| `capslock+a` | `leftshift` | `leftshift+a`
| `enter+a` | `leftshift` | `leftshift+a`
| `rightshift+a` | `rightshift` | `leftshift+a`

The action after holding the 1st key for `leftshift+a` and `enter+a` are both `leftshift` as the direction wasn't specified in the first argument of `overload`, so default to left. All the actions after both keys are pressed have `leftshift` as the direction wasn't specified in the layer heading, so default to left.

However, if the direction can be specified, for example with:

`[rightshift:rS]`

Then the actions would be: 

| combo | 1st key | 1st + 2nd key |
| ------------- | ------------- | ------------- |
| `leftshift+a`  | `leftshift`  | `rightshift+a`
| `capslock+a`  | `rightshift` | `rightshift+a`
| `enter+a`  | `leftshift` | `rightshift+a`
| `rightshift+a`  | `rightshift` | `rightshift+a`

But my intuition may not be different from others', please correct me if so!

**Comment by rvaiya** [comment]
> Regarding your proposal to introduce lS and rS in order to apply left- or rightshift by default: This would only be useful if there is some application which generally (for all or at least almost all letter keys) distinguishes between combinations with the left or right version of shift. I'm not aware of such applications, but even if they exist one could reasonably consider them as exotic and require the user to resort to explicit mappings (adding macro expressions for all letter keys to the above rightshift layer).

+1. I've considered adding dedicated modifiers for right control/shift (`G` is already effectively `rightalt`), but it adds some additional complexity and I remain unconvinced there is a real world use case that is not covered by `overload`. Feel free to advocate for it if you feel you have one. From what I gather, `rightshift = overload(shift, rightshift)` is probably what you want.

**Comment by rvaiya** [comment]
I'm closing this for now. If your problem remains unresolved feel free to reopen it.
