### ISSUE TITLE
Autostart in KDE

### ISSUE THREAD

**Issue by kanishkaverma** [rvaiya/keyd#292]
Hey, 
I am running arch on endevourOS  and on gnome when I used to run ```sudo systemctl restart keyd```. It also used to autostart keyd on startup but on kde that's not the case. I have to manually start the script on startup in kde. Can you tell m how  I can make it so it can automcatically be started? Thanks so much for your time. 
warmest regards, 
Kanishka

**Comment by rvaiya** [comment]
>  I have to manually start the script on startup in kde. 

I assume you are talking about `keyd-application-mapper`. Note that KDE wayland is unsupported. If you are using the X version then it should work, but you will manually need to find a way to add it to your start up logic. I'm closing this for now since it isn't a keyd bug.
