### ISSUE TITLE
Execute a command on layer change.

### ISSUE THREAD

**Issue by rogpld** [rvaiya/keyd#294]
Is there a way of running a given command when a key is pressed for an amount of time? 
Would it be possible to run a different commands on hold and on release?

**Comment by rogpld** [comment]
The manual mentions

```
       overload(<layer>, <action>)
           Activates the given layer while held and executes <action> on tap.
```

How can I run a different command on releasing the key?

**Comment by rogpld** [comment]
Ok, I didn't know that. I'd like to load an RGB profile when switching layers and then come back to the original layer and RGB config after releasing a key. The RGB profile would be loaded by an external command. 
I would be open to double tap, or even hitting a different key to come back to the original layer.

**Comment by rogpld** [comment]
I managed to get it almost working through some scripting and some c code. The purpose is just aesthetic, to have the leds match the current active layer.

My problem now is setting the layer. The following activates the RGB leds correctly but the layer is not activated. You've mentioned using `keyd -e`, how would that look like?

```
[main]
rightalt = layer(intl)
esc = timeout(esc, 200, command( XDG_RUNTIME_DIR=/run/user/1000 /home/user/change-profile.sh > /tmp/logfile 2>&1))

[intl]
a = ã
o = õ
, = ç
3 = €
n = macro(~ space)
c = macro(` space)

[arrows]
j = left
k = down
l = right
i = up
```

**Comment by rvaiya** [comment]
At the moment this is not possible. I've been considering extending keyd's ability to control keyboard lights, but most keyboards use a non standard protocol for this. @rogpld What keyboard/program are you using? You mentioned some C code, can you share it?

**Comment by rogpld** [comment]
That's unfortunate. I thought it was possible to at least set the layer through the expressions or actions. 

I'm using [OpenRGB](https://gitlab.com/CalcProgrammer1/OpenRGB) and some simple code [wait-held.c](https://gist.github.com/rogpld/d92b17af93d6e8f252825a496109beaa). Then just wrap around with something like this:

```
#!/bin/env sh
openrgb --profile p1
wait-held.x
openrgb --profile p2
```

I have a Razer 60% Huntsman keyboard.

**Comment by rvaiya** [comment]
Thanks for the references. I was unaware of OpenRGB, it looks like considerable effort has been invested into reverse engineering the keyboard specific protocols. Adding some kind of introspection to facilitate layer change notifications has been on the agenda for some time, this should help renew the impetus.

**Comment by rvaiya** [comment]
This should now be possible using the `listen` command (see the man page for details). Note that the feature is still experimental and subject to change before the next release.

E.G

```
keyd listen|while read x; do
case "$x" in
     +shift)
     # openrgb <on>
     ;;
     -shift)
     # openrgb <off>
     ;;
esac
done
```

I suspect openrgb will be the main bottleneck, since it seems to have a rather slow initialization time (at least in my testing).

**Comment by rogpld** [comment]
> This should now be possible using the `listen` command (see the man page for details). Note that the feature is still experimental and subject to change before the next release.
> 
> E.G
> 
> ```
> keyd listen|while read x; do
> case "$x" in
>      +shift)
>      # openrgb <on>
>      ;;
>      -shift)
>      # openrgb <off>
>      ;;
> esac
> done
> ```
> 
> I suspect openrgb will be the main bottleneck, since it seems to have a rather slow initialization time (at least in my testing).

Thank you @rvaiya for the swiftly reply. Very elegant indeed. 

Openrgb is unfortunately slow to the point where if you're quick enough on typing you'll not observe the RGB changes.

**Comment by rvaiya** [comment]
One thing you might try is running the server. The client still seems to be quite slow, so you will probably want to background and kill it on the next invocation. Oddly, it seems openrgb will apply the effect long before terminating (suggesting the latency is not due to communication with the keyboard). This is a bit kludgey, but seems to work a bit better. 

```
#!/bin/sh

openrgb --server &

keyd listen|while read x; do
	case "$x" in
		+capslock)
		kill $pid
		openrgb -c ff0000 > /dev/null 2>&1 &
		pid=$!
		;;
		-capslock)
		kill $pid
		openrgb -c 000000 > /dev/null 2>&1 &
		pid=$!
		;;
	esac
done
```
