### ISSUE TITLE
US Keyboard with german layout

### ISSUE THREAD

**Issue by gringofe** [rvaiya/keyd#295]
Hi,

I have a keyboard with the US keyboard layout, but since I am used to the german layout, I just changed it in my OS settings. 

The problem is that german keyboards have a dedicated key for `<`, `>` and `|` right next to the left shift key (http://kbdlayout.info/KBDGR).

Is it possible to map another key combination (e.g. control + y or something like that) to this key using keyd?

**Comment by slakkenhuis** [comment]
You can use `keyd -m` and press the key in question to find out its internal name. You can then map that internal name `key`:

    key = C-y

See the man page for more details.

**Comment by gringofe** [comment]
Sorry, but I am a bit lost. The name of the key in question is `102nd`.

I pasted 

```
[ids]

*

[main]
102nd = C-y
```

into `/etc/keyd/default.conf`, but it doesn't seem to work. Is that correct?

**Comment by gringofe** [comment]
Thank you so much for your response. I might consider remapping at a later time.

What I did for now is this:

```
[ids]

*

[alt]
z = 102nd
```

Works perfectly for me.
