### ISSUE TITLE
How to create a simple macro with key up/down events?

### ISSUE THREAD

**Issue by MikkoHn** [rvaiya/keyd#296]
Hi, I had a look at the documentation but it's beyond my understanding. Below is an autohotkey macro for a video game. Can I achieve the same with keyd? I'm only using application specific remapping (app.conf file).

``
LShift::
{
Send {w down}
Sleep 20
Send {h down}
Sleep 20
Send {w up}
Send {h up}
return
}
``

**Comment by rvaiya** [comment]
If I understand that correctly, you want  `leftshift = macro(w 20ms h 20ms w 20ms h 20ms)`. If you also want leftshift to behave like shift when hold, you can do `leftshift = overload(shift, macro(w 20ms h 20ms w 20ms h 20ms))`. Please reread the relevant sections of the man page for an explanation of how these work. If you feel something is unclear, please let me know.

**Comment by MikkoHn** [comment]
`leftshift = macro(w 20ms h 20ms w 20ms h 20ms)`

results in repeating w h w h twice:

keyd virtual device     0fac:0ade       w down
keyd virtual device     0fac:0ade       w up
keyd virtual device     0fac:0ade       h down
keyd virtual device     0fac:0ade       h up
keyd virtual device     0fac:0ade       w down
keyd virtual device     0fac:0ade       w up
keyd virtual device     0fac:0ade       h down
keyd virtual device     0fac:0ade       h up

What I'm looking for is to hold down w while clicking h and then releasing both:

keyd virtual device     0fac:0ade       w down
keyd virtual device     0fac:0ade       h down
keyd virtual device     0fac:0ade       w up
keyd virtual device     0fac:0ade       h up

**Comment by rvaiya** [comment]
Then you probably want `macro(w+h)`.

**Comment by MikkoHn** [comment]
Of course it's that simple. Thanks for your time this is solved.
