### ISSUE TITLE
Is it possible to distinguish between identical keyboard models?

### ISSUE THREAD

**Issue by monkey-w1n5t0n** [rvaiya/keyd#297]
I have two identical keyboards which I would like to be able to use simultaneously, each with its own layout, while also being able to share state between them (i.e. having key presses on one affect the other).

Is it somehow possible to distinguish between them, given that they have the same vendor and product IDs?

```
$ lsusb
...
Bus 001 Device 009: ID 258a:002a BY Tech Gaming Keyboard
Bus 001 Device 012: ID 258a:002a BY Tech Gaming Keyboard
...
```

**Comment by slakkenhuis** [comment]
I don't think that this is possible yet. Also referencing #289 since if/when this is implemented, you will presumably also want to bind to keyboard-specific keys.

**Comment by monkey-w1n5t0n** [comment]
> I don't think that this is possible (yet?).

What would it take to implement? 

I'm currently using `kmonad` with two separate instances, each with the same `defsrc` but different `device-file` (under `/dev/input/by-path/...`). This works and I can have different layouts/layers on each keyboard, but obviously it's lacking the shared state aspect that `keyd` could provide.

I'm not (yet) familiar with how `keyd` does its device identification and capturing, but perhaps the config format could be extended to allow for optionally specifying the device path (or id) and an assigned name, which could then be used to refer to that specific keyboard in the rest of the config. For example:
```
[ids]
# backwards-compatible definition, matches all devices with these IDs
123a:456b

# narrows down to specific device despite sharing IDs
258a:002a:/dev/input/by-path/kbd_L = "Left"
258a:002a:/dev/input/by-path/kbd_R = "Right"
```
(quotes around the name might make it clearer that it's a made-up name and not a word that's part of the config - just a suggestion)

For the rest of the config, I guess there'd also have to be an optional way to specify if a certain layer or binding should only apply to a specific keyboard. 

For example, the layer heading could become:
```
[main] # standard layer, applies to every ID matched
...

[mylayer1 "Left"] # layer applies only to "Left"
...

[mylayer2 * "Left"] # layer applies to every device except "Left"
...

[mylayer3]
## these apply to all devices
w = C-right
b = C-left

## These are still part of mylayer3
## and only apply to specified devices
["Left"]
a = C-a
s = C-S-s

["Right"]
h = C-left
j = C-down
k = C-up
l = C-right
```
Obviously there are more issues to iron out and there may be better notations for this, but it's a start.

Thoughts?

**Comment by rvaiya** [comment]
> I'm not (yet) familiar with how keyd does its device identification and capturing

Devices are currently identified exclusively through their product and vendor ids. Uniquely identifying a device would require a unique id. USB devices are supposed to report a unique serial number, but from what I can tell many manufacturers omit this in the HID report (I will need to do more research).

> I'm currently using kmonad with two separate instances, each with the same defsrc but different device-file (under /dev/input/by-path/...).

This is a fickle approach since device paths change depending on things like the USB port they are plugged into, making them unsuitable as unique identifiers. If this gets implemented it would need to be platform agnostic.

> For the rest of the config, I guess there'd also have to be an optional way to specify if a certain layer or binding should only apply to a specific keyboard.

There are no plans to support per device key remapping within the same config (#289) for a variety of reason, however I am not opposed to a simple extension of the `[ids]` section which allows unique device ids to be used in place of vendor/product id pairs.

E.G

```
[ids]
<vendor>:<product>
<unique id>
```

**Comment by monkey-w1n5t0n** [comment]
Thanks for the explanation, it seems that `keyd` is unsuitable for my use case then.
