### ISSUE TITLE
possible to use normal key as modifier? 

### ISSUE THREAD

**Issue by kanishkaverma** [rvaiya/keyd#298]
Hey, 
I was wondering if it's possible to use a standard key such as 'f' to modify the functions of other keys. I would like to use f + hjkl as up, down, left, and right. This way I won't have to remap application mappings. Let me know what you think. 
Thanks for your time. 
warmest regards, 
kanishka

**Comment by slakkenhuis** [comment]
In principle, you can overload the letter keys. However, that's fraught with difficulty. For one, many keyboards are affected by rollover (#156, #142), which means that not all combinations of keys will get detected as such by your system. More fundamentally, though, it will likely hamper your ability to type normally, unless you manage to set timeouts that work for your personal typing style that disambiguate between 'f as a modifier' and 'f as a key'. Here are some relevant issues that you might be interested in: #34 #81 #125 #138 #278
