### ISSUE TITLE
dead keys / compose keys

### ISSUE THREAD

**Issue by mefromthepast** [rvaiya/keyd#30]
Is it possible to have dead and compose keys (e.g. `AltGr+[` for `¨` to create characters like `ü` etc.) with `keyd`? The `compose` option does not seem to do this.

(I could probably create a new layer, but then I think that such characters are not available?!)

**Comment by rvaiya** [comment]
The AltGr modifier is represented as `G`. It should as simple as assigning the desired key to `G-u`. 

> I could probably create a new layer, but then I think that such characters are not available?!

You shouldn't need to create another layer. I'm not sure what you mean by your last remark.

**Comment by mefromthepast** [comment]
Thanks for the response!

>  I'm not sure what you mean by your last remark.

I'm referring to using `AltGr + [` as a combined modifier which allows me to create ö, ï, ü, and so on, so I'd think of using `oneshot(G-[)` or something alike instead if I wanted to keep the full functionality of xkb. Then I'd probably put something like `[ = f13` and then again map f13 to the compose key. (While this is a new layer of indirection for  me and mapping is tedious, I understand the benefits of `keyd` and don't want to take the design decisions into question before I have really grasped what I'm dealing with).

[`G-u` itself is mapped to `↓` for my xkb, and while I don't use that character often, I feel that the same answer applies here that you have given [here](https://github.com/rvaiya/keyd/issues/31#issuecomment-915470998) - that I would have to somehow modify `setxkbmap` in order to have a compose key.]

**Comment by rvaiya** [comment]
> I'm referring to using AltGr + [ as a combined modifier which allows me to create ö, ï, ü

You can achieve this by creating a key which toggles the desired layer inside.

E.G

``` rightalt = layer(altgr)

[altgr:G]

[ = layer(symbols)

[symbols]

a = G-b b = G-a ...

```

personally I would do something like

``` [altgr:G]

a = G-b b = G-a ```

instead of nesting the layers, but it should be possible to achieve what you want.

> ... xkb ...

My advice would be to use setxkb only to set the default layout and do the rest of the remapping in keyd. Trying to combine xkb layering and keyd layering is a bad idea. Ideally you should have a keyd config that produces identical results on the virual console and the X server assuming that they both use the same layout for your language.

**Comment by mefromthepast** [comment]
I believe that this issue is basically solved for me as I have found the virtual keyboard of keyd and don't need to assign all those keys any more but can actually do it. with xkb.

**Comment by rvaiya** [comment]
I toyed with this a little bit and think the best solution is to use compose key macros since it requires minimal configuration on the X side and doesn't depend on the layout. See #33.

**Comment by rvaiya** [comment]
There is now first class support for this, so you can do `o = ö` directly in the config file (provided the xkb option `compose:menu` is set. See the man page for details.
