### ISSUE TITLE
About overload

### ISSUE THREAD

**Issue by bommbo** [rvaiya/keyd#302]
If my configuarion is :
```
[ids]
*
[main]
space = overload(spacefn,space)
[spacefn] 
w = leftmeta 
```
It's not working.

If my configuartion is :
```
[main]
space = overload(spacefn,space)
[spacefn]
q = leftmeta
```
It's working

**Comment by rvaiya** [comment]
Are you using the latest version?

**Comment by bommbo** [comment]
https://user-images.githubusercontent.com/61496351/187013051-37a3ef85-1848-4b01-aca3-1fbf043a766b.mp4

**Comment by bommbo** [comment]
https://user-images.githubusercontent.com/61496351/187013090-7f7dd4a6-2ebd-4ad1-8f83-28162c1d96f1.mp4
