### ISSUE TITLE
keyd.socket's group is root instead of keyd

### ISSUE THREAD

**Issue by Penlect** [rvaiya/keyd#306]
Thank you for developing this great project.

I want to bring to your attention that the commit https://github.com/rvaiya/keyd/commit/dba7b7e830218d814fbb24ba0c89dd74f76707af moved the call `chgid()` to the end of the `ipc_create_server()`, after the socket has been created, and therefore the socket will still belong to the root group:
```
$ ls -alth /var/run/keyd.socket
srw-rw---- 1 root root 0 Aug 27 11:23 /var/run/keyd.socket
```

If I instead move the `chgid()` call to before `if (bind(sd, (struct sockaddr *) &addr, sizeof addr) < 0) {`, the group becomes `keyd`:

```
$ ls -alth /var/run/keyd.socket
srw-rw---- 1 root keyd 0 Aug 27 11:24 /var/run/keyd.socket=
```

I noticed this after `keyd-application-mapper` reported `bind: Permission denied` when calling `keyd bind ...`.

**Comment by rvaiya** [comment]
Oops. This should be fixed in the latest commit.

**Comment by opalmay** [comment]
I'm still facing this issue
```bash
$ keyd -v                
keyd v2.4.2 (97b4255)
```

**Comment by gilest** [comment]
I'm also seeing this issue on a nixos install
