### ISSUE TITLE
Dedicated action for stacking oneshot modifiers?

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/keyd#307]
Currently (as always unless I'm doing something wrong), implementing stacking oneshot modifiers is rather cumbersome. A minimal configuration for the modifier keys (so that key combinations like C-S-a can be entered by pressing control, shift and a in sucession) would look like
```
[main]
shift = oneshot(shift)
control = oneshot(control)
alt = oneshot(alt)
meta = oneshot(meta)

[shift]
control = oneshot(shift_control)
alt = oneshot(shift_alt)
meta = oneshot(shift_meta)

#analogous bindings on the alt, control and meta layers

[shift_control:SC]

#five more analogous layers shift_alt, shift_meta etc.
```
so 26 lines in total. Would it make sense to introduce a `oneshot2` action, which carries all active oneshot layers over if the next keypress is defined as a oneshot (or oneshot2) as well? Then one could achieve the above by simply writing
```
[main]
shift = oneshot2(shift)
control = oneshot2(control)
alt = oneshot2(alt)
meta = oneshot2(meta)
```
For example, using the above configuration, pressing shift, control and a in sucession would result in C-S-a, the sequence shift, control, alt and a in C-S-A-a and so on. To clarify, using the configuration
```
[main]
shift = oneshot(shift)
control = oneshot2(control)

[shift+control]
b = c
```
the sequence control, shift and a would result in C-S-a, while shift, control, a would yield S-a. Also, control, shift, b would result in C-S-c while shift, control, b would result in C-b.

**Comment by rvaiya** [comment]
> [main]
> shift = oneshot(shift) 
> control = oneshot2(control)
>
> [shift+control] 
> b = c 
>
> the sequence control, shift and a would result in C-S-a

This is the default behaviour when using `oneshot`.

> while shift, control, a would yield S-a.

This is currently not possible without defining several layers, however it's not clear why you would want `<control>+<shift>+<a>` to differ from `<shift>+<control>+<a>` in the first place. As you've observed, it is technically possible to achieve this using several layers, but not something I want to add first class support for.

> Also, control, shift, b would result in C-S-c.

Key sequences should be unaffected by the modifiers associated with the layers in which they are defined. This minimizes surprises and makes things easier to reason about.

That is `<capslock>+<a>` should always yield `x` given:

```
[main]
capslock=layer(mylayer)

[mylayer:A-S-M]
a = x
```

**Comment by rvaiya** [comment]
> tapping d and then tapping x does not yield the expected S-C-x but results in C-x only, as the shift is resolved immediately upon the toggle, i.e. keyd releases shift as soon as the control layer is activated.

> Unless there is a good reason for this last behaviour, wouldn't it be consistent to add shift there as well?

It is mainly to allow for things like this:

```
[main]
shift = oneshot(shift)

[shift]
shift = toggle(shift)
```

If the oneshot was not cleared on `toggle` then this would immediately clear shift on the next keypress, which is probably not what the user expects. It would be possible to account for this while preserving the behaviour you describe, but it is probably quite rare in practice and not worth the effort.

**Comment by rvaiya** [comment]
Another reason (which I had in mind when I did this, but forgot) is that it allows for layer toggles to be embedded in other layers (which is quite common) without having the embedding layer affect the newly activated layer. 

E.G

```
[shift]
enter = toggle(nav)
[nav]
h = left
...
```

This is effectively a more general version of the above.
