### ISSUE TITLE
strcmp used on string that isn't null-terminated

### ISSUE THREAD

**Issue by Penlect** [rvaiya/keyd#308]
Thank you for sharing and developing keyd.

I want bring to your attention that the commit https://github.com/rvaiya/keyd/commit/8b16e02de55ab2ebe1be91dbd2dbb5d186587a2c removed the line `msg.data[msg.sz] = 0;` in the case `case IPC_BIND` of `static void handle_client(int con)`. This implies that `msg.data` no longer is null-terminated and when passed to `kbd_eval(ent->kbd, msg.data)` the `strcmp(exp, "reset")` will not succeed.

I noticed this when running
```
$ keyd bind reset 'leftalt.y = macro(S-C-v)'

reset� is not a valid keycode or alias
invalid key or action
```

**Comment by rvaiya** [comment]
How embarrassing. I should probably add some client tests. This should be fixed in the latest commit.
