### ISSUE TITLE
autostart on gnome? 

### ISSUE THREAD

**Issue by kanishkaverma** [rvaiya/keyd#311]
Hey, 
i was wondering how can I autostart keyd application mapper on gnome. Right now normal keyd gets autostarted but the application mapper. Thanks for your time. 
wamr

**Comment by slakkenhuis** [comment]
While that is true, we could consider adding a service file for the application mapper, since a service file exists for keyd itself. I can PR if desired.

**Comment by kanishkaverma** [comment]
okay, I guess I will close the issue then?

**Comment by rvaiya** [comment]
@kanishkaverma

The gnome plugin should handle this automatically unless the script is falling back to the X implementation. What version of Gnome are you running?

>  As the application mapper is user-specific and not used by everybody, this should be a systemd user unit at best (which can probably made available in some system path so that individual users can reference it). 

Login session don't necessarily have a display server attached to them, so a systemd unit is the wrong place for this. This should probably be done in initialization logic of the display server/window manager.
