### ISSUE TITLE
Request: Please increase number of allowed descriptors

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/keyd#314]
Commit dba7b7e830218d814fbb24ba0c89dd74f76707af reduced the maximal number of auxiliary descriptors from 64 to 32 (line 113 in `config.h`). Already 64 was quite low for involved layouts, 32 now gives me error messages. I think that this number should at least be quadrupled. If memory usage is of concern, then maybe a section in the manual would be helpful, so that users can easily tune the  descriptor, macro and command limits to their needs before compiling.

**Comment by rvaiya** [comment]
I've increased the number, but I'm surprised you managed to reach the limit. That's a fair few `timeout` and `overload` actions in a single config.
