### ISSUE TITLE
Repeat command action

### ISSUE THREAD

**Issue by tkna91** [rvaiya/keyd#316]
I am trying to move the mouse pointer in the following way
```
[ids]
*

[main]
tab = overload(TAB, tab)

[TAB]
h = command(ydotool mousemove -- -20  0)
j = command(ydotool mousemove --  0  20)
k = command(ydotool mousemove --  0 -20)
l = command(ydotool mousemove --  20  0)
```

Is there a way to hold down the key and repeat the command action?
If not, how about making the `timeout` available for command actions in the following form?
```
h = timeout(command(ydotool mousemove -- -20  0), 100, command(ydotool mousemove -- -20  0))
```

**Comment by rvaiya** [comment]
There are no plans to support this. The correct way to achieve what you want is by adding mouse support to keyd, which is planned for a future released.
