### ISSUE TITLE
Feature request: Optionally add absolute times when monitoring

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/keyd#322]
Even though CLOCK_MONOTONIC is used, adding the absolute time as a first field of `keyd monitor -t` output simplifies parsing significantly, for example when trying to monitor individual key hold times.

**Comment by rvaiya** [comment]
> adding the absolute time as a first field of keyd monitor -t output simplifies parsing significantly, for example when trying to monitor individual key hold times.

Can you clarify what you mean by this? I'm not sure why you would want absolute timestamps, but it should be trivial to recover them from the current output.
