### ISSUE TITLE
Should `macro` swallow modifiers?

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/keyd#326]
I was about to extend the documentation a little bit and then encountered that `macro` and the xcompose-sequences do not swallow modifiers. By this I mean that given a config of
```
[main]
; = ä
3 = macro(test)
```
then holding shift while tapping ; or 3 outputs `<shift_down> [compose_sequence] <shift_up>` and TEST, respectively. Analogous behaviour occurs of course when holding down the other modifiers and in general whenever a layer with the respective modifiers set is active. Is this intended?

If so, wouldn't it be better to have macros and compose sequences swallow all eventually active modifiers? I think the resulting behaviour would be more natural (most natural would probably be that shift+; would output Ä without an explicit binding on the shift layer, with analogous behaviour for all letters accented in some way, the greek/cyrillic alphabet etc., but handling all these exceptions might do more harm than good, for both the end user and the developer).

Of course this would have the following implications:

- in case a user indeed wants to apply a modifier to a all keys in a macro, this has to be written out explicitly, which is a good thing in my opinion
- `a = a` is no longer equivalent to `a = macro(a)`, which again is not a drawback in my opinion
- compose sequences can no longer be sent with a modifier as `; = S+ä` or `; = C+ä` don't (and shouldn't) work. In the first case one could just bind the intended `; = Ä` on the shift layer, but the second case (`<control_down> [compose_sequence] <control_up>`) would not be possible to achieve. But then the question is why one would be interested in typing such a keysequence.

In the documentation, one could clearly make a distinction between
1. Simple key codes plus optional modifiers, i.e. `a`, `C-a` etc., which inherit modifiers from active layers
2. Macros written using `macro()` or a single UTF8-character, during input of which all modifiers from active layers are disabled.

**Comment by rvaiya** [comment]
```
[main]
; = ä
3 = macro(test)
```
> then holding shift while tapping ; or 3 outputs `<shift_down> [compose_sequence] <shift_up>` and TEST, respectively.

Are you using the shipped layout files?

> Analogous behaviour occurs of course when holding down the other modifiers and in general whenever a layer with the respective modifiers set is active. 
> Is this intended?

Yes. I am aware that it is suboptimal, but there isn't a good solution to it. keyd is a tool for remapping keycodes (like QMK) that has some syntactic sugar for emitting compose sequences, but it is fundamentally still constrained by the fact that it is not a display server level tool. Within the context of a keycode oriented tool, the solution is to define a custom shift layer, which is what the shipped layouts do.

> If so, wouldn't it be better to have macros and compose sequences swallow all eventually active modifiers?

No, since there are legitimate use cases.

E.G

```
left = macro2(20, 20, left)
```

> most natural would probably be that shift+; would output Ä without an explicit binding on the shift layer

This is why the layout files already ship with dedicated shift layers. The only alternative would be to hard code the exceptions, which is a non-starter.

> but handling all these exceptions might do more harm than good, for both the end user and the developer).
> [...]
> Of course this would have the following implications:

Yes, this would break keyd's view of the world.

> `a = a` is no longer equivalent to `a = macro(a)`, which again is not a drawback in my opinion

You also introduce more questions, like 'what should C-S-a produce?'.

> but the second case (`<control_down> [compose_sequence] <control_up>`) would not be possible to achieve. But then the question is why one would be interested in typing such a keysequence.

> In the documentation, one could clearly make a distinction between
> 1. Simple key codes plus optional modifiers, i.e. `a`, `C-a` etc., which inherit modifiers from active layers
> 2. Macros written using `macro()` or a single UTF8-character, during input of which all modifiers from active layers are disabled.

Agreed. I have been intended to better document this.
