### ISSUE TITLE
Bug: `keyd reload` stalls when trying to load an invalid config

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/keyd#329]
When trying to reload a config which has been invalidated to an extent that makes keyd exit with a fatal error, the `keyd reload` command stalls (never exits). While this is technically not a bug, I think that keyd should validate all configuration files before actually executing the reload and instead of shutting down just refuse to reload in case of an invalid configuration (with `keyd reload` emitting an error message).

**Comment by rvaiya** [comment]
This should be fixed in the latest commit.
