### ISSUE TITLE
Improvement: Better error message for invalid composite layers

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/keyd#330]
When trying to attach a modifier to a composite layer, such as
```
[control+shift:A]
```
the resulting error messages are
```
ERROR: composite layers cannot have a type.
```
For the end user it would be better to instead complain that composite layers are not allowed to have modifiers attached.

Similarly, trying to define a composite layer without having seen one of the constituents, as in
```
[test+shift]
```
results in
```
ERROR: test is not a valid layer
```
Here again it would be better to complain that a composite layer with an undefined constituent was encountered.

**Comment by rvaiya** [comment]
> For the end user it would be better to instead complain that composite layers are not allowed to have modifiers attached.

Modifiers are not the only valid type.

> ERROR: test is not a valid layer

This should be sufficiently clear.
