### ISSUE TITLE
Improvement: More robust parsing

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/keyd#332]
I am in the process of adding some more documentation regarding macro parsing and went through the code to understand it properly. While doing so, I noticed a few minor and related things, which I include here instead of opening separate issues:

1. Keyd doesn't check for valid pause expressions inside `macro` (every token ending in “ms” is a pause, and the rest of the token is converted using `atoi` without any error checking). With error checking, binding to `macro(isms)` could either be forbidden in the manual and throw an error (as “is” is not an integer), or output what the user expects (my preference, as those who explicitly want to output words ending in “ms” don't have a hard time doing so and the others notice their mistake immediately).

2. A similar possibly problematic usage of `atoi` occurs in `config.c`, when parsing action arguments which should be a positive integer. Here I think that error checking should be added at some point.

3. Wouldn't it be more natural to make plus signs only special when they separate valid keycodes, so that macros like `macro(ab+cd)` are output as is instead of throwing an error?

**Comment by rvaiya** [comment]
> With error checking, binding to macro(isms) could either be forbidden in the manual and throw an error (as “is” is not an integer)

It is permitted. The failure to parse it is a bug and has been fixed.

> A similar possibly problematic usage of atoi occurs in config.c, when parsing action arguments which should be a positive integer.

If the user is entering negative numbers they need to reread the man page.

> Wouldn't it be more natural to make plus signs only special when they separate valid keycodes, so that macros like macro(ab+cd) are output as is instead of throwing an error

No. The user should be familiar with the parsing rules.
