### ISSUE TITLE
Bug: `swap` can replace the main layer and also fires without active `layer` action

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/keyd#335]
I noticed that `swap` replaces the topmost active layer unconditionally, so in particular when:

- the user is currently not executing a `layer` action (not holding a key)
- the topmost active layer is `main`

Shouldn't both of this be illegal?

**Comment by rvaiya** [comment]
Can you provide a config that produces this pathological behaviour? I believe what you describe should be impossible, but `swap` is only really useful when it is embedded inside a layer anyway.

**Comment by rvaiya** [comment]
Thanks. This only occurs before any layers have been activated (i.e as soon as you start keyd). I don't regard this as a bug, since it is undefined behaviour and there is no practical reason for anyone to do this, but I have a fix for it in my development branch.
