### ISSUE TITLE
Feature request: Another plea for `layer2`

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/keyd#336]
After our discussion yesterday, I again thought about an efficient way to enter accented letters and found something which again would need `layer2`.

Let me first state explicitly what accents I frequently need:

- vocals have to be modified by acute, grave, trema/umlaut and circumflex accents
- c needs to be modified with a cedilla
- s needs to be turned into ß

So this could be achieved with four different “modifier actions” (four for the vocals, one of them double serving to also modify the c and s). I've already tried many things and currently use a combination of altgr and a special compose layer, which is optimal for German (where just umlauts and scharfes s is needed, achieved via altgr) but non-optimal for Italian and French, where two additional keystrokes per accent is needed.

Since this morning, I've been using the following solution which I will very likely keep as it's very comfortable to use (using a local branch of keyd which has `layer2` implemented):

All letters which potentially need an accent are bound to `layer2`, which types the unaccented letter and also activates a special `accents` layer. While this layer is active, I can press a thumb key or physical modifier key to delete the unaccented letter and output the accented version instead. Here is part of the configuration:

```
[main]
e = layer2(accents, e)

[accents]
rightcontrol = macro(backspace é)
rightmeta = macro(backspace è)
rightalt = macro(backspace ë)
enter = macro(backspace ê)
[shift+accents]
...
```

Of course it has the drawback that the unaccented letter appears briefly on the screen, but for this you can achieve accents with just one more keystroke (the minimal number assuming that reserving physical keys is not possible), type the more common unaccented letters without any visual delay and also frees the right control key I was using for the dedicated modifier layer to be used for something else or not used at all. It also has the drawback that the vocals (on the homerow in my case) can't be overloaded with regular modifiers anymore, but on the keyboard I've been using this is achieved using two letter combos. I might put all `layer2` calls to a dedicated `language` layer, which is then untoggled when I'm programming or writing exclusively in English.

It then occured to me that I can use the same technique to enter mathematics via LaTeX by introducing some more keys on the `accents` layer turning a into \alpha, b into \beta etc. Also, I will probably configure the backslash key in the same way so that other commonly used macros can be entered quickly by just pressing one additional key.

Finally, let me remark that `layer2` could of course be replaced by `overload2` (`e = overload2(accents, e, 150)`) in the above approach, trading visual latency for no brief visual appearance of the unaccented letter when typing an accented one, but this would also imply that an unaccented letter would only appear on key release. I personally like `layer2` much more.

**Comment by rvaiya** [comment]
This is the in the pipeline.

**Comment by rvaiya** [comment]
This has been added to the latest commit in the form of `layerm`.
