### ISSUE TITLE
Can keyd turns mouse movement into key presses?

### ISSUE THREAD

**Issue by ziontee113** [rvaiya/keyd#338]
Hi again and thank you for reading this issue.

I wonder if there's currently a way for keyd to translate mouse movement into keyboard presses, since `sudo keyd -m` can detect mouse movement.

Thank you very much!

**Comment by rvaiya** [comment]
Not at the moment. This is planned for a future release. In the meantime you might be interested in my other project, [warpd](https://github.com/rvaiya/keyd).

**Comment by ziontee113** [comment]
Gotcha. Thank you for the response.
