### ISSUE TITLE
Output interval adjustment of `keyd input`, Shift-p output

### ISSUE THREAD

**Issue by tkna91** [rvaiya/keyd#339]
There seems to be the following problems with `keyd input`.
```
[ids]
*

[main]
tab = overload(TAB, tab)

[TAB]
j = command(echo -n 12345678901234567890 | keyd input)
k = command(echo -n $(date +%Y%m%d-%H%M%S) | keyd input)
```

1. neovim on Alacritty, which is made a floating window of sway, does not receive all of the keys from `keyd input`.
2. sometimes `shift-p` is printed at the end of the output.

https://user-images.githubusercontent.com/102382754/190388147-8843fb3f-2253-4990-91df-4b01de599a02.mp4

This may be a problem unique to Alacritty, as it was not a problem with foot. Either way, it would be useful to be able to adjust the output interval in case the application does not receive output from keyd.
Sorry if I'm doing something wrong.

**Comment by tkna91** [comment]
@herrsimon Thanks. The same was true below.
```
[ids]
*

[global]
macro_timeout = 1000
macro_repeat_timeout = 1000
layer_indicator = 0
macro_sequence_timeout = 1000000

[main]
tab = overload(TAB, tab)

[TAB]
j = command(echo -n 12345678901234567890 | keyd input)
k = command(echo -n $(date +%Y%m%d-%H%M%S) | keyd input)
```
It seems that at least in this form it is not possible to adjust the spacing of the input from the `keyd input`.

**Comment by rvaiya** [comment]
I've added a new flag (-t) which allows you to control the output interval.

**Comment by tkna91** [comment]
@rvaiya It worked. Thanks!

https://user-images.githubusercontent.com/102382754/190533314-19bfd74d-e617-4f05-b539-65f655b928bb.mp4

**Comment by rvaiya** [comment]
Thanks for the confirmation.
