### ISSUE TITLE
Bug: Include not followed by empty new line throws error

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/keyd#340]
While tidying up my configuration, I just noticed that a “failed to resolve include path” error is thrown if

- there is no empty line after an include statement (if the next statement is a binding, it is ignored in addition),
- there is more than one space between the `include` keyword and the filename,
- the name of the included file contains a dot.

The first should be a bug and it would be appreciated if keyd became more forgiving on the second and third.

**Comment by rvaiya** [comment]
1. I can't reproduce this. Can you provide a sample config?
2. has been fixed.
3. is by design (to prevent people from accidentally including '.conf' files and since fragments should generally not have a file extension)

**Comment by rvaiya** [comment]
Can you try the latest commit?
