### ISSUE TITLE
Application mapper: How to deal with applications not firing window change events?

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/keyd#341]
EDIT: I of course forgot to mention that the applications I'm talking about are all oneshot applications and no daemons. Adjusted the warpd example accordingly.

The application mapper does not detect applications which don't fire window change events, such as warpd (with the --oneshot flag) or rofi. To deal with this, a `--oneshot` flag  would be nice, applying bindings based on the focused window. Then one could wrap the application in a script of the form
```
keyd bind reset [custom bindings here]
/path/to/warpd --hint --oneshot
keyd-application-mapper --oneshot
```
For convenience (though somewhat hacky), it would also be useful to optionally add a string argument to `--oneshot`, selecting a specific section (such as `[warpd]`) to apply bindings from. Then the first line of the above script could simply be `keyd-application-mapper --oneshot warpd`.

Or is there a way to manually trigger window change events from the command line, making the above superfluous?

**Comment by rvaiya** [comment]
If you are using X, I've improved the window detection so things like rofi should be caught. There are still programs that will slip through the cracks, so I've made `keyd-application-mapper` responsive to SIGUSR1 which means you can trigger a reload using something like `pkill -usr1 keyd-application-mapper` in a wrapper script.

**Comment by rvaiya** [comment]
Can you try the latest commit?

**Comment by rvaiya** [comment]
Can you try one more time?
