### ISSUE TITLE
[Question] Moving of the keyd folder?

### ISSUE THREAD

**Issue by Namefailed** [rvaiya/keyd#343]
If there is a better place for questions, such as discord or similar, please let me know. 

I couldn't think of a better place to ask, but are there any issues with moving the keyd folder once it's been configured the first time? Can I move the folder, and are there any commands from the installation I would need to redo to make it function properly?

I honestly didnt think it would become such an important part of my workflow and originally installed in my home dir, as I thought I would end up uninstalling, but I would like to move it under a .folder that I have for similar programs.

Running latest version of popos (linux)

**Comment by slakkenhuis** [comment]
> If there is a better place for questions, such as discord or similar, please let me know.

No Discord (see also [this article](https://drewdevault.com/2021/12/28/Dont-use-Discord-for-FOSS.html)), but there's a `#keyd` IRC channel on [oftc](https://www.oftc.net/).

> Can I move the folder, and are there any commands from the installation I
> would need to redo to make it function properly?

What do you mean? What did you do the first time around? Assuming that your config is still in `/etc/keyd/`, there should be no problem in moving the binary anywhere else, or just re-running `make install`.

> I honestly didnt think it would become such an important part of my workflow

:)

**Comment by Namefailed** [comment]
Thanks so much! I've not actually used make much, and typically I leave stuff alone once I have it working, so I just wanted to make sure. I'll join the IRC for small questions next time. You guys are amazing, Keep up the great work. 

#CLOSED
