### ISSUE TITLE
Application mapper occasionally doesn't apply bindings

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/keyd#347]
Since the recent changes in `keyd-application-mapper`, I experience the following rather strange behaviour when using firefox: I have remapped C-p (which normally brings up the print dialog) to C-S-tab (cycling one tab to the left). It sometimes happens that out of the blue, either when using firefox for a while or when switching to it, C-p still brings up the print dialog. When I cancel it and then press C-p again, the correct mapping is applied.

As this never happened before, it is very likely that the new detection logic is indeed responsible. I tried to investigate but the only hint I found is that sometimes a `firefox-esr|firefox` window is detected instead of the usual `firefox-esr|name_of_currently_focused_tab`. Could this have something to do with it?

Another reason could be the many windows firefox creates (similar to warpd), for example (command `xwininfo -tree -root -all`)

```
 0x4c00072 "Some tab name": ("Firefox" "firefox-esr")  231x46+442+508  +442+508
        1 child:
        0x4c00079 (has no name): ()  1x1+-1+-1  +441+507
     0x4c00210 "Firefox": ("Firefox" "firefox-esr")  340x767+2216+84  +2216+84
        1 child:
        0x4c00214 (has no name): ()  1x1+-1+-1  +2215+83
     0x4c0006e "Firefox": ("Firefox" "firefox-esr")  346x362+807+495  +807+495
        1 child:
        0x4c0006f (has no name): ()  1x1+-1+-1  +806+494
     0x4c000e4 "manifest.json": ("Firefox" "firefox-esr")  121x46+763+710  +763+710
        1 child:
        0x4c000e5 (has no name): ()  1x1+-1+-1  +762+709
     0x4c00120 "Firefox": ("Firefox" "firefox-esr")  340x767+2216+84  +2216+84
        1 child:
        0x4c0013c (has no name): ()  1x1+-1+-1  +2215+83
     0x4c0016d "Firefox": ("Firefox" "firefox-esr")  295x275+2269+72  +2269+72
        1 child:
        0x4c00174 (has no name): ()  1x1+-1+-1  +2268+71
     0x4c00177 "Firefox": ("firefox-esr" "firefox-esr")  200x200+0+0  +0+0
        1 child:
        0x4c00178 (has no name): ()  1x1+-1+-1  +-1+-1
     0x4c00169 "Firefox": ("Firefox" "firefox-esr")  97x46+2463+95  +2463+95
        1 child:
        0x4c0016a (has no name): ()  1x1+-1+-1  +2462+94
```

This is of course not urgent and I'd be thankful for pointers on how I could investigate this by myself.

**Comment by rvaiya** [comment]
This indeed sounds like an issue with the new detection logic. 

You can try running an old version of the application mapper to verify this

E.g

`git show 005b5dc:scripts/keyd-application-mapper|python3 -`

Having said that, the class names are the same in the output you posted, so if you don't have any title specific matching rules then it shouldn't cause a problem.
