### ISSUE TITLE
capslock = overload(C, esc) and keybindings with control+escape(capslock)

### ISSUE THREAD

**Issue by budRich** [rvaiya/keyd#35]
I have noticed this strange issue that everytime i opened htop it seemed like the control key got "stuck". And today I noticed the same thing when opening whiskermeny. it is when i press Control (actual control key) and Escape (actual capslock) in a key combination while having:  
`capslock = overload(C, esc)` in my keyd config, but i think i fixed it with this hack:  

```
capslock = overload(C, esc)

leftcontrol = layer(control)

[control:C]
capslock = C-escape
```

This might be related to other "overload" issues when using the both of the keys in the overload together. 

*edit
the keybinding for whiskermenu is: <key>Control</key>+<key>Esc</key>  
htop: <key>Control</key>+<key>Shift</key>+<key>Esc</key>

**Comment by rvaiya** [comment]
I believe this should be fixed in the latest commit.

> This might be related to other "overload" issues when using the both of the keys in the overload together.

I'm not aware of any issues other than #34 which are related to the lack of configurable timeouts (a feature request). If you were referring to another bug please let me know.

**Comment by budRich** [comment]
Nice. I was referring to #34 , and possible unreported ones. I imagine for example:  
 `capslock = overload(A, esc)` would have the same issues but with the alt key instead of the control key.

**Comment by budRich** [comment]
I just tried keyd with the latest  commit and this issue seems to be fixed now. Good job @rvaiya !
