### ISSUE TITLE
Bug? Chording and macro bindings

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/keyd#350]
When trying to bind a macro to a chording, the macro is executed multiple times. For example, `l+semicolon = macro(compose s s)` results in `ßßß`. Replacing `macro` by `macro2` with zero timeout and repeat timeout results in no activation at all (output `l;`) but binding to `overload(control, macro(compose s s))` results in flawless execution of the macro.

**Comment by rvaiya** [comment]
I believe this should be fixed in the latest commit.
