### ISSUE TITLE
Bug? `macro_timeout` and `macro_repeat_timeout` seem to be ignored

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/keyd#352]
I never used the two settings in the title and just played with them to debug something, but while doing so it seemed as if they were ignored and the defaults are used. I have set `macro_timeout = 5000` and `macro_repeat_timeout = 1000` but still the repeats take place much more rapidly. Are these values capped if too large or is this a bug?

**Comment by rvaiya** [comment]
This seems to work for me as of c1ba86. Can you provide a minimal config which reproduces the issue?
