### ISSUE TITLE
Overloaded ctrl cannot enter some shortcut keys

### ISSUE THREAD

**Issue by afezeria** [rvaiya/keyd#357]
device:XPS 13 9360
os:ubuntu 22.04
env: GNOME 42.4, Wayland
keyd v2.4.2 (190bd68)

/etc/keyd/default.conf
```
[ids]

*

[main]

capslock = overload(control,esc)
#leftcontrol = capslock
```
can not use capslock to enter ctrl-shift-w,ctrl-shift-s,ctrl-shift-x

keyd monitor output:
```
# capslock+shift+a
keyd virtual keyboard	0fac:0ade	leftcontrol down
keyd virtual keyboard	0fac:0ade	leftshift down
keyd virtual keyboard	0fac:0ade	a down
keyd virtual keyboard	0fac:0ade	a up
keyd virtual keyboard	0fac:0ade	leftshift up
keyd virtual keyboard	0fac:0ade	leftcontrol up

# capslock+shift+s
keyd virtual keyboard	0fac:0ade	leftcontrol down
keyd virtual keyboard	0fac:0ade	leftshift down
keyd virtual keyboard	0fac:0ade	leftshift up
keyd virtual keyboard	0fac:0ade	leftcontrol up

```

**Comment by slakkenhuis** [comment]
This sounds like [rollover](https://en.wikipedia.org/wiki/Rollover_(keyboard)) (see also #156, #142), which is unfortunately a hardware thing that `keyd` cannot do anything about. Can you confirm that these key combinations (ie `capslock+shift+s`) are registered correctly outside of keyd by running `libinput debug-events` as root?

**Comment by afezeria** [comment]
Thanks, it looks like it's a hardware problem. When I hold capslock and shift and then press s, there is no output in libinput debug-events, even keyd is stop
