### ISSUE TITLE
Swap ctrl and capslock without any specific action assigned

### ISSUE THREAD

**Issue by gnufied** [rvaiya/keyd#358]
So, I have this in my config file:

```

[main]

# Maps capslock to escape when pressed and control when held.
capslock = overload(control, esc)
esc = capslock
```

The problem is - this breaks text editors that support `ctrl-click` as a way to navigate to a symbol. I don't use `vim`, so I don't need `capslock` to behave as `escape` when pressed and released without any other key.

I have tried few options, but none of them seem to work. 

Few things I have tried:

```
[main]

# swap control and capslock
capslock = control
# also tried
# capslock = leftcontrol
# capslock = overload(control, ctrl)
# ctrl = capslock
```

Nothing seems to work.

**Comment by gnufied** [comment]
Other thing which gets closer is:


```

[main]

# Maps capslock to escape when pressed and control when held.
capslock = overload(control, leftcontrol)
leftcontrol = capslock
```

This still breaks `ctrl-click` though.

**Comment by rvaiya** [comment]
This used to be the default behaviour of overload (eager layer activation). It was recently changed in favour of lazy activation, but since this appears to break some configs I have reverted it. Can you try the latest commit?

**Comment by gnufied** [comment]
That seems to have fixed it. Thanks.
