### ISSUE TITLE
A way to disable a certain key

### ISSUE THREAD

**Issue by raploz** [rvaiya/keyd#359]
Hi. I don't know if this is already possible, but reading the man page and this repository I didn't find any mention of this.
I'd like the ability to assign a key to another that does nothing, that way, it would be possible to effectively disable one keyboard key. For instance, something like

```
[ids]

*

[main]

end = null
```

I'd like to do that because I have a laptop that keeps pressing the End key by itself, and I'd like a way to disable it. Sorry if this is already available and I just didn't pay enough attention.

Thank you.

**Comment by sm1999** [comment]
end = noop
