### ISSUE TITLE
Revert lazy overload (#358, #351) space = overload(shift, space) does not work for FCITX5

### ISSUE THREAD

**Issue by sonhoan** [rvaiya/keyd#364]
I set
space = overload(shift, space)
and worked very smoothly until 13/10/2022 update.
Tapping space bar action allocated to convert by FCITX5 and other IME does not work with this update.

**Comment by rvaiya** [comment]
The old/new behaviour is to eagerly emit `shift` and release it before subsequently producing a space. It was briefly changed for implementation reasons, but this broke a few use cases (e.g click+drag). 

I assume FCITX is one of the few programs which struggles with the extraneous shift (though I'm not sure why it would).  One way to avoid this is to use time based overloading (which is probably a superior solution for shift anyway). E.g `space = overloadt(shift, space, 150)` (modifying 150 to taste) which should also reduce the number of misfires.

**Comment by sonhoan** [comment]
space = overloadt(shift, space, 150) with FCITX works!
Thank you.
