### ISSUE TITLE
How to map delete a line / delete a word？

### ISSUE THREAD

**Issue by Leiyi548** [rvaiya/keyd#365]
In autohotkey, I can map
^w:: send ^+{left}{Del}
 ^+k:: send {Home}{ShiftDown}{End}{Right}{ShiftUp}{Del}

**Comment by rvaiya** [comment]
I believe you want:

```
[control]
w = macro(C-left C-delete)
k = macro(home S-end S-right delete)
```

see the man page for more details.

**Comment by Leiyi548** [comment]
@rvaiya Thankyou
