### ISSUE TITLE
Question: Is it possible to disable internal keyboard?

### ISSUE THREAD

**Issue by vbauerster** [rvaiya/keyd#367]
Is it possible to disable laptop's internal keyboard when external one is connected and enable it back after external is disconnected?

**Comment by vbauerster** [comment]
Thanks for the hint.

**Comment by Arun-42** [comment]
Disabling internal keyboard using xinput as suggested [here](https://askubuntu.com/questions/160945/is-there-a-way-to-disable-a-laptops-internal-keyboard) breaks if keyd is running. Could you suggest a workaround or a pointer to the problem would be great.

**Comment by nsbgn** [comment]
If you use a wildcard config, the keypresses of the internal keyboard will get passed through to keyd's virtual keyboard, so disabling the internal keyboard at the display server level will have no effect.
To prevent keyd from managing the internal keyboard in the first place, put its ID (probably `0001:0001`, but check `lsusb`) in the `[ids]` section, prefixed with `-`.

I'm assuming that's what's happening, at least. If not, can you share your setup and what you're trying to achieve?

**Comment by Arun-42** [comment]
Setting the ID works, should've rtfm. Also, using `lsusb` gave something along the lines of `046d:c52b Logitech, Inc. Unifying Receiver` which ignored the external logitech keyboard in my case. I found the id from the keyd logs - `DEVICE: ignoring 046d:400d  (Logitech K230)`.
