### ISSUE TITLE
wrong behavior with rightshift

### ISSUE THREAD

**Issue by so1ar** [rvaiya/keyd#369]
Here is my config file:
```
[ids]
*

[main]

capslock = escape

escape = capslock

tab = overload(layer, tab)


[layer]

h = left
j = down
k = up
l = right
```

When I enable `keyd.service`, pressing rightshift becomes leftshift.

Here is the `keyd -m` output when I pressing rihgtshift:
```
device added: 0fac:1ade keyd virtual pointer (/dev/input/event18)
device added: 0fac:0ade keyd virtual keyboard (/dev/input/event17)
device added: 258a:0016 F.L BT Keyboard    Keyboard (/dev/input/event19)
device added: 0002:000e ETPS/2 Elantech Touchpad (/dev/input/event16)
device added: 046d:4074 Logitech G304 (/dev/input/event12)
device added: 04f3:309a ELAN2203:00 04F3:309A Touchpad (/dev/input/event13)
device added: 04f3:309a ELAN2203:00 04F3:309A Mouse (/dev/input/event11)
device added: 0001:0001 AT Translated Set 2 keyboard (/dev/input/event3)
keyd virtual keyboard	0fac:0ade	enter up
keyd virtual keyboard	0fac:0ade	leftshift down
keyd virtual keyboard	0fac:0ade	leftshift up
keyd virtual keyboard	0fac:0ade	leftshift down
keyd virtual keyboard	0fac:0ade	leftshift up
keyd virtual keyboard	0fac:0ade	leftshift down
keyd virtual keyboard	0fac:0ade	leftshift up
keyd virtual keyboard	0fac:0ade	leftshift down
keyd virtual keyboard	0fac:0ade	leftshift up
```

**Comment by so1ar** [comment]
Just found out the same thing happens to rightcontrol

**Comment by slakkenhuis** [comment]
This is intentional; see #114, #180, #185, #209. Is the behaviour causing issues?

**Comment by so1ar** [comment]
> This is intentional; see #114, #180, #185, #209. Is the behaviour causing issues?

In my use case, I set rihgtshift to activate the input method to input non-latin language, while leftshfit does nothing to avoid confliction with some games.

**Comment by slakkenhuis** [comment]
Ah, in that case, you can explicitly set `rightshift = rightshift` to override the default `rightshift = layer(shift)` that's causing this behaviour.

Since this issue pops up once in a while, I do think it makes sense to handle it differently, but see [this comment](https://github.com/rvaiya/keyd/issues/209#issuecomment-1121386837) for that.

**Comment by so1ar** [comment]
> Ah, in that case, you can explicitly set `rightshift = rightshift` to override the default `rightshift = layer(shift)` that's causing this behaviour.
> 
That solved the issue, thanks.
