### ISSUE TITLE
Vim Navigation AND Hyperkey?

### ISSUE THREAD

**Issue by liberninja** [rvaiya/keyd#370]
I've got this config right now for basic vim navigation using capslock, and escape when tapped:
```
[ids]
*
[main]

capslock = overload(capslock_layer, esc)

[capslock_layer]
h = left
j = down
k = up
l = right
```

Is there a way I can also use capslock as a hyper key for using keyboard shortcuts? I used to use xmodmap to assign caps to Hyper_L and map it to the mod3 slot and it worked great, but I can't figure out how to get the best of both worlds. Any suggestions?

**Comment by slakkenhuis** [comment]
If I recall correctly, the Hyper key *itself* is an X11 concept (someone correct me if I'm wrong), so you will need the help of something like `xmodmap` if that exact behaviour is important. However, you can attach modifiers to all non-bound keys in your layer by using something like `[capslock_layer:M]` or `[capslock_layer:M-C]`, (`M` is the Super key, `C` is control etc). You can bind keyboard shortcuts accordingly. Does that help?

**Comment by liberninja** [comment]
So map my capslock key to F13? I'm a little confused tbh... Perhaps I'll go through the documentation again and get better familiar w/ how it works.

**Comment by slakkenhuis** [comment]
Glad it works. The more elegant way is this:

```
capslock = overload(capslock_layer, esc)

[capslock_layer:C-S-A-M]
h = left
j = down
k = up
l = right
```

**Comment by liberninja** [comment]
That does 

> 



> Glad it works. The more elegant way is this:
> 
> ```
> capslock = overload(capslock_layer, esc)
> 
> [capslock_layer:C-S-A-M]
> h = left
> j = down
> k = up
> l = right
> ```

Thank you! That does work, however I notice that the escape is a bit more sluggish with this. Looking at xev output it's doing all four modifiers before the escape key. I'll probably just stick with what I have 👍

```
64  Alt_L
50  Shift_L
133 Super_L
37  Control_L
9   Escape
```

**Comment by svonjoi** [comment]
> If you have some hotkey daemon with shortcuts bound to `hyper+<key>`, just replace hyper by some key not physically present on a typical keyboard (such as f13) and then use `f13+<key>`.

For example in i3 configuration this does not work i think cuz in key combinations it reqiuires a modifier
