### ISSUE TITLE
Specify a different compose key

### ISSUE THREAD

**Issue by grezzogg** [rvaiya/keyd#372]
In the docs example it says in order for compose to work you must set the compose key to "menu". But my keyboard doesn't have a menu key.

Is there a way for keyd to use the right alt as compose key?

**Comment by slakkenhuis** [comment]
The compose key is interpreted by your display manager. As I understand it, the fact that 'compose' corresponds to 'menu' in keyd is somewhat arbitrary. On X11, you can do `setxkbmap -option compose:ralt`; on Wayland, it depends on your compositor. 

Then, when keyd sends rightalt, it would be interpreted as the compose key just fine.

**Comment by slakkenhuis** [comment]
As an aside, though, if keyd's virtual keyboard sends the compose key, it shouldn't matter whether your physical keyboard actually has that key.

**Comment by grezzogg** [comment]
Hello

Sorry for the late reply, wasn't feeling good.

You're right and apparently I was overthinking this. Even though my keyboard does not have a menu key keyd is is able to send the menu key which is the compose key I'm setting.

Sorry If this wasn't the right place for this kind of question, is there like an irc channel or something for this?

**Comment by acsqdotme** [comment]
Is there any way to get a compose key from keyd on the tty without needing wayland or X? I wanna be able to turn <rctrl>, <'>, <a> into á (with a sequence not needing each key to be held.)

I put the following in my /etc/keyd/default.conf: 

```
[ids]

*

[main]

rightcontrol = compose
```

then I symlinked the sequences over to my home as the man page recommended:

`ln -s /usr/share/keyd/keyd.compose ~/.XCompose`

then I reloaded, restarted the service and the pc, etc, but I can't it to work in wayland or x or tty through this method. I could just set it through setxkb, but I am really hoping there's a way to have composes independent of display managers.

**Comment by rvaiya** [comment]
Yes, I don't believe the tty used any X functionality until quite recently, and even now only supported XKB which doesn't include legacy XCompose support. It should be possible to set your TTY keymap and then use keyd to simulate the keystrokes necessary to produce non english characters, but you will have to do this manually. The limited unicode support provided by keyd generates sequences described in  a custom XCompose file that relies on increasingly dwindling application level support.
