### ISSUE TITLE
window filter shows Error: is not a valid layer

### ISSUE THREAD

**Issue by kyon328** [rvaiya/keyd#374]
contents in **~/.config/keyd/app.conf**
```
[blender]
0 = kp0
. = kpdot
```
my keyboard doesnt contain numpad, so I wanna emulate numpad0 and numpadDot while using blender, these two numpad keys are useful in blender.
but when I check the **app.log**, it shows 
```
Active window: blender|blender
ERROR:  is not a valid layer
```
I check the manual by `man keyd-application-mapper`, but did not find out what's wrong with my conf file,
so please help me, appreciated X)

**Comment by kyon328** [comment]
> This could be a bug, but in the meantime you can probably fix this by replacing `. = kpdot` with `dot = kpdot`.

thank q! replace with dot solve the problems, and blender works well as expect!  should I close the issue? or admin close it after fix the bug?

**Comment by rvaiya** [comment]
This was indeed a parsing bug. I believe it should be fixed in the latest commit.
