### ISSUE TITLE
modifier guard does not work on altgr

### ISSUE THREAD

**Issue by 0x0013** [rvaiya/keyd#378]
Hi,

I ran into the issue #128 but in my case, using altgr layer. It seems modifier guard only works on leftalt, but altgr/rightalt also triggers this firefox issue.

This doesn't trigger firefox menu:
```
...

[alt:A]
a = ā
```

but this does:
```
...

[altgr:G]
a = ā
```

maybe rightalt should also be applied to modifier guard?

**Comment by rvaiya** [comment]
I believe this should be fixed in the latest commit.
