### ISSUE TITLE
can keyd catching the keys sent by xrdp?

### ISSUE THREAD

**Issue by ifnk** [rvaiya/keyd#379]
keyd is good !
I can't live without it， 
 But when I remote linux(arch+i3wm ) through win10
it doesn't work 

i read this  [article](https://gist.github.com/GregaVrbancic/71f8e9891f4f70032a9e5882a88839ce) ,and use xrdp to remote linux  

I think keyd is not catching the keys sent by xrdp

can keyd support xrdp remote ?

**Comment by rvaiya** [comment]
Unfortunately not. keyd operates at a lower level (evdev), which is completely bypassed by tools like xrdp which connect directly to the display server. It is intended to be run directly on the host. The reverse will work (i.e remoting into a windows desktop if the host is running keyd)
