### ISSUE TITLE
Remapping CapsLock to Ctrl causes dead keys when pressed with Super

### ISSUE THREAD

**Issue by humanplayer2** [rvaiya/keyd#381]
Version: keyd v2.4.2 (c597fd5). OS: Pop!_OS 22.04, Wayland. Machine: ThinkPad X1 Carbon Gen 9, Danish keyboard.

Using the following config

```
[ids]

*

[main]

capslock = layer(capslock_ctrl)

[capslock_ctrl:C]
```
I get some weird dropouts when I press `Super+CapsLock+key`: All keys work as expected, except `key = w, 2, F1, F12, Insert`, where I just get no output in `keyd -m`.

E.g., pressing and holding `CapsLock+Super` and tapping `q w e` I'd expect to see the following output, gotten from `Ctrl+Super + q w e`:

```
keyd virtual keyboard	0fac:0ade	leftcontrol down
keyd virtual keyboard	0fac:0ade	leftmeta down
keyd virtual keyboard	0fac:0ade	q down
keyd virtual keyboard	0fac:0ade	q up
keyd virtual keyboard	0fac:0ade	w down
keyd virtual keyboard	0fac:0ade	w up
keyd virtual keyboard	0fac:0ade	e down
keyd virtual keyboard	0fac:0ade	e up
keyd virtual keyboard	0fac:0ade	leftmeta up
keyd virtual keyboard	0fac:0ade	leftcontrol up
```
but what I see is
```
keyd virtual keyboard	0fac:0ade	leftcontrol down
keyd virtual keyboard	0fac:0ade	leftmeta down
keyd virtual keyboard	0fac:0ade	q down
keyd virtual keyboard	0fac:0ade	q up
keyd virtual keyboard	0fac:0ade	e down
keyd virtual keyboard	0fac:0ade	e up
keyd virtual keyboard	0fac:0ade	leftmeta up
keyd virtual keyboard	0fac:0ade	leftcontrol up
```
The dropout also occurs in TTY.

I do not get dropout if I use regular unremapped `Ctrl`, or if I use the same config, but with `leftalt = layer(capslock_ctrl)`.

I'd love for this to be an issue with my system, but I can't see what it should be.

**Comment by slakkenhuis** [comment]
It's probably [rollover](https://en.wikipedia.org/wiki/Rollover_(keyboard)). Can you check whether the key combinations are registered correctly without `keyd`? See also [this comment](https://github.com/rvaiya/keyd/issues/357#issuecomment-1272520115).

**Comment by humanplayer2** [comment]
Ah. I apologize for not having checked without `keyd`. It had not crossed my mind that this might be a hardware shortcoming. Thank you for teaching me the concept, painful as it is to know of this shortcoming of my machine.
