### ISSUE TITLE
The extension is incompatible with the current GNOME version

### ISSUE THREAD

**Issue by bommbo** [rvaiya/keyd#382]
when I update to GNOME 43.1, the extension is show "The extension is incompatible with the current GNOME version", and app.conf is not work.

**Comment by humanplayer2** [comment]
The text "The extension is incompatible..." sounds like you have installed some GNOME extension? Where do you see that text?

**Comment by humanplayer2** [comment]
Try editing `~/.local/share/gnome-shell/extensions/keyd/metadata.json` and add to the `shell-version` list. I'm unsure if you should add "43", "43.1" or both. Log out and in and see if things are OK.

**Comment by bommbo** [comment]
think you.

**Comment by rvaiya** [comment]
Can someone confirm that the latest commit works without modification? (preferably by running `rm -rf ~/.local/share/gnome-shell/extensions/keyd` first)
