### ISSUE TITLE
Modifier guard: Wrong timing when combined with mouse keys?

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/keyd#385]
Hello,

I just noticed the following issue: On my meta layer, some keys are mapped to mouse buttons. Today, when trying to use these bindings to press some mouse buttons on a webpage (in a text field where some javascript loads choices on every entered letter based on text input), I noticed that they do not work, in the sense that the click is not registered. Then I checked what keyd is actually doing and was a bit surprised, here is the log output of `<leftmeta down> <f down> <f up> <leftmeta up>`, where the f key is bound to leftmouse on the meta layer:

```
+434 ms keyd virtual keyboard   0fac:0ade       leftmeta down
+1475 ms        keyd virtual pointer    0fac:1ade       leftmouse down
+0 ms   keyd virtual keyboard   0fac:0ade       leftcontrol down
+0 ms   keyd virtual keyboard   0fac:0ade       leftmeta up
+0 ms   keyd virtual keyboard   0fac:0ade       leftcontrol up
+1306 ms        keyd virtual pointer    0fac:1ade       leftmouse up
+0 ms   keyd virtual keyboard   0fac:0ade       leftmeta down
+2 ms   keyd virtual keyboard   0fac:0ade       leftcontrol down
+0 ms   keyd virtual keyboard   0fac:0ade       leftmeta up
+0 ms   keyd virtual keyboard   0fac:0ade       leftcontrol up
```

Shouldn't leftmouse down occur three lines later, after the modifier guard finished?

**Comment by rvaiya** [comment]
Indeed. This is a bug. Mouse and key events are generated by different virtual devices and need to be synchronized to accommodate this use case properly. I will take a look when I have some time.

**Comment by rvaiya** [comment]
I believe this should be fixed in the latest commit.
