### ISSUE TITLE
bind: Permission denied

### ISSUE THREAD

**Issue by mateuszwieloch** [rvaiya/keyd#390]
When running `keyd-application-mapper` on Pop_OS (a Ubuntu based distro), I've been getting the following error on every window change:
```
bind: Permission denied
```

I narrowed it down to [this line of code](https://github.com/rvaiya/keyd/blob/ccdca916a39963efea4fb15deb4639bf2405ad84/scripts/keyd-application-mapper#L445):
```python
    subprocess.run(['keyd', 'bind', 'reset', *bindings], stdout=subprocess.DEVNULL)
```

When I added `sudo` in front like this:
```python
    subprocess.run(['sudo', 'keyd', 'bind', 'reset', *bindings], stdout=subprocess.DEVNULL)
```
everything started to work again.

I don't fully understand what's going on, but I'm guessing that there are problems either with how Ubuntu handles root or my setup. Either case it would be great to either fix or at least detect that and display a more useful error message.

Thanks a lot for this amazing tool!

**Comment by rvaiya** [comment]
You probably need to add your user to the keyd group.

**Comment by mateuszwieloch** [comment]
I'm still fairly new to Linux, but I think my user is in the keyd group.

I checked it by looking at the `/etc/group` where I found the `keyd:x:1003:mwieloch` line. (mwieloch is my username)

**Comment by rvaiya** [comment]
Do you see `keyd` in the output of the `groups` command? You may need to restart the session (e.g reboot) for it to take effect.

**Comment by mateuszwieloch** [comment]
Yes I can see it:
```
$ groups
mwieloch adm sudo lpadmin keyd
```
However, I've just checked and now it's working without the `sudo` so you are probably right that the lack of reboot was the cause.

Thanks a lot! Let me know if there's a good way for me to support the project.
