### ISSUE TITLE
how to set tab and "\" key as meta

### ISSUE THREAD

**Issue by kanishkaverma** [rvaiya/keyd#391]
hey,
I wanted to set the tab and \ key as meta when held together with another key and just tab and \ when tapped. I tried to use  
```
tab = overload(leftmeta, meta) 
backslash = overload(backslash, meta) 
``` but It didn't work. 
any help will be appreciated. 
thank you so  much for your time.  
warmest regards, 
Kanishka

**Comment by rvaiya** [comment]
The first argument of overload should be a layer (if you inspect the logs you should see an error). You probably want

```
\ = overload(meta, \)
tab = overload(meta, tab)
```
