### ISSUE TITLE
Help: make esc+f1 toggle a layer while keeping esc tap functioning

### ISSUE THREAD

**Issue by iskur** [rvaiya/keyd#393]
I have this configuration:

```
esc = layer(esc)

[fnlock]
f1 = brightnessdown
f2 = brightnessup
f7 = previoussong
f8 = playpause
f9 = nextsong
f10 = mute
f11 = volumedown
f12 = volumeup

[esc]
f1 = toggle(fnlock)
```

It does just what I want, except for the fact that the esc-key stops working as an esc-key when tapped. Can this be achieved somehow?

**Comment by mushfiqRabbi** [comment]
i believe this should do it.

esc = overload(esc, esc)

[esc]
f1 = toggle[fnlock]

[fnlock]
f1 = brightnessdown
f2 = brightnessup
f7 = previoussong
f8 = playpause
f9 = nextsong
f10 = mute
f11 = volumedown
f12 = volumeup

**Comment by iskur** [comment]
Excellent! It works. Thanks a lot.
I thought I had tried that one, but it turns out, I haven't.

@rvaiya And thanks to you as well! This is fine software. It replaced interception-tools (combined with dual-function-keys) for me, which needed a little more complicated configuration for the one-liner `space = overload(control, space)` and lacked other functionality.
