### ISSUE TITLE
Help me execute command.

### ISSUE THREAD

**Issue by mushfiqRabbi** [rvaiya/keyd#394]
I am a new linux user, I have ubuntu installed on my machine, I want to run the gnome terminal when I press and hold the <enter> key and then tap the <t> key, below is the config I have come to so far, but it is not firing the terminal at all. please help me find out what I am doing wrong

[main]
enter = overload(enter_main, enter)

[enter_main:C]
t = command(gnome-terminal)

**Comment by mushfiqRabbi** [comment]
I looked through issues section and I got it.

**Comment by stuv** [comment]
Did you get it to work?
If so, how? I am struggling a bit with the command-command myself.
