### ISSUE TITLE
Using swap(layer) as overload action does not work as expected

### ISSUE THREAD

**Issue by 0x0013** [rvaiya/keyd#395]
When using swap as normal action in a layer, it deactivates the original layer and activates the swap target, for the duration of first keypress.

```
capslock = layer(extend)
[extend]
f = swap(control)
```
when holding `capslock` and tapping `f`, this would produce following layer changes as expected:
```
+extend
-extend
+control
```

However, when overloaded:

```
capslock = layer(extend)
[extend]
f = overload(control, swap(control))
```

The swap action seems to be ignored, and I see the normal "layer" action both on holding the overloaded key, as well as on tapping:
```
+extend
+control
-control
```

Am I right in my assumption that `swap(<layer>)` should be a valid action for `overload(<layer>,<action>)`?

**Comment by rvaiya** [comment]
This is currently unsupported (and technically a bug, I suppose). swap has a relatively small number of real world use cases. 
Can you elaborate on what you are trying to achieve? If I have correctly interpreted what you are trying to do, you might be better served by a simple unnested `swap` paired with a chord.

Something like this:

```
[main]
capslock+f = layer(control)

[capslock]
f = swap(control)
```

which also has the advantage of being order invariant (`f+capslock` == `capslock+f`). Bear in mind that even if `overload(control, swap(control))` were valid, it would stack `control` *on top* of `extend` if `f` was held (which may be your intention, but generally seems undesirable) meaning that you would end up applying control to whatever is in your extend layer (while merely *tapping* f would deactivate extend and exclusively activate control).

**Comment by rvaiya** [comment]
Update: This should work in the latest commit if you still want to do it.

**Comment by 0x0013** [comment]
Hi,
> 
> Bear in mind that even if `overload(control, swap(control))` were valid, it would stack `control` _on top_ of `extend` if `f` was held (which may be your intention, but generally seems undesirable) meaning that you would end up applying control to whatever is in your extend layer (while merely _tapping_ f would deactivate extend and exclusively activate control).

This was actually my intention. I was trying to define an "extend" layer which places navigation keys, such as arrows etc, on the home row. So while holding `capslock+f` I would be able to easily input combinations such as `control+left` to move one word left, and similar. But this prevents me to use this `control` layer mapping with letter keys, as the navigation layer is now active instead. So by overloading it, I would keep both options - by holding `capslock` and a quick tap on `f` I would get the normal `control` layer, and by holding both, I would get the `control` modifier with the "extended" layer.

> Update: This should work in the latest commit if you still want to do it.

Thanks, will check this out later!
