### ISSUE TITLE
How to map leftshift + key to produce x

### ISSUE THREAD

**Issue by juhaku** [rvaiya/keyd#398]
I cannot figure out how to map `leftshift + y = x`  and then when pressing `y = z`?

Thank you for your help
-Juha

**Comment by slakkenhuis** [comment]
What do you mean? What have you tried? If you mean that pressing y while holding shift should yield z, but pressing y without holding shift should yield y:

```
[shift]
y = z
```

See the manual for details.

**Comment by juhaku** [comment]
Thanks, yeah this is indeed something that I was looking for but for application specific manner. I wanted to achieve following mapping. Pressing \` would yield `esc`. And pressing `esc` would yield to \`. And while holding shift and pressing ` would yield to ~.

But in application specific mappings just reversing `esc` and \` is not enough and while just doing that it will not support the normal hold shift + press \` to yield ~ but instead will threat it as `esc` was pressed.

So what I had previsouly was in `.config/keyd/app.conf` did not allow to to hold shift + \` to yield ~ anymore what of course would be the default behaviour with english key layout. So I tried to use the layers like [shift] or [leftshift] but no avail within the `.config/keyd/app.conf`.  
````
[konsole|*nvim*]

esc = `
` = esc
````

Untill today I looked the manual again and found out that I can configure it as follows and it does work. It did not occur to my eye before that you can define key strokes with `.` (dot) notation as well.
```
[konsole|*nvim*]

shift.`= ~
esc = `
` = esc
```
