### ISSUE TITLE
-0:0 id breaks other ids

### ISSUE THREAD

**Issue by sarmong** [rvaiya/keyd#400]
I just updated keyd to 2.4.2 (I think from 2.4.0). Having this in my config makes config apply to to 1d50:615e device.

```
[ids]
*

-0:0
-1d50:615e
```

What's interesting is that if I swap these lines, everything works as intended

```
-1d50:615e
-0:0
```

From what I remember, I have `-0:0` here to not apply keyd to bluetooth keyboard

**Comment by rvaiya** [comment]
I can't reproduce this. I am closing this for now in an attempt to prune stale issues. Feel free to reopen it if you can reproduce it on master.
