### ISSUE TITLE
Swap fn and leftcontrol on Thinkpad

### ISSUE THREAD

**Issue by sarmong** [rvaiya/keyd#401]
Is it possible to swap Fn and Control keys on a Thinkpad?

`keyd -m` says that Fn key is `wakeup`, so I did this:

```
wakeup = leftcontrol
leftcontrol = wakeup
```

Which makes both `keyd` and `xev` recognize Fn key as Left Control.

However, Fn key still does not function as Control and works with F1-12 keys as before the swap. And Control functions neither as control, nor as Fn key.

I assume this key works on a firmware level and it's not possible to swap them on OS level, right?

**Comment by bubbleguuum** [comment]
Probably. You should be able to swap them in the BIOS.

**Comment by tkna91** [comment]
If the `Fn` key cannot be detected by the `keyd monitor`, then it is an area of hardware or firmware and should not be subject to control by keyd.

**Comment by vg250156** [comment]
The wakeup keysym generated by the fn key cannot be used as a modifier. The BIOS handles that key and if you use it as a modifier, the BIOS will intercept before keyd gets it.

**Comment by rvaiya** [comment]
Those above are correct, `fn` is usually handled in firmware so you will need to change it to another key like `control` in your bios before it can be detected and remapped by the OS.
