### ISSUE TITLE
Simple vim keymapping (right alt + hjkl) not working

### ISSUE THREAD

**Issue by mgryszko** [rvaiya/keyd#403]
I'm trying to map right alt + hjkl to arrow keys with this configuration (stored in `/etc/keyd/default.conf`):
```
[ids]
*

[rightalt]
h = left
j = down
k = up
l = right
```

However, keyd doesn't pick it up, althoughthe configuration is read by keyd (as per output of journalctl). `keyd -m` shows that right alt + hjkl key combinations are still producing h, j, k, l keystrokes, not arrows as desired.

OS: Ubuntu 22.04
keyd version: 2.4.2 (compiled from the git tag)

Keep in mind that I'm using Gnome Tweaks too to remap Caps to escape an Meta to Win (if it can have an impact on keyd).

Am I missing something?

**Comment by slakkenhuis** [comment]
`rightalt` is not a layer, but a key name.

You can set `rightalt = layer(rightalt)` in your `[main]` layer and add the following layer to get the behaviour you (presumably) want:

```
[rightalt:G]
h = left
j = down
k = up
l = right
```

Alternatively, you could have used the `alt` layer (which by default *is* a layer that applies the alt modifier), but this would have changed the behaviour of both the left and the right keys.

**Comment by woojiq** [comment]
I checked both solutions and I can say that `rightalt = layer(rightalt)` is better. With `altgr` in firefox (for example) when I click _right alt and smth_, the firefox top bar is shown every time as if you just press `Alt`.

P.S. thx for *keyd* package, saved my life)

**Comment by mgryszko** [comment]
Due to my misconfigured email address for notifications, I read @nsbgn and @ghost answer 6 months later :facepalm:. Many thanks for the solution, I made my configuration working.

Final configuration:
```
[ids]
*

[main]
rightalt = layer(vim)

[vim]
h = left
j = down
k = up
l = right
```

**Comment by mgryszko** [comment]
Due to my misconfigured email address for notifications, I read @nsbgn answer 6 months later facepalm. Many thanks for the solution, I made my configuration working.

Final configuration:

[ids]
*

[main]
rightalt = layer(vim)

[vim]
h = left
j = down
k = up
l = right
