### ISSUE TITLE
Mapping Caps to Alt+Ctrl+Shift in Linux

### ISSUE THREAD

**Issue by behrangsa** [rvaiya/keyd#408]
Is this possible?

I tried this configuration but it didn't work:

```
[ids]

*

[main]
capslock = A-C-S
```

Under macOS, I use [Karabiner Elements](https://karabiner-elements.pqrs.org) and map my keyboard's Caps Lock key to something like [`Opt+Cmd+Ctrl+Shift`](https://karabiner-elements.pqrs.org/docs/manual/configuration/configure-complex-modifications/) that I use as a brand new, personal, meta key. So then I can create shortcuts like `Opt+Cmd+Ctrl+Shift+T` to open the Terminal (which I trigger by typing `Caps+T`).

Is this doable under keyd? To map Caps Lock to `Alt+Ctrl+Shift`?

Thanks in advance.

**Comment by slakkenhuis** [comment]
It is. Layers can be associated with modifiers:

```
[ids]
*

[main]
capslock = layer(mylayer)

[mylayer:A-C-S]
```
