### ISSUE TITLE
Toggle two layers at once?

### ISSUE THREAD

**Issue by vg250156** [rvaiya/keyd#410]
Hi, thanks for a very useful tool.

I'm wondering if I could have an action that toggles two layers at once and also run a macro. Use case is as such: I have a nav layer that maps a whole bunch of keys to ctrl and alt actions, for use with programs such as firefox and slack. A few of these actions focus on text entry boxes. I would like to implement 'modes', so that if I type 't', it opens a new tab with C-t, and also removes the nav layer, and also adds in a new layer with one change: the enter key re-enters nav 'mode'. Simply toggling a second layer doesn't remove the nav layer, and so I can't enter text properly. Swap would be useful here if the changes were permanent instead of only while holding the key.

`clearm` is what I'm currently using but I'd love to have more precise control over which layers are active at any given time.

I've read through the manpages and issues enough to understand that layers aren't intended to have any kind of priority, and that's fine. I'd just like to be able to toggle two or perhaps even more layers at once along with a macro so I can build up modal workflows. Also would be nice if clear accepted multiple layers, again with a macro.

Thanks again, this might eventually allow me to ditch qmk and the like!!

**Comment by tkna91** [comment]
It may be easier to have a conversation if you can show a specific config that others can reproduce by copy-pasting.

**Comment by vg250156** [comment]
Err, sure. Here is an example of a config I'm using now.

main.conf
```
[main]

capslock = overload(control, esc)
sysrq = layer(meta)
z+x = toggle(nav)

[nav]
```

app.conf
```
[signal]

nav.j = A-S-down
meta.j = M-j
nav.; = A-S-up
meta.; = M-;
nav.c = C-c
nav.g = clearm(C-S-t)
nav.v = C-v
nav.x = C-x
nav.z = C-z
control.enter = togglem(nav, enter)
nav.y = C-1
nav.u = C-2
nav.i = C-3
nav.o = C-4
nav.p = C-5
```

As you can see there are two layers, `main` and `nav` I can get into nav either through z+x globally or with control.enter in signal. Nav switches up the keyboard so it mostly serves for navigating to where I might want to enter text, when I'm ready I hit `g` and it focuses on the text input and then drops the nav layer. All well and good, if I only have two layers to switch between. Let's say I wanted a third layer,  which is just `main` with an additional binding where `enter` instead of `control.enter` switches back to nav. Can't do that from the nav layer, there's no way to swap from one layer to another, though I suppose I could use the `command()` to switch the `enter` binding, I can't do that and clear the nav layer. Scripting to support changing the layer using `keyd -e` would also help.

**Comment by tkna91** [comment]
The wording is not specific enough to allow others to copy-paste just that text and reproduce the setting, and there appears to be room for misunderstanding and interpretation. It might be easier to get the story across if it were in a simpler form.
I think it is likely that I am misunderstanding you, partly because of this, but are `clear()` and `clearm(<macro>)` of no use to you?
If that functionality does not exist (there is no mention of it in `man keyd`), then you need to build the latest version somehow.

**Comment by vg250156** [comment]
Not sure how I can be any clearer. I need to switch from one active layer to another layer in one key action. Doesn't appear to be possible atm.

**Comment by rvaiya** [comment]
@vg250156 Sorry for the belated response, but have you tried using `swap`?

If I understand you correctly, something like this should work

```
[nav]

g = swapm(C-S-t)

[foo]

enter = swap(nav)
```

**Comment by rvaiya** [comment]
Sorry, the above was wrong, since swap only applies to `layer()`. The latest commit adds support for swapping out toggled layers, which should allow you to achieve what you want using my suggestion above.

**Comment by vg250156** [comment]
Thanks! I found a bug, but made a new issue for it.
