### ISSUE TITLE
\ not working?

### ISSUE THREAD

**Issue by mariosk8s** [rvaiya/keyd#411]
When i run keyd 2.4.2 with the following config:

[ids]
*

or: 

[ids]
*

[main]
\ = \

The **\\** key produces **#**

When i run it with:
[ids]
*

[main]
\ = ?

It produces **?**

I'm puzzled about this behavior.
How do i get a **\\**?

**Comment by mariosk8s** [comment]
What i forgot to mention was that i'm running on a US keyboard with
setxkbmap -model pc104 -layout us

keyd reports that \ is pressed, but the \ is just not echoed and # instead

**Comment by rvaiya** [comment]
keyd outputs device keycodes, not keysyms (it doesn't care about your X map). You can find the generated keycodes using `keyd monitor`. For best results use a qwerty keymap in your display server.
