### ISSUE TITLE
Last line of .conf file must be an empty line

### ISSUE THREAD

**Issue by bryan00a** [rvaiya/keyd#414]
I've noticed that if the last line of a .conf file is not an empty line I will get this ambiguous error message:

WARNING: failed to parse /etc/keyd/Air60.conf

Thank you for writing such a useful piece of software !!!

**Comment by ddshore** [comment]
+1, thank you for this, this was driving me crazy.  If possible, I'd change the examples in the readme so that when a user copies and pastes the example, it includes the end of line.

**Comment by rvaiya** [comment]
Valid POSIX text files *must* end in a newline, which is why most editors add them by default. This should probably be considered a bug in whatever editor you are using (I assume helix), but I have accommodated it in the latest commit.
