### ISSUE TITLE
cant bind to leftshift and leftcontrol

### ISSUE THREAD

**Issue by mikdmst1** [rvaiya/keyd#415]
i use app.conf:

this work (accidentally found out):
[blender]
mouse2 = rightshift
mouse1 = rightcontrol

this dont work:
[blender]
mouse2 = leftshift
mouse1 = leftcontrol

why?

**Comment by rvaiya** [comment]
Can you clarify what you mean by "doesn't work"? What key combinations are problematic? In general you should be using `layer(control)` instead of  `leftcontrol`  to avoid problems with modifier stacking.
