### ISSUE TITLE
keyd-application-mapper: Change log file location/Option to disable logging

### ISSUE THREAD

**Issue by Nimmidev** [rvaiya/keyd#418]
I just tried the `keyd-application-mapper` script. It is super useful but i have two minor issues with it:

1. The log file location of `~/.config/keyd/app.log` is problematic for me because i have it checked into a git repository. I know i could just put it on the `.gitignore` but i find the location in general a bit odd for a log file. Maybe moving it to `/tmp` or in case it should be persisted to `/var/log` or `~/.local/share`.
2. An option to disable logging or enable logging and disable it by default would be great. The log contains every window title of a focused application which could contains sensitive information. If a general log file is desired then maybe just an option to disable the logging of the window class/title.

I would love to hear you opinion about these issues. I have no problem to address them in a PR/PRs if you want.

**Comment by mikdmst1** [comment]
-q for quiet mode?

**Comment by Nimmidev** [comment]
> -q for quiet mode?

I am feeling so dumb now. I was reading the man page and did not find anything. Haven't thought of running `keyd-application-mapper -h`. My bad. Thanks.
