### ISSUE TITLE
incompatibility between oneshot and overload when defining shift and some letter

### ISSUE THREAD

**Issue by CRAG666** [rvaiya/keyd#420]
These two instructions are exclusive since when I use shift with any other letter it behaves properly, however when I use it with the letter a it continues to be written in lowercase:
```
shift = oneshot(shift)
a = overload(meta, a)
```

**Comment by rvaiya** [comment]
Thanks, this was indeed a bug. I just pushed a fix, but it is probably worth noting that you will run into other problems with `overload(meta, a)`. You probably want `overloadt` (which doesn't suffer from this problem) if you are going to overload letter keys.
