### ISSUE TITLE
keyd cant start at boot, need service restart [i fixed .service file]

### ISSUE THREAD

**Issue by mikdmst1** [rvaiya/keyd#423]
archlinux, user added to group keyd, service enabled, /etc/keyd/default.conf created:
-------------------
[ids]

*

[main]
---------------------
journalctl log:
![изображение](https://user-images.githubusercontent.com/64324345/212885072-caf0dbe5-6766-475f-b871-e5508efb3d60.png)

after service keyd restarting all working

![изображение](https://user-images.githubusercontent.com/64324345/212885296-d9e94f8e-d03e-478b-bd21-0ab0df352b61.png)

**Comment by mikdmst1** [comment]
okay, i changet Required and After in keyd.service to graphical.target and in works now!

but, keyd-application-mapper cant start from ~/.xinit and ~/.xsession files, why?
and can u disable spam logging to .log file?

**Comment by mikdmst1** [comment]
okay, i use DM LightDM and i must use ~/.xprofile for autostart keyd-application-mapper - u can write it in readme. thx for useful program!

can u add new key for keyd-application-mapper for disable spam to log-file?, because i use ssd. thx!

**Comment by rvaiya** [comment]
> can u add new key for keyd-application-mapper for disable spam to log-file?

`-q` already exists. See `keyd-application-mapper --help`.
