### ISSUE TITLE
How to rebind the acute accent (´)?

### ISSUE THREAD

**Issue by linuxisfreedom** [rvaiya/keyd#425]
First of all, this tool is simply terrific. Thank you so much for programming it. :) This makes it really fun to work with Linux. For the first time, I was able to reprogram my Razer Naga Pro mouse and use all 12 extra buttons, except the 12th button. This button triggers an 'accent aigu' (´) on my system.  But this accent is only written when I press another key resulting in letters like á, é, ṕ, ú, etc. or space resulting in ´. This accent is different from the actual accent ('), which has a separate key on my keyboard.

Now, if I want to rebind the twelfth key, like:

´ = macro(leftcontrol+g)

or

´ = x

it has no effect. This is probably because the accent is actually written with two keys, the accent-aigu key and another key. But the twelfth key only activates the first one, which I can't write in my Razer.conf file. Is there a solution to this problem?

**Comment by linuxisfreedom** [comment]
My apologies, I've found the solution with keyd monitor. The 12th button activates everywhere the Acute accent, including the terminal, but in keyd monitor it shows the '='-button. The following line in Razer.conf does the trick:

= = macro(leftcontrol+g)

**Comment by svonjoi** [comment]
how to invoke accent dead key `<dead_acute>` in normal keyboard?

**Comment by rvaiya** [comment]
@svonjoi You can use `keyd monitor` to see which keystrokes are produced by a given key combination on your keyboard. If you can't achieve the desired result please create a dedicated issue with a detailed description of the problem.
