### ISSUE TITLE
failed to open /dev/input/by-id

### ISSUE THREAD

**Issue by progmanner** [rvaiya/keyd#426]
hi it works for me but i checked  "sudo journalctl -eu keyd " 
and it outputs some errors:

```
Jan 22 11:32:48 pc keyd[363]: ioctl: Inappropriate ioctl for device
Jan 22 11:32:48 pc keyd[363]: ioctl EVIOCGNAME: Inappropriate ioctl for device
Jan 22 11:32:48 pc keyd[363]: failed to open /dev/input/by-id
```

**Comment by rvaiya** [comment]
What version of keyd are you running? (`keyd -v`). I believe this should no longer be an issue.

**Comment by Apacelus** [comment]
@rvaiya this happens if one build from the latest release, as mentioned in the README
> Releases are [tagged](https://github.com/rvaiya/keyd/tags), and should be considered stable.

Perhaps its time for a new release?

**Comment by rvaiya** [comment]
@Apacelus Indeed. See #463.

I'm closing this for now, since the original author hasn't responded.
