### ISSUE TITLE
Is there a way to donate?

### ISSUE THREAD

**Issue by adastx** [rvaiya/keyd#427]
This fantastic program has made switching to a custom layout so seamless I forget it's custom.
I've been using keyd for almost a year now and I'd like to give a little back.
Opened this issue as I couldn't find any relevant links on your profiles (github/gitlab).

**Comment by ad-laurentius** [comment]
+1 for this.
I have tried other similar applications but this one is the best, and the only one that I could rely on for my workflow.

Honestly, I can't believe that keyd is free.

**Comment by rvaiya** [comment]
I'm glad other people find it useful :). I've added a kofi button to the README if you wish to donate.

**Comment by joihn** [comment]
I was not familiar with Kofi, and had to read this issue to figure out it's for donation, maybe a small string "donation" could be added to readme

**Comment by korbal** [comment]
@rvaiya I would have loved to donate as well, but the kofi link seems to be gone. You are doing god's work with Keyd, would love to support it!

**Comment by adastx** [comment]
The link is right at the top of the README, just above the 'Impetus' 
header.

I'll also include it here for good measure: https://ko-fi.com/rvaiya
