### ISSUE TITLE
Do you have a plan to do different remapping depending on the application?

### ISSUE THREAD

**Issue by aeghn** [rvaiya/keyd#43]
As I said in the title, the same key is mapped to different keys depending on the application.

For example, mapping `C-a` to` Home` in an application like firefox
In emacs `C-a` is still `C-a`

**Comment by rvaiya** [comment]
No, this is best done at the application level. keyd aims to be a key->key remapping tool like QMK and has no knowledge of the display server.

**Comment by aeghn** [comment]
Okay, thanks for the reply.

**Comment by rvaiya** [comment]
You may want to keep an eye on #51 and #59.

**Comment by aeghn** [comment]
Thanks for the heads up. I'm currently preparing to fork your code and add this part myself.

**Comment by lemnos** [comment]
A prototype has already been implemented in #51 and will probably be fleshed out and provided as a companion script. The missing piece (to make it performant) is hot reloading which should be provided in the upcoming 2.0 release. Before you fork the project I would appreciate it if you could elaborate on how you expect such a feature to work.

**Comment by rvaiya** [comment]
A prototype has already been implemented in #51 and will probably be fleshed out and provided as a companion script. The missing piece (to make it performant) is hot reloading which should be provided in the upcoming 2.0 release. Before you fork the project I would appreciate it if you could elaborate on how you expect such a feature to work.

**Comment by aeghn** [comment]
I skimmed through #51 and found that it seems to use the gnome interface, but I'm not a fan of gnome and I'm currently using i3wm. so it might be a bit different.

There are two main scenarios for my use

1. mapping to different keys in different windows
    This is not so easy to do at the software level, because many software entries are used to map keys, for example, I like to use control-n for down, but in firefox this can only be used for creating new windows, so it is easier to do this in the uniput layer according to different windows, and different applications get the keys that have been simulated.

    To make things more complicated, I might need to simulate a key as a key sequence or a key sequence as a key, like mapping `c-x c-s` to `c-s` in a window other than emacs.

2. It may be that a key may be used to execute a particular shell command in a different window.

    I'm using `super+<num>` in i3-wm to switch between different workspaces.

    And I usually have a Windows kvm guest on to use some software that is not available on linux, and I put this in a separate workspace, and then if I press `super+num` in the Windows guest, it is grabbed by the windows guest and I can't switch between workspaces. But if I can map different keys to execute shell commands in different applications, then I can execute `i3-msg workspace 1` when I press `super+1`, which can greatly improve my productivity

**Comment by rvaiya** [comment]
> There are two main scenarios for my use

I understand why this is desirable and, given the recent demand, will probably include support for it in the form of an optional companion script which makes use of the core.

> I skimmed through #51 and found that it seems to use the gnome interface.

It was only a prototype demonstrating what is possible. Note that there is a comment in the script `support all the things` :P. I targeted gnome because that is what canadaduane is using. 

> but I'm not a fan of gnome and I'm currently using i3wm. so it might be a bit different.

Indeed.

Unfortunately there isn't a universal way to monitor and obtain window information across environments. While there is no silver bullet, it shouldn't be too hard to add support for the three major platforms (gnome, X, and wlroots based projects). 

But ultimately this sort of patchwork approach is best achieved as a separate component rather than trying to pull a bunch of desktop specific libs into the main daemon. I do plan on making some changes to the core to facilitate this sort of thing, but it is already mostly possible (with a performance bottleneck that should be remedied with the 2.0 release).

**Comment by aeghn** [comment]
> But ultimately this sort of patchwork approach is best achieved as a separate component 

And you can enable different methods of getting windows class (app-id in wayland) with different parameters, different configurations (or automatic detection by the program).


And in my current thinking, the mapping to shell commands via shortcuts should also be in a separate module, because there is a need to drop privileges before executing specific shell commands for security reasons.

**Comment by rvaiya** [comment]
Experimental support for this has been added. Feedback would be appreciated :).

**Comment by aeghn** [comment]
Nice, I'll try it a little later after I'm done with the task at hand.
