### ISSUE TITLE
How I set shift + F10 to rightalt

### ISSUE THREAD

**Issue by Rishav8989** [rvaiya/keyd#431]
How I set shift + F10 to rightalt

**Comment by slakkenhuis** [comment]
Try this snippet:

```
[shift]
f10 = swap(altgr)
# Or layer(altgr), depending on if you want shift to also remain active
```

That said, it's good practice to indicate where the manual was unclear and what you had already tried. :)

**Comment by Rishav8989** [comment]
Still not Working I want to set  rightalt = shift + f10 or something correct me how should i do it

**Comment by slakkenhuis** [comment]
> doesn't explain how to set multiple key strokes

That's under the [macros](https://github.com/rvaiya/keyd/blob/bcfb8bb3390cb293c0b2bc72f04fd0a339d7b1ca/docs/keyd.scdoc#L577) header.

> Still not Working

Depends on what you want to achieve. I now understand you meant the other way around --- emit `shift` and `f10` when you press `rightalt`. Try this:

```
[main]
rightalt = S-f10
```

**Comment by Rishav8989** [comment]
Thank you and Sorry for my Ignorance. You just solve me my most annoying issue, you are such a kind developer. Your projects Inspire me as you are solving real life issue I will follow your Future Projects
