### ISSUE TITLE
how to use layer with oneshot

### ISSUE THREAD

**Issue by kanishkaverma** [rvaiya/keyd#436]
Hey, 
I had an idea but was not sure how to implement it. 
I read the man page and tried to look on GitHub but not sure how to do this or what to look for. 
basically, 
if I hold capslock with d I want it to be a oneshot shift and if I tap capslockwith f, I want it to be a oneshot control. 
and If i use capslock with anything else then it should just work as control and if i tap capslock it's just escape. this is the config i thought would work
```
[ids]

* 

[main]

leftshift = oneshot(shift) 
leftcontrol = oneshot(control)
capslock = overload(test, esc) 

      
[test:C]

d = oneshot(leftshift)
f = oneshot(leftcontrol)
```
However, this doesn't work. if i remove oneshot from the test layer at least i can get shift and control to appear however they go away as soon as i lift my finger from the d and f key. I was thinking of this functionality as to implement something similar to a 40 key ortho keyboard where everything is on the home row. let me know what you think or something of a better functionality which might work for better ergonomics. Thanks for your time. 
warmest regards, 
Kanishka

**Comment by rvaiya** [comment]
@herrsimon is correct, `oneshot` expects a layer argument. The rest of your config looks correct.
