### ISSUE TITLE
Config doesn't work unless every line ends with a newline character?

### ISSUE THREAD

**Issue by slein-nl** [rvaiya/keyd#438]
```
if (line[len-1] != '\n') { 
	err("maximum line length exceed (%d)", MAX_LINE_LEN);
	goto fail;
}
```
This if statement in config.c line 125 seems to be intending to check that each line's length isn't greater than MAX_LINE_LEN (based on the error message), but actually checks that the last character of each line isn't a newline? I assume  something like this was intended:
```
if (len > MAX_LINE_LEN) {
	err("maximum line length exceed (%d)", MAX_LINE_LEN);
	goto fail;
}
```

I was having problems with this because i happened to not put newline on the very last line of my config and was puzzled why i didn't work, adding a newline at the end seemed to fix it, seems like a bug

**Comment by rvaiya** [comment]
> This if statement in config.c line 125 seems to be intending to check that each line's length isn't greater than MAX_LINE_LEN (based on the error message), but actually checks that the last character of each line isn't a newline? I assume something like this was intended:

The code is correct, fgets will read up to size-1 bytes irrespective of whether or not there is a terminating newline.

> I was having problems with this because i happened to not put newline on the very last line of my config

How did you manage to achieve this? Almost every sane editor will automatically add a newline to the end of the file when you save the file.

> seems like a bug

It is in fact a feature ;).

**Comment by slein-nl** [comment]
> How did you manage to achieve this? Almost every sane editor will automatically add a newline to the end of the file when you save the file.

Huh, yea just tested it now and every other editor i tried seems to do this, helix however doesn't for some reason, which is what i normally use
