### ISSUE TITLE
"Stuck" oneshot layer

### ISSUE THREAD

**Issue by Compile-Time** [rvaiya/keyd#44]
Sometimes keyd gets "stuck" on an oneshot layer. This causes every key press to have the stuck oneshot layer applied to 
it. This problem is reproducible with the following config:

```
# Makes the shift key sticky for one keystroke.
leftshift = oneshot(S)
rightshift = oneshot(S)
```

To trigger the stuck state, the following can be done:
1. Hold down left shift and right shift
2. Press any letter on the keyboard once
3. Release left shift and right shift

Now every key press will have the shift modifier applied which looks like caps lock is enabled. To get out of the stuck 
state either left shift or right shift has to be pressed again.

This stuck effect is not specific to left and right shift. I have managed to trigger this effect on oneshot mappings for
AltGr aswell sometimes. However, I only found left shift and right shift to consistently trigger this effect for me.

So I would guess, that there is some issue when two oneshot layers are triggered at the same time or with a small time difference to each other.

Tested with keyd version: 1.1.2 (81313204ad8e9f29b21fa906aaf2838b241939a4)

**Comment by rvaiya** [comment]
Thanks for detailed description. I believe this should be fixed in the latest commit.
