### ISSUE TITLE
Keyd's virtual pointer emits wrong button codes

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/keyd#441]
This is probably not a keyd issue, but nevertheless I'm recording it here: After having updated my laptop (running Archlinux), the buttons emitted by keyd's virtual pointer are suddenly 18, 17 and 16 (leftmouse, middlemouse, rightmouse) instead of 1, 2 and 3. I had to fix this via `xinput set-button-map`. Is there any explanation for this strange behaviour?

**Comment by rvaiya** [comment]
I suppose it is possible that the X/Wayland events corresponding to the generated evdev events have changed, but that seems unlikely. I will investigate when I have some time. If you still have access to another system where it works, you might try comparing the generated keycodes displayed by evtest.

**Comment by rrveex** [comment]
This fixes the issue for me:
```
diff --git a/src/vkbd/uinput.c b/src/vkbd/uinput.c
index b98e585..d1a9fca 100644
--- a/src/vkbd/uinput.c
+++ b/src/vkbd/uinput.c
@@ -103,7 +103,6 @@ static int create_virtual_keyboard(const char *name)
 
 static int create_virtual_pointer(const char *name)
 {
-       uint16_t code;
        struct uinput_user_dev udev = {0};
 
        int fd = open("/dev/uinput", O_WRONLY | O_NONBLOCK | O_CLOEXEC);
@@ -126,11 +125,11 @@ static int create_virtual_pointer(const char *name)
        ioctl(fd, UI_SET_RELBIT, REL_Y);
        ioctl(fd, UI_SET_RELBIT, REL_Z);
 
-       for (code = BTN_LEFT; code <= BTN_TASK; code++)
-               ioctl(fd, UI_SET_KEYBIT, code);
-
-       for (code = BTN_0; code <= BTN_9; code++)
-               ioctl(fd, UI_SET_KEYBIT, code);
+       ioctl(fd, UI_SET_KEYBIT, BTN_LEFT);
+       ioctl(fd, UI_SET_KEYBIT, BTN_RIGHT);
+       ioctl(fd, UI_SET_KEYBIT, BTN_MIDDLE);
+       ioctl(fd, UI_SET_KEYBIT, BTN_SIDE);
+       ioctl(fd, UI_SET_KEYBIT, BTN_EXTRA);
 
        udev.id.bustype = BUS_USB;
        udev.id.vendor = 0x0FAC;
```

**Comment by rvaiya** [comment]
@rrveex Odd, that shouldn't make a difference. What distro/kernel are you using? Can you post your `/usr/include/linux/input-event-codes.h`?

@herrsimon  What is the output of `evtest $(evtest 2>&1|awk -F: '/keyd virtual pointer/{print $1;exit}')`  when trying to use these keys?

**Comment by rrveex** [comment]
> What distro/kernel are you using? 

6.2.2-artix1-1

> Can you post your `/usr/include/linux/input-event-codes.h`?

```
[...]
#define KEY_WWAN		246	/* Wireless WAN (LTE, UMTS, GSM, etc.) */
#define KEY_WIMAX		KEY_WWAN
#define KEY_RFKILL		247	/* Key that controls all radios */

#define KEY_MICMUTE		248	/* Mute / unmute the microphone */

/* Code 255 is reserved for special needs of AT keyboard driver */

#define BTN_MISC		0x100
#define BTN_0			0x100
#define BTN_1			0x101
#define BTN_2			0x102
#define BTN_3			0x103
#define BTN_4			0x104
#define BTN_5			0x105
#define BTN_6			0x106
#define BTN_7			0x107
#define BTN_8			0x108
#define BTN_9			0x109

#define BTN_MOUSE		0x110
#define BTN_LEFT		0x110
#define BTN_RIGHT		0x111
#define BTN_MIDDLE		0x112
#define BTN_SIDE		0x113
#define BTN_EXTRA		0x114
#define BTN_FORWARD		0x115
#define BTN_BACK		0x116
#define BTN_TASK		0x117

#define BTN_JOYSTICK		0x120
#define BTN_TRIGGER		0x120
#define BTN_THUMB		0x121
#define BTN_THUMB2		0x122
[...]
```
I just compared with https://github.com/wyatt8740/mouseemu (which still worked after distro upgrade) and copy/pasted.
Looks like the second loop (BTN_0..BTN_9) does "something" to the udev-mouse.

**Comment by rvaiya** [comment]
@rrveex

> Looks like the second loop (BTN_0..BTN_9) does "something" to the uinput-mouse.

By which I assume you mean:

> -       for (code = BTN_0; code <= BTN_9; code++)
> -               ioctl(fd, UI_SET_KEYBIT, code);

alone solves the problem. If so, my suspicion is that some mouse detection mapping/code has changed in X/libinput, which would also explain why it happened after updating.

@herrsimon

> I clicked left, middle and right. It seems as if the middle and right buttons are recognized correctly, but still the clicks are not recognized 
> (in the sense that graphical applications do not react) without using xinput set-button-map as described above

BTN_RIGHT failing to generate a right click suggests a change higher up the input stack consistent with my theory, though BTN_SIDE being generated by `leftmouse` (I assume this is what you are using in your keyd config) shouldn't happen (indeed, I get BTN_LEFT using 26e19358 in my own testing).

**Comment by rvaiya** [comment]
@herrsimon Can you post the output of `xinput list`?

**Comment by rrveex** [comment]
@rvaiya 
> If so, my suspicion is that some mouse detection mapping/code has changed in X/libinput

Yes, that's what I suspect too. Something like "if your pointer device has 17 buttons, it means it's some new iThingy and has to behave differently".

`libinput debug-events`, press keyboard "shortcut" for middle-mouse-click:

--- original keyd (with both loops)
```
-event13  TABLET_PAD_BUTTON       +39.030s	12 pressed (mode 0)
 event13  TABLET_PAD_BUTTON       +39.157s	12 released (mode 0)
```

--- modified keyd (second loop commented out)
```
 event13  POINTER_BUTTON          +0.000s	BTN_MIDDLE (274) pressed, seat count: 1
 event13  POINTER_BUTTON          +0.128s	BTN_MIDDLE (274) released, seat count: 0
```

**Comment by rvaiya** [comment]
@herrsimon Thanks.

I did a bit of digging and was able to narrow it down this commit in systemd:

https://github.com/systemd/systemd/commit/0855ce6772#diff-e3c18b2fc4f50acbb9f2d66a1daf229fde99a5c8785f17aa6f69e6a9c41ae2c7R261

It seems devices which are capable of emitting BTN_0 (and wheel events) are now treated as 'tablet pads'. This seems odd to me, since I believe BTN_0 is just a generic button event that can be used by any mouse driver, but I couldn't find any documentation which corroborates this (perhaps @whot can shed some light). In any case, the events are currently unused in keyd, so I have removed them in 0fb86d3a9, which should solve the problem.

**Comment by whot** [comment]
>  I believe BTN_0 is just a generic button event that can be used by any mouse driver

Mice and similar devices use the buttons starting with `BTN_LEFT` and up. `BTN_0` is really a "generic numbered button" and only tablet pads use those (statistically anyway) - you shouldn't see real-world mice with those buttons. Mind you, there's [this systemd PR](https://github.com/systemd/systemd/pull/26666) which may also fix this issue here I just haven't had the time to look at that one yet.

**Comment by rvaiya** [comment]
@whot Thanks for the edification :). I'm going to mark this as closed. @herrsimon Feel free to reopen if the issue remains unresolved.

**Comment by rrveex** [comment]
> couldn't find any documentation which corroborates this

Documentation is deprecated in systemd. Documentation is readable by humans, we only do binary, therefore can't read nor write it. By not adhering to documentation, we are able to boot more quickly.
~~ Poettering

**Comment by whot** [comment]
@herrsimon just a troll, ignore them, nothing to be gained by playing in their hands.
