### ISSUE TITLE
Request: increase maximum number of chords

### ISSUE THREAD

**Issue by w-jablonski** [rvaiya/keyd#450]
I get the `max chords exceeded(32)` error. Can we increase this limit please? thanks!

**Comment by rvaiya** [comment]
Can you elaborate on your use case?

**Comment by w-jablonski** [comment]
Yes and thank you. 
Experimenting with using chords to input punctuation, arrows, and others, without moving hands around. Notice that some of these are multiplied, which obviously increases the number of chords. E.g. `d+f = up` so I don't have to move my hand across to hit arrows, but also `s+d = up` to prevent errors. Then also `j+k = up` and `k+l = up` to have similar setup under right hand, for the occasion when I hold mouse under left. Below my current setup. I guess I belong to the minority who get really distracted when having to displace hand from the base position. Thanks again! 

```
h+y = kpleftparen
j+u = kprightparen
k+i = [
l+o = ]
h+n = ;
j+m = :
k+, = "
l+. = apostrophe
y+u = -
h+j = _
n+m = equal

j+k = up
k+l = up
m+, = down
,+. = down

s+w = C-backspace
d+e = backspace
f+r = delete
g+t = C-delete

s+d = up
d+f = up
x+c = down
c+v = down

z+s = left
x+d = left
s+c = right
d+v = right
```

**Comment by rvaiya** [comment]
I didn't expect anyone to actually use this many chords (I was going to suggest composite layers, but it seems you really do need chords to achieve what you want). I've double the maximum number of chords per layer in the latest commit which should allow you to achieve this.
