### ISSUE TITLE
Remaping keys ignores included layout

### ISSUE THREAD

**Issue by montdor** [rvaiya/keyd#454]
Hi! I tried to find a similar issue, but couldn't quite. Happy to delete this if I happened to miss it!

In my configuration, I include an alternative layout (colemak in this case), then later on make a 'navigation' layers with the vi keys. I thought the feature was broken on my end, until I realized that keyd is remapping the vi keys their original positions and not the ones changed in colemak. I think this may be a bug, as most would want the explicitly changed keys (i.e., in the included layout) to be the ones changed later on. I was able to work around it by mapping the keys below the colemak keys instead of the 'normal' vi keys (e.g., y is the original key where colemak j sits, etc.) Below is my default.conf file with the workaround:

`
[ids]
*

include layouts/colemak

[global]
default_layout = colemak

[main]
tab = overload(meta, tab)
backslash = overload(meta, backslash)
capslock = overload(control, esc)

[control]
space = swap(vim_mode)

[vim_mode:C]
h = left
y = down
n = up
u = right
w = C-right
b = C-left

`

Please let me know if any other information would be helpful!

**Comment by montdor** [comment]
Ok, thank you for pointing me in the right direction! I was sure this had to have been discussed somewhere. I'll be sure to try it that way.

**Comment by rvaiya** [comment]
Left hand values always correspond to the same physical positions on the board by design. As mentioned in the referenced posts, a 'layout' in keyd is just a special kind of layer with certain constraints, it has no effect on the rest of the config file.
