### ISSUE TITLE
Keyd has no affect on Fedora 37

### ISSUE THREAD

**Issue by queer-bird** [rvaiya/keyd#455]
Hello, I really enjoy your software. I was using it happily on Arch Linux with KDE on Wayland and Hyprland. I recently moved my laptop to Fedora with GNOME, set keyd up the usual way cloning from github and using the same config file that worked just fine on Arch. However, it seems not to work and my keyboard layout is as default as ever. Any idea how I can troubleshoot this?

**Comment by queer-bird** [comment]
● keyd.service - key remapping daemon
     Loaded: loaded (/usr/lib/systemd/system/keyd.service; enabled; preset: disabled)
     Active: active (running) since Fri 2023-03-10 08:54:42 PST; 13min ago
   Main PID: 1445 (keyd)
      Tasks: 2 (limit: 18787)
     Memory: 608.0K
        CPU: 775ms
     CGroup: /system.slice/keyd.service
             └─1445 /usr/bin/keyd

Mar 10 08:54:42 fedora systemd[1]: Started keyd.service - key remapping daemon.
Mar 10 08:54:42 fedora keyd[1445]: Starting keyd v2.4.2 (0fb86d3)
Mar 10 08:54:42 fedora keyd[1445]: DEVICE: ignoring 0fac:1ade  (keyd virtual pointer)
Mar 10 08:54:42 fedora keyd[1445]: DEVICE: ignoring 04f3:3150  (ELAN0670:00 04F3:3150 Touchpad)
Mar 10 08:54:42 fedora keyd[1445]: DEVICE: ignoring 04f3:3150  (ELAN0670:00 04F3:3150 Mouse)
Mar 10 08:54:42 fedora keyd[1445]: DEVICE: ignoring 0002:000a  (TPPS/2 Elan TrackPoint)
Mar 10 08:54:42 fedora keyd[1445]: DEVICE: ignoring 0001:0001  (AT Translated Set 2 keyboard)

**Comment by queer-bird** [comment]
OK lt does say it is ignoring the keyboard but I don't know what to do with that info.

**Comment by slakkenhuis** [comment]
What's your config? If it did work on Arch, I'm assuming that `*` or `0001:0001` is in your `[ids]` section?

**Comment by queer-bird** [comment]
Yes that is correct, but I fixed it. Somehow my config file got corrupted and replacing it fixed it. Silly me. :/
