### ISSUE TITLE
Is there way to remap numeric keypad for numlock on/off state?

### ISSUE THREAD

**Issue by Signy13** [rvaiya/keyd#457]
First of all I would like to thank you for keyd. I like its approach very much.
But I am struggling with remapping of numeric keypad, when numlock is on/off. My idea is to have numeric keypad for my left hand where:
-  numbers are mirrored (in comparison to regular keypad) 
- but when is numlock off, arrows works almost in the same way: they return the same keycode as normal arrow keys (not the special for numlock).

I managed to remap keys when it is independent to the numlock state:
```
[main]
kp1 = kp3
kp3 = kp1
kp4 = kp6
kp6 = kp4
kp7 = kp9
kp9 = kp7
kpdot = kp0
kp0 = kpdot
```
What I need is different remap when numlock is on from the state when numlock is off, something like this:
```
# When numlock is on
kp1 = kp3
kp3 = kp1
kp4 = kp6
kp6 = kp4
kp7 = kp9
kp9 = kp7
kpdot = kp0
kp0 = kpdot
# When numlock is off
kp2 = down
kp4 = left
kp6 = right
kp8 = up
```

**Comment by tkna91** [comment]
I wonder if it looks like this?
I have not tested it. Sorry if it didn't work.
```
[main]
# When numlock is on
kp1 = kp3
kp3 = kp1
kp4 = kp6
kp6 = kp4
kp7 = kp9
kp9 = kp7
kpdot = kp0
kp0 = kpdot
numlock = toggle(NUMLOCK)

[NUMLOCK]
# When numlock is off
kp2 = down
kp4 = left
kp6 = right
kp8 = up
numlock = clear()
```

**Comment by Signy13** [comment]
Great, works like a charm :-) Thank you very much!
