### ISSUE TITLE
Is it possible to run keyd systemd service as DynamicUser (uid != 0)?

### ISSUE THREAD

**Issue by ybnesm** [rvaiya/keyd#459]
Start a service like this: https://github.com/rvaiya/keyd/blob/04c9e15d70fe1019dc5a38359540270caf86cfcb/keyd.service#L7-L8 is ok on a personal machine, but when you want to create a service "for all" you need to sandbox service as much as possible. Now I'm trying to transfer the `keyd` service to `NixOS` and have a little trouble with `DynamicUser` option. So I'm wondering if this is even possible, I haven't looked at the codebase, maybe someone knows, or even starts the service like that.

**Comment by tkna91** [comment]
This may help you.

- https://github.com/rvaiya/keyd/issues/105
- https://github.com/rvaiya/keyd/issues/228
- https://github.com/rvaiya/keyd/pull/70

**Comment by rvaiya** [comment]
I am not familiar with that particular systemd option, but as long as keyd has r/w access to `/dev/uinput` and `/dev/input/event*` (which the `input` group on most systems usually has access to) as well as `/etc/keyd`, then it should work.

**Comment by ybnesm** [comment]
Yes, it works. Only my fault as I am not a long time systemd user yet. I added access to `/dev/input` correctly and it works now. If anyone is interested in this in the future, the issue mentioned above has the answer to how we achieved this.
Cheers.
