### ISSUE TITLE
Duplicate entries in `keyd -l`

### ISSUE THREAD

**Issue by canadaduane** [rvaiya/keyd#46]
I see some dups in the list of keys available via `keyd -l` (e.g. `up`, `down`, `menu`, `record`):

```
prevgroup
nextgroup
accept
cancel
up
down
up
down
menu
menu
11
12
desc
mode
favorite
record
record
vod
unmute
```

**Comment by rvaiya** [comment]
Thanks. This should be fixed in the latest commit.
