### ISSUE TITLE
Tag a new release with chords?

### ISSUE THREAD

**Issue by focusaurus** [rvaiya/keyd#463]
It seems the latest tag is v2.4.2 from July 2022 and AFAICT that has no chord support yet. Is there a newer commit you could tag and release?

**Comment by rvaiya** [comment]
Some of the changes sitting in master were originally intended to be experimental, but most of them will probably remain. A new release is indeed overdue, and should be due out soon™. I plan on making a few changes over the next week and doing a release shortly after that.

**Comment by rvaiya** [comment]
v2.4.3 has been released. Apologies for the delay :).
