### ISSUE TITLE
oneshot layer+shift becomes original layer+shift

### ISSUE THREAD

**Issue by tkna91** [rvaiya/keyd#464]
When I try to output `out2` below, it becomes `out1`.

`test.conf`
```
[ids]
*

[main]
tab = overload(TAB, tab)

[TAB]
q = overload(layer1, oneshot(layer1))
[TAB+shift]
j = macro(out0)

[layer1]
q = oneshot(layer2)
j = a
[layer1+shift]
j = macro(out1)

[layer2]
j = b
[layer2+shift]
#target
j = macro(out2)
```

screencast:

https://user-images.githubusercontent.com/102382754/228404830-4658db92-f953-4ad9-9501-0d7cf0ea12b9.mp4

**Comment by rvaiya** [comment]
Oneshots are stackable, so after `tab+q+q` both `layer1` and `layer2` are active in the above exampe. Composite layers require an exact match of the active layer set, so to fix it you need to use `layer2+layer1+shift` or use the new swap functionality introduced in `5166081` to ensure only layer2 is active (e.g `q = swap(layer2)`).

**Comment by tkna91** [comment]
I have had success with the following. Thank you!
Close it to your liking.
```
[layer1]
q = swap(layer2)
```
screencast:

https://user-images.githubusercontent.com/102382754/228747982-35c6fb34-a3ee-4690-bd4e-5c024f404939.mp4

**Comment by rvaiya** [comment]
Just be aware that there may be unintended side effects if you activate `layer1` by some other means. See the man page for details.
