### ISSUE TITLE
Keyd monitor shows all inputs coming from the same virtual device

### ISSUE THREAD

**Issue by TLMcNulty** [rvaiya/keyd#465]
Ubuntu 22.02 KDE Plasma 5
Kernel 6.1.19-v8+

```
➜  keyd keyd monitor                  
device added: 8808:6606 HID 8808:6606 Mouse (/dev/input/event8)
device added: 8808:6606 HID 8808:6606 Keyboard (/dev/input/event6)
device added: 8808:6606 HID 8808:6606 (/dev/input/event5)
device added: 8808:6606 HID 8808:6606 (/dev/input/event4)
device added: 0fac:1ade keyd virtual pointer (/dev/input/event10)
device added: 0fac:0ade keyd virtual keyboard (/dev/input/event9)
device added: 05ac:022c Bluetooth 3.0 Macro Keyboard (/dev/input/event3)
device added: 0000:0000 generic ft5x06 (79) (/dev/input/event2)
device added: 0000:0000 vc4-hdmi-1 (/dev/input/event1)
device added: 0000:0000 vc4-hdmi-0 (/dev/input/event0)
keyd virtual keyboard	0fac:0ade	enter up
keyd virtual keyboard	0fac:0ade	d down
keyd virtual keyboard	0fac:0ade	d up
keyd virtual keyboard	0fac:0ade	d down
keyd virtual keyboard	0fac:0ade	d up
keyd virtual keyboard	0fac:0ade	d down
keyd virtual keyboard	0fac:0ade	d up
keyd virtual keyboard	0fac:0ade	d down
keyd virtual keyboard	0fac:0ade	d up
keyd virtual keyboard	0fac:0ade	d down
keyd virtual keyboard	0fac:0ade	d up
keyd virtual keyboard	0fac:0ade	d down
keyd virtual keyboard	0fac:0ade	d up
keyd virtual keyboard	0fac:0ade	esc down
keyd virtual keyboard	0fac:0ade	esc up
keyd virtual keyboard	0fac:0ade	leftcontrol down
keyd virtual keyboard	0fac:0ade	c down
```

First half of these events came from device 8808:6606, the second half from 05ac:022c. Why does keyd show them all as coming from one virtual device?

Configurations with specific IDs set in [id] sections are not working due to this.

**Comment by slakkenhuis** [comment]
If a keyboard is managed by keyd, a keypress on it will show up as being generated by keyd's virtual keyboard. Does it also happen if you press a key on a keyboard that isn't managed by keyd?

If not, the bigger problem would be that your configuration doesn't work if specific IDs are set. What's your config?

**Comment by TLMcNulty** [comment]
Ah perhaps the problem is I hadn't rebooted after installation? How do I ensure a keyboard is or isn't being managed by keyd? I haven't explicitly set either of these devices to be managed by keyd, I simply wanted to use monitor to verify the ID of the device I want to set a specific map for. 

My config is bare bones. Default.conf is the example base config from the repo and macro.conf has one ID set and one macro command. The system is an embedded on so let me wander over to it and I'll post the confs verbatim.

**Comment by TLMcNulty** [comment]
```
➜  keyd cat default.conf 
[ids]

*

[main]

shift = oneshot(shift)
```

```
[ids]

8808:6606 

[main]

d = macro(lefttab+tab)
```

**Comment by TLMcNulty** [comment]
I replaced * with 05ac:022c and reloaded and the behavior is unchanged.
