### ISSUE TITLE
Layers are not deactivated after running oneshot command

### ISSUE THREAD

**Issue by tkna91** [rvaiya/keyd#466]
The `layer1` does not seem to be deactivate after the following `command1` execution.

`test.conf`
```
[ids]
*

[main]
tab = overload(TAB, tab)

[TAB]
q = overload(layer1, oneshot(layer1))

[layer1]
j = 1
k = command(echo -n command1 | keyd input)
```

screencast:

https://user-images.githubusercontent.com/102382754/228768165-3d1602f9-ff67-4d51-833e-e2462750aa52.mp4

**Comment by rvaiya** [comment]
I believe this should be fixed in the latest commit.

**Comment by tkna91** [comment]
Confirmed. Works as expected!
```
$ keyd --version
keyd v2.4.2 (a8469b2)
$
```
