### ISSUE TITLE
How to debug keyd-application-mapper?

### ISSUE THREAD

**Issue by neosix** [rvaiya/keyd#469]
Hello. I have this in my app.conf:

```
[code]
alt.e = macro(down down tab)
```
But nothing happens when I press alt+e. App.log doesn't give any information. Is there a way to debug and see why this doesn't work? I checked docs but I couldn't find anything. Thank you.

**Comment by tkna91** [comment]
In my environment (archlinux, package: `code 1.77.1-1`), the following worked.
```
[code-oss]
alt.e = macro(down down tab)
```

Debugging is available at
```
KEYD_DEBUG=1 keyd-application-mapper
```
Document added to pull request 0b4552d.

**Comment by neosix** [comment]
I solved my current issue, but I was more interested in debugging. Thank you!
