### ISSUE TITLE
Cannot remap left Alt to Left Ctrl and Vice Versa

### ISSUE THREAD

**Issue by donowop** [rvaiya/keyd#471]
Hello, I am new to linux and having trouble remapping my alt to ctrl and my ctrl key to alt on my keyboard using keyd on fedora.

I have followed the instructions to install but am stuck at where to place the default.conf file. Instructions say to place it in /etc/keyd/ but that file didnt exist until I created it. After a placed a default.conf file there and used the recommended config, I still cannot accomplish what I am looking for.

Running keyd monitor returns failed to open/dev/input/event1 and makes my terminal stuck.. I am unsure how to see the map of my keyboard using this tool and how to get this setup with the instructions that are provided, can anyone help please.

**Comment by slakkenhuis** [comment]
>I still cannot accomplish what I am looking for.

What exactly did you put in `/etc/keyd/default.conf`? It should probably look something like this:

```
[ids]
*

[main]
leftalt = layer(control)
leftcontrol = layer(alt)
```

Also, is keyd actually running?

```
sudo systemctl keyd start
sudo systemctl keyd enable
```

>Running keyd monitor returns failed to open/dev/input/event1

This is because it doesn't have access to your keyboard. You can run it with `sudo` (or add your user to the input group).

>and makes my terminal stuck..

It is a process that runs until you explicitly stop it. You can send the stop signal using control-c.

>I am unsure how to see the map of my keyboard

I'm not exactly sure what you mean by seeing the map - are you talking about `keyd monitor`?

If you did all this and you're still lost, you can view the logs with `sudo journalctl -u keyd`.

By the way, general questions like this are perhaps better suited for IRC ;)

**Comment by donowop** [comment]
> > I still cannot accomplish what I am looking for.
> 
> What exactly did you put in `/etc/keyd/default.conf`? It should probably look something like this:
> 
> ```
> [ids]
> *
> 
> [main]
> leftalt = layer(control)
> leftcontrol = layer(alt)
> ```

I originally had leftalt = leftcontrol and vice versa, but made these changes.

![2023-04-02-204550](https://user-images.githubusercontent.com/58542761/229406874-731be7e8-ac66-4f35-90ad-c769ea5414a6.png)


> Also, is keyd actually running?
> 
> ```
> sudo systemctl start keyd
> sudo systemctl enable keyd
> ```

Yes, I have keyd running using these commands and I am still having issues with my alt key being mapped as ctrl.

> > Running keyd monitor returns failed to open/dev/input/event1
> 
> This is because it doesn't have access to your keyboard. You can run it with `sudo` (or add your user to the input group).

Running it with sudo works and returns the following

![2023-04-02-203617](https://user-images.githubusercontent.com/58542761/229405736-e5580355-4288-4747-a7e2-1179b0d12b7d.png)


> > and makes my terminal stuck..
> 
> It is a process that runs until you explicitly stop it. You can send the stop signal using control-c.

Thank you I am learning alot from you <3

> > I am unsure how to see the map of my keyboard
> 
> I'm not exactly sure what you mean by seeing the map - are you talking about `keyd monitor`?

Yes, I am trying to figure out how to tell which key is expressed in the conf file, for example, how did you know leftcontrol was spelled like like and not leftctrl?

> If you did all this and you're still lost as to what's wrong, you can view the logs with `sudo journalctl -u keyd`.
 This is what returns when I run that command
![2023-04-02-204003](https://user-images.githubusercontent.com/58542761/229406282-18573ca3-845c-447a-8a71-9914bd9d5bff.png)


> By the way, general questions like this are perhaps better suited for IRC ;) But hope this helps!

So sorry, I am new to github and linux, I really appreciate the time you spent to help respond to my questions it means alot! Do you see anything I may be doing wrong? Thank you again

**Comment by slakkenhuis** [comment]
No worries! It seems that your config doesn't match any actual keyboards, which is odd because the `[ids]` section has the catch-all `*`.

What version of `keyd` are you running? Use `keyd -v` to check.

What is the ID of the keyboard you're trying to remap? Does something turn up when you press a key while running `keyd monitor`? Normally, this will show you what key you pressed along with the ID of the keyboard that generated it.

You can also see an overview of connected devices using `lsusb`. What's the output of that?

> I am trying to figure out how to tell which key is expressed in the conf file

Ah --- you can use `keyd monitor` and press a key to find out its name. (Alternatively, if you prefer, there's a list [here](https://github.com/rvaiya/keyd/issues/177#issuecomment-1092064707).)

**Comment by donowop** [comment]
> No worries! It seems that your config doesn't match any actual keyboards, which is odd because the `[ids]` section has the catch-all `*`.
> 
> What version of `keyd` are you running? Use `keyd -v` to check.

I am running 2.4.2
![2023-04-04-185952](https://user-images.githubusercontent.com/58542761/229961881-c42d669f-6e0d-4f75-bf8c-c88748ba5d64.png)


> What keyboard do you have? And what is its ID? Does something turn up when you press a key while running `keyd monitor`? Normally, this will show you what key you pressed along with the ID of the keyboard that generated it.

I am using [Logi MX Keys](https://www.amazon.com/Logitech-Advanced-Wireless-Illuminated-Keyboard/dp/B07S92QBCJ/ref=sr_1_1?keywords=logitech+mx+keys&sr=8-1)

Nothing returns when I press a key after sudo keyd monitor is running. Only thing that returns are those two lines pictured above that start with 'device added:' How can I find my keyboards ID?

> You can also see an overview of connected devices using `lsusb`. What's the output of that?

I am running Fedora on Qubes OS so I have a separate VM that directs the usbs to all my other VM including this fedora vm. I wanted to run Qubes for security, but hope I am not in over my head trying to simply remap the keys to be more comfortable on the keyboard @_@

I have two logi devices, one mouse and one keyboard but after testing I found its on Bus 002 Device 006: ID 046d:c52b
![2023-04-04-190621](https://user-images.githubusercontent.com/58542761/229962611-5c05b922-3562-4222-bad2-76e79137d666.png)


> > I am trying to figure out how to tell which key is expressed in the conf file
> 
> Ah --- you can use `keyd monitor` and press a key to find out its name. (Alternatively, if you prefer, there's a list [here](https://github.com/rvaiya/keyd/issues/177#issuecomment-1092064707).)

Ye I figured that was the command that was suppose to give me what I was looking for but I'm guessing this issue is because my usb device is being passed through from my USB VM to my Fedora VM

**Comment by slakkenhuis** [comment]
Ah, yeah, the VM situation might complicate things. I don't have an immediate solution, but just to make sure: the keyboard is `046d:c52b` on both the host machine and the guest VM? And `keyd` is installed and running on the guest VM?

**Comment by donowop** [comment]
> Ah, yeah, the VM situation might complicate things. I don't have an immediate solution, but just to make sure: the keyboard is `046d:c52b` on both the host machine and the guest VM? And `keyd` is installed and running on the guest VM?

Yeah, I'm just going to give up on this =/

**Comment by zach-is-my-name** [comment]
This helped me remap: rightalt=layer(control)
instead of the failing: rightalt=leftcontrol
