### ISSUE TITLE
Is it possible to use continuous pressure?

### ISSUE THREAD

**Issue by CRAG666** [rvaiya/keyd#474]
I am using wayland, and I would like to use the keyboard to control the course, I already managed to do that now my question is how can I do so that when I press an assigned key it invokes the command continuously, something like what happens when you hold down a key for example the "a" key.
This is the configuration I currently have
````
h = command(runuser -l think-crag -c 'wlrctl pointer move -40 0')
j = command(runuser -l think-crag -c 'wlrctl pointer move 0 40')
k = command(runuser -l think-crag -c 'wlrctl pointer move 0 -40')
l = command(runuser -l think-crag -c 'wlrctl pointer move 40 0')
i = command(runuser -l think-crag -c 'wlrctl pointer move 40 -40')
u = command(runuser -l think-crag -c 'wlrctl pointer move -40 -40')
m = command(runuser -l think-crag -c 'wlrctl pointer move 40 40')
n = command(runuser -l think-crag -c 'wlrctl pointer move -40 40')
````

**Comment by CRAG666** [comment]
what i really want to do is the mousekeys functionality

**Comment by rvaiya** [comment]
`command()` is not repeatable. Native mouse support is on the agenda, but in the meantime you might want to check out [warpd](https://github.com/rvaiya/warpd).
