### ISSUE TITLE
Keyboard doesnt deactivate in tablet mode on Chromebooks with normal Linux

### ISSUE THREAD

**Issue by Apacelus** [rvaiya/keyd#475]
This is happening on Chromebooks with normal Linux, not ChromeOS

When flipping into tablet mode, the keyboard doesnt deactivate if keyd is running. As soon as keyd.service is stopped, the keyboard turns off.

This quirks file https://github.com/rvaiya/keyd/commit/0f2926e1cd15bac90853f8a19a13ddd5a3b1234f#diff-ea0aba6559724180cdfe09cbc824013fa38f37142075f977acf0aac076a96457 helps with this, but also in turn disables the touchpad in normal mode too.

**Comment by tkna91** [comment]
Is that in a linux environment built this way?
https://support.google.com/chromebook/answer/9145439

What is the distribution?

**Comment by Apacelus** [comment]
No, as I tried to point out, this is **NOT** in ChromeOS/Crostini/Crouton, etc. This is normal, mainline Linux, running on bare hardware.

The behavior is distro independent (Fedora, arch and Ubuntu have it)

**Comment by tkna91** [comment]
What are you using to achieve that tablet mode?
Perhaps one of the following?
- https://github.com/alesya-h/linux_detect_tablet_mode
- https://github.com/coNQP/tablet-mode

Or is it something that turns the keyboard off when the tablet mode switch is enabled by libinput or some other process without them?

**Comment by Apacelus** [comment]
Im not using anything, it works out of the box. I assume its the ec module in the kernel

**Comment by rvaiya** [comment]
Presumably some part of your input stack is (probably libinput) is doing some magic based on the vendor/product id pair. You will have to modify this to account for the keyd virtual edevice. Since this isn't strictly a keyd issue, I'm closing this for now, but do feel free to post the solution if you find one.
