### ISSUE TITLE
Typo in man page

### ISSUE THREAD

**Issue by pablos-here** [rvaiya/keyd#476]
Hi,

There's a typo in the `ACTIONS` section of the `man` page for `timeout`.

Currently, it says:

>timeout(<action 1>, <timeout>, <action 2>)
>    If the key is held in isolation for more than <timeout> ms, activate
>    the first action, 

but I believe what we want to say is:

>    If the key is held in isolation for more than <timeout> ms, activate
>    the **second** action,

**Comment by rvaiya** [comment]
Thanks. This should be fixed. Feel free to submit a PR next time.

**Comment by pablos-here** [comment]
> Feel free to submit a PR next time.

I was going to but I thought, that it seems too puny of a change to do a PR.  But next time, I will.  _/\_
