### ISSUE TITLE
Setting leftshift as overload(shift, oneshot(shift)) and holding both lshift and rshift causes the "kbd->layer_state[idx].active > 0" assertion to fail

### ISSUE THREAD

**Issue by antrmn** [rvaiya/keyd#478]
I'm running the code from the latest commits. To replicate the issue, use this config:

    [ids]
    *
    [main]
    leftshift=overload(shift, oneshot(shift))

Start keyd, then do the following:

- Hold right shift
- Tap  left shift
- Release right shift

You'll notice that keyd will terminate with the following message (Taken from `systemctl status keyd`):

    apr 06 14:24:34 192.168.1.69 keyd[21873]: keyd: src/keyboard.c:247: deactivate_layer: Assertion kbd->layer_state[idx].active > 0' failed.
    apr 06 14:24:34 192.168.1.69 systemd[1]: keyd.service: Main process exited, code=dumped, status=6/ABRT
    apr 06 14:24:34 192.168.1.69 systemd[1]: keyd.service: Failed with result 'core-dump'.

["kbd->layer_state[idx].active > 0" ](https://github.com/rvaiya/keyd/blob/a8469b2dba3056c06c21e825b6c6ba5d97fbf55e/src/keyboard.c#L247)

If you repeat the steps listed above while reading the output of `keyd listen` you can see the program terminating when it should prit "-shift" 3 times, even if "+shift" has only been printed 2 times:

    $ sudo keyd listen
    +shift
    +shift
    -shift
    -shift
    $ (The program has terminated)

**Comment by nsbgn** [comment]
While neither of these things should probably outright *crash* `keyd` (so it's an issue that should be addressed!), I'd like to point out that they probably aren't the recommended way to solve your use case.

For the first, you probably mean `leftshift=oneshot(shift)`; `oneshot` already handles the case where `leftshift` overlaps with another key, so `overload` is unnecessary.

For the second, you probably want to set a global `oneshot_timeout` instead (unless you want to limit the timeout to only that key, I suppose).

**Comment by rvaiya** [comment]
I believe this should be fixed on master, though as noted `overload(shift, oneshot(shift))` is redundant.
