### ISSUE TITLE
Help: how to turn Alt+c/v into copy paste keys

### ISSUE THREAD

**Issue by fritzrehde** [rvaiya/keyd#482]
Hi, I'm on Linux and am missing the `Cmd+c/v` key combinations from MacOS. I wanted to kind of replicate them on Linux, and this tool looks very cool and promising. However, I am not sure how to achieve this. I naively tried
```
# copy
A-c = C-c
# paste
A-v = C-v
```
to remap `Alt-c` to `Control-c`, but that didn't work. Any help would be appreciated. Thanks for creating this awesome tool!

**Comment by slakkenhuis** [comment]
```
[alt]
c = C-c
v = C-v
```

The manual (`man keyd`) documents this and many other useful features :)

**Comment by vg250156** [comment]
The way to do this in keyd is to have an `alt` section like:
```
[alt]
c = C-c
v = C-v
```

But this is the wrong way to go about it. What you should be doing instead is changing the bindings at the WM level. Find where they're at in Gnome or Ubuntu or whatever you're using.

**Comment by fritzrehde** [comment]
Hmm, thanks for the help. I have tried your suggestions, but it still doesn't seem to work. Maybe I haven't reloaded keyd properly. I just restarted the systemd service, does that perform a reload?

**Comment by fritzrehde** [comment]
Regarding @vg250156 and your comment on changing the bindings at WM level: I'm using `river` (wayland) on Arch Linux. Do you mean I should try to perform a WM-level mapping like `Alt+c -> copy` or, just like with `keyd`, `Alt+c -> Ctrl+c`? I don't think I can really do the former (maybe that's only possible on Gnome or similar).

**Comment by tkna91** [comment]
Personally, I think it is simpler and easier to manage keyd only, without using WM functions for key remapping, because it can be used with getty, KMSCON, etc. and does not need to be reconfigured when switching WMs.

**Comment by vg250156** [comment]
My bad I think. C-c and C-v shortcuts in Linux are mostly implemented by applications now that I think about it.
