### ISSUE TITLE
[Question] left alt, left cmd swap

### ISSUE THREAD

**Issue by DJManas** [rvaiya/keyd#484]
Hello,

I am clueless. I had tried keyd and it seems to be working, but I am unable to remap leftcontrol and leftmeta keys on apple_laptop model keyboard. After a while I had found, that the config file should be like this:

```
[main]
leftctrl = layer(meta)
leftmeta = layer(control)
```
But it only remaps left ctrl to left meta, but won't remap left control to left meta. What am I doing wrong?

Gentoo, 6.1.22, Xorg 21.1.9, Enlightenment  0.25.4. Macbook Air 2015.

I had found out keyd, because xmodmap is not even possible to do simple change of e.g. x to z keys and I am trying to find out reason.

Thanks,
Regards,
Petr Sourek

**Comment by slakkenhuis** [comment]
`journalctl -u keyd` will probably show you an error for `leftctrl`. Try `leftcontrol = layer(meta)`. If that's not it, confirm with `keyd monitor` (or `keyd -m` depending on the version) that the names of the keys are as expected.

**Comment by DJManas** [comment]
I am stupid... :-( changed leftctrl for leftcontrol and it works. Sorry, my fault. Thank you.
