### ISSUE TITLE
Uppercased letters in macros [on Ubuntu 22.04 - Wayland (title edited)]

### ISSUE THREAD

**Issue by pteroctopus** [rvaiya/keyd#485]
Hi,

I'm trying to make a macro that will print exact text "Sometext" with S uppercased, but I'm failing to do it.

If I define macro like this:

`p = macro(S-p)` then when p is pressed capital P will be printed.

but if I define macro like this:

`p = macro(S-s ometext)` then I will get "sometext". 

These also don't work:
`p = macro(leftshift-s ometext)` 
`p = macro(shift-s ometext)` 
`p = macro(S+s ometext)` 
etc.

How to define a macro that will play a random text and preserve uppercased letters.

Thanks,
BR

**Comment by slakkenhuis** [comment]
What's the version you're on? I'm on keyd v2.4.2 (04c9e15) and both of the following work for me:

```
p = macro(Sometext)
p = macro(S-s ometext)
```

**Comment by pteroctopus** [comment]
Hi,

I tested on latest release tag: 
commit aa4c5cf1d48d995b13e59c274547ae5603f0e0e9 (HEAD, tag: v2.4.2)

And on latest commit on master branch:
commit b822f066f6be8b631e9cbeaecf403e3c448508a3 (HEAD -> master, origin/master, origin/HEAD)

In both cases when with configuration bellow I press simultaneously '5' and 'o' or '5' and 'i'  I get sometext insted of Sometext.
(5 is only placeholder for capslock later which I can't map right now because I have remapped it via keyboard firmware)

This is my test config:

```
[ids]

# This is a list of all keyboards for which
# mappings bellow will work.
# Asterisk means all connected keyboards

*

[main]

# With this we turn key one to function button
# All mappings in [function] block will work only
# If key one is pressed
# (5 is only a placeholder, it will be switched with capslock)
5 = layer(function)
control = layer(control)

[function]

# Example of key replacement to simulate vim navigation
j = down
k = up
h = left
l = right

# Example of macro with Shift (This works it prints capital P)
p = macro(S-p)

# Example of random text emit (This doesn't work it prints sometext)
o = macro(S-s ometext)
i = macro(Sometext)

# Example of macro with Control
l = macro(C-l)

[control]

2 = clear()
3 = toggle(normalmode)

[normalmode]

j = down
k = up
h = left
l = right
```

**Comment by pteroctopus** [comment]
Discovered right now that Sometext with capital S is printed ok in Firefox address line but with lowercase s in Gnome terminal and  gedit.

I'm using Ubuntu 22.04.

**Comment by pteroctopus** [comment]
Ok, I switched from Wayland to Xorg right now and everything works as expected. It seams the problems shows up i Wayland is used.

**Comment by rvaiya** [comment]
@pteroctopus Have you tried setting `macro_sequence_timeout`? This is probably a race condition higher up the input stack.

**Comment by pteroctopus** [comment]
I tried to set it from 20ms to 1000ms in intervals (20,50,100,200,500,100) but the result was the same as before on Wayland. Here is the config.

```
[ids]

# This is a list of all keyboards for which mappings bellow will work. Asterisk
# means all connected keyboards

*

[global]

macro_sequence_timeout = 1000

[aliases]

# These are aliases. Left is the real key name. Right is the alias. Alias can
# later be used in configuration.

leftshift = shift
rightshift = shift
leftcontrol = control
rightcontrol = control

# Main layout of the keyboard (insert mode).
[main]

# If capslock is presed down mappings from [function] block will be applied.
# If capslock is just tapped once then the switch to [normalmode] block mappins
# will be applied.  If capslock is tapped again then switch to [main] mappings
# will be done.  This simulates vim normal and insert modes
capslock = overload(function, esc)

# Mappings for when capslock key is pressed
[function]

# Vim navigation keys
h = left l = right k = up j = down
# Go to end of line.
4 = end
# Go to beggining of line
0 = home
# Go to beggining of file
f = C-home
# Go to end of file
g = C-end
# Go to next word
w = macro(C-right C-right C-left)
# Go to beggining of current word
b = C-left
# Go to end of current word
e = C-right
# Add new line bellow current one and enter insert mode ([main] block)
o = macro(end enter)
# Paste
enter = S-insert
# Select line
v = macro(home leftshift+end)
# Page down
d = pagedown
# Page up
u = pageup
# Delete
backspace = delete
# Text
q = macro(Sometext)
```

**Comment by rvaiya** [comment]
> macro_sequence_timeout = 1000000

This sets the timeout to 1s between each keystroke, which you should definitely observe if you are executing a macro using the latest version. Are you saying `capslock+q` instantaneously produces `Sometext`?

**Comment by pteroctopus** [comment]
Hi, I wrongly thought that interval was in ms at first. I edited the post yesterday, please look at he last version. Timeout works ok. But capital s is not printed on wayland.

**Comment by rvaiya** [comment]
I was unable to reproduce this on sway using the following config:

```
[global]

macro_sequence_timeout = 500000

[main]

capslock = layer(capslock)

[capslock]

1 = macro(Sometext)
```

Please try the above. You should see `Sometext` printed slowly when you press `capslock+1`. Please also post the output of `keyd monitor -t` while activating the macro.

**Comment by rvaiya** [comment]
I wasn't able to reproduce it, but I believe the latest patch should fix the issue. Can you try building from  d2ef4ab9?

**Comment by pteroctopus** [comment]
Hi, I pulled the latest commit, built it and now everything works on Wayland!
Macros emits capital S in Sometext.
macro_sequence_timeout works as expected and it worked before also, I just wrongly configured it (ms instead of microseconds).

Thank you very much @rvaiya . I'm already using keyd and it works great.
