### ISSUE TITLE
how to map alt jkhl keys to alt arrow keys

### ISSUE THREAD

**Issue by sathishmanohar** [rvaiya/keyd#487]
I want to map jkhl keys to the corresponding arrow keys only while pressing alt like below, to make my life easier in emacs.

alt+j to alt+down
alt+k to alt+up
alt+h to alt+left
alt+l to alt+right

I tried this one. Doesn't work as expected.

```
# Remap alt j k h l to alt down up left right
A-h = A-left
A-j = A-down
A-k = A-up
A-l = A-right
```

How to make this work? I went through the man page couldn't find such an example.

**Comment by nsbgn** [comment]
```
[ids]
*

[alt]
h = A-left
j = A-down
k = A-up
l = A-right
```

**Comment by sathishmanohar** [comment]
Perfect! Thanks.

**Comment by sathishmanohar** [comment]
Now there is another problem. This keymap seems to affect all `alt+j,k,l,h` even when other modifiers are used. When I press `Ctrl+alt+j` this rebind is used instead of my regular `Ctrl+alt+j` inside my programs (vim, emacs)

**Comment by nsbgn** [comment]
That is by design. If you want to reinstate the original mapping when combined with other modifiers, you can use composite layers:

```
[alt]
j = A-down
#...
[control+alt]
j = C-A-j
#...
```

**Comment by sathishmanohar** [comment]
Thanks. The following snippet made it work for me.

```
[alt]
h = A-left
j = A-down
k = A-up
l = A-right

[control+alt]
h = C-A-h
j = C-A-j
k = C-A-k
l = C-A-l

[shift+alt]
h = S-A-h
j = S-A-j
k = S-A-k
l = S-A-l
```

Although these lines are explicit. I feel making the alt block to scope to only alt key and not other modifier key would make the configuration file simpler. I don't know about the broader design choices. I am giving my feedback for consideration. something like `[only:alt]` may be.

**Comment by nsbgn** [comment]
Not stacking modifier layers might be easier for your particular use case, but in general, it's not what you want. It's even an [explicit goal](https://github.com/rvaiya/keyd/blob/41bcceef3c4c1876b5df0a5ba48812fa7c61d908/docs/keyd.scdoc#L165) of keyd to stack modifiers transparently.

I can't think of a way to selectively disable that behaviour in a way that's cleaner than simply reinstating the mappings via composite layers, because as far as I can tell, it would change the logic deeply.

Glad it worked!

**Comment by rvaiya** [comment]
> I feel making the alt block to scope to only alt key and not other modifier key would make the configuration file simpler. 

The problem then becomes:

```
[alt]

h = left
j = down
l = right
k = up
```

doesn't cause `control+alt+h` to produce `C-left`, which is potentially also
unintuitive. Addtionally, it shifts the burden of remapping all possible
modifier combinations on to the user.

The way to think about this is that when you do `control+alt+j`, you are
applying a modifier (`control`) to a layer binding (`j` in `alt`).  The
assumption is that if the user is remapping something fundamental like `alt+j`,
they presumably have another way to produce the sequence `A-j`, which can also
be used to produce `C-A-j`, `C-S-j`, etc.

For example:

```
leftalt = layer(customalt)
rightalt = layer(alt)

[customalt:A]

h = left
l = right
k = up
j = down
```

Would allow you to access `A-j` with `rightalt+j`, while also allowing you to produce
`C-A-left` by pressing `leftalt+leftcontrol+j`.

**Comment by sathishmanohar** [comment]
Remapping alt was a bad idea. It broke many of my key combinations. I've been looking for other ways to get to use the arrow keys without moving away from the home row. This is what I ended up with now.

```
# When tab is held hjkl keys becomes arrow keys
tab = overload(arrow_layer, tab)

[arrow_layer]
chord_hold_timeout = 500
h = left
j = down
k = up
l = right
```

**Comment by sathishmanohar** [comment]
The above [solution](https://github.com/rvaiya/keyd/issues/487#issuecomment-1594145854) considerably slowed down the tab key. So had to sacrifice my Esc for this toggle to work. So now use capslock for Esc and use the Esc key to toggle the arrow layer. This approach has been working fine without any problems for a while now.

```conf
esc = toggle(vim_mode)

[vim_mode]
h = left
j = down
k = up
l = right
```
