### ISSUE TITLE
Keychron issue esc = overload

### ISSUE THREAD

**Issue by rickalex21** [rvaiya/keyd#489]
Hello, thanks for this awesome program.

I have a keychron keyboard and the downside to that is that it shares esc, tilde, and
backtick all in one key. I have to use FN1+Esc to use the tilde and backtick.

I was looking at the examples and would like to have:

escape  to tilde/backtick and when I hold it to act as escape. However,
this does not work: **esc = overload(esc,`)**

Here is my config:

```sh
[ids]

*

[main]

capslock    = layer(meta)
leftmeta    = capslock
leftalt     = layer(control)

esc = overload(esc,`)

leftcontrol = layer(alt)
```

Thanks

**Comment by nsbgn** [comment]
Use `journalctl -u keyd` to see the error log.

In this case, the first error is that `esc` is not a layer, it's a key. If you want to differentiate keys based on hold time, try `esc = timeout(grave, 800, esc)`.
