### ISSUE TITLE
Line comments in kbd config files

### ISSUE THREAD

**Issue by canadaduane** [rvaiya/keyd#49]
Add ability to comment a line, maybe ';' or '//' ?

- It would be nice during testing to be able to comment out a line
- Actual comments above a line or section would be helpful for future readers

**Comment by rvaiya** [comment]
You can prepend a line with # to comment it out.

**Comment by canadaduane** [comment]
Oh, very cool! Thank you.

Maybe that should be added to the man page.

**Comment by rvaiya** [comment]
Done.
