### ISSUE TITLE
Mapping caps lock to ctrl causes weird ctrl+shift functionality

### ISSUE THREAD

**Issue by AshKmo** [rvaiya/keyd#490]
I currently have the following config, which aims to remap the caps lock key to ctrl, amongst other things:
```
[ids]

*

[main]

leftcontrol = layer(alt)

capslock = layer(control)

leftalt = esc

esc = capslock
```
Ctrl and shift both register in `keyd -m` perfectly fine, although if I hold ctrl+shift and press another key (such as  "i", to do ctrl+shift+i), said key is not registered until I release either ctrl or shift. I also have to hold "i" down until I release ctrl or shift for it to register the "i", which it thinks I started holding just before I released ctrl or shift. As such, my `keyd -m` looks like this:

```
keyd virtual device     0fac:0ade       leftcontrol down
keyd virtual device     0fac:0ade       leftshift down
keyd virtual device     0fac:0ade       i down (this fires right after I physically release either ctrl or shift)
keyd virtual device     0fac:0ade       leftcontrol up
keyd virtual device     0fac:0ade       leftshift up
keyd virtual device     0fac:0ade       i up
```

**Comment by nsbgn** [comment]
Does this also happen when activating capslock, shift and i without keyd running? If it does, it unfortunately sounds like rollover --- a hardware issue.

**Comment by AshKmo** [comment]
Caps lock, shift, "i" and capslock+shift+i all register fine no matter if keyd is stopped or running

**Comment by AshKmo** [comment]
Glitch seems to have fixed itself for now, but it may have fixed itself before and then became broken again

**Comment by AshKmo** [comment]
Andddd it's doing it again

**Comment by rvaiya** [comment]
This sounds like a hardware rollover issue. Can you post the output of `keyd monitor` while pressing the same physical keys (annotating the output as before)? What keyboard are you using? A lot of cheap boards won't allow you to simultaneously press other keys while capslock is depressed.

**Comment by AshKmo** [comment]
Turns out my Thinkpad's keyboard does the combos fine but my external keyboard doesn't. You're right; hardware issue.
