### ISSUE TITLE
Unexpected behavior from shiftable characters ( * ^ % ⋯) in macro

### ISSUE THREAD

**Issue by Acumane** [rvaiya/keyd#492]
In some applications (e.g. LibreWolf), the output of `x = *` vs `x = macro(*)` is different. The former results in `*` whereas the latter is `8`

`macro(S-8)` and `macro(shift+8)` also don't produce expected results (`*`). The above is reproable for all characters above a number on the QWERTY keyboard

**Comment by rvaiya** [comment]
Check the output of `keyd monitor`. The keys are probably being emitted, but libreoffice can't process them fast enough. Have you tried setting `macro_sequence_timeout`?

**Comment by Acumane** [comment]
Output from `keyd -m` for both is identical:
```
keyd virtual device	0fac:0ade	leftshift down
keyd virtual device	0fac:0ade	8 down
keyd virtual device	0fac:0ade	8 up
keyd virtual device	0fac:0ade	leftshift up
```

I should try `macro_sequence_timeout` but I'm running a Copr build of the latest release. Is the main branch stable enough to drive daily?

**Comment by Acumane** [comment]
Built `c9e4da2` and all is well! No `macro_sequence_timeout` necessary

**Comment by rvaiya** [comment]
@Acumane Keep in mind the value is in microseconds. Try bumping it up to a second (`macro_sequence_timeout=1000000`), which should produce a visible delay between the keys, then adjust it downwards. If it still doesn't work, please post the output of `keyd monitor -t`.
