### ISSUE TITLE
Use caps as ctrl and esc. Only send ctrl when combo pressed

### ISSUE THREAD

**Issue by bamert** [rvaiya/keyd#493]
Thank you for working on keyd! Great piece of software that I wish I'd found sooner.
I have been using caps as a combination of ctrl (when tapped) and escape for a couple of years with differing tools and have found an edge case that I can't replicate with `keyd` yet. 
My current configuration is:
```
[ids]
*

[main]
capslock = overload(symbols, esc)
```

When I tap caps (intending to send only an escape), `keyd monitor` shows me the following sequence:
```
keyd virtual keyboard   0fac:0ade       leftcontrol down
keyd virtual keyboard   0fac:0ade       leftcontrol up
keyd virtual keyboard   0fac:0ade       esc down
keyd virtual keyboard   0fac:0ade       esc up
```
I'd like the leftcontrol down/up sequence to only fire if another key is pressed while caps is down. 
I've had a look at the manpage; `overloadt` and `overloadt2` don't seem to be doing this. 
Is there another way / might I be experiencing a bug?

I'd be happy to work on a PR if this is something that would be interesting for other users as well.

**Comment by rvaiya** [comment]
> I'd like the leftcontrol down/up sequence to only fire if another key is pressed while caps is down.

This generally shouldn't be an issue unless your software does something with the lone control key. Is this causing you a problem in practice?

By design, modifier layers (`symbols:C`) will behave like normal modifier keys so users can still do things like control click.

The alternative is to define a normal layer and then define a control binding for each key:

```
[symbols]
a = [
b = C-b
c  = C-c
# etc...
```
which will avoid the eager activation.

**Comment by psychosis448** [comment]
Scenario, where the sending of  both keys causes an issue:
When Ctrl+Space is the modifier key for tmux, and it opens  up tmux-fzf, the sending of the esc key, closes the fzf menu.

**Comment by psychosis448** [comment]
Another example is fzf -- by default `ctrl + t` opens up the search menu, but the additionally sent `esc` key closes it.
