### ISSUE TITLE
Set repeat rate and delay on all keys

### ISSUE THREAD

**Issue by dk949** [rvaiya/keyd#494]
I was wondering if there is a way to increase the rate at which all key presses are repeated, I have found the ` macro_timeout` and `macro_repeat_timeout` global settings in the man page, but if I understand correctly, they only apply to macros, not all key presses.

I am currently using `xset r rate [DELAY] [REPEAT]` to set this, but would be great if there was a way to set it with `keyd` and keep the whole config in one place.

Thank you!

**Comment by rvaiya** [comment]
Unfortunately not. The display server ignores repeat events sent by hardware, so the correct approach is to use `xset r`.

**Comment by dk949** [comment]
Makes sense. Thanks for the reply.
