### ISSUE TITLE
Unsupported keys 277 (BTN_FORWARD) and 278 (BTN_BACK)

### ISSUE THREAD

**Issue by giddie** [rvaiya/keyd#495]
This appears to be a similar issue to this: https://github.com/rvaiya/keyd/issues/428

My Elecom DEFT PRO TrackBall (056e:0133) has a couple of buttons that keyd is not able to bind. `evtest` reports them like this:

```
Event: time 1684313820.868023, -------------- SYN_REPORT ------------
Event: time 1684313821.491629, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90007
Event: time 1684313821.491629, type 1 (EV_KEY), code 278 (BTN_BACK), value 1
Event: time 1684313821.491629, -------------- SYN_REPORT ------------
056e:0133Event: time 1684313821.604855, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90007
Event: time 1684313821.604855, type 1 (EV_KEY), code 278 (BTN_BACK), value 0
Event: time 1684313821.604855, -------------- SYN_REPORT ------------
```

Is this something that is fixable in keyd, or should I start looking into `hwdb` to figure out how to remap the relevant keys?

**Comment by rvaiya** [comment]
I believe this should work in the latest commit.

**Comment by giddie** [comment]
Yeah, perfect. Thanks :)
