### ISSUE TITLE
Warn on invalid options, or at least add -h / --help options

### ISSUE THREAD

**Issue by canadaduane** [rvaiya/keyd#50]
Today I was trying to remember how to enter monitor mode, and kept trying options that didn't work but were silently ignored. What further fooled me is that monitor mode and non-daemon "main loop" mode are similar in that they mention the name of the keyboard and wait.

It would be handy to have a `--help` option for a quick reminder of the options.

And/or warn on invalid options.

**Comment by rvaiya** [comment]
Done.
