### ISSUE TITLE
kind of having trouble defining capslock as an overload as (ctrl+meta) layer and esc

### ISSUE THREAD

**Issue by yilkalargaw** [rvaiya/keyd#500]
I tried the following config to switch make capslock behave as ctrl+alt but it reverts to its default behavior. I know it might be my fault and I might have misunderstood the syntax.
```
[ids]

*

[main]

# Maps capslock to escape when pressed and control when held.
capslock = overload(layer(control+alt), esc)

# Remaps the escape key to capslock
esc = capslock

leftalt = layer(control)
leftcontrol = layer(alt)
rightalt = layer(control)

```
ps. Sorry if this is not be the right place to ask question and I appreciate any help.

**Comment by nsbgn** [comment]
No worries!

The first argument of `overload()` is already a layer; you don't need to add a nested `layer()`.  Also, you can't activate a composite layer like `control+alt` directly with a single action (see also https://github.com/rvaiya/keyd/issues/334); you will need to define a special layer for it. The following should work:

```
[ids]

*

[main]

# Maps capslock to escape when pressed and control when held.
capslock = overload(controlalt, esc)

# Remaps the escape key to capslock
esc = capslock

leftalt = layer(control)
leftcontrol = layer(alt)
rightalt = layer(control)

[controlalt:C-A]
```

**Comment by yilkalargaw** [comment]
Thank you very much @nsbgn that worked.
