### ISSUE TITLE
failed to open /dev/input/event*

### ISSUE THREAD

**Issue by ayidsudirman** [rvaiya/keyd#502]
Thank you very much for working on keyd. it works and very usefull for colmak user like me especially for navigation.
When i start keyd in monitor mode, the output:
```
failed to open /dev/input/event17
failed to open /dev/input/event15
failed to open /dev/input/event16
failed to open /dev/input/event13
failed to open /dev/input/event14
failed to open /dev/input/event12
failed to open /dev/input/event11
failed to open /dev/input/event10
failed to open /dev/input/event9
failed to open /dev/input/event8
failed to open /dev/input/event7
failed to open /dev/input/event6
failed to open /dev/input/event5
failed to open /dev/input/event4
failed to open /dev/input/event3
failed to open /dev/input/event2
failed to open /dev/input/event1
failed to open /dev/input/event0
```
How to re-enable keyd in monitor mode? and also command `sudo keyd reload` no longer available.
i run keyd on void linux cinnamon (linux6.1-6.1.29_1) and i already added my self to keyd group.

**Comment by rvaiya** [comment]
> When i start keyd in monitor mode, the output:

Suggests you don't have access to the input nodes. What is the output of `ls -l /dev/input/` and `groups`?

> and also command sudo keyd reload no longer available.

This should work. What version are you running? (`keyd -v`).

**Comment by ayidsudirman** [comment]
the output of `ls -l /dev/input/` : 
```
total 0
drwxr-xr-x 2 root root     120 May 30 21:36 by-id
drwxr-xr-x 2 root root     140 May 30 21:36 by-path
crw-rw---- 1 root input 13, 64 May 30 21:36 event0
crw-rw---- 1 root input 13, 65 May 30 21:36 event1
crw-rw---- 1 root input 13, 74 May 30 21:36 event10
crw-rw---- 1 root input 13, 75 May 30 21:36 event11
crw-rw---- 1 root input 13, 76 May 30 21:36 event12
crw-rw---- 1 root input 13, 77 May 30 21:36 event13
crw-rw---- 1 root input 13, 78 May 30 21:36 event14
crw-rw---- 1 root input 13, 79 May 30 21:36 event15
crw-rw---- 1 root input 13, 80 May 30 21:36 event16
crw-rw---- 1 root input 13, 81 May 30 21:36 event17
crw-rw---- 1 root input 13, 66 May 30 21:36 event2
crw-rw---- 1 root input 13, 67 May 30 21:36 event3
crw-rw---- 1 root input 13, 68 May 30 21:36 event4
crw-rw---- 1 root input 13, 69 May 30 21:36 event5
crw-rw---- 1 root input 13, 70 May 30 21:36 event6
crw-rw---- 1 root input 13, 71 May 30 21:36 event7
crw-rw---- 1 root input 13, 72 May 30 21:36 event8
crw-rw---- 1 root input 13, 73 May 30 21:36 event9
crw-rw-r-- 1 root input 13,  0 May 30 21:36 js0
crw-rw---- 1 root input 13, 63 May 30 21:36 mice
crw-rw---- 1 root input 13, 32 May 30 21:36 mouse0
crw-rw---- 1 root input 13, 33 May 30 21:36 mouse1
```

`groups` output: 

`ayid wheel floppy audio video cdrom optical kvm plugdev xbuilder libvirt keyd`

My bad. I just realized that reload command is mentioned in changelog. i thought i run the latest version. it's still v2.4.2 in void's repo.

**Comment by rvaiya** [comment]
You will need to add yourself to the `input` group if you want to monitor key events, or else run it as root (`sudo keyd monitor`).

**Comment by ayidsudirman** [comment]
It works properly run as root. i'll try to update to the latest version.

**Comment by diplodocuslongus** [comment]
> You will need to add yourself to the `input` group if you want to monitor key events, or else run it as root (`sudo keyd monitor`).

Using `keyd v2.5.0 (393d341)`, only `sudo keyd monitor` works.
I've added myself to the `input` group but still get the `failed to open /dev/input/event*` as the OP. 

```
groups mel
mel : mel adm dialout cdrom sudo dip plugdev input lpadmin sambashare flirimaging keyd
```

(Ubuntu 22.04)
