### ISSUE TITLE
Macro prints wrong character

### ISSUE THREAD

**Issue by fkaksa** [rvaiya/keyd#503]
Hi,

In keyd config file I have a macro which contains **&** sign, e.g. **test&**. After executing marco I'm getting **test/**.

Changing macro to **test^** or **test S-6** solves the problem.

I'm using Ubuntu 22.04.2 LTS, Gnome version 42.5, Wayland

My default keyboard layout is Croatia which is setup in  Settings->Keyboards->Input Sources.

**/etc/default/keyboard** file contains **XKBLAYOUT="hr"**

**Comment by rvaiya** [comment]
keyd operates at the level of the keycode, so `&` is just syntactic sugar for `S-7`l which corresponds to `&` on a US qwerty layout. My advice would be to set your display server keymap to qwerty and do all of your remapping in keyd. keyd ships with some common layout files by default, so you should be able to add `include layouts/hr` to the top of your configuration file after linking the compose file mentioned in the man page.

**Comment by fkaksa** [comment]
Thanks for the clarification. I implemented my keyd config as you mentioned above and now it is working how it should be.
