### ISSUE TITLE
Scripted Bash Command to Start / Stop `keyd-application-mapper` Keybindings

### ISSUE THREAD

**Issue by cheyngoodman** [rvaiya/keyd#504]
I use Input Leap to share keyboard and mouse between two systems. On my server system I have `keyd-application-mapper` to configure 1 key bindings when no window is open (`app.conf`):

```ini
[root]
# Change i32m workspaces with only  number keys
1 = M-1
2 = M-2
3 = M-3
# ...
```

I don't want these key bindings to apply when I'm on the client system. I can execute a wrapper script to manage keyd that is executed when moving between server and client system (`keyd-input-leap-mapper`):

```sh
#!/bin/sh
case "$1" in
  client)
    killall keyd-application-mapper
    keyd -e reset
    ;;
  server)
    keyd-application-mapper -d
    ;;
esac
```

This method almost works, but when I connect back to the server and execute `keyd-application-mapper -d` it doesn't report the first active window and my per application keybindings don't apply until I focus a different window.

Is there a more elegant way to "pause" `keyd-application-mapper` mappings with a command and then start the mappings again from the current X11 window?

**Comment by cheyngoodman** [comment]
I think the fix is to stop the mapper, clear the bindings, then apply the mapper while off screen:

```sh
#!/bin/sh
if [ "$1" == "client" ] ; then
    killall keyd-application-mapper
    keyd -e reset
    keyd-application-mapper -d
fi
```

Since when `keyd-application-mapper` first starts it doesn't apply the per application configurations. When returning to the server X11 reports the first active window and the per application keybindings work as expected.

Is there a more elegant way to "pause" the bindings? This workaround currently works for me.

**Comment by rvaiya** [comment]
Not at the moment I'm afraid. I am working on some changes which will make this sort of scripting easier that should make it into the next major release.
