### ISSUE TITLE
default key binding

### ISSUE THREAD

**Issue by aklaing** [rvaiya/keyd#508]
Is there a way to specify a default binding for a layer?  I want all the keys to do a noop by default (I know there is a noop action but it would be nice if I don't have to list all the possible keys and bind each of them one by one to noop).  So I wish I could say that if a key is not bound explicitly, then it does nothing.  Is there a way to do that?

As to why I would want to do this -- it is a second keyboard, and it will  be used as a macro keyboard, so it would be nice if the unbound keys on that one to do nothing until they are explicitly bound.

If this does not already exist, the syntax for this new feature could look like this, maybe:

```
[newlayer]

a = a
b = b
* = noop
```

meaning that only a and b work on this keyboard.  Everything else is noop until more definitions are added manually.

Thanks for any advice!!

**Comment by rvaiya** [comment]
At the moment this is unsupported (support should be added to the next release), so you will have to explicitly assign each key to noop. If you do this often, you can create a file called 'noop' which contains all such bindings and then include it in the layer before defining subsequent bindings.

E.G

```
[layer]
include noop
a = b
# etc...
```

where 'noop' is a file containing this:

https://gist.github.com/rvaiya/81b1bac81ef1323e17ff16e5a432badd

**Comment by aklaing** [comment]
Thank you for the solution!  I like that it makes it easier to see the actual bindings that are currently in use, and because of the overriding, one does not need to edit the noop file each time you add a new binding to the main file.  Thanks again!!

**Comment by aklaing** [comment]
It seems that with the overriding rules, the syntax that would be more consistent with your solution would have the catch-all first, maybe?:

```
[newlayer]
* = noop
a = b
# etc ...
```

**Comment by rvaiya** [comment]
Depending on the semantics of `*`, those could be roughly equivalent, though I'm not sure what form the syntax will take yet. The next major release of keyd (3.0) will likely introduce some breaking changes, so I might just end up making it a new kind of layer (e.g `[layer:opaque]`).

**Comment by aklaing** [comment]
I was trying it out and this happened:

```
myhost:keyd$ sudo /usr/bin/keyd
[sudo] password for laing: 
CONFIG: parsing /etc/keyd/default.conf
CONFIG: parsing /etc/keyd/keyboard2macros.conf
keyd: src/ini.c:138: ini_parse_string: Assertion `section->nr_entries < MAX_SECTION_ENTRIES' failed.
Aborted
```

This caused the "sudo keyd reload" to hang, ...
Just thought I'd mention it, but please don't waste any more time on it right now.  I can wait for the next release.  Thank you.

**Comment by rvaiya** [comment]
Ah, I forgot about the binding limit :P. The next release might take a while. I just pushed a commit which increases the limit, so the above should work if you compile from source.

**Comment by aklaing** [comment]
Yes, it works with the limit increase.   Thank you so much!!
