### ISSUE TITLE
Why `Failed to grab /dev/input/event4` but `keyd-application-mapper` is working?

### ISSUE THREAD

**Issue by kohane27** [rvaiya/keyd#509]
Hello @rvaiya. Hope you're doing well. Thank you for creating `keyd`. `keyd` is the only key remapper that can run on top of [kanata](https://github.com/jtroo/kanata).

Why `keyd` `Failed to grab /dev/input/event4` but `keyd-application-mapper` is working?

## Description

I use `kanata` to implement home-row mod for my laptop keyboard `/dev/input/event4`. [kanata](https://github.com/jtroo/kanata) is similar to [kmonad](https://github.com/kmonad/kmonad). I use `keyd` solely for its application-specific remaps. `/home/username/.config/keyd/app.conf`:

```
[firefox]
control.semicolon = C-comma
control.w = C-backspace
control.p = up
control.n = down
```

`/etc/keyd/default.conf`:

```
[ids]

*

```

## Steps to reproduce

1. Run `kanata` as a `systemd` service
2. Run `keyd` as a `systemd` service and make sure `keyd.service` is started after `kanata.service` (by the following):

`sudo systemctl edit keyd.service`:

```
[Service]
ExecStartPre=/bin/sleep 20
```

3. `keyd` is indeed `Failed to grab /dev/input/event4` with `sudo systemctl status keyd.service`:

```bash
● keyd.service - key remapping daemon
     Loaded: loaded (/usr/lib/systemd/system/keyd.service; enabled; preset: disabled)
    Drop-In: /etc/systemd/system/keyd.service.d
             └─override.conf
     Active: active (running) since Mon 2023-06-05 11:38:29 HKT; 3h 52min ago
   Main PID: 66384 (keyd)
      Tasks: 1 (limit: 37076)
     Memory: 1.1M
        CPU: 2.786s
     CGroup: /system.slice/keyd.service
             └─66384 /usr/bin/keyd

Jun 05 11:38:29 username keyd[66384]: CONFIG: parsing /etc/keyd/default.conf
Jun 05 11:38:29 username keyd[66384]: Starting keyd v2.4.3 (5e4ef41)
Jun 05 11:38:29 username keyd[66384]: DEVICE: ignoring 0fac:1ade  (keyd virtual pointer)
Jun 05 11:38:29 username keyd[66384]: DEVICE: match    2333:6666  /etc/keyd/default.conf        (ydotoold virtual device)
Jun 05 11:38:29 username keyd[66384]: DEVICE: match    0001:0001  /etc/keyd/default.conf        (kanata)
Jun 05 11:38:29 username keyd[66384]: DEVICE: ignoring 0002:000a  (TPPS/2 Elan TrackPoint)
Jun 05 11:38:29 username keyd[66384]: DEVICE: ignoring 0002:0007  (SynPS/2 Synaptics TouchPad)
Jun 05 11:38:29 username keyd[66384]: EVIOCGRAB: Device or resource busy
Jun 05 11:38:29 username keyd[66384]: DEVICE: WARNING Failed to grab /dev/input/event4
```

4. Run `keyd-application-mapper` in the terminal

5. Go to Firefox and the remap works!

`kanata` is "using" `/dev/input/event4`, and thus `keyd` failed to grab `/dev/input/event4`. But very strangely (and happily) `keyd-application-mapper` still works!

This isn't exactly an issue but I'm writing to try to understand the following:

1. Why `keyd-application-mapper` works when `keyd` `Failed to grab /dev/input/event4`
2. Performance implication running two keymappers on the same input device (I have not noticed any input lag fortunately)
3. Potential problems running two keymappers on the same input device

I am very interested to see your input on this peculiar use case of mine. Thank you!

**Comment by rvaiya** [comment]
kanata and keyd are mutually incompatible. keyd is flexible enough to accommodate home row mods (and has a better chording implementation than QMK). Is there a reason you are using two programs?

**Comment by kohane27** [comment]
Thank you for getting back to me. I appreciate it.

It's just that I used `kanata` and `xremap` before finding out `keyd`. I'll give `keyd` a try as it seems it can achieve what both of them can do without using two keymappers. Thank you again!
