### ISSUE TITLE
Modifier Not Working Under Layer

### ISSUE THREAD

**Issue by cheyngoodman** [rvaiya/keyd#511]
Using this example configuration, I'm hoping to layer the meta key to default to Ctrl bindings but "pass through" Meta+Alt+d binding:

```ini
[ids]
*

[main]
leftmeta = layer(meta_mac)

[meta_mac:C]
# Open launcher
space = M-space
# Toggle Dock / Status Bar
alt.d = M-A-d
```

With this example, `meta.space` gets "passed though" the layer properly as `M-space` and triggers the window manger.

When I use `meta.alt.d`, the combination is passed as `C-A-d` but I hope for it to "pass through" similar `meta.space`. Is this a bug or a misconfiguration?

**Comment by rvaiya** [comment]
> I'm hoping to layer the meta key to default to Ctrl bindings but "pass through" Meta+Alt+d binding

If I understand you correctly, you want:

```
[main]
meta = layer(meta_mac)

[mac_meta:C]
space = M-space

[mac_meta+alt]
d = M-A-d
```

`alt.d` is not a valid left hand value (you are conflating it with the IPC binding/keyd-application-mapper syntax). Please see the composite layer section of the man page for more details.

**Comment by cheyngoodman** [comment]
Thank you, that's the syntax I was looking for.
