### ISSUE TITLE
keyd generates extraneous control down/up for keys in layer with `:M` modifier

### ISSUE THREAD

**Issue by carljohnson93** [rvaiya/keyd#516]
First of all, thank you for your amazing work, keyd is life changing program that makes me more productive and happy every day of my life.
So I have a home_arrows layer which is activated by leftmeta key, obviously I still want super key so this layer has `:M` modifier.
However when using my shell I noticed that when I (accidentally) press both keys from this layer (when one key wasn't released yet and other is pressed), some weird escape sequences are inserted in the shell's input prompt. I ran `keyd monitor` and saw that when I hold leftmeta and press e.g. j (left) key, the following is logged:
```
keyd virtual keyboard	0fac:0ade	leftcontrol down
keyd virtual keyboard	0fac:0ade	leftmeta up
keyd virtual keyboard	0fac:0ade	leftcontrol up
keyd virtual keyboard	0fac:0ade	left down
keyd virtual keyboard	0fac:0ade	left up
keyd virtual keyboard	0fac:0ade	leftmeta down
keyd virtual keyboard	0fac:0ade	leftcontrol down
```
As you can see there's control events (I did not press anything but the leftmeta and j).
Here's minimal reproducible config:
```
[ids]
*

[main]
leftmeta = layer(home_arrows)

[home_arrows:M]
# arrow keys on the home row
j = left
k = down
l = up
; = right
```
When I removed `:M` from the layer header control events disappeared, but this is not an option for me since I still need super key (and my right super key is mapped to different layer).

**Comment by humanplayer2** [comment]
I experience something similar in v2.4.3, but where `meta` is also returned when unwanted when using `overload`.

MWE: 

```
[ids]
*
[main]
a = overload(meta,space)
```
Tapping `a` prints

```
keyd virtual keyboard	0fac:0ade	leftmeta down
keyd virtual keyboard	0fac:0ade	leftcontrol down
keyd virtual keyboard	0fac:0ade	leftmeta up
keyd virtual keyboard	0fac:0ade	leftcontrol up
keyd virtual keyboard	0fac:0ade	space down
keyd virtual keyboard	0fac:0ade	space up
```

**Comment by humanplayer2** [comment]
Hm, I think we might be seeing the "modifier guard". From the man page, GLOBALS section:

```
*disable_modifier_guard*: By default, keyd will inject additional control keypresses where necessary in order to prevent programs from seeing additional modi‐
           fier taps (E.g alt in firefox). If set, this option disables that behaviour. (default: 0)
```

**Comment by carljohnson93** [comment]
Yes I've found this recently too so it seems this is intentional. Well it haven't bothered me much anyways, so closing
