### ISSUE TITLE
overload bug?

### ISSUE THREAD

**Issue by nazya** [rvaiya/keyd#519]
Hi!
Fist of all, many thanks for the idea and work!!!

For example, rightshift = overload(shift, .) works as expected.
But rightshift = overload(shift, ,) leads to the following error: overload requires 2 arguments.

The obvious solution leftshift = overload(shift, macro(,)) leads to a buggy behavoiur. After releasing leftshift, the input of ',' infinitely repeats (sometimes may not, then one can restart the service).

overload(leftshift, macro2(300, 0, macro(,))) inputs ',' two times. But it should be only one AFAIU.
overload(leftshift, macro2(999999999, 0, macro(,))) works as expected, but I think it does because I have never reached 999999999ms, or just missed the input event.

Minimal config to reproduce
[main]
leftshift = overload(shift, macro(,))

**Comment by whoizit** [comment]
this works for me
```
leftshift = overload(shift, .)
rightshift = overload(shift, macro2(0, 0, macro(,)))
```
and this
```
leftshift = overload(shift, macro2(0, 0, macro(\()))
rightshift = overload(shift, macro2(0, 0, macro(\))))
```

**Comment by nazya** [comment]
Thanks! But after several days of testing of rightshift = overload(shift, macro2(0, 0, macro(,))) I noticed buggy behavoiur again. I can prepare minimal config and steps to reproduce, but it also inputs ',' two times.

**Comment by matcls** [comment]
If I understand the issue correctly this should work
rightshift = overload(shift, comma)

**Comment by nazya** [comment]
Thanks @matcls! Works perfectly!
