### ISSUE TITLE
is it supported to set key code of round bracket ?

### ISSUE THREAD

**Issue by meyergin** [rvaiya/keyd#530]
seems config syntax doesn't support raw key code of ( 
```
leftshift = overload(shift, ()
```
right now, I used shift combo key
```
leftshift = overload(shift, S-9)
```

**Comment by luetage** [comment]
That’s because keyd deals with keys and not symbols. There is unicode support, but you have to set it up as explained in the documentation. Your second approach is the way to go about it in my opinion.
