### ISSUE TITLE
keyd prevents setting leds

### ISSUE THREAD

**Issue by luetage** [rvaiya/keyd#531]
I’m using a noppoo choc mid board on Fedora. Unfortunately I’m neither able to set leds (capslock, scrolllock) with the `setleds` command, nor with help of OpenRGB. The keyboard is unsupported. The only way I found is to manually edit the brightness files in `/sys/class/leds` with root, but this only works with keyd disabled. I’m assuming keyd takes control of these files and resets their status when the service is running. This cannot be influenced with the layer_indicator setting. Would it be possible to introduce an option in keyd to leave setting leds to the user? It would be possible to introduce logic to set the leds to my liking then.

**Comment by rvaiya** [comment]
I believe this should be fixed in the latest commit.

**Comment by luetage** [comment]
Thank you for the fix. I was able to setup a script to toggle the scrolllock light on layer toggle.
