### ISSUE TITLE
Pressing two overloaded keys quickly drops first key

### ISSUE THREAD

**Issue by nwotero** [rvaiya/keyd#535]
I have a config with **a** overloaded as **meta** and **s** overloaded as **alt**, and if I press **s** **a** quickly, only the **a** prints. They are not being pressed at the same time. The monitor mentions the leftcontrol button being pressed, but it is not pressed, nor are any keys mapped to it pressed.

Monitor output:

> keyd virtual keyboard	0fac:0ade	leftalt down
> keyd virtual keyboard	0fac:0ade	leftmeta down
> keyd virtual keyboard	0fac:0ade	leftalt up
> keyd virtual keyboard	0fac:0ade	leftcontrol down
> keyd virtual keyboard	0fac:0ade	leftmeta up
> keyd virtual keyboard	0fac:0ade	leftcontrol up
> keyd virtual keyboard	0fac:0ade	a down
> keyd virtual keyboard	0fac:0ade	a up

Config:

```
[ids]

*

[main]

# Maps capslock to escape when pressed and control when held.
capslock = overload(control, esc)

# Remaps the escape key to capslock
esc = capslock

a = overload(meta, a)
; = overload(meta, ;)

s = overload(alt, s)
l = overload(alt, l)

d = overload(control, d)
k = overload(control, k)

f = overload(shift, f)
j = overload(shift, j)
```

**Comment by luetage** [comment]
Read the docs for `overloadt` concerning homerow modifiers, `overload` is not a good fit.
E.g. `a = overloadt(meta, a, 200)`

The control key action you noticed while monitoring is normal behavior. It’s the modifier guard and you can disable it globally, but in my experience it doesn’t hurt leaving it on.

**Comment by nwotero** [comment]
Thank you for the advice, it seems to be working. Do you think this would be a good candidate for the FAQ in the README? I'll contribute the PR if you think its a good idea.

**Comment by luetage** [comment]
I’m neither a maintainer nor a contributor. But I think it’s fine in the docs, you gotta read them anyway. There’s no way around it, if you want to do any advanced modification that goes beyond setting capslock to ctrl/esc.
