### ISSUE TITLE
KEY_VOICECOMMAND missing

### ISSUE THREAD

**Issue by samozrejmost** [rvaiya/keyd#538]
This is a minor problem I guess but it would be nice if KEY_VOICECOMMAND was included in the _keyd_. Now with the _--monitor_ option _keyd_ gives "unsupported evdev code" (keyd v2.4.3).

The rationale is that the Voicecommand button is included in some remote control style keyboards (for controlling HTPCs, PCs) and some people might not have any use for remote voice control. On the other hand, there are very few buttons on such controls, so remapping this would greatly expand their capabilities. (Example: (https://www.umax.cz/galerie/9_47415/name-original.jpg) id 1915:1025, the button is the blue microphone in the middle)

I was able to remap the voicecommand key by choosing a random key in the code (BTN_FORWARD - KEYD_MOUSE_FORWARD) and swapping it with (KEY_VOICECOMMAND - KEYD_VOICECOMMAND) and it works perfectly. But of course a "native" solution would be much better.

Thanks!

**Comment by rvaiya** [comment]
Support for this should be added to the latest commit. Confirmation would be appreciated.

**Comment by samozrejmost** [comment]
It works a treat! Thanks a lot!
