### ISSUE TITLE
Some Control + Meta key combinations are ignored

### ISSUE THREAD

**Issue by plurry** [rvaiya/keyd#539]
I just started using `keyd` and I've run into a problem.

I've overloaded <kbd>Tab</kbd> and <kbd>Caps Lock</kbd> to be <kbd>Meta</kbd> and <kbd>Control</kbd> like so:
```
# /etc/keyd/default.conf

[ids]
*

[main]
esc = capslock
tab = overload(meta, tab)
capslock = overload(control, esc)
```

Now, <kbd>Caps Lock</kbd> + <kbd>Tab</kbd> + <kbd>L</kbd> does not work. Other letters work fine, but <kbd>L</kbd> and the number keys do not. Plain <kbd>Tab</kbd> + <kbd>L</kbd> and <kbd>Caps Lock</kbd> + <kbd>L</kbd> work.

In both X11 and a virtual terminal, when I run `sudo keyd monitor` and type <kbd>Caps Lock</kbd> + <kbd>Tab</kbd> + <kbd>J</kbd> / <kbd>K</kbd> / <kbd>L</kbd>, this is what I get:
```device added: 0fac:1ade keyd virtual pointer (/dev/input/event13)
device added: 0fac:0ade keyd virtual keyboard (/dev/input/event12)
device added: 04f3:30c6 ELAN1301:00 04F3:30C6 Touchpad (/dev/input/event7)
device added: 04f3:30c6 ELAN1301:00 04F3:30C6 Mouse (/dev/input/event6)
device added: 0001:0001 AT Translated Set 2 keyboard (/dev/input/event4)
keyd virtual keyboard   0fac:0ade   enter up
keyd virtual keyboard   0fac:0ade   leftcontrol down
keyd virtual keyboard   0fac:0ade   leftmeta down
keyd virtual keyboard   0fac:0ade   j down
keyd virtual keyboard   0fac:0ade   j up
keyd virtual keyboard   0fac:0ade   k down
keyd virtual keyboard   0fac:0ade   k up
keyd virtual keyboard   0fac:0ade   leftmeta up
keyd virtual keyboard   0fac:0ade   leftcontrol up
keyd virtual keyboard   0fac:0ade   leftcontrol down
keyd virtual keyboard   0fac:0ade   c down
```

Using the real <kbd>Control</kbd> and <kbd>Meta</kbd> keys still works.

**Comment by nsbgn** [comment]
Does this also happen without keyd running? It's likely due to [rollover](https://en.wikipedia.org/wiki/Key_rollover), a fairly common keyboard quirk (cf #490, #381, #357, #156, #142)

**Comment by plurry** [comment]
I stopped the `keyd` service and `keyd monitor` still didn't pick up <kbd>Caps Lock</kbd> + <kbd>Tab</kbd> + <kbd>L</kbd> so I guess it is a hardware problem.

Thanks for the quick response.
