### ISSUE TITLE
Example 4 not working (Meta to alt-tab)

### ISSUE THREAD

**Issue by joihn** [rvaiya/keyd#541]
I'm trying to use example 4 of man page (`man keyd`)
```
Example 4
   Meta behaves as normal except when ` is pressed, after which the alt_tab layer is activated for the duration of the left‐
   meta keypress. Subsequent actuations of will thus produce A-tab instead of M-\.
```
```
[meta]

` = swap(alt_tab, A-tab)

[alt_tab:A]

tab = A-S-tab
` = A-tab
```

I've tried to paste it in my `default.conf`  (and reloading ) **without success**

i've also tried the following variants with no success
```
[ids]
*

[meta]

` = swap(alt_tab, A-tab)

[alt_tab:A]

tab = A-S-tab
` = A-tab
```

```
[ids]
*
[main]
[meta]

` = swap(alt_tab, A-tab)

[alt_tab:A]

tab = A-S-tab
` = A-tab
```

**Comment by joihn** [comment]
actually is does work ,  I had a confusion, 

for other user : meta key = alt key

**Comment by nsbgn** [comment]
Example 4 is confusing. The `alt_tab` layer activates the `alt` modifier, not the `meta` modifier; `swap` takes two arguments but it can't; and I don't know where `M-\\` comes from since it was previously talking about `M-\``. I think the example is best just removed. Are you only pointing out that the example is wrong, or were you actually trying to achieve something similar?

> Moreover, am I correct saying that on a modern keyboard and linux, Meta key = super key = windows keys ?

I think the terminology isn't consistent everywhere, but yes, that's how `keyd` uses it.

**Comment by joihn** [comment]
thanks for your answer, 

I am indeed **trying to achieve a similar purpose,** and kind of struggling:

on gnome (and a lot of OS), you can switch apps with:
a) next : `alt`+`tab`
b) previous : `alt` + `shift` + `tab`  
c) moreover, after triggering one of the above, keeping `alt` pressed keeps the menu displayed. (cf screenshot):
![image](https://github.com/rvaiya/keyd/assets/11663917/9a7c9459-b866-4067-ac30-6f74b75c36c1)

======   

Am I trying **to achieve the same with the following key:**
A) next : `super`+`k`
B) previous : `super`+`j`
C) moreover, after having one of the above, keeping `super` pressed should keep the menu displayed.
D) when we are not in the above scenario, `super` should behave as a normal super key


here is my attempt (requirement _A) B) C)_ are fullfilled, but not _D_)
```
meta = overload(alt_tab, A-tab)
[alt_tab:A]
j = A-S-tab
k = A-tab
```

**Comment by nsbgn** [comment]
Got it. To also fulfill *D)*, I think you just need to swap `A` with `M`:

```
[ids]
*
[main]
meta = overload(alt_tab, A-tab)
[alt_tab:M]
j = A-S-tab
k = A-tab
```

**Comment by luetage** [comment]
> thanks for your answer,
> 
> I am indeed **trying to achieve a similar purpose,** and kind of struggling:
> 
> on gnome (and a lot of OS), you can switch apps with: a) next : `alt`+`tab` b) previous : `alt` + `shift` + `tab` c) moreover, after triggering one of the above, keeping `alt` pressed keeps the menu displayed. (cf screenshot): ![image](https://user-images.githubusercontent.com/11663917/254538148-9a7c9459-b866-4067-ac30-6f74b75c36c1.png)
> 
> ======
> 
> Am I trying **to achieve the same with the following key:** A) next : `super`+`k` B) previous : `super`+`j` C) moreover, after triggering one of the above, keeping `super` pressed should keep the menu displayed. D) when we are not in the above scenario, `super` should behave as a normal super key
> 
> here is my attempt (requirement _A) B) C)_ are fullfilled, but not _D_)
> 
> ```
> meta = overload(alt_tab, A-tab)
> [alt_tab:A]
> j = A-S-tab
> k = A-tab
> ```

You can change the shortcuts in Gnome itself. Install dconf editor, in `org/gnome/desktop/wm/keybindings` you will find the shortcut for switching applications and the shortcut for switching applications backward. The latter’s unavailability in regular keyboard shortcut settings is probably the reason why you are trying to do it with keyd.

**Comment by joihn** [comment]
it works, thanks @luetage  !
