### ISSUE TITLE
keyd reload not working

### ISSUE THREAD

**Issue by ahloiscreamo** [rvaiya/keyd#542]
hello.
I am trying to replace my enter key to capslock as my enter key is broken.

i have create the config as the guide in /etc/keyd/default.conf

when i issued  `sudo keyd reload` it just give me `bind: No such file or directory` output.

keyd installed through aur repo.

config -

```
[ids]

*

[main]

# Maps capslock to enter when pressed and control when held.
capslock = overload(control, enter)

# Remaps the enter key to capslock
enter = capslock



```

**Comment by rvaiya** [comment]
Is the daemon running (`systemctl status keyd`)?

**Comment by ahloiscreamo** [comment]
Thanks for reaching back,
I don't use systemd, so i don't have systemctl (artix linux)

**Comment by rvaiya** [comment]
In either case, you will need to ensure the daemon is running as a system service (probably by populating `/etc/init.d` with a script if you installed from source). You can check if the daemon is running with `pgrep -l keyd`.

**Comment by ahloiscreamo** [comment]
Thanks for the guide, i solved my issues by adding new *hwdb config file in `etc/udev/hwdb.d/ `
This issues is unrelated to keyd, to make keyd work i need to make a runit startup file for keyd as i use runit as service manager. Void linux has keyd runit on their repo, but artix have none.
I guess this is the cursed for using 'simple init' service manager. 
I will close this issues.
