### ISSUE TITLE
How to override space only if space and the letter press overlaps for n+ milliseconds

### ISSUE THREAD

**Issue by pksadiq** [rvaiya/keyd#546]
I recently switched to keyd for remapping my keys. I use space as control for letters and as shift for symbols.

The problem I have is that when I type fast some keys are registered as control actions. Say, if I type `hello world` the ` w` may result in Control+w. So to overcome this I would like to activate control or shift only if the spacebar and the other key press overlaps for at least `n` milliseconds, or otherwise space and the other key is inserted independently.

Or alternately, the spacebar/f overrides to control/shift only if I hold it for more than `m` milli/micro seconds.

Is it possible to do so?

Here is my configuration:

```octave
[main]

# Let f act as shift when combined with other keys
f = overload(shift, f)

capslock = overload(control, esc)
alt = overload(alt, esc)
space = overload(customspace, space)

# Let space result in shift for symbols and control otherwise
[customspace:C]
, = <
. = >
/ = ?
; = :
' = "
[ = {
] = }
\ = |
` = ~
1 = !
2 = @
3 = #
4 = $
5 = %
6 = ^
7 = &
8 = *
9 = (
0 = )
- = _
= = +
```

**Comment by nsbgn** [comment]
You can! See the `overloadt` and `overloadt2` actions. The behaviour you describe would look like `overloadt(customspace, space, 100)`. Be wary, though: you'll need to experiment with the timeout, and not everyone's typing habits are regular enough to make it work. Mine aren't. Also, the visual latency it introduces can be grating.

**Comment by pksadiq** [comment]
Thanks, `overloadt` was what I need.  I guess overlapped keypress timeout is not something that can be done.

I wish the `examples` had a lot of examples explaining various possibilities.

And thanks for writing and maintaining `keyd`.
