### ISSUE TITLE
Can keyd be used when connecting to remote server by using ssh?

### ISSUE THREAD

**Issue by FunnyDragonK** [rvaiya/keyd#551]
I ssh to a remote server of the unbuntu 22.04 system. After successfully installing the keyd and following the quick start config. The keymap does not work.

**Comment by yashlala** [comment]
I'm a bit confused -- did you install `keyd` on your own laptop, or on the server you're SSHing into?

**Comment by rvaiya** [comment]
Your local machine interprets keystrokes and inputs them into the terminal. ssh is a program which creates a pseudo-terminal that allows you to interact with a remote machine. The keystrokes are still interpreted by your local input stack. Consequently, installing keyd on the machine you are remotely logged into will have no effect.
