### ISSUE TITLE
keyd interferes with xkb option "grp_led:scroll"

### ISSUE THREAD

**Issue by gobenji** [rvaiya/keyd#554]
When keyd is running and matched on my keyboard, the xkb option "grp_led:scroll" (see xkeyboard-config(7)) does not work well. When I switch to another layout using the keyboard, the layout changes but the led does not change accordingly.

I've reproduced the problem in a qemu vm from a clean install:
* Install Ubuntu 23.04
* apt install kde-plasma-desktop, logout from Gnome and login to KDE
* From KDE System Settings, Input Devices, Keyboard
	* on the Layouts tab, add English (US) and French (Canada)
	* on the Advanced tab
		* enable "Switching to another layout"/"Win+Space"
		* enable "Use keyboard LED to show alternative layout"/"Scroll Lock"
* Open a terminal and run the following command to monitor the scroll lock led:
	`watch -n0.3 -d 'grep -H . /sys/class/leds/input1::scrolllock/brightness; xset -q | grep Lock'`
* Open another terminal, switch keyboard layouts a few times by pressing Win+Space
* In each layout,
	* type the '/' key to confirm that the layout is changed (result is '/' or 'é')
	* look in the terminal running `watch`, confirm that the scroll lock led is on according to sysfs and xset when the second layout ("ca") is active
* apt install git build-essential
* Clone, compile and install keyd (reproduced with commit eeea96a)
* Create /etc/keyd/default with the following contents:
```
[ids]
*
[main]
```
* Start keyd (`systemctl start keyd.service`)
* Change the keyboard layout again by pressing Win+Space. Look at the terminal running `watch`, the output of xset is as expected but the scroll lock led file in sysfs is **not** updated accordingly. This is the problem. On a real machine, it manifests itself as the physical keyboard led not being on.

### Extra observations
When changing the keyboard layout using the task bar layout indicator, the problem does not occur.

When running keyd with no configuration file, the problem does not occur. When running keyd with the minimual configuration file specified above, the problem does occur. So it seems the problem only occurs when keyd matches on the keyboard.

Instead of KDE, I have also reproduced the problem using openbox, i3 and twm.
In those cases, I set the keyboard configuration using
```
setxkbmap -layout us,ca -option -option grp:win_space_toggle -option grp_led:scroll
```

The problem does not reproduce with gnome-x11. According to [this ticket](https://gitlab.gnome.org/GNOME/mutter/-/issues/1665), "mutter implements some custom mechanism for switching keyboard layouts". Maybe it's related to that. The problem also does not reproduce under gnome-wayland and plasma-wayland.

I have also tried using [evremap](https://github.com/wez/evremap) instead of keyd and the same problem occurs. I guess both utilities work in a similar way.

The issue I'm reporting is probably the same problem that was reported in the following comment:
https://github.com/rvaiya/keyd/issues/305#issuecomment-1480210485

Can you narrow down if this is a problem with how evdev is used in keyd, or a problem in evdev itself or Xorg?

**Comment by gobenji** [comment]
I have created a small screen recording to show the issue:

https://github.com/rvaiya/keyd/assets/254681/9edfb3ce-33ad-44ac-a342-4a5f985c5af1

00:38 Scroll lock led changes according to keyboard layout
01:00 Starting keyd
01:26 Scroll lock led no longer changes when changing the layout using win+space keyboard shortcut
01:44 Scroll lock led changes when using taskbar layout indicator
02:05 Stopping keyd
02:14 Scroll lock led changes according to keyboard layout again

**Comment by korikori** [comment]
Experiencing the same issue when changing keyboard layouts with setxkbmap and the grp_led:scroll option. (openbox)

**Comment by rvaiya** [comment]
Thanks for the detailed reproduction steps. I don't have the time to set up  a virtual machine at the moment, but running `setxkbmap -layout us,ca -option -option grp:win_space_toggle -option grp_led:scroll` on my local box seems to produce the desired result. What version of keyd are you using (`keyd -v`)? Does this problem persist when building the latest one from source?

**Comment by rvaiya** [comment]
Nevermind, I was indeed able to reproduce it. My suspicion is that the compositor/X server sets the LED status using evdev and can't wrest control from the keyd virtual device. Assuming this is indeed the case, I'm not sure it will be possible to fix, as uinput doesn't provide a way to capture the EV_LED event (as far as I can tell).

**Comment by rvaiya** [comment]
I did a bit of kernel diving and it appears it is indeed possible to capture EV_LED events from userspace. This should work in the latest commit. Can you give it a go?

**Comment by gobenji** [comment]
I just tested at commit 23f329a in my normal environment (openbox) and the keyboard led changes according to the layout, as expected. Thank you for resolving this issue.

**Comment by bileslav** [comment]
Unfortunately, I'm facing this issue on FreeBSD 14.1 with all latest versions; using Xfce.

**/usr/local/etc/keyd/menu.conf**
```
[ids]
*

[main]
meta = overload(meta, A-f1)
```

**/usr/local/etc/X11/xorg.conf.d/xkb.conf**
```
Section "InputClass"
	Identifier "MyXkbRules"
	MatchIsKeyboard "true"
	MatchDriver "libinput"
	Option "XkbModel" "pc104"
	Option "XkbLayout" "us,ru"
	Option "XkbOptions" "shift:both_capslock_cancel,grp:caps_toggle,grp_led:scroll"
EndSection
```

Meaning of my xkb setup:
1. CapsLock: toggle us/ru layout, use Scroll LED as indicator;
2. LShift + RShift: switch Caps mode on, use Caps LED as indicator;
2.1. Any Shift: switch Caps mode off.

When keyd is running, the effect on that is the following:
1. CapsLock still toggles layout, but the indicator (Scroll LED) not working;
2. Caps mode and LED aren't working entirely.

Everything starts working again as soon as keyd is stopped. keyd itself working great.

_Off-topic: NumLock and its LED are always works._

**Comment by bileslav** [comment]
I'm not sure whether I should create a new issue on this matter, and whether @rvaiya will be notified now, so I'm tagging them. Thank you.
