### ISSUE TITLE
+shift as +meta in pop

### ISSUE THREAD

**Issue by HeyJwd** [rvaiya/keyd#556]
I'm having a bit of trouble replicating the meta key in Pop_Os.  

I'd like to have `+leftshift` behave as `+meta` to take advantage of the system mapping that is already in place, rather than remapping all of the system configured keystrokes... i.e. `+meta+ h,j,k,l` = window navigation (rather than left, up, down, right keystrokes inside of the window...)

To add one more wrinkle, I'd like this to be system wide with the exception of Firefox, where I'm using a vim extension which I would like to maintain. Not sure if
 this is possible.

Any hints would be appreciated.

**Comment by rvaiya** [comment]
I believe this should be as simple as:

```
[main]

leftshift = layer(meta)
```

Please see the man page for more details.
