### ISSUE TITLE
Allow longer layer names

### ISSUE THREAD

**Issue by rxhfcy** [rvaiya/keyd#558]
@rvaiya This is the follow-up to #557 where you said:

> 32 characters seems reasonable, if you feel strongly about the length please open a dedicated issue.

I found #557 in the first place because I **genuinely**, *without irony*, tried to use a layer name that happened to be one character longer than what is currently allowed. Was the name ludicrously long and overly descriptive? Sure, but is that such a crime? Was it really worth it to silently reject the rule just because the name was silly?

Sure, you do get to read a warning if you happen to know the correct spell (`systemctl status keyd`), and most people will never use names that long, but is it absolutely necessary to have this potential footgun / papercut in the first place? In the name of great "customer service", if the max was 64 characters (or even 256), I'm pretty sure nobody would ever hit this issue again.

Thanks for considering this and thank you again for making keyd!

**Comment by rvaiya** [comment]
The latest commit increases the limit to 64 characters as requested.
