### ISSUE TITLE
Mention the fact that keyd works in Wayland explicitly on the GitHub "home page" 

### ISSUE THREAD

**Issue by rxhfcy** [rvaiya/keyd#559]
I found keyd because I needed to find something that works in Wayland. I'm pretty sure I'm not the only one, because Wayland is *The Future*:registered: etc. However, the project's GitHub home page (https://github.com/rvaiya/keyd) could have been more helpful: there's nothing about Wayland at all (for comparison: X11 is mentioned three (3) times).

I was able to read between the lines that yes, keyd does indeed work in Wayland, for the same exact reason it works in X11: it doesn't care about which one you're using, because it works on the kernel level.

However, from a potential new user's perspective I think it would have been very helpful if the page explicitly mentioned that keyd works in both Wayland *and* X11 (also add "wayland" in the topics list because "x11" is there too).

This would make it a little bit easier for new users to find this excellent project.

**Comment by fecet** [comment]
I'm wodering weather the app-level  remap also works in wayland? As it's should not happen at kernel level

**Comment by rvaiya** [comment]
> This would make it a little bit easier for new users to find this excellent project.

Thanks, I've made thsi more explicit in the readme.

> I'm wodering if the app-level  remap also works in wayland? As it's should not happen at kernel level

There is support for gnome and sway (mentioned in the README). 'wayland' isn't one thing, it is a protocol which is implemented by multiple compositors (with most useful extensions only being implemented in some of them). keyd will work everywhere (including a TTY) by dint of being a low level remapped, but app support needs to be explicitly added for each platform, which it has been in the case of `gnome` and `sway`.
