### ISSUE TITLE
Autodetection of Keyboard & Keys

### ISSUE THREAD

**Issue by canadaduane** [rvaiya/keyd#56]
My goal is to bundle keyd in a deb, and then depend on it as part of a higher level app that makes a Mac-like experience easier on X11 & Wayland. To achieve this, there are two autodetection features that I've been thinking about. This relates to part of the discussion in #55 as well.

1. **Get key left of spacebar**: To detect whether the user has a Mac keyboard or a Windows keyboard plugged in, it seems a "best practice" is to ask the user to press the key "to the left of the spacebar". 

2. **Figure out which keyboard is being used**: To detect which keyboard the user expects to have remapping applied, it would be user friendly to listen for all keyboards, and then check which one is the source of a key press event.

To accomplish both of the above, would it be possible to start `keyd` in monitor mode, but end after just one key press? I'm thinking I could tell the user "Please press the key to the left of spacebar" (like kinto does) and start `keyd` in monitor mode / autodetect mode. The `keyd` would respond with its usual line:

```keyd virtual keyboard: alt down```

it would then quit and the stdout could be parsed ("keyd virtual keyboard" and "alt down" would be enough to go on... although a device ID would be better).

**Comment by rvaiya** [comment]
> Figure out which keyboard is being used: To detect which keyboard the user expects to have remapping applied

I'm not sure what you mean by this. Keyd already distinguishes between keyboards by default. If you have a configuration in `Magic Keyboard.conf` and another in `Kinesis Advantage.conf` keyd will apply the correct rules to each keyboard (even if they are both plugged in).

> To accomplish both of the above, would it be possible to start keyd in monitor mode, but end after just one key press?

You could just spawn keyd and terminate it after reading one line of STDIN. You can also just do this in whatever language you are using. Python has a `keyboard` package which uses evdev and seems to be fairly easy to use.

> ("keyd virtual keyboard" and "alt down" would be enough to go on... although a device ID would be better).

The correct way to do this is to terminate keyd first so you can see the actual device events. You are doing this preconfiguration anyway.

**Comment by canadaduane** [comment]
I guess what I'm trying to do is sketch the outline of a "user-friendly" process that involves no scripting knowledge or touching of "cfg" files. There are several pieces involved:

1. We don't know how many actual keyboards the user has plugged in.
2. We don't know which keyboard or keyboards to apply the remapping rules to.
3. Some devices are detected as keyboards but aren't what a user would think of as a keyboard (e.g. mouse, camera).
4. Of the keyboards that the user thinks of as keyboards, we want to know what the physical keyboard layout is, so that we can apply the correct remapping rules to give a Mac OS-like muscle memory experience.

(please forgive the use of "we" here--I know you aren't trying to solve all the problems, but I do appreciate the collaboration :)

None of the above actually requires any change to keyd. But it would be nice if there were an additional command-line option to limit the number of keystrokes "monitor mode" accepts before exiting. A shell script, for example, would be easier to write if it went something like:

```
echo "Please press the key to the left of your keyboard:"
DETECT=$(sudo keyd -m --max-events=1)
echo "Looks like you're using $DETECT"
```

We could also get the same thing if `keyd` respected SIGPIPE, I think:

```
sudo keyd -m | head -n 1
```

**Comment by canadaduane** [comment]
Hmm, I'm still unable to suppress the actual key itself. For example if "a" is pressed, I get an "a" (that I think is coming from keyd?) and an "a" that is coming from the regular shell's echo:

```
$ DETECT=$(sudo keyd -m 2>&1 1>/dev/null | head -n 1)
aduane@pop-os-fw1:~/Relm/relm$ a
^                              ^
```

**Comment by rvaiya** [comment]
> We don't know how many actual keyboards the user has plugged in.

I don't see why this would be relevant if you want to configure the keyboard in front of the user.

> We don't know which keyboard or keyboards to apply the remapping rules to.

If you use the `keyd -m` output while keyd is not running it should print the name of the keyboard which generated the event. I will probably add the vendor and product ids too shortly.

> Some devices are detected as keyboards but aren't what a user would think of as a keyboard (e.g. mouse, camera).

This should be regarded as a bug. `keyd` intentionally ignores anything which can generate mouse events. If it is incorrectly identifying something as a keyboard please file a separate issue.

> Of the keyboards that the user thinks of as keyboards, we want to know what the physical keyboard layout is, so that we can apply the correct remapping rules to give a Mac OS-like muscle memory experience.


> (please forgive the use of "we" here--I know you aren't trying to solve all the problems, but I do appreciate the collaboration :)

No need to apologize :). I just assumed it was the royal we.

> A shell script, for example, would be easier to write if it went something like:

The problem is that keyd is writing to stderr, not that it doesn't respect SIGPIPE. `keyd -m 2>&1|head -n1` should do the trick, as you've identified in your last post, though you will probably want a timeout to avoid registering the enter key up event.

`-m` is really intended for debugging and probably shouldn't be relied on in a script. It's output is subject to change (though this is unlikely).

>  I'm still unable to suppress the actual key itself.

There is no way to achieve this with `-m`, it just passively logs all key events. This generally shouldn't be a problem for alt in a terminal.

**Comment by rvaiya** [comment]
Actually, there is an additional complication. `keyd` won't try to write to the closed pipe until it receives an event, so if the user depresses the key before the timeout and releases it then it won't terminate until the next key down event.

**Comment by rvaiya** [comment]
`keyd -m|head -n1` should work now.
