### ISSUE TITLE
Hash as a key name

### ISSUE THREAD

**Issue by szopeno** [rvaiya/keyd#563]
This is my keyd config (for a faulty keyboard)

[ids]
0001:0001

[main]
capslock = layer(dia)
3=noop

[dia]
e = #

Why caps+e does not produce hash? How to make it? Docs have it that hash is comment only at the beginning of the line and do not seem to have  a way to quote a character.

**Comment by nsbgn** [comment]
Does caps+e produce anything (in `keyd monitor` or similar) when you don't have keyd running?

**Comment by szopeno** [comment]
God dammit, thank you. It was my fault - I should check it more diligently before posting an issue. There was accidental conflict with another binding. 

Sorry for making all the trouble.
