### ISSUE TITLE
keyd breaks "Disable while typing" touchpad option in libinput

### ISSUE THREAD

**Issue by coordinatio** [rvaiya/keyd#565]
Hi! First, thanks for the wonderful program, it is really a life changer for me.

Keyd somehow breaks "Disable while typing" option for a touchpad. Touchpad is always active despite if you type or not. I use KDE on Wayland, so touchpad is handled by libinput.

If I stop keyd "Disable while typing" starts working immediately.

I suspect that the virtual pointer device that keyd creates may be related to the problem.
Can you suggest a way to prevent keyd from creating that device?
Can you suggest other ways to diagnose or fix the problem?

**Comment by nsbgn** [comment]
I remember this issue coming up before --- see #66 and #375. Does [this quirks file](https://github.com/rvaiya/keyd/issues/66#issuecomment-985983524) help?

**Comment by coordinatio** [comment]
The quirks file helps! Thanks a lot!

It seems to me that that information deserves to be placed into the main help file. From general considerations, that should be a frequent case.
