### ISSUE TITLE
issue: Overload with short combined key press does not register them together

### ISSUE THREAD

**Issue by joihn** [rvaiya/keyd#567]
Overload with short combined key press does not register them
**reproduction**

1) set this config
```
[ids]
*

[main]
tab = overload(tab_layer, tab)
[tab_layer]
u = 7
```
2) very shortly, press `alt+Tab` and quickly release

**expected**
the OS shoud receive `alt+Tab`
**observed**
the OS shoud receives first `alt`, then tab `Tab`

**Comment by joihn** [comment]
it seems to be due to the fact that without 
keyd
tab key is sent when *pressing*, 
however with 
`tab = overload(tab_layer, tab)`
key is sent when releasing

**Comment by joihn** [comment]
solved :)
```
[ids]
*

[main]
tab = overload(tab_layer, tab)
[tab_layer]
u = 7
[alt]
tab = A-tab
```

**Comment by rvaiya** [comment]
This is by design. It allows sequences like `alt+tab+u` to correctly produce `alt+7`. If you want alt+tab to disable the tab layer while alt is pressed, you can modify it inside the alt layer.

E.G

```
[alt]

tab = A-tab
```
