### ISSUE TITLE
Quick Thanks

### ISSUE THREAD

**Issue by Crsarmv7l** [rvaiya/keyd#568]
Wanted to leave a quick thanks. I have an oddball aliexpress laptop that has been a royal pain; from sound (essx8336 soundcard) , screen rotations (because portrait screen in landscape orientation); and mouse buttons. 

I finally got everything worked out with my left click working (provided I turned on mouse keys,) but no right click. After 2 hours struggling with keyboard remapping, all sorts of other programs and issues because I am using wayland, and complicated config files none of which worked, I found keyd.

Your program had a simple install, built in key detection and a super simple config, I was able to quickly get right click working, then go back, turn off mouse keys and map the left click to leftmouse, which also fixed click and hold.

I know I am not using this to its full potential, but thanks so much for this it has been incredibly useful for me!

**Comment by rvaiya** [comment]
I am glad you find value in it :).
