### ISSUE TITLE
Can I remap a key combination to mouse button press/release?

### ISSUE THREAD

**Issue by tehkonst** [rvaiya/keyd#57]
Can I make something like this:
press ctrl+super+m -> press mouse button 3  
release ctrl+super+m -> release mouse button 3

**Comment by rvaiya** [comment]
Not at the moment. Adding some rudimentary mouse support should be fairly trivial, though you may want to check out one of my other projects, [warpd](https://github.com/rvaiya/warpd), in the meantime.

**Comment by tehkonst** [comment]
Ok. Thanks.
