### ISSUE TITLE
keyd-application-mapper not working with wine

### ISSUE THREAD

**Issue by lucasmr** [rvaiya/keyd#575]
I would like to use keyd-application-mapper for a game using wine. Tried modifying the config file ~/.config/keyd/app.conf with the identifiers:
[wine] 
[wineserver]
[Game.exe]

But they are not working. I wonder if they have to be a process chilld under X?

**Comment by rahenry** [comment]
Try running `keyd-application-mapper --verbose`, it may give some more helpful identifiers

**Comment by lucasmr** [comment]
```
X detected
Active window: plasmashell|plasma
```

Nothing else with --verbose

**Comment by rahenry** [comment]
That's weird. It should output something when your focus changes. Perhaps plasma is hogging focus? It might be similar to #521

**Comment by lucasmr** [comment]
It might be a permission issue. I have the current user in the `keyd` group but there's output after some time: `bind: Connection refused` and I can't run keyd-application-mapper with sudo because it won't find the config file.

**Comment by lucasmr** [comment]
I don't know what else to change. I'm running:
- Gentoo Linux, kernel 6.1.46 and openrc
- KDE Plasma 5.108
- keyd v2.4.3

**Comment by rahenry** [comment]
You could try the hack I describe in #521

**Comment by lucasmr** [comment]
Thanks, that solved the issue.
