### ISSUE TITLE
remap right control to menu key.

### ISSUE THREAD

**Issue by jeremyjjbrown** [rvaiya/keyd#577]
I use the menu key so I'd like to map the right control key on my laptop to the menu key.

```
[ids]

*

[main]

rightcontrol = menu

capslock = overload(capslock, esc)

# The default shift layer (the layer activated when shift is pressed).
[shift]

capslock = layer(capslock_shift)

[capslock:C]

shift = layer(capslock_shift)
h = left
j = down
k = up
l = right

[capslock_shift]

h = C-left
j = C-down
k = C-up
l = C-right
```

Not sure why it doesn't work.

**Comment by nsbgn** [comment]
What do you mean by 'doesn't work'? What behaviour is exhibited and what had you expected? You can use `keyd monitor` to inspect what happens.

**Comment by jeremyjjbrown** [comment]
```
  sudo keyd monitor
device added: 2a94:a813 GTCH7503:00 2A94:A813 (/dev/input/event16)
device added: 04f3:31ec ELAN0763:00 04F3:31EC Touchpad (/dev/input/event19)
device added: 04f3:31ec ELAN0763:00 04F3:31EC Mouse (/dev/input/event15)
device added: 0fac:1ade keyd virtual pointer (/dev/input/event18)
device added: 0fac:0ade keyd virtual keyboard (/dev/input/event17)
device added: 0001:0001 AT Translated Set 2 keyboard (/dev/input/event3)
keyd virtual keyboard	0fac:0ade	enter up
keyd virtual keyboard	0fac:0ade	menu down
keyd virtual keyboard	0fac:0ade	menu up
keyd virtual keyboard	0fac:0ade	menu down
keyd virtual keyboard	0fac:0ade	menu up
keyd virtual keyboard	0fac:0ade	menu down
keyd virtual keyboard	0fac:0ade	menu up
keyd virtual keyboard	0fac:0ade	menu down
keyd virtual keyboard	0fac:0ade	menu up
keyd virtual keyboard	0fac:0ade	leftcontrol down
keyd virtual keyboard	0fac:0ade	c down
```
Nothing happens on the right ctrl click, if I use the menu key on a usb keyboard I get the menu in a text box for example. Here is a usb keyboard menu key.
```
  sudo keyd monitor
device added: 1d50:6124 Ultimate Gadget Laboratories UHK 60 v2 (/dev/input/event10)
device added: 1d50:6124 Ultimate Gadget Laboratories UHK 60 v2 (/dev/input/event8)
device added: 1d50:6124 Ultimate Gadget Laboratories UHK 60 v2 (/dev/input/event7)
device added: 1bcf:0005 USB Optical Mouse (/dev/input/event6)
device added: 047d:2041 Kensington Kensington Slimblade Trackball (/dev/input/event4)
device added: 2a94:a813 GTCH7503:00 2A94:A813 (/dev/input/event16)
device added: 04f3:31ec ELAN0763:00 04F3:31EC Touchpad (/dev/input/event19)
device added: 04f3:31ec ELAN0763:00 04F3:31EC Mouse (/dev/input/event15)
device added: 0fac:1ade keyd virtual pointer (/dev/input/event18)
device added: 0fac:0ade keyd virtual keyboard (/dev/input/event17)
device added: 0001:0001 AT Translated Set 2 keyboard (/dev/input/event3)
keyd virtual keyboard	0fac:0ade	enter up
keyd virtual keyboard	0fac:0ade	leftmeta down
keyd virtual keyboard	0fac:0ade	compose down
keyd virtual keyboard	0fac:0ade	compose up
keyd virtual keyboard	0fac:0ade	leftmeta up
keyd virtual keyboard	0fac:0ade	leftmeta down
keyd virtual keyboard	0fac:0ade	compose down
keyd virtual keyboard	0fac:0ade	compose up
keyd virtual keyboard	0fac:0ade	leftmeta up
keyd virtual keyboard	0fac:0ade	leftcontrol down
keyd virtual keyboard	0fac:0ade	c down
```

Thanks.

**Comment by nsbgn** [comment]
I'm assuming the first output is what you get (ie `menu`, which doesn't do what you expected but looks correct) and the second output is what you'd like to get (ie `compose`). On my keyboard, the key with a little menu icon also emits `compose` and brings up a context menu by default. Perhaps you can achieve what you want by setting `rightcontrol = compose` instead?

See also <https://github.com/rvaiya/keyd/issues/177#issuecomment-1092064707>.

**Comment by jeremyjjbrown** [comment]
Let me try it. Thanks. Compose is certainly unexpected.

**Comment by jeremyjjbrown** [comment]
Thanks, that worked although it surprised me.

**Comment by Grief** [comment]
How about adding `102nd = compose` as an example of overriding of this key
![image](https://github.com/rvaiya/keyd/assets/7239315/a9625305-b692-4640-b8b5-cb4b337b74a9)
to a context menu action which is usually located here?
![image](https://github.com/rvaiya/keyd/assets/7239315/2d46faa8-a844-4a8b-9d3d-ec43dc6fe2de)

**Comment by tukusejssirs** [comment]
FYI: I wanted to make `PrtSc` (`keyd monitor` calls it `sysrq`) to the menu key on the buil-in Lenovo ThinkPad P15 Gen 1 built-in keyboard (note that there is no menu key on the keyboard). I tried using both `sysrq = menu` (which didn’t work), but `sysrq = compose` works as expected in Firefox, JetBrains WebStorm, GNOME Prompt, Insomnia, EletronMail (ProntonMail web client), Discord, ClickUp (AppImage), Slack, Todoist. It does not work in Warp (terminal) which might be expected as it is a new type of terminal and it is still in development.
