### ISSUE TITLE
Appreciation for keyd

### ISSUE THREAD

**Issue by canadaduane** [rvaiya/keyd#58]
> Just installed keyd and used it to remap home to delete, because my keyboard manufacturer thinks that one is more important than the other. And it only took me 2 minutes. -- [ImJustPassinBy](https://www.reddit.com/r/linux/comments/qz5r2n/comment/hlmdnqs/?utm_source=share&utm_medium=web2x&context=3)

> I use keyd for everything and love it! -- [that1communist](https://www.reddit.com/r/linux/comments/qz5r2n/comment/hll2gfs/?utm_source=share&utm_medium=web2x&context=3)

> I have been having a play with keyd today and it's really neat... It's making the capslock key, which has been mapped to esc as a default for vim, into a much more versatile key triggering the different modes and using esc to return to the main mapping. Super simple configuration and potential to be open the keyboard up a bit without having to buy a Planck just yet. -- [textandmetal](https://www.reddit.com/r/linux/comments/qz5r2n/comment/hllv8ke/?utm_source=share&utm_medium=web2x&context=3)

**Comment by rvaiya** [comment]
Much obliged, though I'm not sure this is technically an issue ;).
