### ISSUE TITLE
Bind longpress `leftctrl` to `hyper`, one hit `leftctrl` to capslock not work.

### ISSUE THREAD

**Issue by eval-exec** [rvaiya/keyd#581]
I want:
1. bind `long press capslock` to `control`
2. bind `one hit capslock` to `esc`
3. bind `long press leftctrl` to `hyper` (C-M-S-A)
4. bind `one hit leftctrl` to trigger `capslock`

1 and 2 work well, but 3 and 4 not work.
When I long press `leftctrl`, it's still `leftctrl`, when I short hit `leftctrl` is's `leftctrl` also.

My configuration is:
```
[main]
capslock=overload(control, esc)
leftctrl=overload(hyper, capslock)

[hyper:C-M-S-A]
```

Do you think my configuration is wrong?

**Comment by nsbgn** [comment]
Iirc, `leftctrl` should be `leftcontrol` (cf. `keyd monitor`). Looks good otherwise.

**Comment by eval-exec** [comment]
> Iirc, `leftctrl` should be `leftcontrol` (cf. `keyd monitor`). Looks good otherwise.

Thank you, it works well after I changed to `leftcontrol` :smile:
