### ISSUE TITLE
Feature Query

### ISSUE THREAD

**Issue by aklaing** [rvaiya/keyd#582]
Hello,
my main config looks something like this:

`[main]
meta = layer(alt)
meta = oneshot(alt)

shift = layer(shift)
shift = oneshot(shift)
`

and it works fine.  Recently I have been having finger pain problems from holding down the modifier keys.  So I want to change my configuration so that every time I hold down a modifier key to press a key the computer will do something annoying (like make a beep) to remind me that I'm not supposed to do that.  But it will still do what I want.

Is it possible to let everything work like right now, but in addition have a beep when I hold down a key instead of tapping it?  ie. Tap-Shift k will give uppercase K
but Hold-Shift k will give an uppercase and make an annoying beep

If I can't do this, my second choice will be to completely disable the hold-down semantics and have those make a beep, while if I tap it will work.  Is that possible?  In this case Tap-Shift k will give uppercase K, but Hold-shift k will just make an annoying beep and not produce any letter.

How can I configure this?  Any pointers will be appreciated.
Thanks,

Ambrose

**Comment by nsbgn** [comment]
Assuming that you have the `beep` program (or something similar), you can try something like:

```
[main]
shift = overload(beepshift, oneshot(shift))

[beepshift:S]
a = command(beep; keyd do S-a)
b = command(beep; keyd do S-b)
# ... etcetera
```

However, I expect that you will run into problems with this solution. Over the course of normal touch typing, it's actually very common to have overlapping keys. That is, if you type `ab`, you'll often press `b` before letting go of `a`. The same will probably hold for `shift` taps.

Obviously depends on the typist, though --- maybe you won't have this problem. If you do but you don't want to give up, you could mitigate the issue by adding a timeout:

```
shift = overloadt(beepshift, oneshot(shift), 100)
```

**Comment by aklaing** [comment]
Thanks for your response!

Unfortunately it isn't quite working for me because first, the number of commands required is very high: each letter has to have its own command and for each modifier key there are maybe 100 letters, so total of 600 commands needed (just as an estimate), but one can only have 64 commands in the config file; above that I get an error message saying the command limit is exceeded.  I could try to fix this one by changing the constant and recompiling.

Secondly, for some reason, the sound-making programs (cw and aplay) both do not work when invoked by keyd.  Both work when manually invoked outside of keyd.  This 
is the problem I don't quite understand or know how to fix.

When I have tried this with a small set of keys mapped so that I don't exceed the command limit, I find that running "command(command1; command2)" works when the command1 and command2 are both "keyd do" commands, but if one of them is a sound making program, I just get silence.  So in principle the method works, it's just something about the sound programs that is weird.

I'm also wondering if maybe there is a different way to do this without assigning a separate command to each letter.  That would allow much shorter config files?

Thanks again

**Comment by nsbgn** [comment]
As for the silence: you might need to set some environment variables or use a different method. The problem is likely that `keyd` is neither attached to a tty, nor connected to your display server, and afaik it needs one of those to play a sound. I would suggest trying `echo -en "\a" > /dev/tty5` (cf https://unix.stackexchange.com/questions/1974/how-do-i-make-my-pc-speaker-beep )

As for the proliferation of commands: you could instead run a seperate script that uses `keyd listen` to find out if we enter the `beepshift` layer, then play the beep accordingly. Then you only need to define the `[beepshift:S]` layer, without giving any explicit bindings. (Let me know if you need help writing the script.)

**Comment by aklaing** [comment]
I've got a listener script working which gets the output from "keyd listen" one line at a time in a loop.

The config file is now just: 

`[main]
shift = overload(beepshift, oneshot(shift))

[beepshift:S]
`

As it turns out, the "beepshift" is printed out every time whether you Hold the shift key or tap it.  The plain "shift" is printed out only when you tap.  In order to detect times when the key was held but not tapped, one has to use something like a state machine, which resets its own state after a reasonable timeout.  That is, if you see a beepshift but don't see a shift within x milliseconds, then that is a "Hold", and then you should beep.

Another approach may be to use only the "beepshift" tag, and find the time difference between when the modifier key goes down and when it comes back up, and if it is a long time, then beep, else it is a short time so don't beep.  That's probably easier. <time passes> Okay the second approach is working for me now.  I didn't try the first approach in the previous paragraph at all.

Thanks for your help!

**Comment by aklaing** [comment]
My script wasn't working reliably because of the following problem:

If you tap a modifier key (say Ctrl) and a letter, and the modifier goes down at 0.0 seconds, the modifier goes up at 0.1 seconds and the letter goes down at say 0.4 seconds and comes up at 0.5 seconds, then the layer will be printed out (as activated) at 0.0 seconds, and as deactivated at 0.5 seconds.  This did not allow me to correctly determine that the way the modifier was pressed was with a tap, because I was using a short threshold like 0.2 to distinguish between taps and holds.  

So I needed to access the actual key presses for the modifier keys, instead of the layer changes, and this required me to modify the keyd source code.  I created a new function which basically checks whether the key that was pressed is a modifier key and if it is, prints that out onto the listeners' connections.

This does not work perfectly because if a modifier key is mapped to another modifier key, then both are printed out.  If you tap the physical key, and then tap a letter, the logical modifier key will show as a hold (instead of a tap).  So that is a problem, but my listener script can ignore the logical keys correctly and only pay attention to the physical keys, so for me personally that is not an issue.

If anyone is interested in code-reviewing this and/or improving it, please let me know and I can make it a pull request.

Thanks

**Comment by rvaiya** [comment]
If you are going to patch the source, I think the cleanest solution in this case is to just increase the command limit and use @nsbgn's solution. aplay and friends may or may not work depending on which particular soup of sound daemons you are running (pipewire, alsa, pulse). You will need to hack together a script that can play sound when you run it as root, which will likely involve setting `$XDG_RUNTIME_DIR` if pulseaudio is not running as a system wide daemon.

**Comment by rvaiya** [comment]
If you opt to go the `noop` route, you can just set the first parameter of `overload` to an empty layer.

E.g

```
shift = overload(null, oneshot(shift))

[null]
```

**Comment by aklaing** [comment]
Thanks for the pointer.  My current script did run into the $XDG_RUNTIME_DIR issue.  Maybe that would fix the problems I had before with aplay and friends, but eventually it was while using a python listener script based on pygame that I figured it out.  Also good to know about the null layer.  Overall this hack works, I can already notice it changing my typing habits for the better.  Thanks!!

**Comment by nsbgn** [comment]
Sounds like you got a satisfactory solution and it can be closed :)

>Another solution might be to just use noop

Orrr an arbitrary prefix like `M-esc` and have that trigger the beep in your environment (still requires lots of `x = macro(M-esc x)` though).

**Comment by aklaing** [comment]
Thanks for the suggestion and yes, I'm all set, thanks.  If I have the permissions I will close it now (never done this before).  It's great that there are so many approaches to solving it.  I have come to depend greatly on keyd and could not imagine going back to an unconfigured keyboard.  :-)
