### ISSUE TITLE
Cannot map the backslash \ with spanish layout

### ISSUE THREAD

**Issue by Aqa-Ib** [rvaiya/keyd#583]
Hello. I have a spanish layout with this key:
![20230927_19h08m56s_grim](https://github.com/rvaiya/keyd/assets/16420574/26f164d2-0d58-4af7-97eb-5027f330f877)
The main character printed when pressed is º . I can map that character without problem. The backslash is printed with G-º . It is the only key that I cannot map. Do you know why? 

Thanks for your time.

**Comment by Aqa-Ib** [comment]
Alright I found the bug:
In /usr/share/keyd/layouts/es

[es_altgr:G]
- = \

In my opinion, that should be corrected to:
º = \

**Comment by nsbgn** [comment]
The problem with fixing that is that keyd's keys actually do not refer to symbols, but keycodes. They have been given names corresponding to their symbols in the US layout, but if you do not use that layout, the names won't correspond.

Just using an US layout on the display server and letting keyd handle layouts is one way to deal with that.

I also personally think there's something to be said for also allowing keycodes of the form `0xFF` in place of symbols, but that's rvaiya's call :P

**Comment by Aqa-Ib** [comment]
I understand. But then, why this one is the only key in the entire keyboard that presents a problem when mapping it ?

**Comment by nsbgn** [comment]
Oh oops, I just saw that the issue you pointed out was in the Spanish layout file - I just read too quickly. My bad!

**Comment by Aqa-Ib** [comment]
Nevermind, the problem is just in my mind. After key mapping the whole day my brain is very confused.  Everything is alright though. Sorry for the mess. Have a nice one. Cheers!
