### ISSUE TITLE
Key bound to layer is not remapped in `toggle`d layer

### ISSUE THREAD

**Issue by carljohnson93** [rvaiya/keyd#589]
I'm using keyd with warpd, both are my favourite programs of all time so thank you very much. Here's the issue I've encountered:
```txt
[main]
# colemak-dh-based layout that starts from num-row (to free up bottom letter row for thumb keys)
# ...

# thumb keys:
c = enter
v = overload(nav, clear()) # left thumb rests on this key
b = space

n = layer(shift)
m = overload(sym, clear()) # right thumb rests on this key
, = layer(num)

# activate warpd layer, start warpd normal mode
space = togglem(warpd, A-M-c)

[warpd]
space = togglem(warpd, escape) # exit warpd layer
m = d # decelerate cursor movement
, = a # accelerate cursor movement
 
```
`m` and `,` keys in `[warpd]` layer are not rebound when warpd layer is toggled, as I assume because they are somewhat "special" (bound to layer/overloaded).

I assume this is a bug?

**Comment by rvaiya** [comment]
If that is actually your config, you will need to remove the comments at the end of line. Trailing comments are currently unsupported (since it makes `x = #` ambiguous). You can find more clues by inspecting the output of the daemon.

**Comment by carljohnson93** [comment]
wow thank you very much, that fixed the issue! and just wanted to say again that I appreciate your work and your software is most suckless, cleanest and useful software I've ever came across.
