### ISSUE TITLE
Hot config reloading

### ISSUE THREAD

**Issue by canadaduane** [rvaiya/keyd#59]
Putting this here to track hot config reloading as a feature currently under discussion.

https://gist.github.com/rvaiya/5f2ba4b92f9c56dca76a99df6ca609a0#file-keyd_app_demo-py-L54

https://github.com/rvaiya/keyd/issues/51#issuecomment-974410035

This would enable a parent process to send keyd a signal to reload config, without having to reload the entire daemon / re-grab the keyboard devices.

**Comment by rvaiya** [comment]
This should be implemented in the latest commit. Sorry this took so long. The process should now reload upon receiving `SIGUSR1`. There are still a few optimizations that need to be made but it should be an order of magnitude faster than restarting the daemon.

**Comment by rvaiya** [comment]
Closing this in favour of #91
