### ISSUE TITLE
Request: Allow defining arbitrary modifiers

### ISSUE THREAD

**Issue by dnaik42** [rvaiya/keyd#592]
I'm using Tab as my numpad layer key, where if I hold tab, a part of my keyboard turns into a numpad. However, when I press Tab+x, where x is any key that is not defined in my numpad layer, i want it to be registered as Tab+x and not just as x.

An implementation of this that I can see is by allowing me to define Tab as a modifier T, so that I can then initialize my layer as `[numpad:T]`

If there already exists another way of acheiving this, please let me know.

**Comment by nsbgn** [comment]
This isn't possible, because modifiers aren't something that keyd can just make up --- whatever is emitted by the virtual keyboard need to be interpreted by the applications you're running.

What you can do is send some combination of modifiers `C/S/A/M/G` as a 'custom' modifier. For example, as I understand, what's commonly called 'hyper' is just `C-S-A-M`.

**Comment by svonjoi** [comment]
+1
the problem with creating fake modifier from a combination of other modifiers (`C-S-A-M`) is that it cannot be used in conjunction with the modifiers that compose it.

Is there a way to add completely-functional modifier like adding Hyper_L via xmodmap?

**Comment by svonjoi** [comment]
I have remapped capslock to `Hyper_L` mammoth so this way I can combine this new modifier with another modifiers within my hotkey daemon.

The problem I was facing was that whenever a USB device was connected or disconnected, the key remapping settings in my `~/.Xmodmap` file would be reset. To reapply these settings, I had to manually run `xmodmap ~/.Xmodmap`

So I enabled the keyd.service and this problem was gone

I think *keyd* run `xmodmap ~/.Xmodmap` under the hood via keyd.service (`systemd service`) every time the usb is added or removed. Is it?

**Comment by rvaiya** [comment]
> Is there a way to add completely-functional modifier like adding Hyper_L via xmodmap?

Not within keyd. Modifiers are a display server construct. In X, you can achieve something similar by doing:

`xmodmap -e "add mod5 = XF86Tools"` 

and then something like

```
tab = layer(mylayer)
[mylayer]
a = macro(f13+a)
b = macro(f13+b)
c = macro(foo)
```

or alternatively:

`xmodmap -e "add mod5 = Alt_R"` 

```
tab = layer(mylayer)

[mylayer:G]
c = macro(foo)
```

if you don't use altgr.

I'm not sure about wayland, but I believe you can achieve a similar result by modifying xkb layout files.

**Comment by rvaiya** [comment]
> I think keyd run xmodmap ~/.Xmodmap under the hood via keyd.service (systemd service) every time the usb is added or removed. Is it?

Not with the copy that ships with this repo. The systemd service shouldn't affect anything run within the context of the user session, it is just used for managing the root level daemon.

**Comment by svonjoi** [comment]
> > Is there a way to add completely-functional modifier like adding Hyper_L via xmodmap?
> 
> Not within keyd. Modifiers are a display server construct. In X, you can achieve something similar by doing:
> 
> `xmodmap -e "add mod5 = XF86Tools"`
> 
> and then something like
> 
> ```
> tab = layer(mylayer)
> 
> [mylayer]
> a = macro(f13+a)
> b = macro(f13+b)
> c = macro(foo)
> ```
> 
> or alternatively:
> 
> `xmodmap -e "add mod5 = Alt_R"`
> 
> ```
> tab = layer(mylayer)
> 
> [mylayer:G]
> c = macro(foo)
> ```
> 
> if you don't use altgr.
> 
> I'm not sure about wayland, but I believe you can achieve a similar result by modifying xkb layout files.

thanks!! it's working well

**Comment by svonjoi** [comment]
> > I think keyd run xmodmap ~/.Xmodmap under the hood via keyd.service (systemd service) every time the usb is added or removed. Is it?
> 
> Not with the copy that ships with this repo. The systemd service shouldn't affect anything run within the context of the user session, it is just used for managing the root level daemon.

My assumption that keyd is running my home config was stupid, however my xmodmap user-configuration still applied after reattaching my keyboard, while keyd service is running.

**Comment by rvaiya** [comment]
> however xmodmap user-configuration still applied after reattaching my keyboard

The X config will apply to the virtual keyboard which is only 'unplugged' when the keyd service is restarted. Your physical keyboard will be subsumed by the keyd virtual device, which X will see as being persistently plugged in.

**Comment by svonjoi** [comment]
> > however xmodmap user-configuration still applied after reattaching my keyboard
> 
> The X config will apply to the virtual keyboard which is only 'unplugged' when the keyd service is restarted. Your physical keyboard will be subsumed by the keyd virtual device, which X will see as being persistently plugged in.

thanks for clarification
