### ISSUE TITLE
Request: Allow running commands as user

### ISSUE THREAD

**Issue by dnaik42** [rvaiya/keyd#593]
This would be useful for sending messages to programs like polybar, which are running for the user. Another useful feature would be the ability to pass the config file from an arbitrary location rather than in /etc/keyd.

**Comment by nsbgn** [comment]
`command`s are discouraged for such use cases --- keyd is meant to simulate a keyboard, not be a hotkey manager, and this inherently needs elevated privileges. Putting the configuration in `/etc/keyd` also communicates this: you don't want the configuration to be editable by any other program.

See also #211, #229, #243. 

That said, you *can* already run a command as another user using `su` (though you would likely also need to pass some environment variables to make it work in general).
