### ISSUE TITLE
`x = overload(..., macro(x))` behaves differently than `x = overload(..., x)`

### ISSUE THREAD

**Issue by motato1** [rvaiya/keyd#595]
OS: ArchLinux, Linux kernel 6.5.6
Version: keyd v2.4.3 (5e4ef41)
Keyd config:

```
[ids]
*

[main]
x = overload(control, macro(x))
``` 

My goal with this was that `x` acts as `control` when held and as `x` when tapped.
And it works. However, when tapping the `x` key, the key code for `x`  is sent over and over again until I press any other key.

I could fix my particular use case by removing `macro(...)`  (`x = overload(control, x)`).

However, in other cases this might not work. E.g. `, = overload(control, ,)` does not work because comma needs to be wrapped in a `macro` directive.

My understanding from reading the `MACROS`  section in the manual is that `macro(x)` and `x` should behave identically.

I don't know if my interpretation of the man page is wrong or if the behavior is indeed faulty. In any case, I appreciate you taking the time to read this :)

And let me thank you for this fantastic piece of software. I love how easily it allows me to make my laptop keyboard fit my needs better :pray:

**Comment by nsbgn** [comment]
As I remember this come up before in #519. That issue was closed, but only because there's a workaround, so probably shouldn't have been. Just a quick fyi

**Comment by rvaiya** [comment]
I believe this should be fixed in the latest commit.

**Comment by motato1** [comment]
Hey, sorry for the radio silence from my end.

I've finally gotten around to test the master branch and the behavior now is indeed as expected/described in the manpage.

Thank you for your work and have a nice 2024 :)
