### ISSUE TITLE
Cannot rebind leftmeta key

### ISSUE THREAD

**Issue by SuperCraftAlex** [rvaiya/keyd#596]
I have this: 
```
leftmeta = macro(leftcontrol+leftshift+u 2 1 a 7 space)
rightalt = macro(leftcontrol+leftshift+u 2 1 a 5 space)
```
It changes the behaviour of the rightalt key but not for the leftmeta key

Keyd detects the keypresses
![image](https://github.com/rvaiya/keyd/assets/63254202/56f023dd-06d6-4609-985d-699544069e9d)

**Comment by nsbgn** [comment]
```
leftmeta = macro(C-S-u 2 1 a 7 space)
rightalt = macro(C-S-u 2 1 a 5 space)
```

`a+b` is a chord, which you can bind something to but it is not (currently) a macro.

**Comment by SuperCraftAlex** [comment]
> ```
> leftmeta = macro(C-S-u 2 1 a 7 space)
> rightalt = macro(C-S-u 2 1 a 5 space)
> ```
> 
> `a+b` is a chord, which you can bind something to but it is not (currently) a macro.

i dont quite understand

**Comment by nsbgn** [comment]
Please be descriptive, because I'm not sure what was confusing. I'll do my best to be clearer:

You used `leftcontrol+leftshift+u`, but that is not a valid macro expression. `leftcontrol+leftshift+u` is a chord, which is probably not what you're looking for (see the manual). You probably meant `C-S-u`.

**Comment by SuperCraftAlex** [comment]
I used `leftcontrol+leftshift+u` for all other keys and it works perfectly fine.
it just doesn't work for leftmeta.
`C-S-u` doesn't work for leftmeta either.

**Comment by SuperCraftAlex** [comment]
Oh I just realised that I already binded leftmeta accidentally.

**Comment by nsbgn** [comment]
Huh, you're right. Sorry, my mistake --- gotten too in the habit of answering issues without testing my assumptions :P That said, it does work for me. What is your full config?
