### ISSUE TITLE
Prevent rolls from registering as a hold when using `overloadt2`

### ISSUE THREAD

**Issue by amarakon** [rvaiya/keyd#607]
I use `overloadt2` for home row mods. For example, if I hold down `k` and tap and release `t` before releasing `k`, that will result in `Control T`. This is my configuration:

```
[ids]

*

[main]

s = overloadt2(alt, s, 2000)
d = overloadt2(control, d, 2000)
f = overloadt2(meta, f, 2000)
j = overloadt2(meta, j, 2000)
k = overloadt2(control, k, 2000)
l = overloadt2(alt, l, 2000)
```

When typing really fast, I often roll two keys that are next to each other and accidentally trigger a modifier. For example, I might do (on colemak these keys are next to each other):

```
r down
s down
s up
r up
```

This will trigger `Alt S` when what I want it to do is `rs`. Can you add an option to make it so that `overloadt2` modifiers are only seen as modifiers when tapping a key on the other side of the keyboard?

**Comment by nsbgn** [comment]
For now, I will assume that `overloadt2` is indeed preferable over `overload`/`overloadt` for your use case (though this sounds questionable, since the high timeout of `2000` suggests that the timeout won't be reached often anyway).

I'll focus on:

> make it so that overloadt2 modifiers are only seen as modifiers when tapping a key on the other side of the keyboard

I believe you could achieve this by making custom layers that override the modifier behaviour (and disable the custom layer) when tapping a key on the 'wrong' half of the keyboard, ie:

```
[ids]
*

[main]
s = overloadt2(alt_rhs, s, 2000)
l = overloadt2(alt_lhs, l, 2000)
# ...

[empty]

[alt_rhs:A]
y = swapm(empty, s y)
u = swapm(empty, s u)
i = swapm(empty, s i)
# ...

[alt_lhs:A]
q = swapm(empty, l q)
w = swapm(empty, l w)
e = swapm(empty, l e)
# ...
```

Would that be satisfactory?

**Comment by amarakon** [comment]
> For now, I will assume that `overloadt2` is indeed preferable over `overload`/`overloadt` for your use case (though this sounds questionable, since the high timeout of `2000` suggests that the timeout won't be reached often anyway).

I use `overloadt2` because it resolves as a hold when another key is tapped. I set the timeout to a high number like `2000` because I don't wait for the timeout anyway.

> I believe you could achieve this by making custom layers that override the modifier behaviour (and disable the custom layer) when tapping a key on the 'wrong' half of the keyboard, ie:

I tried the following:

```
s = overloadt2(alt_rhs, s, 2000)
l = overloadt2(alt_lhs, l, 2000)

[empty]

[alt_rhs:A]
y = swapm(empty, s y)
u = swapm(empty, s u)
i = swapm(empty, s i)
o = swapm(empty, s o)
p = swapm(empty, s p)
h = swapm(empty, s h)
j = swapm(empty, s j)
k = swapm(empty, s k)
l = swapm(empty, s l)
n = swapm(empty, s n)
m = swapm(empty, s m)

[alt_lhs:A]
q = swapm(empty, l q)
w = swapm(empty, l w)
e = swapm(empty, l e)
r = swapm(empty, l r)
t = swapm(empty, l t)
a = swapm(empty, l a)
s = swapm(empty, l s)
d = swapm(empty, l d)
f = swapm(empty, l f)
g = swapm(empty, l g)
z = swapm(empty, l z)
x = swapm(empty, l x)
c = swapm(empty, l c)
v = swapm(empty, l v)
b = swapm(empty, l b)
```

But it doesn't seem to change anything. I can type `Alt S` with modifiers from either side.

**Comment by nsbgn** [comment]
Sorry, my mistake --- the syntax is `swapm(empty, macro(s y))`. Also, `lhs` and `rhs` should probably be swapped. Double my mistake. :P

**Comment by amarakon** [comment]
I used the proper syntax and swapped `lhs` and `rhs`, and now using `Alt` works as intended. But it doesn't work for other modifiers. For example, doing `k down`, `t down`, `t up`, `k up` results in `Alt T` when I want it to do `Control T`. Here is my configuration now:

```
[ids]
*

[main]

leftshift = oneshot(shift)

j+k+l = escape

s = overloadt2(alt_lhs, s, 2000)
d = overloadt2(control_lhs, d, 2000)
f = overloadt2(meta_lhs, f, 2000)
j = overloadt2(meta_rhs, j, 2000)
k = overloadt2(control_rhs, k, 2000)
l = overloadt2(alt_rhs, l, 2000)

[empty]

[alt_lhs:A]
q = swapm(empty, macro(s q))
w = swapm(empty, macro(s w))
e = swapm(empty, macro(s e))
r = swapm(empty, macro(s r))
t = swapm(empty, macro(s t))
a = swapm(empty, macro(s a))
s = swapm(empty, macro(s s))
d = swapm(empty, macro(s d))
f = swapm(empty, macro(s f))
g = swapm(empty, macro(s g))
z = swapm(empty, macro(s z))
x = swapm(empty, macro(s x))
c = swapm(empty, macro(s c))
v = swapm(empty, macro(s v))
b = swapm(empty, macro(s b))

[control_lhs:A]
q = swapm(empty, macro(d q))
w = swapm(empty, macro(d w))
e = swapm(empty, macro(d e))
r = swapm(empty, macro(d r))
t = swapm(empty, macro(d t))
a = swapm(empty, macro(d a))
s = swapm(empty, macro(d s))
d = swapm(empty, macro(d d))
f = swapm(empty, macro(d f))
g = swapm(empty, macro(d g))
z = swapm(empty, macro(d z))
x = swapm(empty, macro(d x))
c = swapm(empty, macro(d c))
v = swapm(empty, macro(d v))
b = swapm(empty, macro(d b))

[meta_lhs:A]
q = swapm(empty, macro(f q))
w = swapm(empty, macro(f w))
e = swapm(empty, macro(f e))
r = swapm(empty, macro(f r))
t = swapm(empty, macro(f t))
a = swapm(empty, macro(f a))
s = swapm(empty, macro(f s))
d = swapm(empty, macro(f d))
f = swapm(empty, macro(f f))
g = swapm(empty, macro(f g))
z = swapm(empty, macro(f z))
x = swapm(empty, macro(f x))
c = swapm(empty, macro(f c))
v = swapm(empty, macro(f v))
b = swapm(empty, macro(f b))

[meta_rhs:A]
y = swapm(empty, macro(j y))
u = swapm(empty, macro(j u))
i = swapm(empty, macro(j i))
o = swapm(empty, macro(j o))
p = swapm(empty, macro(j p))
h = swapm(empty, macro(j h))
j = swapm(empty, macro(j j))
k = swapm(empty, macro(j k))
l = swapm(empty, macro(j l))
n = swapm(empty, macro(j n))
m = swapm(empty, macro(j m))

[control_rhs:A]
y = swapm(empty, macro(k y))
u = swapm(empty, macro(k u))
i = swapm(empty, macro(k i))
o = swapm(empty, macro(k o))
p = swapm(empty, macro(k p))
h = swapm(empty, macro(k h))
j = swapm(empty, macro(k j))
k = swapm(empty, macro(k k))
l = swapm(empty, macro(k l))
n = swapm(empty, macro(k n))
m = swapm(empty, macro(k m))

[alt_rhs:A]
y = swapm(empty, macro(l y))
u = swapm(empty, macro(l u))
i = swapm(empty, macro(l i))
o = swapm(empty, macro(l o))
p = swapm(empty, macro(l p))
h = swapm(empty, macro(l h))
j = swapm(empty, macro(l j))
k = swapm(empty, macro(l k))
l = swapm(empty, macro(l l))
n = swapm(empty, macro(l n))
m = swapm(empty, macro(l m))

[global]

chord_timeout = 50
oneshot_timeout = 1000
```

**Comment by nsbgn** [comment]
For other modifiers, you can change `:A` to `:C` (for control) or `:M` (for meta).

>Also, do I need the `[empty]` line?

I think so. Afaik there is no way to 'deactivate the current layer', but there is a way to swap the current layer with an empty layer, which is functionally the same thing. Maybe there is a better way.

**Comment by amarakon** [comment]
> For other modifiers, you can change `:A` to `:C` (for control) or `:M` (for meta).

Thanks, this works.

> I think so. Afaik there is no way to 'deactivate the current layer', but there is a way to swap the current layer with an empty layer, which is functionally the same thing and is what the `[empty]` layer is doing there. Maybe there is a better way.
>
> (You could also leave it out completely and use `macro(s y)` instead of `swapm(empty, macro(s y))`, but you'd notice the difference when your overloaded key overlaps with multiple keypresses.)

Okay, I will keep the `[empty]` line then.

---

It works well right now except for one thing: sometimes a key won't be registered even though I tapped it. For example, if I type the word "friend" really fast, it sometimes outputs as "fend". The characters on Qwerty for this word are "eslkjg" (I use the Colemak layout). For some reason, "ri", which is "sl" in Qwerty which are tap-hold modifiers for me, did not register. I don't know what causes this issue.

**Comment by nsbgn** [comment]
> It works well right now except for one thing: sometimes a key won't be registered even though I tapped it. For example, if I type the word "friend" really fast, it sometimes outputs as "fend". The characters on Qwerty for this word are "eslkjg" (I use the Colemak layout). For some reason, "ri", which is "sl" in Qwerty which are tap-hold modifiers for me, did not register. I don't know what causes this issue.

I suspect it's got something to do with keypresses that overlap and activate and deactivate layers all over the place (note that `slkj` are all overloaded keys). I'll find some time to properly investigate later (if you don't figure it out before me :P). However, for a quick solution, maybe it will help if you explicitly override all overloaded keys in the `empty` layer? ie.

```
# ...

[empty]
s = s
d = d
f = f
j = j
k = k
l = l

# ...
```

**Comment by amarakon** [comment]
I tried that and it did not make a difference. With further testing, I think I know what the problem is. I am accidentally triggering `Alt I` instead of `ri` because I released the `i` key before releasing the `r` key. It is my own mistake, not a bug. I think this issue can be closed now.
