### ISSUE TITLE
Are media keys possible to be sent?

### ISSUE THREAD

**Issue by sameerasw** [rvaiya/keyd#609]
I want to map my pause key for media play/pause but I couldn't figure out the media keys names to use here. Is there a list of key names that I can use?

<3

**Comment by sameerasw** [comment]
NVM, Figured out

**Comment by Moanrisy** [comment]
@sameerasw can you share what you found? It gonna help people like you or me who need this.

**Comment by sameerasw** [comment]
> @sameerasw can you share what you found? It gonna help people like you or me who need this.

Actually `keyd monitor` helped me as the readme states.... I also found a list of keys but no longer can find it since I'm away from linux and my project for now

**Comment by nsbgn** [comment]
@Moanrisy The list at https://github.com/rvaiya/keyd/issues/177#issuecomment-1092064707 may be helpful, but do bear in mind that the correspondence between the keys at the keyd level and the keysyms interpreted at the compositor level may not be 1:1

**Comment by Moanrisy** [comment]
Thank you nsbgn, I found that #177 too earlier but forgot to reply back.

this is my comment on my /etc/keyd/default.conf.

```
# sudo keyd monitor to know key name (ex: media button, etc)
# complete list keys: 
# https://gist.githubusercontent.com/rvaiya/be31f42049a4b5ad46666a8e120d9843/raw/a441bc104f2eba0fb8bf53053d82f06c3a19da64/keysym_to_keyd.txt
#
# or run keyd list-keys
```
