### ISSUE TITLE
overload not working

### ISSUE THREAD

**Issue by szz-dvl** [rvaiya/keyd#612]
Using the following config file:

`
[ids]

*

[main]

home = pageup
end = pagedown
pageup = overload(pageup, home)
pagedown = overload(pagedown, end)
capslock = leftshift
`

I'm receiving the following error:

`
nov 26 00:37:41 t14s keyd[5429]: CONFIG: parsing /etc/keyd/default.conf
nov 26 00:37:41 t14s keyd[5429]:         ERROR: line 10: pageup is not a valid layer
nov 26 00:37:41 t14s keyd[5429]:         ERROR: line 11: pagedown is not a valid layer
nov 26 00:37:41 t14s keyd[5429]:         WARNING: You should use layer(shift) instead of assigning to leftshift directly.
nov 26 00:37:41 t14s keyd[5429]: Starting keyd v2.4.3 (5e4ef41)
`

Datails on the system: 

`System:
  Host: t14s Kernel: 6.6.2-2-MANJARO arch: x86_64 bits: 64 compiler: gcc
    v: 13.2.1 Desktop: sway v: 1.8.1 Distro: Manjaro Linux base: Arch Linux
Machine:
  Type: Laptop System: LENOVO product: 21F6CTO1WW v: ThinkPad T14s Gen 4
    serial: <superuser required>
  Mobo: LENOVO model: 21F6CTO1WW serial: <superuser required> UEFI: LENOVO
    v: N3PET19W (1.10 ) date: 08/25/2023
Battery:
  ID-1: BAT0 charge: 17.3 Wh (30.1%) condition: 57.5/57.0 Wh (100.9%)
    volts: 15.0 min: 15.4 model: LGES 5B10W51874 status: discharging
CPU:
  Info: 10-core (2-mt/8-st) model: 13th Gen Intel Core i7-1365U bits: 64
    type: MST AMCP arch: Raptor Lake rev: 3 cache: L1: 928 KiB L2: 6.5 MiB
    L3: 12 MiB
  Speed (MHz): avg: 483 high: 825 min/max: 400/5200:3900 cores: 1: 825
    2: 400 3: 693 4: 400 5: 400 6: 400 7: 679 8: 400 9: 400 10: 400 11: 400
    12: 400 bogomips: 64536
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3
Graphics:
  Device-1: Intel Raptor Lake-P [Iris Xe Graphics] vendor: Lenovo driver: i915
    v: kernel arch: Gen-13 bus-ID: 00:02.0
  Device-2: Syntek Integrated Camera driver: uvcvideo type: USB
    bus-ID: 3-4:2
  Display: wayland server: Xwayland v: 23.2.2 compositor: sway v: 1.8.1
    driver: gpu: i915 resolution: 1920x1200~60Hz
  API: EGL Message: EGL data requires eglinfo. Check --recommends.
Audio:
  Device-1: Intel Raptor Lake-P/U/H cAVS vendor: Lenovo
    driver: sof-audio-pci-intel-tgl bus-ID: 00:1f.3
  API: ALSA v: k6.6.2-2-MANJARO status: kernel-api
  Server-1: sndiod v: N/A status: off
  Server-2: JACK v: 1.9.22 status: off
  Server-3: PipeWire v: 0.3.85 status: active
Network:
  Device-1: Intel Raptor Lake PCH CNVi WiFi driver: iwlwifi v: kernel
    bus-ID: 00:14.3
  IF: wlan0 state: down mac: fa:2b:01:bc:5d:d9
  Device-2: Realtek USB 10/100/1G/2.5G LAN driver: r8152 type: USB
    bus-ID: 4-2:2
  IF: eth0 state: up speed: 2500 Mbps duplex: full mac: 80:3f:5d:f6:90:1b
Bluetooth:
  Device-1: Intel AX211 Bluetooth driver: btusb v: 0.8 type: USB
    bus-ID: 3-10:4
  Report: btmgmt ID: hci0 rfk-id: 0 state: up address: 90:09:DF:57:2D:CA
    bt-v: 5.3 lmp-v: 12
Drives:
  Local Storage: total: 1.86 TiB used: 12.19 GiB (0.6%)
  ID-1: /dev/nvme0n1 vendor: KIOXIA model: N/A size: 1.86 TiB temp: 24.9 C
Partition:
  ID-1: / size: 193.36 GiB used: 8.38 GiB (4.3%) fs: btrfs dev: /dev/nvme0n1p3
  ID-2: /boot/efi size: 1.95 GiB used: 584 KiB (0.0%) fs: vfat
    dev: /dev/nvme0n1p2
  ID-3: /home size: 1.66 TiB used: 3.81 GiB (0.2%) fs: btrfs
    dev: /dev/nvme0n1p1
  ID-4: /var/log size: 193.36 GiB used: 8.38 GiB (4.3%) fs: btrfs
    dev: /dev/nvme0n1p3
Swap:
  ID-1: swap-1 type: partition size: 7.81 GiB used: 0 KiB (0.0%)
    dev: /dev/nvme0n1p4
Sensors:
  System Temperatures: cpu: 33.0 C mobo: N/A
  Fan Speeds (rpm): fan-1: 0
Info:
  Processes: 324 Uptime: 2h 53m Memory: total: 32 GiB note: est.
  available: 31.01 GiB used: 2.67 GiB (8.6%) Init: systemd Compilers:
  gcc: 13.2.1 clang: 16.0.6 Packages: 854 Shell: Zsh v: 5.9 inxi: 3.3.31`
  
  
  uname:
  
 Linux t14s 6.6.2-2-MANJARO #1 SMP PREEMPT_DYNAMIC Fri Nov 24 12:36:53 UTC 2023 x86_64 GNU/Linux

**Comment by nsbgn** [comment]
Pageup is not a layer, so this makes sense. What are you trying to do?

Assuming that you want to give a single key both the home and pageup functions based on how long you press them, you can use `timeout(home, 300, pageup)`, but it probably won't feel very ergonomic. You're better off assigning them to separate keys (possibly in a layer).

**Comment by szz-dvl** [comment]
Hi nsbgn;

I will give it a try, thank you for the quick answer!,

closing the issue.
