### ISSUE TITLE
Workman layout incorrect

### ISSUE THREAD

**Issue by jeremiah-miller** [rvaiya/keyd#613]
The included workman layout (/usr/share/keyd/layouts/workman) is incorrect. 

[it should be](https://workmanlayout.org/):

```
[workman:layout]

q = q
w = d
e = r
r = w
t = b
y = j
u = f
i = u
o = p
p = ;
a = a
s = s
d = h
f = t
g = g
h = y
j = n
k = e
l = o
; = i
' = '
z = z
x = x
c = m
v = c
b = v
n = k
m = l
```

**Comment by rvaiya** [comment]
Thanks, this should be fixed in the latest commit.

**Comment by jm355** [comment]
@eNV25 if keyd doesn't release before the next arch linux keyd update, would you mind including 6a9cf304cb071167652a926d70caac61e29d67aa in the arch linux package so the next update doesn't overwrite the correct workman layout file to an incorrect copy? I updated my system and got really confused why I was typing gibberish for a minute 😅

**Comment by eNV25** [comment]
I don't really get what you mean. I release on AUR when there is a release here.

**Comment by eNV25** [comment]
Use aur/keyd-git if you want latest commits.

**Comment by jm355** [comment]
I got an update to keyd (not at my computer rn so I don't have the exact number, but iirc it was 2.4.3-4), but the last release here was in May 2023

**Comment by eNV25** [comment]
@jm355 The keyd Arch Linux package (but not keyd-git) has been added to the main repositories and removed from AUR. I don't maintain it anymore.

**Comment by jm355** [comment]
Ohh I see. Sorry to bother you then, but thanks!

**Comment by jm355** [comment]
Until this gets added to the arch package, I use this pacman hook to fix the workman file since everytime keyd updates in arch, it overwrites it

/etc/pacman.d/hooks/keyd_worman_fix.hook
```
[Trigger]
Operation = Install
Operation = Upgrade
Type = Package
Target = keyd

[Action]
When = PostTransaction
Exec = /usr/bin/cp /home/user/workman /usr/share/keyd/layouts/workman
```
/home/user/workman
```
[workman:layout]

q = q
w = d
e = r
r = w
t = b
y = j
u = f
i = u
o = p
p = ;
a = a
s = s
d = h
f = t
g = g
h = y
j = n
k = e
l = o
; = i
' = '
z = z
x = x
c = m
v = c
b = v
n = k
m = l
```

**Comment by eNV25** [comment]
Otherwise, switch to aur/keyd-git

**Comment by jm355** [comment]
I guess I could do those, but now I'll just use the hook since I already set it up
