### ISSUE TITLE
Could not find app.conf

### ISSUE THREAD

**Issue by basharatusman** [rvaiya/keyd#617]
I'm trying to transition from MacOS to Ubuntu and Keyd has been great so far.

I'm trying to add app-specific keybindings, however, when I run `keyd-application-mapper` I get the following error.

ERROR: could not find app.conf, make sure it is in ~/.config/keyd/app.conf

The file exists with the following content.

```
[google-chrome]

alt.[ = C-S-tab
alt.] = macro(C-tab)
```

I also have app.lock and app.log in the ~/.config/keyd directory. There is no output in the log file.

My default key mappings are working. I'm using Ubuntu 22.04.3 LTS (default Wayland).

Any suggestions on what I should try?

**Comment by rvaiya** [comment]
Did you install from source? Are you running keyd-application-mapper as root (you shouldn't be)?

**Comment by basharatusman** [comment]
Thank you for the fast reply. I was running it as root. I ran it without sudo and it returned "Gnome Detected". However, the app.conf defined google-chrome shortcuts are not working. I tried restarting chrome after running the mapper.

I ran `sudo journalctl -eu keyd` and received not a valid key error on line 22. I'm using the macos settings from the examples folder. The issue seems to be with `leftmeta = alt`.

**Comment by rvaiya** [comment]
`leftmeta = alt` is not a valid binding. `alt` is a layer `leftalt` is a key (which is bound to `layer(alt)` by default. As a separate point, `google-chrome` may or may not be a valid application class name, you can use `keyd-application-mapper -v` to print class names as you switch apps.

**Comment by basharatusman** [comment]
I ran `keyd-application-mapper -v` but I just get `Gnome detected` as the output. I checked the app.log file and it's empty.

**Comment by basharatusman** [comment]
Got it working! I was playing around with gnome-tweaks and while in the extensions realized that key-mapper had to be enabled.
