### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by MaxGyver83** [rvaiya/keyd#62]
```
~/repos/keyd (master|✔) [2] ▶ make
mkdir -p bin
cc -DVERSION=\"1.1.2\" -DGIT_COMMIT_HASH=\"231e3ebd1cb58607e21952a0ab93030970d22010\" -DCONFIG_DIR=\""/etc/keyd"\" -DLOG_FILE=\""/var/log/keyd.log"\" -DLOCK_FILE=\""/var/lock/keyd.lock"\" -I/usr/local/include -L/usr/local/lib -O3 src/*.c -o bin/keyd -ludev
src/main.c: In function ‘monitor_exit’:
src/main.c:827:26: error: parameter name omitted
  827 | static void monitor_exit(int)
      |                          ^~~
```

It looks like a parameter name is missing for `monitor_exit`.

**Comment by rvaiya** [comment]
This is intentional. The exit status should be zero since SIGINT isn't considered and error and I don't care about the parameter. What compiler are you using? gcc ignored this and clang just issues a warning.

**Comment by MaxGyver83** [comment]
OK, I didn't know that this can work.

I use this version: `x86_64-linux-gnu-gcc-9 (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0`

(cc → gcc → gcc-9 → x86_64-linux-gnu-gcc-9)

**Comment by MaxGyver83** [comment]
What's the point in having a function parameter and never using it? Does `signal` require `monitor_exit` to have an unused `int`?

**Comment by rvaiya** [comment]
Indeed, signal expects the handler to have type ` void (*func)(int)`. Curiously it doesn't seem to produce an error on either of my machines (gcc 8/11). Did you modify any compiler flags?

**Comment by MaxGyver83** [comment]
> Did you modify any compiler flags?

No.

I tried it again in a clean environment, using this `Dockerfile`:

```Dockerfile
FROM ubuntu:20.04

RUN apt-get update && apt-get install -y build-essential git libudev-dev

RUN cd $HOME && git clone https://github.com/rvaiya/keyd.git && cd keyd && git checkout 231e3ebd1cb58607e21952a0ab93030970d22010 && make
```

And I got the the same error. But when I use `ubuntu:21:10` (with `gcc version 11.2.0`) instead, the error does not show up.

**Comment by rvaiya** [comment]
This has been cleansed by the sands of time :P. Sorry it took so long. I believe this is no longer an issue.
