### ISSUE TITLE
Several issues with uninstall in Makefile

### ISSUE THREAD

**Issue by HalimNaim** [rvaiya/keyd#620]
I don't have experience with Linux programming so I'm not sure if this is expected or not. 

1. Directory $(DESTDIR)$(PREFIX)/share/keyd/ not uninstalled.
2. Why is the default `$PREFIX` not `/usr/local`?
3. Why don't we call `groupdel` on `keyd` group that is created?

**Comment by rvaiya** [comment]
I believe you are correct on all counts. 2 is probably a function of my ancient linux knowledge which precedes the widespread FHS adoption. These should be fixed in the latest commit.

**Comment by tkna91** [comment]
The following of keyd.service is not `/usr/bin/keyd` in arch linux environment. Can you please check?
```
ExecStart=/usr/local/bin/keyd
```

```bash
$ keyd --version
keyd v2.4.3 (07a993d)
$ paru -Q keyd-git
keyd-git 2.4.3.r33.07a993d-1
$
$ nl -ba /usr/lib/systemd/system/keyd.service
     1  [Unit]
     2  Description=key remapping daemon
     3  Requires=local-fs.target
     4  After=local-fs.target
     5
     6  [Service]
     7  Type=simple
     8  ExecStart=/usr/local/bin/keyd
     9
    10  [Install]
    11  WantedBy=sysinit.target
$
```

I think it is expected to be stored in `/usr/bin/keyd`, since the PKGBUILD states the following. Sorry if I'm wrong.
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=keyd-git#n40
```
make DESTDIR="${pkgdir}" PREFIX='/usr' install
```

**Comment by tkna91** [comment]
I am not sure, but is this the way to do it?

https://github.com/rvaiya/keyd/commit/03d4a27b83ac69bc6854f7759de6124cc5e74d6d#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R5

```
PREFIX ?= /usr/local
```

**Comment by HalimNaim** [comment]
In the provided `PKGBILD` you are not passing the prefix to `make` 

```
build() {
	cd "$srcdir/${pkgname%-git}"
	make
}
```
You need to provide it here now that the default changed.

**Comment by tkna91** [comment]
@HalimNaim I Reported. Thanks.
https://aur.archlinux.org/packages/keyd-git#comment-948558-content

**Comment by eNV25** [comment]
AUR PKGBUILD Fixed

**Comment by tkna91** [comment]
The following packages may also need to be modified in this regard

- Alpine @jirutka
- Fedora @alternateved
- openSUSE @bubbleguuum

**Comment by alternateved** [comment]
COPR package uses the released version, so those changes could wait until the next version. Are there any plans for another release?

**Comment by tkna91** [comment]
I don't know, but if you need to modify the package after that release, please refer to the above.

**Comment by rvaiya** [comment]
Moved to #628.

@alternateved 

> Are there any plans for another release?

You can expect a final minor release in a week or two after which I intend on working on the next major version which will likely break backward compatibility and introduce several new features.
