### ISSUE TITLE
[Maintainer Note] PREFIX changed to /usr/local

### ISSUE THREAD

**Issue by rvaiya** [rvaiya/keyd#628]
03d4a27 changed the default `PREFIX` value to `/usr/local` to make it more consistent with FHS. I am creating this issue to make the relevant package maintainers aware of the change.

- Alpine @jirutka
- Arch @eNV25
- Fedora @alternateved
- openSUSE @bubbleguuum

Thank you for your contributions :).

**Comment by alternateved** [comment]
Thanks! I will update COPR package once `keyd` gets a release as mentioned in https://github.com/rvaiya/keyd/issues/620#issuecomment-1868231847.

**Comment by bubbleguuum** [comment]
Will do the same.

**Comment by eNV25** [comment]
@ainola
