### ISSUE TITLE
How to make oneshot keep activated until pressed again?

### ISSUE THREAD

**Issue by Moanrisy** [rvaiya/keyd#633]
```
Shift down
h down
h up
j down
j up
k down
k up
Shift up
```

This way I can do
S-h S-j S-k by pressing
S h j k S(without holding any key)

is this possbile?

**Comment by nsbgn** [comment]
Yes, use `toggle(shift)` instead of `oneshot(shift)`.

**Comment by Moanrisy** [comment]
Thank you, idk why I can't find that command in 3 hours -_-


I even tried using ydotool to press rightcontrol (so it will be hold)
then do what I need
trigger ydotool again to turn it off

but ydotool didn't work for rightcontrol (idk why, it work just fine for other a-z, return key)
