### ISSUE TITLE
Doesn't recognise specific symbols

### ISSUE THREAD

**Issue by jaygal0** [rvaiya/keyd#635]
Hello, 

I recently came across keyd and I'm really enjoying remapping my linux machine to somewhat mimic my macos keybindings. However, when it comes to symbols that I use often (e.g. @$|[{}] and etc...) it doesn't seem to register them correctly. 

For example this is what I have in my config
```
leftmeta = layer(alt_mac)

[alt_mac:A]

2 = @
```
This is to recreate the macos keybinding of <option+2> to give me `@`, unfortunately when I reload keyd I always get `"` instead. This is the same with a few of the other symbols as well, it registers a totally different symbol instead.

Am I doing something wrong here?

Also, I'm using the Swedish keyboard layout, I'm not sure if that's the main issue or not.

**Comment by nsbgn** [comment]
> Also, I'm using the Swedish keyboard layout, I'm not sure if that's the main issue or not.

It probably is! The names that `keyd` gives to keycodes correspond to their names if you use a US layout.  A further point of confusion may be that `@` is just a shortcut for `S-2` (since that's how you get a `@` on the US keyboard). To figure out what the names are in your layout, use `keyd monitor` and press the key you're trying to use (and sprinkle modifiers to taste). In this case, I think `G-2` would get you `@` in Swedish layouts?

The names should probably be made layout-dependent, since there seems to be a lot of confusion around this.

**Comment by jaygal0** [comment]
Thank you so much for the advice! 

`G-2` was the correct keybinding that got me `@`, plus I was able to guess the other symbols that I needed (e.g. {[]} and etc...).

Unfortunately, `keyd monitor` didn't really provide any insight as I'm trying to find the naming for `~`. Whenever I type it in while I'm monitoring I just get `XXXXXXXX 045e:07a5       ] up`. It doesn't really give me any indication what to add in my config file. 

Do you happen to know what I should do?

One last thing, on MacOS in order to type `{` you would enter `Shift+Option+8`, I noticed on keyd to get the character I would need to enter `G-7`. I would love to be able to hold `Shift+Meta+8` to get the same effect. Do you happen to know what I need to write in my config file?

**Comment by nsbgn** [comment]
For the first, my guess would be `G-[` (ie. AlgtGr plus the key which in US layouts is bracketopen)?

For the second:

```
[shift+meta]
8 = G-7
```

**Comment by jaygal0** [comment]
Thank you so much for your help!

Unfortunately, for some strange reason `[shift+meta]` didn't seem to work, but `[shift+control]` did. I can live with that for now and try to retrain my brain and get used to the new keybinding. 

Thanks again!

**Comment by nsbgn** [comment]
Good to hear! You can probably make the `[shift+meta]` also work in some way or another (`[shift+alt]`?) so don't hesitate to change your mind :) Cheers!

**Comment by jaygal0** [comment]
Unfortunately, I tried that and it didn't work, but thanks again for all the advice! :)

**Comment by Kochise** [comment]
> The names should probably be made layout-dependent (somehow...), since there seems to be a lot of confusion around this.

Provide support for scan codes, which isn't relying on US keyboard layout, and let us emit whatever we want out of it.

**Comment by jaygal0** [comment]
Sorry I don't quite understand. What is it that you exactly want me to provide?
