### ISSUE TITLE
Clarification in examples/capslock-esc-basic.conf

### ISSUE THREAD

**Issue by sanjayrao77** [rvaiya/keyd#641]
Thank you for this wonderful tool. I have it working great on my RPI4 and I expect to use it on all of my desktops.

When first configuring keyd, I looked at examples/capslock-esc-basic.conf and followed the instructions there. I was quickly confused.
Maybe that wasn't the intent of that file, but the comment there suggests this is a reasonable approach. I suspect either
this isn't meant to be read in isolation or it's an example for a previous version. I think clarifying the instruction there would help
some new users.

As an aside, examples/meta-esc.conf is also incomplete as a conf file but it doesn't have the same instructions in it.

Thanks again!

**Comment by rvaiya** [comment]
Thanks, I've updated the examples accordingly :).
