### ISSUE TITLE
Add support for pen tablet buttons

### ISSUE THREAD

**Issue by AesaraB** [rvaiya/keyd#647]
When using ``keyd monitor`` to find inputs for my drawing tablet, I get  ``ERROR: unsupported evdev code``.

I saw a mention of ``BTN_0`` in #441.
Related issues are #428, and #495.

Some of these keys don't exist on my device. Using evtest I can see keypresses of BTN_0 through to BTN_9, and BTN_SOUTH & BTN_EAST, but these are unsupported in keyd.

```
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 256 (BTN_0)
    Event code 257 (BTN_1)
    Event code 258 (BTN_2)
    Event code 259 (BTN_3)
    Event code 260 (BTN_4)
    Event code 261 (BTN_5)
    Event code 262 (BTN_6)
    Event code 263 (BTN_7)
    Event code 264 (BTN_8)
    Event code 265 (BTN_9)
    Event code 304 (BTN_SOUTH)
    Event code 305 (BTN_EAST)
    Event code 306 (BTN_C)
    Event code 331 (BTN_STYLUS)
  Event type 3 (EV_ABS)
    Event code 0 (ABS_X)
      Value      0
      Min        0
      Max        1
    Event code 1 (ABS_Y)
      Value      0
      Min        0
      Max        1
  Event type 4 (EV_MSC)
    Event code 4 (MSC_SCAN)
```

**Comment by AesaraB** [comment]
A bit tangential, and though I don't write C, this stack of else if statements in ``device.c`` does seem to yearn to become a switch statement.

```
		if (ev.code >= 256) {
			if (ev.code == BTN_LEFT)
				ev.code = KEYD_LEFT_MOUSE;
			else if (ev.code == BTN_MIDDLE)
				ev.code = KEYD_MIDDLE_MOUSE;
			else if (ev.code == BTN_RIGHT)
				ev.code = KEYD_RIGHT_MOUSE;
			else if (ev.code == BTN_SIDE)
				ev.code = KEYD_MOUSE_1;
			else if (ev.code == BTN_EXTRA)
				ev.code = KEYD_MOUSE_2;
			else if (ev.code == BTN_BACK)
				ev.code = KEYD_MOUSE_BACK;
			else if (ev.code == BTN_FORWARD)
				ev.code = KEYD_MOUSE_FORWARD;
			else if (ev.code == KEY_FN)
				ev.code = KEYD_FN;
			else if (ev.code == KEY_ZOOM)
				ev.code = KEYD_ZOOM;
			else if (ev.code == KEY_VOICECOMMAND)
				ev.code = KEYD_VOICECOMMAND;
			else if (ev.code >= BTN_DIGI
				 && ev.code <= BTN_TOOL_QUADTAP);
			else {
				keyd_log("r{ERROR:} unsupported evdev code: 0x%x\n", ev.code);
				return NULL;
			}
		}
```

**Comment by rvaiya** [comment]
Sorry for the belated response, and thanks for filing this. At the moment this is a bit tricky to support properly since the internal keymap is full. The next major release (a few moths away) should hopefully remedy the issue.

> A bit tangential, and though I don't write C, this stack of else if statements in device.c does seem to yearn to become a switch statement.

Indeed, but then the last else if clause would need to be a conditional in the `default:` clause anyway, since C can't match on arbitrary conditions.

I'm closing this for now, but will revisit it as I work on the next version.

**Comment by AesaraB** [comment]
Hi, thanks for your work on this.

If this issue needs to be revisited, there was recently a change in DIGImend (which will eventually be merged into the kernel) about increasing the maximum no. of drawing tablet buttons and implementing touch strips.

You can find a complete libinput recording of the new behaviour [here](https://github.com/DIGImend/digimend-kernel-drivers/pull/683#issuecomment-2072096720)
