### ISSUE TITLE
Error in keyd-application-mapper script.

### ISSUE THREAD

**Issue by yzhou216** [rvaiya/keyd#649]
```
/usr/bin/keyd-application-mapper:465: SyntaxWarning: invalid escape sequence '\W'
  return re.sub('[\W_]+', '-', s).strip('-').lower()
ERROR: could not find app.conf, make sure it is in ~/.config/keyd/app.conf
```

The error occurs when running the `keyd-application-mapper` script. The configuration is also at the correct location at: `~/.config/keyd/app.conf`.

**Comment by Cash-coder** [comment]
Same here, maybe this extra data helps
Using Fedora 39 and GNOME 45.3 and Hyprland as Window manager

during installation I had this prompt:

`make & sudo make install
[1] 5282
mkdir bin
         cp scripts/keyd-application-mapper bin/
                                                sed -e 's#@PREFIX@#/usr/local#' keyd.service.in > keyd.service
                                                                                                              cc -DVERSION=\"v2.4.3\ \(ccd17ad\)\" -I/usr/local/include -L/usr/local/lib -Wall -Wextra -Wno-unused -std=c11 -DSOCKET_PATH=\"/var/run/keyd.socket\" -DCONFIG_DIR=\"/etc/keyd\" -DDATA_DIR=\"/usr/local/share/keyd\" -D_FORTIFY_SOURCE=2 -D_DEFAULT_SOURCE -Werror=format-security  -O3  src/*.c src/vkbd/uinput.c -lpthread -o bin/keyd 
                                                                               mkdir -p /etc/keyd
mkdir -p /usr/local/bin/
mkdir -p /usr/local/share/keyd/
mkdir -p /usr/local/share/keyd/layouts/
mkdir -p /usr/local/share/man/man1/
mkdir -p /usr/local/share/doc/keyd/
mkdir -p /usr/local/share/doc/keyd/examples/
groupadd keyd
install -m755 bin/* /usr/local/bin/
install -m644 docs/*.md /usr/local/share/doc/keyd/
install -m644 examples/* /usr/local/share/doc/keyd/examples/
install -m644 layouts/* /usr/local/share/keyd/layouts
src/daemon.c: In function ‘add_listener’:
                                         src/daemon.c:84:33: warning: ignoring return value of ‘write’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
                                                84 |                                 write(con, layer->type == LT_LAYOUT ? "/" : "+", 1);
                       |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                                            src/daemon.c:85:33: warning: ignoring return value of ‘write’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
                                                                                                                   85 |                                 write(con, layer->name, strlen(layer->name));
                                                                                   |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                         src/daemon.c:86:33: warning: ignoring return value of ‘write’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
                                                86 |                                 write(con, "\n", 1);
                                                                                                               |                                 ^~~~~~~~~~~~~~~~~~~
                                            install -m644 data/*.1.gz /usr/local/share/man/man1/`

**Comment by rvaiya** [comment]
Gnome 45 broke older extensions. The latest commit should have support for it, though you will need to follow the instructions produced by `keyd-application-mapper` and install the new extension.

**Comment by dantearaujo1** [comment]
i have this problem too in archlinux using hyprland.

**Comment by rickalex21** [comment]
I'm getting the same issue, maybe an r needs to be added to it? `r'[\W_]+'`

**Comment by derelbenkoenig** [comment]
I noticed that this has been fixed, but the version from the arch linux repository appears not to have the fix yet
