### ISSUE TITLE
Help: is it possible to set an "all others" rule?  Trying to customize dead keys

### ISSUE THREAD

**Issue by cosme-benito** [rvaiya/keyd#651]
I've been using `keyd` to "fix" my dead keys on wayland electron apps and it has been working great. In portuguese the only keys with accents are vowels and cedilla (ç). I'm trying to make so that dead keys ignore all non-vowel or c keys.

Example: `'` followed by `t` would produce `'t` instead of absolutely nothing.

This is my current configuration:

```
[ids]
*

[main]
' = oneshotm(apostrophe, ')

[apostrophe]
a = a
b = macro(space backspace apostrophe space b)
c = macro(backspace G-,)
d = macro(space backspace apostrophe space d)
e = e
f = macro(space backspace apostrophe space f)
g = macro(space backspace apostrophe space g)
h = macro(space backspace apostrophe space h)
i = i
j = macro(space backspace apostrophe space j)
k = macro(space backspace apostrophe space k)
l = macro(space backspace apostrophe space l)
m = macro(space backspace apostrophe space m)
n = macro(space backspace apostrophe space n)
o = o
p = macro(space backspace apostrophe space p)
q = macro(space backspace apostrophe space q)
r = macro(space backspace apostrophe space r)
s = macro(space backspace apostrophe space s)
t = macro(space backspace apostrophe space t)
u = u
v = macro(space backspace apostrophe space v)
w = macro(space backspace apostrophe space w)
x = macro(space backspace apostrophe space x)
y = macro(space backspace apostrophe space y)
z = macro(space backspace apostrophe space z)
```

This works perfectly but it's very verbose and certainly incomplete. I was wondering if I could do something like

```
[ids]
*

[main]
' = oneshotm(apostrophe, ')

[apostrophe]
a = a
c = macro(backspace G-,)
e = e
i = i
o = o
u = u

# The syntax below is my wishlist, not an actual example
* = macro(space backspace apostrophe space KEY_PRESSED_HERE)
```

This would be way easier to maintain and read. Is such a thing possible? Thanks!

**Comment by rvaiya** [comment]
This is not currently possible, but I have considered adding something like this before. It might make it into the next major version. 

What you want to achieve in this particular instance I believe you can eliminate a lot of the redundant mappings by doing the inverse of what you have done. 

Something like:
```
[main]
' = oneshotm(apostrophe, macro(' space))

[apostrophe]
a = macro(backspace ' a)
e = macro(backspace ' e)
#etc..
```

**Comment by cosme-benito** [comment]
Thank you very much for spending your time helping me. Your solution is exactly what I was looking to do, it's perfect. I only had to replace `macro(backspace ' a )` with `macro(backspace G-a)`, it was causing me problems with uppercase `Á`. 

My final `/etc/keyd/default.conf`:

```
[ids]
*

[main]
' = oneshotm(apostrophe, macro(' space))

[apostrophe]
c = macro(backspace G-,)
a = macro(backspace G-a)
e = macro(backspace G-e)
i = macro(backspace G-i)
o = macro(backspace G-o)
u = macro(backspace G-u)
space = macro(space backspace)
```
