### ISSUE TITLE
switching to default layout

### ISSUE THREAD

**Issue by Pinoinha** [rvaiya/keyd#652]
hello,

I've just switched to keyd from kmonad, and while I was able to migrate everything from my kmonad setup quite easily, there's a feature I haven't been able to wrap my head around quite so

basically, in my kmonad setup I have a default layer with the dvorak layout, but when playing games I switch to a default qwerty layer to have the WASD keys and whatnot where the game expects them to be

I have a US keyboard, and the dvorak layout works perfectly, but I still haven't figured out how to do the same "layout switching" on keyd yet. my initial thoughts were something in the lines of (using the esc key to switch between layouts):
```ini
include layouts/dvorak

[dvorak]
esc = setlayout(us)
```
but then I found out that the default us layout doesn't exist as a file, and as such cannot be toggled to. I then tried
```ini
include layouts/dvorak

[dvorak]
esc = layer(main)

...

[main]
esc = setlayout(dvorak)
```
but also found out that one can't toggle to the main layer.

ultimately, I tried
```ini
include layouts/dvorak

[dvorak]
esc = layer(qwerty)

...

[qwerty]
esc = setlayout(dvorak)
```
but, once again, this doesn't work as I expected it to. the qwerty layer seems to "inherit" everything from the dvorak layout

how could I go about my intended behavior?

thanks in advance!

**Comment by toftul** [comment]
Probably, somewhat connected. How to make several layouts including international? Say something like:
- colemak/dvorak
- qwerty
- russian

**Comment by mhantsch** [comment]
I have a similiar use case. I did not use setlayout(). I just defined the layout (colemak) I want to switch to and from, and use a+s+d+f (pressed simultaneously) to toggle between them. Here's part of my keyd config:

```
# press asdf together = switch to Colemak
a+s+d+f = toggle(colemak)

[colemak]
# definition of Colemak layout
# US-qwerty keypress => produced Colemak character
q = q
w = w
e = f
r = p
t = g
y = j
u = l
i = u
o = y
p = ;
a = a
s = r
d = s
f = t
g = d
h = h
j = n
k = e
l = i
; = o
z = z
x = x
c = c
v = v
b = b
n = k
m = m

# press asdf together = switch back from Colemak
a+s+d+f = toggle(colemak)
```

**Comment by rvaiya** [comment]
This should probably be considered a bug. I will probably add something like `setlayout(default)` or `clearlayout()` shortly.

The way to achieve this presently would just be to switch to some identity layout (i.e qwerty). 

Something like:

```
a = a
b = b
# etc...
```

I don't believe keyd currently ships with such a layout, so you will have to define it yourself.

**Comment by rvaiya** [comment]
In the latest commit you can do `setlayout(main)`.
