### ISSUE TITLE
Composite layer not working with shift

### ISSUE THREAD

**Issue by Pinoinha** [rvaiya/keyd#656]
probably just a misuse by my part, but couldn't find any issue which tackled the exact problem (#464 comes close tho)

as I use a br-abnt2 layout in my laptop, there's a lot of diacritics. following advice from other issues, I managed to setup a working configuration for acute (`) and tilde (~) diacritics, as following:
```ini
include layouts/br

[br]

[ = oneshot(agudo)
' = oneshot(til)

...

[agudo]
[ = ´
a = á
e = é
i = í
o = ó
u = ú

[til]
' = ~
a = ã
o = õ
```
since the br-abnt2 layout turns shift+´ into ` and shift+~ into ^, I tried reproducing this behavior with composite layers:
```ini
[agudo+shift]
[ = `
a = à
e = è

[til+shift]
' = ^
a = â
e = ê
o = ô
```
however, this unexpectedly does not work. weirdly enough, I'm able to write the diacritics themselves (shift+´ twice produces `, shift+~ produces ^), but not the letters (what should be â comes out as ã, à comes out as á, etc.)

any tips on what I'm missing here?

thanks in advance!

**Comment by rvaiya** [comment]
The layout file you've included redefines `shift` to `layer(br_shift)`, so you want your corresponding layers to be  `til+br_shift` and `agudo+br_shift`. The default `shift` layer is deliberately not overwritten so the user can switch back to the default layout.

**Comment by Pinoinha** [comment]
> The layout file you've included redefines `shift` to `layer(br_shift)`, so you want your corresponding layers to be `til+br_shift` and `agudo+br_shift`. The default `shift` layer is deliberately not overwritten so the user can dynamically switch back to the default layout.

it works, thank you! but on a similar note, now since shift+layer emits the lowercase letter with the diacritic, I'm unable to type such letters in uppercase

what I expect is:
`´ + a = á`
`´ + shift + A (as in typing the uppercase A letter) = Á`
but with the current solution this is not achievable, since `´ + shift + a` enters the `br_shift+agudo` layer and as such emits `à`.

what I'm thinking is maybe a combination of oneshot layers, but just wanted to know if there's another means of achieving this

**Comment by rvaiya** [comment]
> what I expect is:
> ´ + a = á
> ´ + shift + A (as in typing the uppercase A letter) = Á
> but with the current solution this is not achievable, since ´ + shift + a enters the br_shift+agudo layer and as such emits à.

Can you clarify what you are trying to achieve? I assume by `´` you mean the key physically labeled `´` on a Brazilian keyboard, which you've mapped using `[` to activate `agudo`.

You currently have:

```
[agudo+br_shift]
a = à
```

so naturally `´`+`shift`+`a` produces `à`. If you want to change this, simply change `à` to `Á`.

**Comment by Pinoinha** [comment]
I finally got it!

after your comment I noticed I was going about this the wrong way. just to clarify my rationale, in br-abnt2 keyboards the `´` and ``` diacritics are positioned on the same key, and the way you go about using one or the other is through the shift key. more specifically:
`´ then a = á`
`shift + ` then a = à`

that I was able to reproduce with the snippets above. however, what I was **not** able to reproduce was the following behavior:
`´ then shift + a = Á`
`shift + ´ then shift + a = À`

that's because through the config above `shift + ´ then shift + a` toggled the `br_shift+agudo` layer, and as such `à` was emitted.

what solved my needs was the following:
```config
[br]
[ = oneshot(agudo)
' = oneshot(til)

...

[shift]
[ = oneshot(grave)
' = oneshot(circunflexo)
...

[agudo]
[ = ´ # this is standard for abnt2 layout
space = ´ # same
a = á
e = é
i = í
o = ó
u = ú

[shift+agudo]
a = Á
e = É
i = Í
o = Ó
u = Ú

[grave]
[ = `
space = `
a = à
e = è

[shift+grave]
a = À
e = È
```

the same behavior was replicated for the `til` and `circunflexo` layers (in abnt2 `~` and `^` are also on the same key) and it now works perfectly!
