### ISSUE TITLE
Remap a multi-modifier combo per-application

### ISSUE THREAD

**Issue by murtaza64** [rvaiya/keyd#660]
I want to map meta-l to ctrl-l in firefox, but leave meta-shift-l as meta-shift-l. I tried the following in `app.conf`:

```
[firefox]

meta.l = C-l
meta+shift.l = M-S-l
shift+meta.l = M-S-l
meta.shift.l = M-S-l
shift.meta.l = M-S-l
```

but none of them seem to work. It seems like combining two layers with + isn't a valid input to `bind`?

**Comment by auditiontheftcure** [comment]
Seems like it works if you predefine composite layers in keyd's main config:

`/etc/keyd/default.conf`
```
[ids]
*

[meta+shift]
```

Then `keyd bind 'meta+shift.l = M-S-l'` succeeds.

**Comment by murtaza64** [comment]
Thanks! looking forward to trying this out
