### ISSUE TITLE
Allow defining mappings per application without impacting global mappings/shortcuts

### ISSUE THREAD

**Issue by mburz** [rvaiya/keyd#663]
Let's take Firefox as an application.
I would like to be able to define a mapping for F2 for it similar to:
```
[firefox]
f2 = right
```
But without having this mapping impact all key combinations using F2 with modifiers.

Currently, with the above mapping, pressing F2 in Firefox results in ArrowRight being sent. This is as expected.
If on the other hand, I press Alt+F2 while Firefox is focused, Alt+ArrowRight is being sent. I'm looking for Alt+F2 being sent.

Especially when it comes to F-keys, it would be very useful to be able to define per application mappings for them, that won't interfere with global mappings/shortcuts containing the same F-keys.

**Comment by rvaiya** [comment]
You can do:

```
[firefox]
f2 = right
alt.f2 = A-f2
meta.f2 = M-f2
control.f2 = C-f2
shift.f2 = S-f2
```

**Comment by mburz** [comment]
It's what I indeed do, as a workaround. It is working fine.

The overhead and annoyances it caused me over the past ~1.5 years moved me to write this issue in the hope that you can implement a new feature to address this shortcoming.

There's nothing that could beat allowing to remap a single keyboard shortcut to a single action per application, with the guarantee that nothing else gets changed.

Would really appreciate if you could implement this feature. Thank you!

**Comment by rvaiya** [comment]
It's what I indeed do, as a workaround. It is working fine.

> The overhead and annoyances it caused me over the past ~1.5 years moved me to write this issue in the hope that you can implement a new feature to address this shortcoming.

Aside from the minor annoyance of having to remap modifiers for each key, do you have any other issues with the approach?

> There's nothing that could beat allowing to remap a single keyboard shortcut to a single action per application, with the guarantee that nothing else gets changed.

Making this the default behaviour would produce the opposite problem for the (far more common) case in which the user expects the remapped key to be compatible with modifiers. In the odd case where you actually want different behaviour when a key is used in combination with a modifiers, it seems reasonable to require the user to explicitly define this.

**Comment by mburz** [comment]
> Aside from the minor annoyance of having to remap modifiers for each key, do you have any other issues with the approach?

It's about keeping track and thinking about this issue every time I change things that could impact global shortcuts.



> Making this the default behaviour would produce the opposite problem for the (far more common) case in which the user expects the remapped key to be compatible with modifiers. In the odd case where you actually want different behaviour when a key is used in combination with a modifiers, it seems reasonable to require the user to explicitly define this.

Not asking for changing the default behavior, that would be way too big a change that literally break everything in place nowadays. TO do that would be a mistake imho.

You could add a new construct to allow for this behavior to be specified explicitly, e.g.
f2 = direct(...)
f2 = simple(...)

**Comment by rvaiya** [comment]
I think this is a bit too niche to warrant a dedicated feature, but I will consider it for the next major release. I am closing this issue for now since I am trying to slim down the set of active issues.
