### ISSUE TITLE
Documentation error capslock vs control

### ISSUE THREAD

**Issue by lobre** [rvaiya/keyd#664]
Hello,

Am I wrong saying that there is an error in the man page?

https://github.com/rvaiya/keyd/blob/dcbb68b12f71245121035b730b50872802a259b4/docs/keyd.scdoc#L180

> will  cause  capslock  to behave as control, except in the case of control+j, which will emit down.

Don’t you mean "except in the case of **capslock**+j, which will emit down"?

Same here.

https://github.com/rvaiya/keyd/blob/dcbb68b12f71245121035b730b50872802a259b4/docs/keyd.scdoc#L186

"shift+**capslock**+j will produce shift+down as expected."

**Comment by rvaiya** [comment]
Indeed. Thanks for catching this. For documentation issues, you can just submit a PR. I've fixed in the latest commit.
