### ISSUE TITLE
Layer toggle behind layer hold

### ISSUE THREAD

**Issue by lobre** [rvaiya/keyd#665]
I am having a hard time trying to accomplish the following.

I have the `[main]` layer. On this layer, I do have a layer-hold on `space` which leads me to a `[headside]` layer. To note that on `[main]`, I also have `tab` which does not have any mapping assigned, so it regularly inputs a `tab` character.

On `[headside]` (while keeping `space` maintained), I would then like to have the `tab` key toggling back and forth **on tap** (and not hold) between another layer `[tailside]` and this `[headside]`.

And so if at any moment I decide to release `space`, I should go back to `[main]` whatever if `[headside]` or `[tailside]` was active.

As an example:
1. From `[main]` I hold `space`,
2. Landed on `[headside]`, I type some keys that are mapped on this layer,
3. I single tap `tab` (while keeping `space` held) which activates `[tailside]`,
4. I type some keys that are mapped on `[tailside]`,
5. I single tap `tab` (while still keeping `space` held), which re-toggles `[headside]`,
6. _... <loop from 3 to 5 as long as needed>_
7. I decide to go back to `[main]` by releasing `space`.

Do you think such a behavior (mix of hold and tap) is achievable in keyd? Help would be greatly appreciated, and heads up for this awesome project!

**Comment by nsbgn** [comment]
The following sort-of achieves what you want:

```
[main]
space = overload(headside, space)

[headside]
tab = swap(tailside)
a = b

[tailside]
tab = swap(headside)
b = c
```

However, since `space` is a tricky key to overload, you probably want at least `space = overloadt(headside, space, 200)` or `lettermod(headside, space, 100, 200)` instead of plain `overload`. Unfortunately, `swap` doesn't seem to work with any of these. @rvaiya, that would be a bug, right?

**Comment by lobre** [comment]
Thank you, at first sight, I confirm that this behavior does what I expect.

But I notice the same bug as you. It is fine with `overload`, but not with `overloadt` :neutral_face:

**Comment by lobre** [comment]
I read the code a little bit yesterday, and I have the feeling that `overloadt` (and `overloadt2`) should have theoretically the same behavior as `overload`, apart from the timeout. Am I guessing right @rvaiya?

I could not yet identify where the bug is. I need to dig more but as I am not familiar with the codebase, it is hard for me to catch it for the moment.

**Comment by matcls** [comment]
changing [this line](https://github.com/rvaiya/keyd/blob/459cb1fff1d863edd48a2713d07b43d87fd4a182/src/keyboard.c#L758) 
from
`for (i = 0; i < CACHE_SIZE; i++)`
to
`for (i < 0; i <= CACHE_SIZE; i++)`

makes swap work here.

**Comment by lobre** [comment]
@matcls , you mean this instead no?

```
 for (i = 0; i <= CACHE_SIZE; i++)
```

If so, do you understand why looping one step further is necessary? I am not sure to exactly grasp what is the purpose of this cache.

**Comment by rvaiya** [comment]
Sorry for the slow response, I haven't had much time to triage issues lately. This was indeed a bug and should be fixed in the latest commit.

**Comment by lobre** [comment]
No worries, open source does not need reactivity! Thank you a lot for fixing the bug.

I just tested with the commit you introduced, and it effectively resolves my issue :partying_face:.

I am closing this issue.
