### ISSUE TITLE
Unable to start keyd-application-mapper

### ISSUE THREAD

**Issue by SandeshGowda-0094** [rvaiya/keyd#666]
I have followed the documentation and tried several troubleshooting steps to resolve the issue, including:
- verified the configuration in the `app.conf` file for multiple applications.
```conf
[librewolf-default]
ctrl.] = C-tab
ctrl.[ = C-S-tab

[brave-browser]
ctrl.] = C-tab
ctrl.[ = C-S-tab

[Alacritty]
ctrl.] = C-tab
ctrl.[ = C-S-tab
````
- Restarting the keyd-application-mapper with debug mode (`-d` flag).
```shell
keyd-application-mapper -d
```

- Using `xprop` to confirm the window class names.
-Checking for logs in `~/.config/keyd/app.log` file
- Checking for logs using `journalctl -u keyd-application-mapper`.

Despite these efforts, the key remappings are still not working as expected for any of the applications.

I have exhausted all available troubleshooting steps and have not been able to resolve the issue. Any assistance or guidance on resolving this issue would be greatly appreciated.

**Comment by rvaiya** [comment]
`ctrl` should be `control` if you are using the default layers. You can try using the `-v` flag to debug and discover window names.

**Comment by SandeshGowda-0094** [comment]
Thanks a lot now the bindings are working perfectly..
you have create a great project @rvaiya, this is one of the project which boosted my productivity by a lot ...
thanks a lot once again...
