### ISSUE TITLE
flock open: Permission denied

### ISSUE THREAD

**Issue by gb-jairo** [rvaiya/keyd#68]
I'm getting this error while trying to start the keyd service.

System: fresh Ubuntu 21.10 installation

Tested versions: 
- v1.3.0 (7ad410d)
- master (f7e1c7d)

`systemctl status keyd` output:

```
× keyd.service - key remapping daemon
     Loaded: loaded (/lib/systemd/system/keyd.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2021-12-07 21:35:23 -03; 17s ago
    Process: 28974 ExecStart=/usr/bin/keyd (code=exited, status=1/FAILURE)
   Main PID: 28974 (code=exited, status=1/FAILURE)
        CPU: 935us

 ... systemd[1]: Started key remapping daemon.
 ... keyd[28974]: flock open: Permission denied
 ... systemd[1]: keyd.service: Main process exited, code=exited, status=1/FAILURE
 ... systemd[1]: keyd.service: Failed with result 'exit-code'.
```

my config file:
```
capslock = overload(C, f13)
```

**Comment by rvaiya** [comment]
Hmm, looks like it is failing to open the lock file. Can you post the output of `ls -l /var/lock/keyd.lock`? I'm assuming you did `make && sudo make install`.

**Comment by gb-jairo** [comment]
Yes, that's the command I used to install.

Strange thing, but I reinstalled keyd (same commit from master mentioned above) and it's working now.

`ls -l /var/lock/keyd.lock`:
-rw------- 1 root root 0 dez  8 10:25 /var/lock/keyd.lock

**Comment by rvaiya** [comment]
It seems like a permissions issue, thought it shouldn't happen when running as root. Let me know if you figure out how to reproduce it.

**Comment by slakkenhuis** [comment]
Maybe helpful: I came across this message too at some point after I first installed keyd, but I figured it had something to do with permissions in such a way that it'd probably go away after a reboot/login, and I was right. Can't reproduce now.

**Comment by rvaiya** [comment]
I believe this should no longer be an issue. If anyone encounters a similar problem please open another issue.
