### ISSUE TITLE
Bug: keyd doesn't seem to handle backslash well inside overload

### ISSUE THREAD

**Issue by firtrees** [rvaiya/keyd#684]
In short, if I try binding `a = macro(\ )`, or `a = \`, all is well. But if I try the same solution while also overloading the key, for example `a = overload(shift, macro(\ ))`, then it seems to work fine, until you realise that hitting the `a` key and waiting results in a continuous stream of `\`, as though I kept the actual `\` key depressed.
Perhaps surprisingly, when I run `keyd monitor` and press the key, it says
```
keyd virtual keyboard	0fac:0ade	\ down
keyd virtual keyboard	0fac:0ade	\ up
keyd virtual keyboard	0fac:0ade	\ down
keyd virtual keyboard	0fac:0ade	\ up
keyd virtual keyboard	0fac:0ade	\ down
keyd virtual keyboard	0fac:0ade	\ up
keyd virtual keyboard	0fac:0ade	\ down
keyd virtual keyboard	0fac:0ade	\ up
keyd virtual keyboard	0fac:0ade	\ down
keyd virtual keyboard	0fac:0ade	\ up
keyd virtual keyboard	0fac:0ade	\ down
keyd virtual keyboard	0fac:0ade	\ up
keyd virtual keyboard	0fac:0ade	\ down
```
and so on, which is not the behaviour that you get when you keep a key depressed.
The behaviour doesn't seem to change when I change modifier, or key (in fact, I started out with the extra key that ISO keyboards have, but that is not the problem here).
I should also note that it's relatively easy to break this assignment, for example `a = overload(shift, \ )` doesn't work at all.

**Comment by rvaiya** [comment]
I can't replicate this. What version are you running? (`keyd -v`)

**Comment by firtrees** [comment]
The version is `keyd v2.4.3 (5e4ef41)`. 
Just to make sure: this faulty behaviour is triggered when hitting `a` once, releasing the key, and then waiting about a second without doing anything else.

**Comment by rvaiya** [comment]
I believe this has been fixed. Can you check whether or not this is still an issue on the latest commit?

**Comment by firtrees** [comment]
You are perfectly right, I'm sorry. Thank you for your help!
