### ISSUE TITLE
Latency Benchmarks

### ISSUE THREAD

**Issue by ComplexPlane** [rvaiya/keyd#688]
Have you ever, or would you consider, providing latency benchmarks? It'd be nice to know for sure that keyd doesn't add more than a handful of microseconds of typing latency in general.

**Comment by rvaiya** [comment]
You can run make test-io in the latest commit to get a sense of how much time is spent in the inner loop. It is on the order of single digit microseconds.

This does not account for any additional latency introduced by reading/writing to the kernel subsystems, which constitutes the bulk of time and is on the order of 30-40 us in my experiments (I haven't bothered to polish or publish these end to end tests). These will be hard limits for any remapping software.

The result should be under 1ms (by at least an order of magnitude), which is well below perceptual limits, even for those who are picky ;).

**Comment by ComplexPlane** [comment]
Good to hear! I'm satisfied with that
