### ISSUE TITLE
Bug: overloadt with swap as action does not swap

### ISSUE THREAD

**Issue by lobre** [rvaiya/keyd#690]
It is quite hard to explain so I will give an example to understand the bug.

The following example with `overload` works. Meaning, holding `leftalt` and then also holding `capslock` while typing another key will resolve to `control+key`. And if I hold `leftalt` and only tap `capslock`, I can swap to layer2 and type numbers using `asdf`.

```
leftalt = layer(level1)

[level1]
capslock = overload(control, swap(level2))

[level2]
a = 1
s = 2
d = 3
f = 4
capslock = clear()
```

But if I change it to `overloadt` on `layer1`, I can no longer activate `layer2`. Nothing happens on tap on `capslock`.

```
leftalt = layer(level1)

[level1]
capslock = overloadt(control, swap(level2), 500)

[level2]
a = 1
s = 2
d = 3
f = 4
capslock = clear()
```

**Comment by rvaiya** [comment]
Thanks for the clear reproduction steps. I believe this should be fixed in the latest commit.

**Comment by lobre** [comment]
Awesome, thank you. I confirm it is fixed.
