### ISSUE TITLE
keyd polls standard output, causing a spin loop

### ISSUE THREAD

**Issue by zackw** [rvaiya/keyd#696]
At least in `keyd monitor` mode (I haven't yet tried anything else), file descriptor 1 (i.e. stdout) always seems to be included in the set of file descriptors supplied to `poll()`.  This doesn't ever do anything useful AFAICT, and in many cases (e.g. when stdout is a file or /dev/null, both of which are always considered readable) it will cause keyd to spin calling poll() over and over again, pegging the CPU and, for battery-powered devices, draining the battery.

A relevant excerpt of the output of `strace -ttt -t keyd monitor > keycodes`:

```
2713  1710702150.380721 write(1, "device added: 0002:000e ETPS/2 E"..., 70) = 70
2713  1710702150.380806 write(1, "device added: 0001:0001 AT Trans"..., 73) = 73
2713  1710702150.380890 poll([{fd=3, events=POLLIN}, {fd=6, events=POLLIN|POLLERR}, {fd=5, events=POLLIN|POLLERR}, {fd=1, events=POLLIN|POLLERR}], 4, -1) = 1 ([{fd=1, revents=POLLIN}])
2713  1710702150.380971 poll([{fd=3, events=POLLIN}, {fd=6, events=POLLIN|POLLERR}, {fd=5, events=POLLIN|POLLERR}, {fd=1, events=POLLIN|POLLERR}], 4, -1) = 1 ([{fd=1, revents=POLLIN}])
2713  1710702150.381047 poll([{fd=3, events=POLLIN}, {fd=6, events=POLLIN|POLLERR}, {fd=5, events=POLLIN|POLLERR}, {fd=1, events=POLLIN|POLLERR}], 4, -1) = 1 ([{fd=1, revents=POLLIN}])
... 570 more repeats skipped ...
2713  1710702150.402360 poll([{fd=3, events=POLLIN}, {fd=6, events=POLLIN|POLLERR}, {fd=5, events=POLLIN|POLLERR}, {fd=1, events=POLLIN|POLLERR}], 4, -1) = 2 ([{fd=5, revents=POLLIN}, {fd=1, revents=POLLIN}])
2713  1710702150.402485 read(5, "F>\367e\0\0\0\0\305#\6\0\0\0\0\0\4\0\4\0\34\0\0\0", 24) = 24
2713  1710702150.402655 poll([{fd=3, events=POLLIN}, {fd=6, events=POLLIN|POLLERR}, {fd=5, events=POLLIN|POLLERR}, {fd=1, events=POLLIN|POLLERR}], 4, -1) = 2 ([{fd=5, revents=POLLIN}, {fd=1, revents=POLLIN}])
2713  1710702150.402829 read(5, "F>\367e\0\0\0\0\305#\6\0\0\0\0\0\1\0\34\0\0\0\0\0", 24) = 24
2713  1710702150.402914 write(1, "AT Translated Set 2 keyboard\t000"..., 48) = 48
2713  1710702150.402948 read(5, "F>\367e\0\0\0\0\305#\6\0\0\0\0\0\0\0\0\0\0\0\0\0", 24) = 24
2713  1710702150.402978 poll([{fd=3, events=POLLIN}, {fd=6, events=POLLIN|POLLERR}, {fd=5, events=POLLIN|POLLERR}, {fd=1, events=POLLIN|POLLERR}], 4, -1) = 1 ([{fd=1, revents=POLLIN}])
2713  1710702150.403012 poll([{fd=3, events=POLLIN}, {fd=6, events=POLLIN|POLLERR}, {fd=5, events=POLLIN|POLLERR}, {fd=1, events=POLLIN|POLLERR}], 4, -1) = 1 ([{fd=1, revents=POLLIN}])
2713  1710702150.403044 poll([{fd=3, events=POLLIN}, {fd=6, events=POLLIN|POLLERR}, {fd=5, events=POLLIN|POLLERR}, {fd=1, events=POLLIN|POLLERR}], 4, -1) = 1 ([{fd=1, revents=POLLIN}])
... back to the spin loop ...
```

**Comment by zackw** [comment]
Looks like this is intentional, due to https://github.com/rvaiya/keyd/blob/4370049b3c0eafb2da9c3a5c7fad9721d8c7cdb3/src/monitor.c#L96-L98:

```
        /* Eagerly terminate on pipe closures. */
        if (!isatty(1))
                evloop_add_fd(1);
```

The problem with this is that it's totally normal to want to redirect the output of `keyd monitor` to a file, but _files are always considered to be readable_ (and writable) by `poll()`, and so `poll` will never block if there's a file in the poll set. Looking at the rest of the code, I think what you actually want to be doing is setting `SIGPIPE` to be ignored, and then, in `_keyd_log`, exiting cleanly if vprintf errors out.  I may try to put a patch together in the next week or so.

**Comment by rvaiya** [comment]
> This doesn't ever do anything useful AFAICT

This is by design. `keyd monitor` terminates once the consuming process has terminated, which is quite
useful for scripts.

> when stdout is a file or /dev/null, both of which are always considered readable [...] will cause keyd to spin calling poll()

Thanks, this was an oversight. The latest commit should fix the issue.

> I think what you actually want to be doing is setting  SIGPIPE  to be ignored, and then, in  _keyd_log , exiting cleanly if vprintf errors out.

The problem with this is that it does not immediately cause keyd to exit until it attempts to output another line. Eager termination is quite useful, as it allows the user to do things like this: `keyd monitor | awk '/esc down/ { exit }'`. So polling stdout is indeed desirable in this case.

**Comment by zackw** [comment]
Change 8be57cd works in my testing and I believe the new condition is logically correct (accounts for all the cases where you _want_ to listen for stdout events). Thanks for the quick fix.

> The problem with this is that it does not immediately cause keyd to exit until it attempts to output another line

Oh, good point. In that case, long term it might make sense to augment evloop_add_fd to also let you set the poll bits, so that you can listen for POLLERR without also listening for POLLIN. That would also have corrected the problem, and I feel like it would be a nice bit of extra defensiveness.
