### ISSUE TITLE
Is there a way to distinguish multiple keys with the same code?

### ISSUE THREAD

**Issue by tukusejssirs** [rvaiya/keyd#701]
I have Lenovo ThinkPad P15 Gen 1 and there is the following keyboard built-in (I have an ISO layout, however, it does not matter in this case).

![](https://i.ebayimg.com/images/g/DesAAOSwvqJkA884/s-l1200.webp)

Note the four keys (`=`, `(`, `)`, `Backspace`) above the NumPad. I have never ever used them, therefore I’d like to remap them.

However, the issue is that `keyd monitor` returns the same code as if I have pressed their alpha-numeric counterpart:

- `=`;
- `leftshift` + `9`;
- `leftshift` + `0`;
- `backspace`.

Is there a way to distinguish these keys? I presume no because the keyboard sends the key code, and no location, but I hope to get a different answer. :wink:

Thanks for creating such a usefull program and your help! :pray:

**Comment by nsbgn** [comment]
>I presume no because the keyboard sends the key code, and no location

Yeah, if there is no data sent to distinguish them, unfortunately, there's no way. I do see a FnLock key that presumably changes the code that will be sent for the `=` and `backspace` keys --- you could remap those (but of course that has side effects :P)

**Comment by rvaiya** [comment]
You might be able to abuse the chording functionality to remap `(` and `)`. 

Something like this:

```
leftshift+9 = a
leftshift+0 = b
```

The others are indistinguishable from their non num pad counterparts.
