### ISSUE TITLE
application mapper doesn't work

### ISSUE THREAD

**Issue by anasouardini** [rvaiya/keyd#702]
I know this is an experimental feature, but can I get a hint on how to debug this?

## here is the output of the command
```bash
╭─ venego@i5:~
╰─> -_- % keyd-application-mapper
X detected
Traceback (most recent call last):
  File "/usr/local/bin/keyd-application-mapper", line 439, in <module>
    mon.init()
  File "/usr/local/bin/keyd-application-mapper", line 200, in init
    import Xlib
ModuleNotFoundError: No module named 'Xlib'
```

## here is the config file
```bash
[alacritty]

alt.] = macro(C-g n)
alt.[ = macro(C-g p)
```

This might be an XY problem, so here is what I'm trying to achieve: I have this post-installation script that sets up `keyd`, and I wish I could just add a config file `.config/keyd/default.conf` to my dotfiles repository and just clone it without worrying about copy over to `/etc/keyd`.

Thanks for consideration.

**Comment by anmolmathias** [comment]
You're missing Xlib. Try installing  python-xlib from your package manager.

**Comment by anasouardini** [comment]
I think I already have that module:
![image](https://github.com/rvaiya/keyd/assets/114059811/f6cd4b22-a4d5-4c86-9e47-322888660194)

Also I did install `libx11-dev` but I still the same error!

**Comment by rvaiya** [comment]
You need the python xlib bindings. The name of the package may vary depending on your package manager. Closing, since this is not a keyd issue.
