### ISSUE TITLE
Application specific remapping doesn't work on GNOME 46

### ISSUE THREAD

**Issue by anmolmathias** [rvaiya/keyd#707]
Rebuilt from source, removed extension checks, edited required DE version in the manifest but no effect. Can anyone confirm and suggest a fix?

**Comment by rvaiya** [comment]
Adding 46 to the gnome extension manifest should work, I can't reproduce this. Can you confirm that this is still an issue using the latest commit? If so, please report any errors issued by gnome, and report the colour of the toggle when trying to enable the extension in gnome settings.

**Comment by anmolmathias** [comment]
Can confirm it doesn't work for me on 46. But it might have something to do with the install being on Fedora 40. The toggle returns an ok-blue. If you can help me figure out how to get some logs out of it, that'd be great

**Comment by anmolmathias** [comment]
Works on Ubuntu with 46 so I guess it's something to do with the updated python packages. Closing.
