### ISSUE TITLE
macro with shifted keys

### ISSUE THREAD

**Issue by darkcruix2** [rvaiya/keyd#708]
when I have a macro that e.g. shall contain a email address like john@doe.com, I have to shift 2 to produce the @ sign.
Example:
x = macro(john S-2 doe dot com)
this produces: john2doe.com instead. But when I have the @ in the beginning and as only character it works, like:
x = macro(S-2)
this produces: @

Is there a way to hand down character codes or similar that allows this?

**Comment by al-ce** [comment]
The first macro you provided works fine for me and produces `john@doe.com`, on different keyboards across different computers (Arch Linux, keyd `v2.4.3`). Do you have any settings in your `[global]` section that might be impeding this, like `macro_sequence_timeout`, or might adding/changing that setting solve this? Also, what about experimenting with adding timeouts, like  `x = macro(john 100ms S-2 100ms doe dot com)` ?

**Comment by darkcruix2** [comment]
I am using Debian 12. I only have a /etc/keyd/default.conf that looks like this:
```
[ids]
*

[main]
x = macro(john S-2 doe dot com)
y = macro(S-2)
z = macro(john 100ms S-2 100ms doe dot com)
```

The output is very strange. On the terminal and other Gnome apps I have john2doe.com as output
but here on the browser it is john@doe.com (x and z). The @ sign always works when standing there alone - even the gnome-terminal etc.
When I test it outside the Gnome Shell (pure textmode terminal) it also works. I assume there is something in Gnome that does something unusual....

**Comment by rvaiya** [comment]
> In the gnome-terminal and other Gnome apps I get john2doe.com as output, but here on the browser it is [john@doe.com](mailto:john@doe.com) (x and z).

Sounds like a timing bug. IIRC some gnome stuff has weird input loop bugs. You can try manually accounting for it by adding a timeout between shift and 2 like so:

```
z = macro(john 100ms leftshift+100ms+2 100ms doe dot com)
```

adjust the timeouts to taste.
