### ISSUE TITLE
Bug with overloadi and timeout together

### ISSUE THREAD

**Issue by lobre** [rvaiya/keyd#710]
This bug is strange, I struggle to create a smaller example where the bug arises. So let me show you the smallest I have for now.

My assertion for the example is that holding `2` should send `meta+2`.

It works with this first example:

```
[ids]
*

[main]
[ = timeout(backspace, 150, C-backspace)

102nd = timeout(z, 300, M-z)
z = timeout(x, 300, M-x)
x = timeout(c, 300, M-c)
c = timeout(v, 300, M-v)
v = timeout(b, 300, M-b)

a = timeout(a, 300, M-a)
d = timeout(d, 300, M-d)
e = timeout(e, 300, M-e)
f = timeout(f, 300, M-f)
m = timeout(m, 300, M-m)
q = timeout(q, 300, M-q)
r = timeout(r, 300, M-r)
s = timeout(s, 300, M-s)
t = timeout(t, 300, M-t)
w = timeout(w, 300, M-w)

1 = timeout(1, 300, M-1) # this works
2 = timeout(2, 300, M-2) # this works
```

However, it does not work for this one:

```
[ids]
*

[main]
[ = timeout(backspace, 150, C-backspace)

102nd = overloadi(z, timeout(z, 300, M-z), 150)
z = overloadi(x, timeout(x, 300, M-x), 150)
x = overloadi(c, timeout(c, 300, M-c), 150)
c = overloadi(v, timeout(v, 300, M-v), 150)
v = overloadi(b, timeout(b, 300, M-b), 150)

a = overloadi(a, timeout(a, 300, M-a), 150)
d = overloadi(d, timeout(d, 300, M-d), 150)
e = overloadi(e, timeout(e, 300, M-e), 150)
f = overloadi(f, timeout(f, 300, M-f), 150)
m = overloadi(m, timeout(m, 300, M-m), 150)
q = overloadi(q, timeout(q, 300, M-q), 150)
r = overloadi(r, timeout(r, 300, M-r), 150)
s = overloadi(s, timeout(s, 300, M-s), 150)
t = overloadi(t, timeout(t, 300, M-t), 150)
w = overloadi(w, timeout(w, 300, M-w), 150)

1 = timeout(1, 300, M-1) # this works
2 = timeout(2, 300, M-2) # this does not work
```

Note that `meta+1` works, but not `meta+2`.

If anyone has an idea...

It seems there is something to do with the number of other `overloadi` mappings that I have before my `2` mapping. Because if I remove some mappings before, it works, but other mappings further down the file don't work. Like if it was a problem of indexing or something like this.

**Comment by lobre** [comment]
Is it even correct to have an `overloadi` with a `timeout` used together? For me it makes sense, but since I added such mappings, I often have `keyd` who crashes or mappings that don’t work anymore in my configuration.

```
h = overloadi(h, timeout(h, 300, M-h), 150)
j = overloadi(j, timeout(j, 300, M-j), 150)
k = overloadi(k, timeout(k, 300, M-k), 150)
l = overloadi(l, timeout(l, 300, M-l), 150)
```

My intent is to add a hold variation so that it activates the `meta` version of a key. But to reduce the delays when normally typing sentences, I thought `overloadi` would help me to only enable this behavior when the letter is not typed in a sequence with other letters.

It also helps to still allow repeating a key by tap-and-hold (rapidly within my 150ms). This way, the timeout will not be applied because the `action1` will be selected, so I can repeat `hhhhhhhhh`.

**Comment by lobre** [comment]
Looking more deeply into this problem, it seems I hit the maximum number of descriptors (which seems to be 64).

Is it normal that I am able to reach it? My configuration is sufficiently large, but not neither too complex to my eyes. I wanted to have a timeout for most keys so that holding them would give the `meta+key`. Not sure how I can reduce this.

How was this number chosen?

**Comment by rvaiya** [comment]
> Is it even correct to have an `overloadi` with a `timeout` used together?

Yes, this should be supported and makes sense.

> My intent is to add a hold variation so that it activates the `meta` version of a key. But to reduce the delays when normally typing sentences, I thought `overloadi` would help me to only enable this behavior when the letter is not typed in a sequence with other letters.

What you describe should indeed be the observed behaviour.

> Looking more deeply into this problem, it seems I hit the maximum number of descriptors (which seems to be 64).

This is a known limitation, which should manifest itself as a config error in your keyd logs (always the first port of call when config debugging).

> Is it normal that I am able to reach it? My configuration is sufficiently large, but not neither too complex to my eyes. I wanted to have a timeout for most keys so that holding them would give the `meta+key`. Not sure how I can reduce this.

This seems like a reasonable use case. I have increased the limit in the latest commit, which should accommodate your use case.

> How was this number chosen?

Poorly :P. Mainly it was a tradeoff between memory requirements (with the original plan being to port to SOCs without much ram) and anticipated config complexity.

**Comment by lobre** [comment]
Thank you for your detailed answer. I will close this issue as everything was working properly except when hitting this limit. I suppose the new value will be more than enough.
