### ISSUE TITLE
keyd mangles touchpad events from integrated Trackpad

### ISSUE THREAD

**Issue by jottr** [rvaiya/keyd#714]
On my [Macbook Pro 11,3](https://support.apple.com/en-us/111935), with `keyd` enabled, tap events are interpreted as keyboard events instead of click events, specifically `kpminus up/down` and `numlock up/down`:

```bash
# keyd monitor -t
device added: 0fac:1ade keyd virtual pointer (/dev/input/event2)
device added: 0fac:0ade keyd virtual keyboard (/dev/input/event1)
device added: 05ac:0262 bcm5974 (/dev/input/event8)
device added: 05ac:0262 Apple Inc. Apple Internal Keyboard / Trackpad (/dev/input/event0)
+759199167 ms	keyd virtual keyboard	0fac:0ade	enter up
+0 ms	keyd virtual keyboard	0fac:0ade	kpminus down
+0 ms	keyd virtual keyboard	0fac:0ade	numlock down
+8 ms	keyd virtual keyboard	0fac:0ade	kpminus up
+0 ms	keyd virtual keyboard	0fac:0ade	numlock up

```

This renders the touchpad unusable. It does not matter if tap-to-click is enabled or disable in Gnome Shell.  

I'm unsure if this is a configuration error or caused by `keyd`'s implementation.

```bash
$ cat /etc/keyd/internal.conf
[ids]
05ac:0262

[capslock]
h=left
j=down
k=up
l=right

[main]
capslock=overload(capslock, esc)
esc=capslock
```

```bash
$ uname -rsm 
Linux 6.1.82 x86_64

$ keyd --version
keyd v2.4.3 ()

```

`# lshw -numeric -sanitize -class input`: [lshw.txt](https://github.com/rvaiya/keyd/files/14951301/lshw.txt)
 
 Maybe this [issue](https://github.com/rvaiya/keyd/issues/66) is related?

**Comment by jottr** [comment]
Additional info:
Finger-taps with multiple fingers are interpreted/emitted as: `kp1 down/up, kp6 down/up, kp8 up/down, kpplus up/down`.

**Comment by jottr** [comment]
My issue seems to be related to https://github.com/rvaiya/keyd/issues/676 or even a duplicate.
The maintainer [writes](https://github.com/rvaiya/keyd/issues/676#issuecomment-1982060420):
> However, laptops will often group other keys into the touchpad device which can cause keyd to misidentify them as keyboards. 

In my case, the keyboard and the touchpad have the same ID. So it seems that it is impossible to simply ignore the tap events by ignoring the relevant ID of the touchpad via `-<id>`.

```
journalctl -u keyd.service 

Apr 12 00:02:03 titan keyd[1043]: Starting keyd v2.4.3 ()
Apr 12 00:02:03 titan keyd[1043]: DEVICE: ignoring 0fac:1ade  (keyd virtual pointer)
Apr 12 00:02:03 titan keyd[1043]: DEVICE: match    05ac:0262  /etc/keyd/internal.conf        (bcm5974)
Apr 12 00:02:03 titan keyd[1043]: DEVICE: match    05ac:0262  /etc/keyd/internal.conf        (Apple Inc. Apple Internal Keyboard / Trackpad)
```

**Comment by NikkSaan** [comment]
As a temporary workaround, try this: 
```
[id]
 *
```
it works on my mbp9,2.

**Comment by rvaiya** [comment]
> My issue seems to be related to https://github.com/rvaiya/keyd/issues/676 or even a duplicate.

Indeed. I've added a note about this to the man page.

> In my case, the keyboard and the touchpad have the same ID.

Try the latest commit, it should now allow you to distinguish between device notes with the same product and vendor id pairs. `keyd monitor` should produce unique ids for each pseudo device that gets created.

**Comment by jottr** [comment]
@rvaiya please excuse the delayed response.
I just got around to testing your commit (on a different Mac model mind you).
`keyd` indeed distinguishes between internal keyboard and mouse on Apple devices. 
The internal keyboard is identified as: 
`Apple SPI Keyboard      0000:0000       v down`
while the internal touchpad is identified as 
`Apple Inc. Magic Trackpad       05ac:0265       v up`
`
Can I assume that the id of `0000:0000` is to be expected here? Thanks!

**Comment by jassik** [comment]
Had the same problem on MacBookPro12,1 as keyd was intercepting the trackpad stream with the keyboard. Using ~$ keyd monitor  got  the 2 diff sets of id mappings for the trackpad and the internal keyboard with the same first 2 parts.  Using the full ID for the keyboard fixed the issue. Thanks for the support :)
