### ISSUE TITLE
USB Gadget

### ISSUE THREAD

**Issue by gkbd** [rvaiya/keyd#72]
There are plenty of small single board computers that have USB OTG port that can be configured to act as HID device.

One can connect keyboard to host port of such SBC, PC to OTG or device port and use SBC as USB to USB converter that can remap keys, add layers, macros etc.

As a proof of the concept I modified keyd to write HID reports via USB Gadget instead of sending evdev events to uinput:

[https://github.com/gkbd/keyd/tree/gadget](https://github.com/gkbd/keyd/tree/gadget)

I'm testing it now and so far it looks promising, tried plugging it in Linux, Windows, Chrome OS and Android devices.

It's based on version 1.3.1 though, will take a look at 2.0 later.

If there is interest in making virtual input device configurable and adding USB Gadget as one of the output options I can eventually make sure that changes are upstreamable.

Otherwise I can keep it as proof of the concept for a while and decide later how to proceed.

**Comment by rvaiya** [comment]
This indeed looks quite promising! 

I have been contemplating adding some degree of multi platform support, which would start by factoring out the evdev/uinput specific code and allow for arbitrary input and output sinks. Once done, it should be relatively straightforward to add USB Gadget as an output. 

I'm curious to know what you are running this on.

**Comment by gkbd** [comment]
Good to hear that.

At the moment I'm running it on [Cubietruck](https://linux-sunxi.org/Cubietech_Cubietruck), one of the early ARM devboards that I had lying in basement.

Eventually I want to try it on smaller boards like [MangoPi MQ](https://mangopi.org/mangopi_mq), but it might take some time before RISC-V devices like this gain mainline Linux support.

Until then I can keep prototyping it on ARM or Aarch64 devices, can pick low hanging fruit Pis first.

**Comment by rvaiya** [comment]
Interesting. How do these compare to the dedicated controllers? Are they battery powered, or is power supplied by the host? 

I have winnowed out some space for alternative virtual keyboard implementations in the latest commit. 

See 6819c1cd0 for a sample implementation which can be built with `make vkbs-stdout` and prints to stdout.  (note that if you run the resultant binary you will have to terminate with the panic key sequence).

**Comment by gkbd** [comment]
Very good solution. Thank you. Will try it.

Some SBCs can be powered by host PC, more power hungry ones are powered from barrel plug or GPIO pins.

Dedicated controllers are good option too, some run TMK/QMK even.

**Comment by gkbd** [comment]
Pushed USB gadget output sink and helper files to

https://github.com/gkbd/keyd/tree/gadget2

After your changes it was indeed much easier to add new output option.

And vkbd-stdout was also useful both as example and on it's own.

Thanks for that.

Let me know if further changes are required.

Can send PR if no other refactoring is needed at this stage.

**Comment by rvaiya** [comment]
Sounds good, go ahead and create a PR.

**Comment by rvaiya** [comment]
Merged.
