### ISSUE TITLE
request: a gnome extension that shows the layout and layers

### ISSUE THREAD

**Issue by wmertens** [rvaiya/keyd#720]
It would be great if there was a way to inspect the keyd state and show it with an extension.
That way you could have an indicator of which layout and layers are active.

How about a unix socket that when you open it, you get the current layout and layers, and every time a change happens it gets pushed?

**Comment by nsbgn** [comment]
This is already implemented via `keyd listen` :)

**Comment by wmertens** [comment]
well, minus the layout message on connection :)

**Comment by nsbgn** [comment]
Which version are you on? The layout message (as `/layout`) was added in https://github.com/rvaiya/keyd/commit/44d0864ef122c24329f8830c9fa4b1cea23afac1

**Comment by wmertens** [comment]
ah cool! I'm on nixos with version 2.4.3. I see there's not been a release with it yet.
Should nixos follow master instead?

**Comment by rvaiya** [comment]
> Should nixos follow master instead?

Probably not :P

> ah cool! I'm on nixos with version 2.4.3. I see there's not been a release with it yet.

Yes, a 2.x release is long overdue. I need to shore up a few things and will hopefully have something out by the end of the month, after which I intend to start work on the next major version.
