### ISSUE TITLE
Shift not usable after setting a layer for shift

### ISSUE THREAD

**Issue by Arom1a** [rvaiya/keyd#727]
The feature I want to achieve is that treating `leftshift` + `space` as `_`. 
However, using 
```
[id]
*

[main]
leftshift = layer(mylayer)

[mylayer]
space = _
```
causes my left shift loses it original function, eg. `a` is not capital after typing `shift` + `a`. Also, system navigation like `ctrl` + `shift` + `tab` is not working. 

Am I doing it wrong? Or it is able to achieve this functionality?

**Comment by nsbgn** [comment]
You have remapped your shift, so this is expected behaviour. If you also want to activate shift when you enter your custom layer, you can attach it with `:S` like so:

```
[id]
*

[main]
leftshift = layer(mylayer)

[mylayer:S]
space = _
```

**Comment by Arom1a** [comment]
Yes, this works pretty good! I didn't understand this section well. 
Thank you for your help so much!!!
