### ISSUE TITLE
Postpone the effect of layer-level modifiers at key press instead of at layer activation

### ISSUE THREAD

**Issue by lobre** [rvaiya/keyd#728]
Here is a simple example:

```
[ids]
*

[global]
disable_modifier_guard = 1

[main]
space = overloadt(nav, space, 150)

[nav:M]
h = left
j = down
k = up
l = right
```

I do have a `nav` layer which has the `:M` (meta modifier) applied by default. So any mappings defined on that layer will override this default modifier.

Here, `x` will give `meta+x` while `j` will simply give `down`.

Given this context, the current implementation seems to be that as soon as layer `nav` is entered (by holding space), a `leftmeta down` is emitted. Then it waits for an actual key to be pressed. If that key has no corresponding mapping on `nav`, let’s say `x`, `leftmeta` will stay active and the output will be `meta+x`.

On the opposite, if I hit `j` which is defined on `nav`, it will send a `leftmeta up` to cancel the modifier, and apply just `down`. Here is below the output of `keyd monitor` showing this behavior. We also see that `leftmeta` is directly reapplied when `down` is finished.

```
keyd virtual keyboard   0fac:0ade       leftmeta down
keyd virtual keyboard   0fac:0ade       leftmeta up
keyd virtual keyboard   0fac:0ade       down down
keyd virtual keyboard   0fac:0ade       down up
keyd virtual keyboard   0fac:0ade       leftmeta down
keyd virtual keyboard   0fac:0ade       leftmeta up
```

This implementation has some side effects in certain situations.

For example, I am using the xfce application launcher. When it is revealed, it has a text input in which I can search for an application, and I can do `up` and `down` to navigate the results. However, if `meta` is entered, it will dismiss the launcher. So with my above example, trying to navigate with `up` and `down` would close it.

I am wondering why the implementation is not the other way around. Taking again my example, here activating the `nav` layer would not activate directly the modifier. Instead, it would wait for another key (or mouse) event and decide **at that moment** if the modifier should be applied or not according to the presence of a mapping. So while holding `nav`, tapping `x` would send `leftmeta+x`. And `j` would not see any `meta` modifier applied at all. It would just send `down`.

I can be wrong, but it feels to me that this implementation would bring more benefits than harm. Is there any reason why it is done this way?

**Comment by wmertens** [comment]
The `design.md` explains the reasoning, I personally prefer it the way it is. If you want to have it the other way round, which imho is not most of the time, you can leave off the `:M` and add all the keys you're going to use with `M-key`.

Granted, that's more work, but it's not the end of the world.

**Comment by lobre** [comment]
> The design.md explains the reasoning, I personally prefer it the way it is.

I just re-read the design document and I don't find anything related specifically to the issue I am talking about. Or maybe I misread or don't exactly understand. If you can point to a specific question this would be appreciated!

> If you want to have it the other way round

In fact, I don't really want "the other way around". The semantics are fine to me the way they are. It is the implementation that feels a bit off to me.

I am just expecting the layer-level modifier to be emitted only when needed, when a subsequent key is pressed instead of directly at layer activation.

If I use the opposite representation as you suggest, by leaving off `:M` and applying `meta` individually, this is tedious but it effectively "works".

But again, my concern here is to understand why the `leftmeta` (to take my initial example again) is emitted directly when I press (and hold) `space`, and not afterwards when I actually press a subsequent key that is not defined on this `nav` layer.

I don't know if that makes sense?

**Comment by nsbgn** [comment]
I don't recall the design doc --- I'll edit this comment later --- but I'd quickly like to drop two reasons here:

1. If the mouse is not managed by keyd, then you'd not be able to combine mouse clicks with modifiers. I vaguely recall this being given as a reason before --- keyd was not always able to manage mice.

2. Recall that modifier keys are by default bound to corresponding layers. If they didn't still immediately emit the corresponding modifiers, that would be rather confusing. This is less of an issue in explicitly created layers, but having a separate behaviour there doesn't seem ideal.

Enabling the modifier guard (that you have disabled with `disable_modifier_guard`) often mitigates the adverse effects of 'cancelling' a modifier keypress (like cancelling that launcher), but perhaps a case can be made for optional lazy modifier activation if there is a benefit (... and it would probably be covered by other feature requests calling for default actions and the like)
