### ISSUE TITLE
Failed to start

### ISSUE THREAD

**Issue by rjahrj** [rvaiya/keyd#73]
This happens on v1 and master branch, whether its built from source or installed from the AUR
![image](https://user-images.githubusercontent.com/20189326/147515708-102e2e96-0fde-4f02-bf0f-1a242d5c9a99.png)

**Comment by rvaiya** [comment]
Odd, I can't seem to reproduce this on my system. It seems it is having trouble creating the lock file, can you post the output of `ls /var/lock`?

**Comment by rvaiya** [comment]
Does this also happen when you manually start the systemd service (`systemctl restart keyd`) or only on boot?

**Comment by rjahrj** [comment]
> Odd, I can't seem to reproduce this on my system. It seems it is having trouble creating the lock file, can you post the output of `ls -lH /var/lock`?

`ls: cannot access '/var/lock': No such file or directory.

it was working perfectly fine when I installed lastnight, then just stopped. Doesnt work either way, reboot or manual

**Comment by rvaiya** [comment]
> `ls: cannot access '/var/lock': No such file or directory.

There's yer problem :P. 

It seems your lock directory is missing. I'm not sure how this happened. `/var/lock` should be symlinked to `/var/run/lock` on arch. Did you do anything else to your system shortly before encountering this issue?

**Comment by rjahrj** [comment]
Not that I know off lol.
So how do I get this back

**Comment by rvaiya** [comment]
if `/var/run/lock` exists you can manually create the symlink like so: `sudo ln -s /var/run/lock/ /var/lock`. This should also have broken a few other programs, so I am curious to know what might have caused it.

**Comment by rjahrj** [comment]
well what if i dont have `/var/run/lock` lmao!!!!

**Comment by rvaiya** [comment]
Does `/run/lock` exist? Try rebooting your system.

**Comment by rjahrj** [comment]
> Does `/run/lock` exist? Try rebooting your system.

nope rebooting now

**Comment by rjahrj** [comment]
i got a `/var/lock' but nothing else

**Comment by rvaiya** [comment]
As mentioned, `/var/lock` should be symlinked to `/run/lock`. keyd only cares that `/var/lock` exists, so it should work as long as the directory is writable, however it seems like your system might be broken, so you may want to find out why.

**Comment by rjahrj** [comment]
I just installed arch from scratch and installed keys from source, and it still is giving me the same error

**Comment by rjahrj** [comment]
If I create `/var/run/lock/` and symlink it myself it works, but if I reboot it stops working

**Comment by rvaiya** [comment]
`/var/run` should just be symlinked to `/run`, you shouldn't have to manually create either of them. I just tried this on a fresh arch install without issue. How are you bringing up your system? Are you using the latest iso?

**Comment by rjahrj** [comment]
yeah only diff is i used the archinstall package

**Comment by rvaiya** [comment]
Resolved offline.
