### ISSUE TITLE
Simlayer support

### ISSUE THREAD

**Issue by argenkiwi** [rvaiya/keyd#733]
Could you please support the concept of _simlayer_? They are basically like overload but a timeout applies to holding the key after which the key does what it would normally if held (e.g. holding "a" would eventually repeat: "aaa...").

I have come across this concept using Karabiner Elements on MacOS (only because I need to for work and wanted to replicate what keyd does on Linux). It could be useful for overloading backspace, for example, while allowing for it to still be used to delete multiple characters without multiple taps.

Please ignore the request if it's already possible to do and I just could not find out how. Thanks.

**Comment by nsbgn** [comment]
`timeout(overload(control, backspace), 500, backspace)`? ;)

**Comment by argenkiwi** [comment]
Thanks! I didn't see any examples of  actions passed as parameters for other actions so I assumed it was not possible, but that did the trick.
