### ISSUE TITLE
Keymap, remote not working using rustdesk

### ISSUE THREAD

**Issue by cctv130** [rvaiya/keyd#735]
I found that keyd didn't work at all when using the remote screen.

**Comment by nsbgn** [comment]
What do you mean? What is your setup? 

From https://github.com/rvaiya/keyd/issues/551#issuecomment-1806616435:

> Your local machine interprets keystrokes and inputs them into the terminal. ssh is a program which creates a pseudo-terminal that allows you to interact with a remote machine. The keystrokes are still interpreted by your local input stack. Consequently, installing keyd on the machine you are remotely logged into will have no effect.

**Comment by rvaiya** [comment]
> I use the rustdesk client matepad Android system to connect to my Ubuntu remote desktop. My keyboard and mouse are connected to the matepad. I have set up the keyboard mapping in the Ubuntu system, but the input keys through the matepad do not work.

This won't work. keyd only intercepts keys generated by keyboards attached to the system (it works at a lower layer than the display server). You will need to use a display server remapping tool if you want bindings to be remotely applied.
