### ISSUE TITLE
Overload inherits from layer when nested

### ISSUE THREAD

**Issue by slakkenhuis** [rvaiya/keyd#74]
Before the beta, I had the following:

    leftalt = overload(M, esc)
    rightalt = overload(symbol, enter)

    [symbol:S]
    leftalt = overload(M-S, \)

This worked well, but in the beta, tapping `leftalt` while in the `symbol` layer emits `S-\`, that is, `|`. This is not a huge issue in that I can just drop the inheritance from `S` and add an explicit `S-` where desired, but I thought I'd mention it because I do think that the previous behaviour was more intuitive, as it is consistent with the behaviour of non-overloaded keys in a layer, where modifiers are inherited unless explicitly overridden.

**Comment by rvaiya** [comment]
Thanks, this is indeed a regression. It should be fixed in the latest commit.

**Comment by slakkenhuis** [comment]
It is. Thanks :)

**Comment by slakkenhuis** [comment]
Oh, actually, it's still there when you put a timeout:

```
leftalt = overload(M, esc)
rightalt = overload(symbol, enter)

[symbol:S]
leftalt = overload(M-S, \, 150)
```

**Comment by rvaiya** [comment]
Oops. I believe this should be fixed.
