### ISSUE TITLE
What would be the intended way to fallthrough to QWERTY on held Meta

### ISSUE THREAD

**Issue by DanisDGK** [rvaiya/keyd#752]
```
[qwerty:layout]

[kuntum:layout]
q = v
w = l
...
```
I have this in my config right now and I want all Meta presses to fall through to QWERTY. Unsure what the intended way to do this would be.

**Comment by rvaiya** [comment]
You want something like:

```
[kuntum:layout]
q = v
w = l

[meta]
q = M-q
l = M-l
# ...
```
