### ISSUE TITLE
macro with oneshot layer

### ISSUE THREAD

**Issue by Zite303** [rvaiya/keyd#754]
First thanks a lot for your work on keyd. It has really helped me with my RSI.

Would it be feasible to add the possibility to finish a macro with a oneshot layer (like on zmk), e.g something like : 
a = macro(a oneshot(layer_x)) 

This would make it possible to use alternate keys : alternate keys  are used in some alternative layout to qwerty. They output a different character depending on the previous keys that has been used.  For instance : 
a = macro(a oneshot(layer_a)) 

[layer_a]
a = u

so that typing aa output au

**Comment by nsbgn** [comment]
This is already implemented via `oneshotm(layer_x, a)` :)

**Comment by Zite303** [comment]
wow i did not realize this. I have just tried it and it works perfectly ! This is amazing :)
