### ISSUE TITLE
Incompatibility with Python library evdev

### ISSUE THREAD

**Issue by dev-nll** [rvaiya/keyd#762]
`keyd` works well, but there's an incompatibility with the `evdev` library, in particular when I use `evdev` to listen to the keyboard. The below script will only work when I am not using `keyd`:

```
from evdev import InputDevice

def main():
    device_path = '/dev/input/by-id/usb-ELECOM_EG_VK300-event-kbd'
    keyboard = InputDevice(device_path)
    for event in keyboard.read_loop():
        print("Found event.")
```

**Comment by nsbgn** [comment]
What do you mean by 'will only work'? If you mean that the script won't get any events anymore, then that is expected, as keyd routes keyboard events through its virtual keyboard. I think you can change the `device_path` to the virtual keyboard's ID to get the rerouted events.

**Comment by dev-nll** [comment]
>  I think you can change the `device_path` to the virtual keyboard's ID to get the rerouted events.

This worked, thanks.
