### ISSUE TITLE
special overload for space key to act as control comfortable

### ISSUE THREAD

**Issue by lambdaloop** [rvaiya/keyd#768]
I want to have a special kind of configuration to make the space key act as control but also a comfortable space key for typing.

Basically, I want to have something similar to 
```space = overload(control, space)```
...but with the special override that when space is pressed shortly  after a non-modifier key is pressed, it acts as a regular space. This makes it much more comfortable to type with it, as I don't have to fully release space when typing text.

For instance, if I type "hello" then press <space> quickly after "o", it would treat it as <space> on keydown.  
Alternatively, if I just hold <space> then it acts as a <control> when combined with another key or <space> on release as in classic overload.

So far, I've been using a hacked version of the X11 evdev driver to accomplish this: https://github.com/lambdaloop/at-home-modifier-evdev 
keyd would be really nice to implement this.

I think implementing this function would also open up the use of many more keys for use in `overload` where it would otherwise be uncomfortable for fast typing.

Is this possible to implement with the current keyd functions? If not, where would I start to implement this feature?

**Comment by nsbgn** [comment]
Yes, this is what `overloadi` is for. See the man page and #608 for details. You'll need a recent version. 

I would warn you that overloading space needs tuning and may feel inherently uncomfortable, but you have experience with it, so I suppose there's no need. Still, you may also want to look at its siblings `overloadt`, `overloadt2` and `lettermod`.

    space = lettermod(control, space, 100, 200)

**Comment by lambdaloop** [comment]
Woah, this is amazing! This does exactly what I want, thank you so much!

**Comment by nsbgn** [comment]
Great! I think that config would be equivalent to `overloadi(space, control, 400)` :)

**Comment by lambdaloop** [comment]
I thought so too so I tried that first, but it didn't work. Space would just always output space. Specifically this line:
```space = overloadi(space, control, 300)```

Since I'm new to the package, I'm not sure if this a bug with overloadi or if I misunderstood something.

For context, I'm on the latest commit (ce1bab6).
