### ISSUE TITLE
Can't map a key to control+shift

### ISSUE THREAD

**Issue by HazemHussien1** [rvaiya/keyd#775]
I need to remap the letter a to type a when tapped and map it to CTRL+ SHIFT when held, i tried these solutions and none worked

leftcontrol = leftcontrol
leftshift = leftshift
control = control
shift = shift

```
# first try
a = overload(C-S, a)

# second try
a = overload(control+shift, a)
```

none of these work, please keep in mind that i mapped control to capslock later in the file as well (not sure if that makes a difference so here's my config

```
[ids]

*

[main]

# Maps capslock to escape when pressed and control when held.
capslock = overload(control, esc)
; = overload(control, ;)

leftcontrol = leftcontrol
leftshift = leftshift
control = control
shift = shift
compose = down

rightalt = rightalt
rightalt = overload(alt, left)

rightshift = rightshift
rightshift = overload(shift, up)

rightcontrol = rightcontrol
rightcontrol = overload(control, right)

leftcontrol = leftcontrol
leftcontrol = capslock


```

**Comment by nsbgn** [comment]
Try defining a custom layer with the associated modifiers:

```
[main]
a = overload(controlshift, a)

[controlshift:C-S]
```

(That said, you will probably find you'll need something like `a = lettermod(controlshift, a, 50, 100)` or one of the other overload variants to avoid misfires)

**Comment by HazemHussien1** [comment]
This worked flawlessly, thank you <3
