### ISSUE TITLE
Combination Trackpad/Keyboard - Trackpad Unstable

### ISSUE THREAD

**Issue by vollink** [rvaiya/keyd#776]
`keyd monitor` where I hit the a key on the keyboard, then barely touch the trackpad...

```
Apple Inc. Apple Internal Keyboard / Trackpad	05ac:024c	a down
Apple Inc. Apple Internal Keyboard / Trackpad	05ac:024c	a up
bcm5974	05ac:024c	a up
bcm5974	05ac:024c	a up
bcm5974	05ac:024c	a up
bcm5974	05ac:024c	a up
bcm5974	05ac:024c	a up
bcm5974	05ac:024c	kpminus down
bcm5974	05ac:024c	numlock down
bcm5974	05ac:024c	kpminus up
bcm5974	05ac:024c	numlock up
bcm5974	05ac:024c	numlock up
bcm5974	05ac:024c	numlock up
Apple Inc. Apple Internal Keyboard / Trackpad	05ac:024c	leftcontrol down
Apple Inc. Apple Internal Keyboard / Trackpad	05ac:024c	c down
```

Everything works fine if keyd isn't "service running", but the trackpad is unusable if the keyd is active.  If it were different devices, I'd be able to just `-` ignore the ID, but as a combo unit, whatever this software can't figure out about this trackpad isn't working.

I expect this is a low to zero priority since this issue is with a MacBookAir5,2 (2012) and there aren't actually that many of those both still surviving and running Manjaro/Wayland/Gnome.

**Comment by nsbgn** [comment]
I think you should be able to match exclusively the keyboard portion with the `k:` prefix to the id, see https://github.com/rvaiya/keyd/issues/345

**Comment by vollink** [comment]
I've been using this successfully now for the whole weekend, and it does work great.  Putting `k:05ac:024c` as the only entry on the ids is all I needed, and the whole thing became perfect!   Sorry I didn't comment right away (I wanted to actually verify it was fully stable).
