### ISSUE TITLE
mouse1 and mouse2 remapping not working

### ISSUE THREAD

**Issue by bluescorpion35** [rvaiya/keyd#781]
On my mouse, I have side buttons. The buttons appear as `mouse1` and `mouse2` when I run `sudo keyd monitor`. When I add them to the config, nothing happens with them, although the other items work, such as remapping capslock to backspace. The config looks like this:
```
[ids]

*

[main]
capslock = backspace
compose = leftmeta
mouse1 = leftmeta
mouse2 = leftshift
```

**Comment by nsbgn** [comment]
Try adding the mouse ID to the `[ids]` section explicitly, see https://github.com/rvaiya/keyd/blob/ce1bab682baf98396b957b4c7950c89413b4c96f/docs/keyd.scdoc#L132

**Comment by bluescorpion35** [comment]
Thank you!
