### ISSUE TITLE
how to open right click Context Menu?

### ISSUE THREAD

**Issue by Mohammad9760** [rvaiya/keyd#786]
hi, I'm new to keyD and so far I love it.
I'm using this config:
```
[capslock:C]
j = left
k = down
i = up
l = right
```
and I'd like to add ```p = menu``` but it doesn't work. I want p to work like the Menu key which some keyboards have or like a right mouse click that brings up the context menu.
thanks
edit: typo

**Comment by nsbgn** [comment]
Try `compose`. In general, you can use `keyd monitor` to check if the key you press has the name you expect it to have :) cf. #363, #577

**Comment by Mohammad9760** [comment]
> Try `compose`.

omg thank you it works.
I tried ``` p = compose``` and it works.
monitor command didn't work it threw me ```failed to open /dev/input/event0``` and a bunch of other event numbers.
but thanks
