### ISSUE TITLE
Stateful layers

### ISSUE THREAD

**Issue by dickrp** [rvaiya/keyd#789]
I am trying to define two alternative stateful layers. Only one should be active at a time. When layer [one] is active and the meta key is held, a = j. When layer [two] is active and the meta key is held, a = k. M-t should switch to layer [one]. M-g should switch to layer [two]. The most straight-forward way would be to have M-t first clear() then toggle(one). I don't see a way to do that with keyd so I tried the following roundabout method.

[meta]
t = toggle(one)
g = toggle(two)

[one]
[one+meta]
t = noop
g = swap(two)
a = j

[two]
[two+meta]
t = swap(one)
g = noop
a = k

This doesn't work. I can toggle into either layer, but switching between them doesn't work, perhaps because [meta] is the top layer on the stack instead of [one] or [two]. Is there a good way to make stateful layers using keyd?

**Comment by nsbgn** [comment]
Ah. I see what you mean. Here, too, something like multiple actions (#590) would really help.

For your specific example, which I suppose may be a MWE, I would expect that something like this might work if my assumptions about the layer stack are correct (untested, may need tweaking):

```
[meta]
t = toggle(one)
g = toggle(two)

[one]
[one+meta]
t = noop
g = toggle(two)
a = j

[two]
[two+meta]
t = toggle(one)
g = noop
a = k

[one+two+meta]
t = toggle(two)
g = toggle(one)
```

... but needless to say, this is horrifying. :P

**Comment by dickrp** [comment]
Thanks. That passes basic tests. Although both layers are active much of the time, it acts like only one is active if they both modify the same keys because the most recently activated layer has precedence.

**Comment by rvaiya** [comment]
If you only care about the meta+`layer` case, then a better solution might be to make use of keyd's modifier layers:

```
[meta]
t = swap(one)
g = swap(two)

[one:M]
g = swap(two)
a = j

[two:M]
t = swap(one)
a = k
```
