### ISSUE TITLE
make `meta+jikl` simulate arrow keys

### ISSUE THREAD

**Issue by spaceunifyfifty** [rvaiya/keyd#795]
I want `leftmeta+j` to simulate `left`, `leftmeta+i` to simulate `up`, and so on.

Here is my config file
```
[ids]

*

[main]

# Maps capslock to escape when pressed and control when held.
capslock = overload(control, esc)

# Remaps the escape key to capslock
esc = capslock

leftmeta + j = left
leftmeta + l = right
leftmeta + i = up
leftmeta + k = down
```

I confirm that the `capslock` <-> `esc` behavior is working, but the meta + jikl behavior does not. I have also tested with

```
meta + j = left
```
 
instead of `leftmeta`, neither work. 

What am I doing wrong? Thanks.

**Comment by nsbgn** [comment]
`leftmeta+j` is the syntax for chords (see the manual or issue #320), not for remapping keys modifier layers. That is, it is activated only when you press `leftmeta` and `j` *simultaneously* (within some short interval).

You're probably looking for this:

```
[meta]
j = left
l = right
i = up
k = down
```
