### ISSUE TITLE
 mouse + keyboard combination remapping in diffrent device

### ISSUE THREAD

**Issue by Maziar123** [rvaiya/keyd#796]
Hi
Do these libs currently support mouse + keyboard combination remapping?

especially when the mouse & keyboard is a different device

**Comment by nsbgn** [comment]
Yes, to some extent. Things like mouse scroll support isn't there yet afaik, but state is shared between devices in the same config (cf #202) and thus can be combined

**Comment by Maziar123** [comment]
HI
thnx, for the answer 
have any sample & guide for example for extra buttons (1 or 2) & ctrl to for example ctrl + shift +c

**Comment by nsbgn** [comment]
If I understand correctly

```
[ids]
# you will have to add your mouse id here, even if your keyboard is grabbed with *; find out the id with `keyd monitor`
*

[main]

[control]
# Find out the actual name of your button with `keyd monitor`
mouse2 = C-S-c
```

**Comment by Maziar123** [comment]
if dont understand how:
input :extra buttons (1 or 2) & ctrl
to output : ctrl + shift +c

is 
mouse2 = C-S-c
what rel to my topic ?

as comment for example I need when press left_ctrl  + mouse_extra_btn_2  -->> map to -->> ctrl ctrl + shift +c

**Comment by nsbgn** [comment]
I don't understand what you are asking. Are you confused about the syntax? It says 'when in the `control` layer, the second mouse button should emit `C`ontrol-`S`hift-`c`. But also, the manual may be of help.

**Comment by Maziar123** [comment]
seems I must read the manual again, thx
