### ISSUE TITLE
Does keyd support hyper key?

### ISSUE THREAD

**Issue by marsjane** [rvaiya/keyd#799]
hi, I use capslock as hyper key by setting in Xmodmap
```
> cat .Xmodmap                             
! remap caps_lock to Hyper_l/mod3
clear lock
keycode 66 = Hyper_L

remove mod4 = Hyper_L
add mod3 = Hyper_
```
I wonder: 1) can I use hyper as modifier in keyd config? I didn't see it in the manual; 2) Is there any way I can do above Xmodmap config in keyd? So that I would only keep keyd and drop the Xmodmap config

**Comment by nsbgn** [comment]
Not within keyd, because the Hyper key is an X11 concept. cf #761

**Comment by marsjane** [comment]
Thanks! Yeah I got what I need in #370
