### ISSUE TITLE
make: Move systemd service generation to "install" target

### ISSUE THREAD

**Issue by ainola** [rvaiya/keyd#801]
Hi, thanks for developing!

Would you be amenable to moving the systemd service generation lines (https://github.com/rvaiya/keyd/blob/f0b5f122e0d0772f3fedd5bb6295212b0bb18174/Makefile#L37C1-L38C1) down to the "install" target? Running `make` with PREFIX is usually the install target, not the regular building targets.

**Comment by rvaiya** [comment]
This should be done in the latest commit.

**Comment by ainola** [comment]
Thank you!
