### ISSUE TITLE
How to swap Super with the "play next multimedia key" ?

### ISSUE THREAD

**Issue by hatosu** [rvaiya/keyd#804]
I can't find documentation on how to do this. Couldn't find any answers in both the examples folder, and issues tab. 

I know I should read "rtfm" but I genuinely don't know :pensive:

**Comment by nsbgn** [comment]
```
[ids]
*
[main]
leftmeta = nextsong
```

cf #177 :)

**Comment by hatosu** [comment]
Sorry for late reply D:

tysm <3 <3 <3 <3 <3

**Comment by tkna91** [comment]
@hatosu If the problem appears to be resolved, please close.
