### ISSUE TITLE
Label `v2.5.0` as the Latest version

### ISSUE THREAD

**Issue by tkna91** [rvaiya/keyd#807]
Currently, `v2.4.3` seems to be the Latest version on the following release page.
https://github.com/rvaiya/keyd/releases

Perhaps that label could be moved to `v2.5.0`?
![image](https://github.com/user-attachments/assets/0b75cbcc-8a19-49fd-bb9c-11d4fae93993)

**Comment by David-Else** [comment]
@rvaiya You might have missed this one, very quick issue to close and avoids quite a bit of confusion! I totally missed there was a new release.

**Comment by rvaiya** [comment]
Sorry for the delay, there is a lot of noise in the issue tracker. This should be fixed.
