### ISSUE TITLE
long macro don't work 

### ISSUE THREAD

**Issue by joihn** [rvaiya/keyd#809]
thanks for this tool
### issue
```
a = macro(printf'\eP$f{"hook":"SourcedRcFileForWarp","value":{"shell":"bash"}}\x9c')
```
does not work without any error message
It seems the macro length limit of keyd is too low. how to increase ?

**Comment by tkna91** [comment]
There are several similar threads. The most recent is this one.
https://github.com/rvaiya/keyd/issues/787

If you have no problem, please follow them and then close this issue.

**Comment by joihn** [comment]
For anyone interrested, 
there is a limit at 64 character hardcoded here:
https://github.com/rvaiya/keyd/blob/master/src/macro.h#L24
