### ISSUE TITLE
feature request: cosmic DE support for app specific remaps

### ISSUE THREAD

**Issue by PavelSlepushkin** [rvaiya/keyd#810]
There's new DE in alpha stage now - cosmic desktop.
Is it possible to add support for it to application-specific remap?
Protocol is close to wlroots and they expose active window via socket
https://github.com/pop-os/cosmic-protocols/blob/main/unstable/cosmic-toplevel-info-unstable-v1.xml

**Comment by PavelSlepushkin** [comment]
Well, figured it out myself, here the PR
https://github.com/rvaiya/keyd/pull/813
Obviously, it's ok to reject it, since cosmic is still in alpha and I did not test all possible cases.

**Comment by rvaiya** [comment]
Merged :).
