### ISSUE TITLE
[BUG] When changing to a non latin letters layout like ara or ru letters are broken.

### ISSUE THREAD

**Issue by Motaz-bellah1** [rvaiya/keyd#824]
when typing asdf for example i get 0qj0qq0q10pz instead of عقسى which means nothing but you get the point 
my config:
___________________________________
include layouts/ara

[ids]
*

[main]
...

[leftalt_layer:A]
2 = setlayout(ara)
1 = setlayout(main)
[space_layer]
...
___________________________________

**Comment by Motaz-bellah1** [comment]
solved by RTFM :
ln -s /usr/share/keyd/keyd.compose ~/.XCompose
and rebooting

**Comment by sonjiku** [comment]
Hey, sorry to "necropost"(?), but which de/wm are you using?
