### ISSUE TITLE
Print current layout

### ISSUE THREAD

**Issue by Kommynct** [rvaiya/keyd#829]
Since part of my keyd config is switching between dvorak and qwerty, it'd be nice if I could see the current layout on hyprlock

I'd just need a CLI way of printing the current layout.

**Comment by sonjiku** [comment]
You should have a look at the `keyd listen` command.

**Comment by Kommynct** [comment]
i saw that, it runs continuously and changes, which doesn't work for my usecase, i want my lockscreen to show the current layout, with that, it'd show every previous layout as well

It needs to print, then immediately exit.

**Comment by rvaiya** [comment]
> It needs to print, then immediately exit.

If you use the latest commit, you can do something like `keyd listen|grep -m1 '/'`. Make sure to use something newer than e154bf7, or this won't work properly.

However if you plan on continuously polling this command, it is advisable to keep a long running `keyd listen` around instead, as IPC connections are handled in the main event loop.
