### ISSUE TITLE
(built-in) volume up/down buttons ignored by keyd

### ISSUE THREAD

**Issue by Garbaz** [rvaiya/keyd#830]
Hi,

My laptop (Surface Go 2) has built in volume up/down keys like a Smartphone or Tablet usually has. I also have a little [Bluetooth camera remote](https://www.amazon.com/s?k=bluetooth+camera+remote) that in effect is just a input device sending `volumedown`/`volumeup` events.

However, while the events of both show up in `showkeys`, neither of these devices are found by `keyd`. They neither show up in `keyd monitor`, nor does this:

```
...
volumedown = nextsong
volumeup = playpause
...
```

in the `/etc/keyd/default.conf` change their behavior (while the volume up/down keys on my regular keyboard do change behavior, so the config is fine).

Running `KEYD_DEBUG=2 keyd monitor` as the person in [this issue](https://github.com/rvaiya/keyd/issues/638) does, I do get:

```
...
DEBUG: src/device.c:134: capabilities of /dev/input/event13 (Intel HID 5 button array): 0
...
DEBUG: src/device.c:134: capabilities of /dev/input/event26 (UBeesize): 0
...
```

_Intel HID 5 button_ array is the media keys. _UBeesize_ is the Bluetooth remote. It appears they are both detected to have no "capabilities" and therefore are ignored by `keyd` (?)

Question 1: Is it possible to just disable this check for capabilities? I assume it is only there for optimization, as not to listen to devices that are deemed not to send relevant input events.

~~Question 2: Would something similar to [this PR](https://github.com/rvaiya/keyd/commit/fd0b99d73297cf255994a0bc414100bc7a6240f1) be possible to resolve this issue?~~ Yes, see PR #832.

**Comment by rvaiya** [comment]
Merged :).
