### ISSUE TITLE
Ignore mouse devices

### ISSUE THREAD

**Issue by z0rzi** [rvaiya/keyd#837]
I use keyd to remap some keys on my keyboard, and it seems like it's blocking the smooth scrolling of my mouse (MX3)... When I turn off the keyd service, the smooth scrolling works just fine

It would be nice if in the settings of keyd, there was a way to say "ignore all mouse devices and don't create a virtual pointer"

**Comment by rvaiya** [comment]
By default keyd will not try an remap your mouse, however some devices (e.g laptops) will assign the trackpad and keyboard to the same vendor/product id. The latest version of keyd accounts for this by using internal ids that can distinguish between the devices and explictly whitelisted/blacklisted in your config.

You can see these ids using `keyd monitor`.
