### ISSUE TITLE
Keys freeze after hibernation

### ISSUE THREAD

**Issue by PragmaticProgrammingPenguin** [rvaiya/keyd#840]
From the bit of debugging I've been able to do after hibernation keyd will glitch and a key will end up permanently stuck down. Issue is temporarily fixed after a systemctl restart keyd but until the entire system has been rebooted the issues will reoccur.

Edit: Issue occured again without hibernation involved. Checking configs for errors and will update if issues occurs again.

**Comment by rvaiya** [comment]
I can't seem to reproduce this on master. I am tentatively closing, but feel free to reopen it.
