### ISSUE TITLE
Can I tap g to get a g and hold g for a control+g?

### ISSUE THREAD

**Issue by xircon** [rvaiya/keyd#848]
Can't see the wood for the trees!

It's an emacs thing, just can't work it out for myself :(

**Comment by nsbgn** [comment]
Tapping and holding mean different things to different people, so this depends on what exact behaviour you have in mind! The simplest way to interpret your question would be `g = timeout(g, 200, C-g)`, with the disambiguation between tapping and holding being a based strictly on hold time. But what should happen when keys start overlapping? That happens quite often in normal typing.

**Comment by xircon** [comment]
Thank you! I must have misread the timeout section, I missed the `g =` part off, then I went down a rabbit hole of all the variations of overload.  I understand what you are saying and have increased the time to 500 to hopefully counter this.
