### ISSUE TITLE
Overloading leftmeta, KDE Plasma, what am I doing wrong?  

### ISSUE THREAD

**Issue by xircon** [rvaiya/keyd#849]
Disabled meta as the menu launcher in systemsettings,  then

```
# Doesn't work:
## HELD/TAPPED
leftmeta = overload(macro(leftalt+f1),macro(leftmeta+0))

# So tried each of the below individually and both work:
leftmeta = macro(leftalt+f1)
leftmeta = macro(leftmeta+0)
```
Thanks

**Comment by nsbgn** [comment]
`overload` takes a layer for holding and a key for tapping; that is, a key is considered 'held' if it overlaps with a subsequent keypress. If your understanding of 'holding' is time-based, you are probably looking for `timeout(A-f1, 300, M-0)` or similar.

See https://github.com/rvaiya/keyd/issues/713#issuecomment-2044532113 for explanation

**Comment by xircon** [comment]
Thanks, makes sense,  was looking at it from the wrong perspective (and being a bit dim!).
