### ISSUE TITLE
Issue with combo capslock+leftalt+a

### ISSUE THREAD

**Issue by jaddawyn** [rvaiya/keyd#851]
Hi all,

First of all thank you for this great tool ! I daily use keyd and it is very helpful :)

Yet, I have an issue with the combo 'capslock+leftalt+a' that is not catched.

Here is the configuration file I got (to reproduce the issue).
```
[ids]
*
[main]

# When capslock is pressed, emacs layout is activated
capslock = layer(emacs)

[emacs]
a = left
d = right

[emacs+alt]
a = C-left
d = C-right

```

When I press capslock+a this is OK. But capslock+leftalt+a is not detected. If I launch 'keyd --monitor' I can see that capslock+leftalt+a is not catched at all.
The same with letter 'd' is working correctly (capslock+d and capslock+leftalt+d are working).

Notes:
- I use french keyboard (where keys 'a' and 'q' are reversed comparing to qwerty keyboard). Could it be the source of this problem ?
- capslock+rightalt+a is also not working,
- I'm using branch "master" (checkout 393d341464fe567515e767bfae8167a38fa6fb3d).

I've try to add some prints into the source code, and it seems that deep in the software (up to device_read_event()), the key 'a' is not catched.
Any workarround would be appreciated.

Many thanks for your help.

**Comment by nsbgn** [comment]
This sounds like a the consequences of [rollover](https://en.wikipedia.org/wiki/Key_rollover) --- keyboards cannot always physically register every possible key combination. To confirm, check if this happens even without keyd running.

https://github.com/rvaiya/keyd/issues/539, https://github.com/rvaiya/keyd/issues/490, https://github.com/rvaiya/keyd/issues/381, https://github.com/rvaiya/keyd/issues/357, https://github.com/rvaiya/keyd/issues/156, https://github.com/rvaiya/keyd/issues/142

**Comment by jaddawyn** [comment]
Many thanks for the quick answer.
Indeed it is a hardware issue.

Have a nice day,
