### ISSUE TITLE
Tripple chords

### ISSUE THREAD

**Issue by xged** [rvaiya/keyd#857]
after `kpslash+kp7+kp9 = 3`
`kpslash+kp7`, `kp7+kp9`, `kpslash+kp9` doesnt work

**Comment by nsbgn** [comment]
What exactly do you mean by "after ... doesn't work"? You mean that `kpslash+kp7` no longer produces anything if you have set `kpslash+kp7+kp9 = 3`, but it does produce something if you have not set that?

**Comment by xged** [comment]
@nsbgn correct

**Comment by nsbgn** [comment]
It's hard to know if I get what you mean without a specific explanation of what you expect to happen and what happens instead, ideally with output from `keyd monitor -t` to illustrate.

That said, I can reproduce the following:

```
kpslash+kp7+kp9=3
kpslash+kp7=2
```

Chording `kpslash+kp7` (ie their keydown events happening within some small amount of milliseconds) gives me `2`, but `kpslash+kp7+kp9` *also* gives me `2`.

However, swapping the order of the config will emit `3` for `kpslash+kp7+kp9` and `2` for `kpslash+kp7`, as expected:

```
kpslash+kp7=2
kpslash+kp7+kp9=3
```

Is that the issue you're running into? (If not, this merits a separate issue.)

**Comment by xged** [comment]
I also had `chord_timeout = 0`
Removing it and chaning the order fixes the problem for me, thanks.
