### ISSUE TITLE
Reload with different config file

### ISSUE THREAD

**Issue by JPRomer0** [rvaiya/keyd#858]
Am using keyd v2.5.0

What I am trying to do is have different config files, to use at different points in time,
and I am not sure about how to do this, reading this: https://github.com/rvaiya/keyd/blob/master/docs/keyd.scdoc

I know how to change default.conf and then reload the config( with systemctl reload keyd), but I haven't been able to reload a different config.

I want to do this for two reasons, some applications that I can use better with different keybinds, and to learn about how keyd works without changing my default config.

**Comment by kbtz** [comment]
>I want to do this for two reasons, some applications that I can use better with different keybinds

Doesn't [application specific remapping](https://github.com/rvaiya/keyd#application-specific-remapping-experimental) helps with that?

>and to learn about how keyd works without changing my default config

When working on my main keyboard config I usually connect another cheap one so even if the config breaks it is only applied to my main keyboard id, while the cheap one is using a copy of my latest config.
