### ISSUE TITLE
[ctr] d = leftshift(leftalt)

### ISSUE THREAD

**Issue by tim1737** [rvaiya/keyd#860]
help pls what I'm doing wrong the last condition doesn't work

[ids]

*

[main]

capslock = leftmeta

[meta]
j = left
k = up
l = down
; = right
f = backspace
h = esc
d = overload(leftcontrol, leftshift)

**Comment by nsbgn** [comment]
See https://github.com/rvaiya/keyd/issues/713#issuecomment-2044532113. `leftcontrol` is not a layer, but a key. What are you trying to do? `overload(control, leftshift)` would be a valid binding, but of course might not correspond to what you want.

**Comment by tim1737** [comment]
@nsbgn 
I'm sorry, I didn't poison what I planned, I want the right combination to be executed with cablock + d so that I could eventually pick up from xorg and change the language layout on them, since you can't use capslock + d

**Comment by nsbgn** [comment]
I'm not sure I follow what you are asking. If the question is how to get a single tap of `leftshift+leftalt` when pressing `capslock`-`d`, it would be simply:

```
[ids]
*
[main]
capslock = layer(control)

[control]
j = left
k = up
l = down
; = right
f = backspace
h = esc
d = leftshift+leftalt
```
