### ISSUE TITLE
Unable to use keyboard shortcuts

### ISSUE THREAD

**Issue by ViniiR** [rvaiya/keyd#864]
hi, first of all I'm on NixOS and using cinnamon DE(X11)
I've successfully been able to set up keyd and I can confirm this because remapping capslock = q works as expected whoever I've tried the following:

[control+shift]
p = command(firefox)
m = command(firefox)
w = command(wezterm)

and it does not work no matter the variations i try
my intention is to make Control+Shift+p open Firefox the other keybinds are just to see if it's a problem with p, keyd successfully registers key presses when using "sudo keyd monitor" (sudo is necessary for some reason) I am unaware if it's a compatibility problem with cinnamon or if I just miss used the syntax

**Comment by nsbgn** [comment]
> sudo is necessary for some reason

Intercepting and generating keypresses is inherently a privileged action. You wouldn't want all your programs to be able to do that.

That is also the reason why using `command()` is discouraged for arbitrary applications, especially something like a web browser. You may be able to get it to work by changing the user and setting the appropriate `DISPLAY` variable, but for hotkeys you're much better off using your WM's config or something like <https//github.com/baskerville/sxhkd>.

cf #692, #593, https://github.com/rvaiya/keyd/issues/211, https://github.com/rvaiya/keyd/issues/229, https://github.com/rvaiya/keyd/issues/243
