### ISSUE TITLE
Mapping shortcuts to custom scripts

### ISSUE THREAD

**Issue by SandeshGowda-0094** [rvaiya/keyd#866]
Hey, can anyone tell weather its possible to have custom key maps set to run scripts when active in a particular application using the **keyd-application-mapper**.

For example, lets say I need to map alt+= and alt+- to increase or decrease the transparancy of alacritty-terminal, as there is no direct way for this, hence I have written a custom python script the tweaks the alacritty config file.

I wanted to know weather there is a way to trigger this script to **keyd-application-mapper**

**Comment by rvaiya** [comment]
Use `command()`. Be aware of the usual caveats (the command will run as root with no environment variables set).
