### ISSUE TITLE
German Umlauts

### ISSUE THREAD

**Issue by moiselazarus** [rvaiya/keyd#87]
How can I map umlaute? äü... the code names are udiaeresis, odiaeresis, ssharp ... 
I tried this [ = macro(control+shift+u u f c space), but doesn' t work. (in terminal it works)
Perfect would be a layer and then u = udiaeresis and with shift uppercase.
Thank you for keyd! I like it and switch from xcape.

**Comment by rvaiya** [comment]
The best way to achieve this is to use compose key sequences in conjunction with macros. See #33 for an example. I have also added  an [example](https://github.com/rvaiya/keyd/blob/master/examples/international-glyphs.conf).

**Comment by moiselazarus** [comment]
Perfect, exactly what I was looking for.
