### ISSUE TITLE
Add support for an XDG compliant config location

### ISSUE THREAD

**Issue by averagebrine** [rvaiya/keyd#870]
I hopped distros and forgot my keyd configuration because it was in /etc. Oops.

I've forked the repo and will work on adding a simple solution that prefers ~/.config/keyd, but will fallback to /etc/keyd. If you feel like this should be implemented, I'd love to collaborate on a PR.

Thanks!

**Comment by nsbgn** [comment]
See https://github.com/rvaiya/keyd/issues/767#issuecomment-2156734805 and #45 ;) There is no per-user support at the moment

**Comment by averagebrine** [comment]
Ah, thank you!
