### ISSUE TITLE
key presses is no registering

### ISSUE THREAD

**Issue by barslmn** [rvaiya/keyd#871]
Hi,

Thanks for your time you put into making this program.

I have the following config:
```
[ids]

*

[main]
capslock = overload(nav, esc)

t = overloadi(t, timeout(t, 200, home), 200)
y = overloadi(y, timeout(y, 200, end), 200)
u = overloadi(u, timeout(u, 200, backspace), 200)

a = overloadi(a, overloadt(meta, a, 200), 200)
s = overloadi(s, overloadt(shift, s, 200), 200)
d = overloadi(d, overloadt(alt, d, 200), 200)
f = overloadi(f, overloadt(control, f, 200), 200)
g = overloadi(g, timeout(g, 200, pageup), 200)
h = overloadi(h, timeout(h, 200, pagedown), 200)

j = overloadi(j, overloadt(control, j, 200), 200)
k = overloadi(k, overloadt(altgr, k, 200), 200)
l = overloadi(l, overloadt(shift, l, 200), 200)
; = overloadi(;, overloadt(meta, ;, 200), 200)


[nav]
h = left
j = down
k = up
l = right
```

My down, right arrow keys are working but **up** and **left** keys are not working when pressed by themselves, same goes for **home** and **end** keys, but backspace works. They don't show up in `evtest` neither.
It's my first time dabbling with home row mods, and I am not sure what I am missing?
Any kind of pointers for a fix is appreciated.

System info: I am on a laptop, with wayland.

**Comment by nsbgn** [comment]
Could you give the output of `keyd monitor -t` while keyd is not running and pressing the keys you want to press, and then exactly the same once again with keyd running to show what keys are emitted?

**Comment by barslmn** [comment]
> Could you give the output of `keyd monitor -t` while keyd is not running and pressing the keys you want to press, and then exactly the same once again with keyd running to show what keys are emitted?

I can't reproduce it after stopping starting it again. I will open a new issue when I can reproduce the error.
