### ISSUE TITLE
Conflict: Ctrl+space also grabs Meta+Ctrl+Space

### ISSUE THREAD

**Issue by serranomorante** [rvaiya/keyd#872]
Hi! Is it possible that I'm doing something wrong here?

The following config is not only grabbing the `Ctrl+Space` combination (to emit the oneshot layer) but it also grabs the `Meta+Control+Space` combination which is a shortcut that I use on another app (dwm) leaving it unusable. Do I really need to also include the comment lines below to avoid this conflict? Are there any alternatives that use the oneshot action?

```gitconfig
[main]
capslock = layer(control)

# [meta+control]
# space = M-C-space

[control]
space = oneshot(spanish)

[spanish]
a = macro(compose a ')
e = macro(compose e ')
i = macro(compose i ')
```

**Comment by nsbgn** [comment]
In general, this behaviour is desirable --- it is a design goal of keyd to preserve stacking of modifiers. Consider what would happen if you remap keys in the `shift` layer and you suddenly can no longer do anything with `control+shift`.

Overriding that for the specific situations where you don't want that, as you have done, seems to me a clean way to handle it.

**Comment by serranomorante** [comment]
Thank you so much!
