### ISSUE TITLE
Uppercase letter not considered symbol and resets the overloadi timer

### ISSUE THREAD

**Issue by lobre** [rvaiya/keyd#875]
Here is my config.

```
q = overloadi(S-q, q, 1000)
```

I was expecting to be able to keep entering uppercase `Q` when repeatedly pressing `q` because it would trigger `<action 1>` as I keep below 1000ms. However, it seems `S-q` is not considered a "non-action" (or symbol). So every 1000ms, I have `<action 2>` triggered.

Is there a way to make it consider that `Q` is a "regular symbol key"?

I tried this, but same result:

```
q = overloadi(Q, q, 1000)
```

And for context, I am trying to active a mode/layer where everything I type is uppercase as long as I keep typing below 1s. It would be kind of a smart capslock that would deactivate itself is no key is entered for 1s.

**Comment by sonjiku** [comment]
What if you use a macro? I dont recall correctly and will probably check when i get home and have time to check the config, but there probably is a macro repeat action or something similar. Check the manpage

**Comment by sonjiku** [comment]
What if you used `timeout(macro(S-q),100,q)`?

If you change all keys to be like that you will have auto capslock if you tap any key less than 100ms.

**Comment by lobre** [comment]
> What if you used timeout(macro(S-q),100,q)?

This is not exactly the same. `timeout()` is for triggering an action if key is **held** more or less than a certain timing. So here with your example, if I press the key for more than 100ms, it will trigger `q`, otherwise `Q`.

What I want is to trigger the uppercase version if **the last non-action** key (that was typed before the current key) was less than 100ms ago.

**Comment by rvaiya** [comment]
Sorry for the delay.

> I was expecting to be able to keep entering uppercase Q when repeatedly pressing q because it would trigger <action 1> as I keep below 1000ms. However, it seems S-q is not considered a "non-action" (or symbol). So every 1000ms, I have <action 2> triggered.

This is indeed a bug and should be fixed in the latest commit. I am closing this tentatively, but feel free to reopen it if the bug isn't fixed.
