### ISSUE TITLE
Odd key on my keyboard - can I make it do something useful?  

### ISSUE THREAD

**Issue by xircon** [rvaiya/keyd#892]
Minisforum V3 tablet computer, the key is for co-pilot.  It reports:
```
keyd virtual keyboard	0fac:0ade:efba1ddf	leftmeta down
keyd virtual keyboard	0fac:0ade:efba1ddf	leftshift down
keyd virtual keyboard	0fac:0ade:efba1ddf	f23 down
keyd virtual keyboard	0fac:0ade:efba1ddf	f23 up
keyd virtual keyboard	0fac:0ade:efba1ddf	leftshift up
keyd virtual keyboard	0fac:0ade:efba1ddf	leftmeta up
```
How can I map in my config?

**Comment by rvaiya** [comment]
Assuming you can't remap the key in firmware, you can do something like this: `leftmeta+leftshift+f23 = <action>`.

**Comment by xircon** [comment]
Tried that (should have put in my post, sorry!), tried:
```
leftmeta+leftshift+f23 = macro(leftcontrol+g)
```
It didn't work, so assuming I got the above syntax right, looks like it is a hardwired key, only useful in windows.
