### ISSUE TITLE
Application mapper not applying to windows in Sway

### ISSUE THREAD

**Issue by ProfessorHoover** [rvaiya/keyd#893]
I've tried running version 2.5.0 and building the master branch manually but get the same behaviour in both cases. Running keyd-application-mapper -v in Sway on Debian 12 shows me the active windows, however no matter which window I define in app.conf my keyboard acts as if I had not applied any changes.
 I have confirmed that keyd works as changes made in the main configuration file are applied. My app.conf is very simple, and can be found below. My primary need at this time is to remap capslock to control in emacs only. A stretch goal is for this behaviour to apply to emacs when run in terminal as well, however the window class and title do not change so I am unsure if this is possible. I have tried applying changes to other keys and window classes without luck.
`[emacs]`
`capslock = control`

`[foot]`
`capslock = control`

**Comment by rvaiya** [comment]
This sounds like it a permission issue. Does the user running `keyd-application-mapper` have access to the keyd socket? Have you added it to `keyd`? The output of `key-application-mapper -v` might be of some use.

**Comment by ProfessorHoover** [comment]
I think I've found the issue. I wasn't capturing my keyboard with an id in any of my existing keyd configs. 

However, capslock remapping doesn't work. I'll submit another issue to track that.
