### ISSUE TITLE
Basic Capslock remapping does not work 

### ISSUE THREAD

**Issue by ProfessorHoover** [rvaiya/keyd#894]
Capslock remapping doesn't work in either Keyd or Application Mapper. Other keys I've tested randomly in application mapper and keyd work, except for capslock = control. I can tell that Keyd is capturing my keyboard as the ids shown in keyd monitor have changed to the keyd virtual keyboard and are showing the default keys. Other than that application-mapper and keyd are working correctly. Thanks for the help.

**Comment by ProfessorHoover** [comment]
On a whim, I decided to try overloading capslock to only be control when held. So my app.conf looks like this:
`[emacs]`
`capslock = overload(control, capslock)`
This works as expected. Am I misunderstanding whether capslock can be simply remapped?

**Comment by IbrahimElk** [comment]
```
[main]
capslock = oneshot(control)
```

this did work for me. The overloading with ``overload(control, control)``  did also not work.

**Comment by polybluez** [comment]
This also didn't work for me, but using the latest commit helped

**Comment by rvaiya** [comment]
Can you elaborate? Please provide a minimally viable sample config which reproduces the problem, as well as the expected behaviour.

**Comment by ProfessorHoover** [comment]
The app.conf that doesn't work looks like this:
```
[emacs]
capslock = control
```
I'd like to have the capslock key output control when I'm in Emacs, but not in other programs.
