### ISSUE TITLE
Overload breaks Alt-Tab

### ISSUE THREAD

**Issue by laktak** [rvaiya/keyd#895]
This config breaks `alt+tab`:

```
[main]
tab = overload(control, tab)
```

When I "slowly" press `alt+tab` it works but not when quickly pressing `alt+tab`. I also tried `tab = overloadi(tab, overloadt2(control, tab, 200), 150)`.

When I define alt-tab explicitly

```
[main]
tab = overload(control, tab)
leftalt = layer(lt_lalt)

[lt_lalt:A]
# define tab so there is no conflict with the tab overload
tab = macro(leftalt+tab)
```

it works again. IMO the overload should not trigger when another key is pressed first.

**Comment by argenkiwi** [comment]
Have you tried to use `overloadt` instead? It set a timeout after which to trigger the overload. If you don't hold it for as long as the timeout it should behave as tab instead.

**Comment by rvaiya** [comment]
`tab` will only get sent if `tab` is tapped, which means that releasing `alt` before `tab` will not produce the expected sequence. This just comes with the territory. There are a few work arounds like explicitly overriding this behaviour for frequently used shortcuts.

e.g

```
[main]

tab = overload(control, tab)

[alt]

tab = A-tab
```

**Comment by laktak** [comment]
Thank you for the explanation - I release both keys at once so it didn't occur to me that `alt up` might get sent first.

I only mapped control to tab because I couldn't get

```
capslock = overload(capslock, esc)
```

to work. When I quickly press `esc` then `k` with that mapping, I have the same problem.

monitor will show:

```
keyd virtual keyboard   0fac:0ade:efba1ddf      leftcontrol down
keyd virtual keyboard   0fac:0ade:efba1ddf      k down
keyd virtual keyboard   0fac:0ade:efba1ddf      leftcontrol up
keyd virtual keyboard   0fac:0ade:efba1ddf      k up
```

which produces `ctrl+k`. Without the overload I get what I want (`esc` then `k`) even though the inputs overlap:

```
keyd virtual keyboard   0fac:0ade:efba1ddf      esc down
keyd virtual keyboard   0fac:0ade:efba1ddf      k down
keyd virtual keyboard   0fac:0ade:efba1ddf      esc up
keyd virtual keyboard   0fac:0ade:efba1ddf      k up
```

Do you have a workaround for such a situation as well?

In any case, thanks for keyd - it's a really great tool!

**Comment by laktak** [comment]
I think I already tried all combinations but now I understand that it's just not possible to distinguish in this case, thanks.

But just to be clear on the use case: when in `vi` mode in bash (or readline) you are in input by default. So the first key is `esc`, not the last.


Unrelated but maybe a bug? When I tried 

```
capslock = overloadi(control, esc, 200)
# or escape instead of esc
```

it gives me 

> Dec 29 22:21:10 alpha keyd[1207]:         ERROR: line 10: invalid key or action

but 

```
capslock = overloadi(esc, overloadt2(control, esc, 200), 150)
# or
capslock = lettermod(control, esc, 200, 150)
```

work fine. Man says

>        overloadi(<action 1>, <action 2>, <idle timeout>)

isn't esc an action? Why does it work as action 1?
