### ISSUE TITLE
How to properly swap modifier keys?

### ISSUE THREAD

**Issue by hagaram** [rvaiya/keyd#90]
Hi,
first of all, that you for this great project!.

I might be a little denser, but I can't seem to find valid configuration to swap Alt and Meta on Macbook-like (not the magic one, but with Macbook like button layout) keyboard. I was thinking maybe something like the snippet below might work.

    [ids]
    
    0c45:7016
    
    [main]
    
    leftmeta = leftalt
    leftalt = leftmeta
    
    
    Which seems to be wrong approach and wrong understanding, how keys are remmaped and how config is handled.
    
    Even when I try to use minimal configuration like 
    
        [ids]
    
    0c45:7016
    
    [main]
    
    leftmeta = leftalt

Xev seems to recognize right key code, but my keyboard shortcut doesn't seem to work. When I try to setup some keyboard shortcut, while keyd is running, the remmaped key seems to be ignored, like it wasn't pressed during shortcut setup. X11 nad Plasma desktop is used.

Any help is greatly appreciated.

**Comment by rvaiya** [comment]
You probably want 
```
[ids]

0c45:7016

[main]

meta = layer(alt)
alt = layer(meta)
```

Mapping directly to modifier codes is unsupported. I should probably clarify this in the documentation :P.

**Comment by hagaram** [comment]
@rvaiya Yes, thats exactly what I needed! Thanks!
