### ISSUE TITLE
Space with modifier stopped working

### ISSUE THREAD

**Issue by magthe** [rvaiya/keyd#95]
After an upgrade to

```
[I] ➜ keyd --version
keyd version: 2.2.1-beta (05d994b7e98c8d090e67c43cb37ac23a36948efc)
```

It seems like all combinations of modifiers and space result in just `space`. Is someone else seeing the same thing?

It's messing up Emacs bit :disappointed:

**Comment by rvaiya** [comment]
What is your config? I can't seem to reproduce this with a blank one.

**Comment by magthe** [comment]
This is my config

```
[ids]
0001:0001

[main]
# swap escape and capslock
capslock = esc
esc = capslock

# alt on hold and rightalt on tap (compose)
leftalt = overload(A, rightalt)
rightalt = overload(A, rightalt)

# meta on PrtSc
sysrq = layer(meta)

# vim movement layer, on space
space = overload(vim_mov, space)

[vim_mov]
h = left
j = down
k = up
l = right
p = pageup
; = pagedown
[ = home
' = end
```

**Comment by rvaiya** [comment]
Thanks. Overloaded sequences are now executed literally irrespective of context.  I've changed this behaviour in latest commit so this doesn't happen in the base layer which should fix your problem.

**Comment by magthe** [comment]
Excellent, that fixed it! Thanks for amazingly quick response.
