### ISSUE TITLE
Option to set the typematic rate and delay

### ISSUE THREAD

**Issue by Moempfred** [rvaiya/keyd#97]
A config/cli option to set the typematic rate and delay would be useful.
The delay specifies the time until the typematic begins, the rate is the amount of times a char is repeated per second if its key is held down.
 With X11 this can be set through `xset r rate [delay in ms] [rate in Hz]`

**Comment by rvaiya** [comment]
Repetitions are handled by the display server, so you should be able to control them using `xset`. The one exception to this is macros since keyd must generate synthetic repeat events in the form of up/down pairs to ensure they execute as intended.

**Comment by Moempfred** [comment]
Well my bad, I had the rate set before I started the keyd daemon, after starting it xset must be run again. 
Thanks for the reply!
