### ISSUE TITLE
Can't run `keyd-application-mapper -m` without app.conf

### ISSUE THREAD

**Issue by canadaduane** [rvaiya/keyd#99]
I think it should be possible to run the python script with `-m` even if there is no ~/.config/keyd/app.conf:

```
$ ./scripts/keyd-application-mapper -m
ERROR: could not find app.conf, make sure it is in ~/.config/keyd/app.conf
```

**Comment by canadaduane** [comment]
Alternatively, if we do want to require `app.conf`, then maybe this should just be a "debug mode" rather than "monitor"? I think that would be useful, and a debug mode need not return on line 274: 

```
    if args.monitor:
        print(cls)
        return
```

This helped me debug my app.conf.

**Comment by rvaiya** [comment]
Yes, this makes more sense. Monitor mode can't run concurrently with an instance of the daemon anyway since certain monitors (i.e gnome) only allow a single process to monitor changes at a time.
